BTB_btac_t Class Reference
Classes
struct BTB_btac_Entry_t
class BTB_btac_sc_t
Public Member Functions
BTB_btac_t (char *const arg_name, const int arg_num_entries, const int arg_num_ways, const int arg_tag_width, const char arg_replacement_policy)
~BTB_btac_t ()
Protected Attributes
int num_entries
int num_ways
int tag_width
int tag_mask
int tag_shift
char replacement_policy
struct BTB_btac_Entry_t ** set
int btac_mask
Detailed Description
Definition at line 22 of file btb-btac.cpp.
Constructor & Destructor Documentation
BTB_btac_t::BTB_btac_t (char *const arg_name, const int arg_num_entries, const int arg_num_ways, const int arg_tag_width, const char arg_replacement_policy) [inline]
Definition at line 53 of file btb-btac.cpp.
References BTB_t::bits, btac_mask, CHECK_POS, CHECK_PPOW2, COMPONENT_NAME, fatal(), BTB_t::init(), log_base2(), mytolower(), BTB_t::name, BTB_btac_t::BTB_btac_t::BTB_btac_Entry_t::next, num_entries, num_ways, BTB_btac_t::BTB_btac_t::BTB_btac_Entry_t::prev, replacement_policy, tag_mask, tag_shift, tag_width, and BTB_t::type.
BTB_btac_t::~BTB_btac_t () [inline]
Definition at line 111 of file btb-btac.cpp.
References BTB_t::name, BTB_btac_t::BTB_btac_t::BTB_btac_Entry_t::next, num_entries, and BTB_t::type.
Member Data Documentation
int BTB_btac_t::btac_mask [protected]
Definition at line 49 of file btb-btac.cpp.
Referenced by BTB_btac_t().
int BTB_btac_t::num_entries [protected]
Definition at line 41 of file btb-btac.cpp.
Referenced by BTB_btac_t(), and ~BTB_btac_t().
int BTB_btac_t::num_ways [protected]
Definition at line 42 of file btb-btac.cpp.
Referenced by BTB_btac_t().
char BTB_btac_t::replacement_policy [protected]
Definition at line 46 of file btb-btac.cpp.
Referenced by BTB_btac_t().
struct BTB_btac_Entry_t** BTB_btac_t::set [read, protected]
Definition at line 47 of file btb-btac.cpp.
int BTB_btac_t::tag_mask [protected]
Definition at line 44 of file btb-btac.cpp.
Referenced by BTB_btac_t().
int BTB_btac_t::tag_shift [protected]
Definition at line 45 of file btb-btac.cpp.
Referenced by BTB_btac_t().
int BTB_btac_t::tag_width [protected]
Definition at line 43 of file btb-btac.cpp.
Referenced by BTB_btac_t().
The documentation for this class was generated from the following file:
btb-btac.cpp