prefetch_t Class Reference
#include <zesto-prefetch.h>
Public Member Functions
prefetch_t (void)
virtual ~prefetch_t ()
virtual md_paddr_t lookup (const md_addr_t, const md_paddr_t)=0
virtual void reg_stats (struct stat_sdb_t *const, const struct core_t *const)
Protected Member Functions
void init (void)
Protected Attributes
struct cache_t * cp
char * type
int bits
counter_t lookups
Detailed Description
Definition at line 82 of file zesto-prefetch.h.
Constructor & Destructor Documentation
prefetch_t::prefetch_t (void)
Definition at line 93 of file zesto-prefetch.cpp.
References init().
prefetch_t::~prefetch_t () [virtual]
Definition at line 98 of file zesto-prefetch.cpp.
References type.
Member Function Documentation
void prefetch_t::init (void) [protected]
Definition at line 85 of file zesto-prefetch.cpp.
References bits, cp, lookups, and type.
Referenced by prefetch_context_t::prefetch_context_t(), prefetch_IP_t::prefetch_IP_t(), prefetch_nextline_t::prefetch_nextline_t(), prefetch_stream_t::prefetch_stream_t(), and prefetch_t().
virtual md_paddr_t prefetch_t::lookup (const md_addr_t, const md_paddr_t) [pure virtual]
Referenced by cache_process(), and cache_process_llc().
void prefetch_t::reg_stats (struct stat_sdb_t * const sdb, const struct core_t * const core) [virtual]
Definition at line 106 of file zesto-prefetch.cpp.
References bits, cp, core_t::current_thread, thread_t::id, lookups, cache_t::name, stat_reg_counter, stat_reg_formula(), stat_reg_int(), and type.
Referenced by cache_reg_stats(), and LLC_reg_stats().
Member Data Documentation
int prefetch_t::bits [protected]
Definition at line 87 of file zesto-prefetch.h.
Referenced by init(), prefetch_context_t::prefetch_context_t(), prefetch_IP_t::prefetch_IP_t(), prefetch_nextline_t::prefetch_nextline_t(), prefetch_stream_t::prefetch_stream_t(), and reg_stats().
struct cache_t* prefetch_t::cp [read, protected]
Definition at line 85 of file zesto-prefetch.h.
Referenced by init(), prefetch_context_t::prefetch_context_t(), prefetch_IP_t::prefetch_IP_t(), prefetch_nextline_t::prefetch_nextline_t(), prefetch_stream_t::prefetch_stream_t(), and reg_stats().
counter_t prefetch_t::lookups [protected]
Definition at line 88 of file zesto-prefetch.h.
Referenced by init(), and reg_stats().
char* prefetch_t::type [protected]
Definition at line 86 of file zesto-prefetch.h.
Referenced by init(), prefetch_context_t::prefetch_context_t(), prefetch_create(), prefetch_IP_t::prefetch_IP_t(), prefetch_nextline_t::prefetch_nextline_t(), prefetch_stream_t::prefetch_stream_t(), reg_stats(), and ~prefetch_t().
The documentation for this class was generated from the following files:
zesto-prefetch.h
zesto-prefetch.cpp