GenericInterfaceVcs Class Reference
#include <genericInterfaceVcs.h>
Public Member Functions
GenericInterfaceVcs ()
~GenericInterfaceVcs ()
uint get_no_credits () const
void set_no_credits (int credits)
void set_no_vcs (uint v)
void set_buffer_size (uint b)
void setup (uint v, uint cr)
string toString () const
void process_event (IrisEvent *e)
string print_stats ()
ullint get_packets_out ()
ullint get_packets ()
ullint get_flits_out ()
Public Attributes
bool is_mc_interface
Private Member Functions
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_tick_event (IrisEvent *e)
void handle_link_arrival (IrisEvent *e)
Private Attributes
uint vcs
uint buffer_size
int credits
bool in_packet_cleared
vector< bool > in_packet_complete
uint flast_vc
bool ticking
GenericBuffer out_buffer
GenericBuffer in_buffer
GenericArbiter out_arbiter
vector< int > downstream_credits
vector< LowLevelPacket > out_packets
vector< uint > out_packet_flit_index
vector< LowLevelPacket > in_packets
vector< uint > in_packets_flit_index
vector< bool > in_packets_valid
vector< bool > in_ready
ullint flits_in
ullint packets_in
ullint flits_out
ullint packets_out
ullint total_packets_in_time
Detailed Description
Definition at line 47 of file genericInterfaceVcs.h.
Constructor & Destructor Documentation
GenericInterfaceVcs::GenericInterfaceVcs ()
Definition at line 26 of file genericInterfaceVcs.cc.
References NetworkComponent::name, and ticking.
GenericInterfaceVcs::~GenericInterfaceVcs ()
Definition at line 32 of file genericInterfaceVcs.cc.
References in_packets, and out_packets.
Member Function Documentation
ullint GenericInterfaceVcs::get_flits_out () [virtual]
Implements Interface .
Definition at line 602 of file genericInterfaceVcs.cc.
References flits_out.
uint GenericInterfaceVcs::get_no_credits () const
Definition at line 121 of file genericInterfaceVcs.cc.
References credits.
ullint GenericInterfaceVcs::get_packets () [virtual]
Implements Interface .
Definition at line 614 of file genericInterfaceVcs.cc.
References packets_in, and packets_out.
ullint GenericInterfaceVcs::get_packets_out () [virtual]
Implements Interface .
Definition at line 608 of file genericInterfaceVcs.cc.
References packets_out.
void GenericInterfaceVcs::handle_link_arrival (IrisEvent * e) [private]
link arrival can be for a flit or credit. FLIT: Add incoming flit to buffer and send a credit back. Credit for the tail flit is not sent here. This is held till we know the ejection port is free. (This is modelled here for the additional MC backpressure modelling and need not be this way). CREDIT: Update state for downstream credits. Generate a TICK event at the end of it. This will restart the interface if it is blocked on a credit(outgoing path) or initiate a new packet(incoming path).
Definition at line 213 of file genericInterfaceVcs.cc.
References _DBG, HeadFlit::addr, NetworkComponent::address, GenericBuffer::change_push_channel(), CREDIT_ID, do_two_stage_router, downstream_credits, IrisEvent::event_data, FLIT_ID, flits_in, HEAD, in_buffer, Interface::input_connection, is_mc_interface, LINK_ARRIVAL_EVENT, Simulator::Now(), ONE_FLIT_REQ, packets_in, process_event(), NetworkComponent::process_event(), LinkArrivalData::ptr, GenericBuffer::push(), Simulator::Schedule(), TAIL, TICK_EVENT, ticking, total_packets_in_time, IrisEvent::type, Flit::type, LinkArrivalData::type, LinkArrivalData::valid, IrisEvent::vc, Flit::vc, and LinkArrivalData::vc.
Referenced by process_event().
void GenericInterfaceVcs::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 307 of file genericInterfaceVcs.cc.
References _DBG, HighLevelPacket::addr, IrisEvent::event_data, is_mc_interface, Simulator::Now(), out_packet_flit_index, out_packets, NetworkComponent::process_event(), Simulator::Schedule(), TICK_EVENT, ticking, HighLevelPacket::to_low_level_packet(), IrisEvent::vc, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void GenericInterfaceVcs::handle_ready_event (IrisEvent * e) [private]
These are credits from the processor and hence do not update flow control state. Flow control state is updated at the link arrival event for a credit.
Definition at line 177 of file genericInterfaceVcs.cc.
References _DBG, in_ready, is_mc_interface, Simulator::Now(), NetworkComponent::process_event(), Simulator::Schedule(), TICK_EVENT, ticking, and IrisEvent::vc.
Referenced by process_event().
void GenericInterfaceVcs::handle_tick_event (IrisEvent * e) [private]
Definition at line 346 of file genericInterfaceVcs.cc.
References _DBG, HighLevelPacket::addr, HeadFlit::addr, NetworkComponent::address, HighLevelPacket::avg_network_latency, GenericBuffer::change_pull_channel(), GenericBuffer::change_push_channel(), GenericArbiter::clear_winner(), CREDIT_ID, credits, do_two_stage_router, downstream_credits, IrisEvent::event_data, flast_vc, FLIT_ID, flits_out, HighLevelPacket::from_low_level_packet(), GenericBuffer::get_occupancy(), HEAD, HighLevelPacket::hop_count, in_buffer, in_packet_complete, in_packets, in_packets_flit_index, in_ready, Interface::input_connection, GenericArbiter::is_empty(), is_mc_interface, GenericArbiter::is_requested(), LINK_ARRIVAL_EVENT, NEW_PACKET_EVENT, NetworkComponent::node_ip, Simulator::Now(), ONE_FLIT_REQ, out_arbiter, out_buffer, out_packet_flit_index, out_packets, Interface::output_connection, packets_out, GenericBuffer::peek(), GenericArbiter::pick_winner(), process_event(), NetworkComponent::process_event(), Interface::processor_connection, LinkArrivalData::ptr, GenericBuffer::pull(), GenericBuffer::push(), READY_EVENT, HighLevelPacket::recv_time, HighLevelPacket::req_start_time, GenericArbiter::request(), Simulator::Schedule(), IrisEvent::src_id, TAIL, TICK_EVENT, ticking, IrisEvent::type, Flit::type, LinkArrivalData::type, IrisEvent::vc, Flit::vc, LinkArrivalData::vc, vcs, HighLevelPacket::virtual_channel, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
string GenericInterfaceVcs::print_stats (void) [virtual]
Implements Interface .
Definition at line 586 of file genericInterfaceVcs.cc.
References flits_in, flits_out, NetworkComponent::node_ip, packets_in, packets_out, and total_packets_in_time.
void GenericInterfaceVcs::process_event (IrisEvent * e) [virtual]
READY_EVENT: A ready is the credit at a packet level with the injection/ejection point
LINK_ARRIVAL_EVENT: This is a flit/credit arrival from the network. (Incoming path)
NEW_PACKET_EVENT: This is a high level packet from the processor connected to this node
TICK_EVENT: Update internal state of the interface. This involves two distinct paths (Incoming and Outgoing). Push flits into the output buffer and send them out after all flits for a packet are moved to the output buffer(Outgoing path). Push flits from the input buffer to a low level packet. Convert the low level packet to a high level packet when complete and then send it to the injection processor connected to this node (Incoming path).
Implements Interface .
Definition at line 137 of file genericInterfaceVcs.cc.
References handle_link_arrival(), handle_new_packet_event(), handle_ready_event(), handle_tick_event(), LINK_ARRIVAL_EVENT, NEW_PACKET_EVENT, READY_EVENT, TICK_EVENT, and IrisEvent::type.
Referenced by handle_link_arrival(), and handle_tick_event().
void GenericInterfaceVcs::set_buffer_size (uint b) [virtual]
Implements Interface .
Definition at line 132 of file genericInterfaceVcs.cc.
void GenericInterfaceVcs::set_no_credits (int credits) [virtual]
Implements Interface .
Definition at line 116 of file genericInterfaceVcs.cc.
void GenericInterfaceVcs::set_no_vcs (uint v) [virtual]
Implements Interface .
Definition at line 127 of file genericInterfaceVcs.cc.
void GenericInterfaceVcs::setup (uint v, uint cr) [virtual]
Implements Interface .
Definition at line 40 of file genericInterfaceVcs.cc.
References NetworkComponent::address, buffer_size, credits, downstream_credits, flast_vc, flits_in, flits_out, in_buffer, in_packet_complete, in_packets, in_packets_flit_index, in_packets_valid, in_ready, Component::myId(), out_arbiter, out_buffer, out_packet_flit_index, out_packets, packets_in, packets_out, GenericBuffer::resize(), GenericArbiter::set_no_requestors(), ticking, total_packets_in_time, and vcs.
string GenericInterfaceVcs::toString () const [virtual]
Reimplemented from Interface .
Definition at line 103 of file genericInterfaceVcs.cc.
References NetworkComponent::address, in_buffer, NetworkComponent::node_ip, out_buffer, out_packets, and GenericBuffer::toString().
Member Data Documentation
uint GenericInterfaceVcs::buffer_size [private]
Definition at line 71 of file genericInterfaceVcs.h.
Referenced by setup().
int GenericInterfaceVcs::credits [private]
Definition at line 72 of file genericInterfaceVcs.h.
Referenced by get_no_credits(), handle_tick_event(), and setup().
vector< int > GenericInterfaceVcs::downstream_credits [private]
Definition at line 81 of file genericInterfaceVcs.h.
Referenced by handle_link_arrival(), handle_tick_event(), and setup().
uint GenericInterfaceVcs::flast_vc [private]
Definition at line 75 of file genericInterfaceVcs.h.
Referenced by handle_tick_event(), and setup().
ullint GenericInterfaceVcs::flits_in [private]
Definition at line 101 of file genericInterfaceVcs.h.
Referenced by handle_link_arrival(), print_stats(), and setup().
ullint GenericInterfaceVcs::flits_out [private]
Definition at line 103 of file genericInterfaceVcs.h.
Referenced by get_flits_out(), handle_tick_event(), print_stats(), and setup().
GenericBuffer GenericInterfaceVcs::in_buffer [private]
Definition at line 79 of file genericInterfaceVcs.h.
Referenced by handle_link_arrival(), handle_tick_event(), setup(), and toString().
bool GenericInterfaceVcs::in_packet_cleared [private]
Definition at line 73 of file genericInterfaceVcs.h.
vector<bool> GenericInterfaceVcs::in_packet_complete [private]
Definition at line 74 of file genericInterfaceVcs.h.
Referenced by handle_tick_event(), and setup().
vector< LowLevelPacket> GenericInterfaceVcs::in_packets [private]
Definition at line 88 of file genericInterfaceVcs.h.
Referenced by handle_tick_event(), setup(), and ~GenericInterfaceVcs().
vector< uint > GenericInterfaceVcs::in_packets_flit_index [private]
Definition at line 89 of file genericInterfaceVcs.h.
Referenced by handle_tick_event(), and setup().
vector< bool> GenericInterfaceVcs::in_packets_valid [private]
Definition at line 90 of file genericInterfaceVcs.h.
Referenced by setup().
vector< bool > GenericInterfaceVcs::in_ready [private]
Definition at line 92 of file genericInterfaceVcs.h.
Referenced by handle_ready_event(), handle_tick_event(), and setup().
bool GenericInterfaceVcs::is_mc_interface
Definition at line 65 of file genericInterfaceVcs.h.
Referenced by handle_link_arrival(), handle_new_packet_event(), handle_ready_event(), and handle_tick_event().
GenericArbiter GenericInterfaceVcs::out_arbiter [private]
Definition at line 80 of file genericInterfaceVcs.h.
Referenced by handle_tick_event(), and setup().
GenericBuffer GenericInterfaceVcs::out_buffer [private]
Definition at line 78 of file genericInterfaceVcs.h.
Referenced by handle_tick_event(), setup(), and toString().
vector< uint > GenericInterfaceVcs::out_packet_flit_index [private]
Definition at line 85 of file genericInterfaceVcs.h.
Referenced by handle_new_packet_event(), handle_tick_event(), and setup().
vector< LowLevelPacket> GenericInterfaceVcs::out_packets [private]
Definition at line 84 of file genericInterfaceVcs.h.
Referenced by handle_new_packet_event(), handle_tick_event(), setup(), toString(), and ~GenericInterfaceVcs().
ullint GenericInterfaceVcs::packets_in [private]
Definition at line 102 of file genericInterfaceVcs.h.
Referenced by get_packets(), handle_link_arrival(), print_stats(), and setup().
ullint GenericInterfaceVcs::packets_out [private]
Definition at line 104 of file genericInterfaceVcs.h.
Referenced by get_packets(), get_packets_out(), handle_tick_event(), print_stats(), and setup().
bool GenericInterfaceVcs::ticking [private]
Definition at line 77 of file genericInterfaceVcs.h.
Referenced by GenericInterfaceVcs(), handle_link_arrival(), handle_new_packet_event(), handle_ready_event(), handle_tick_event(), and setup().
ullint GenericInterfaceVcs::total_packets_in_time [private]
Definition at line 105 of file genericInterfaceVcs.h.
Referenced by handle_link_arrival(), print_stats(), and setup().
uint GenericInterfaceVcs::vcs [private]
Definition at line 70 of file genericInterfaceVcs.h.
Referenced by handle_tick_event(), and setup().
The documentation for this class was generated from the following files:
genericInterfaceVcs.h
genericInterfaceVcs.cc