GenericTPGVcs Class Reference
#include <genericTPGVcs.h>
Public Member Functions
GenericTPGVcs ()
~GenericTPGVcs ()
void setup (uint no_nodes, uint vcs, uint max_sim_time)
void finish ()
void process_event (IrisEvent *e)
string toString () const
string print_stats () const
void set_trace_filename (string filename)
void set_no_vcs (uint v)
void set_output_path (string outpath)
bool compare ()
Public Attributes
unsigned int packets
unsigned int packets_in
double min_pkt_latency
double last_packet_out_cycle
ullint fwd_path_delay
ullint roundTripLat
ullint TotalBLP
ullint stat_round_trip_network_latency
ullint stat_round_trip_hop_count
ullint stat_round_trip_memory_latency
ullint stat_waiting_in_ni
MSHR_H * mshrHandler
vector< bool > ready
bool sending
ullint max_time
vector< uint > mc_node_ip
ullint lastSentTime
Private Member Functions
Request * GetNextRequest ()
bool GetNewRequest (Request *req)
Request * GetRequest ()
void convertToBitStream (Request *req, HighLevelPacket *hlp)
void convertFromBitStream (Request *req, HighLevelPacket *hlp)
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_out_pull_event (IrisEvent *e)
Private Attributes
uint vcs
uint no_nodes
uint no_outstanding
ullint max_sim_time
deque< HighLevelPacket > out_packets
deque< HighLevelPacket > sent_packets
string out_filename
string trace_name
ofstream out_file
ifstream * trace_filename
unsigned int last_vc
Detailed Description
Definition at line 23 of file genericTPGVcs.h.
Constructor & Destructor Documentation
GenericTPGVcs::GenericTPGVcs ()
Definition at line 15 of file genericTPGVcs.cc.
References last_vc, NetworkComponent::name, Processor::ni_recv, out_filename, and sending.
GenericTPGVcs::~GenericTPGVcs ()
Definition at line 26 of file genericTPGVcs.cc.
References MSHR_H::mshr, mshrHandler, out_file, and MSHR_H::trace_filename.
Member Function Documentation
bool GenericTPGVcs::compare ()
void GenericTPGVcs::convertFromBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 494 of file genericTPGVcs.cc.
References Request::address, CACHE_BLOCK_SIZE, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, Request::cmdType, Request::data, HighLevelPacket::data, max_phy_link_bits, Request::mcNo, NETWORK_ADDRESS_BITS, Data::size, HighLevelPacket::source, and Data::value.
Referenced by handle_new_packet_event().
void GenericTPGVcs::convertToBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 456 of file genericTPGVcs.cc.
References Request::address, Request::arrivalTime, bool, CACHE_BLOCK_SIZE, CACHE_WRITEBACK, Request::cmdType, HighLevelPacket::data, HighLevelPacket::data_payload_length, max_phy_link_bits, HighLevelPacket::msg_class, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, ONE_FLIT_REQ, HighLevelPacket::sent_time, Request::threadId, and WRITE_REQ.
Referenced by handle_out_pull_event().
void GenericTPGVcs::finish ()
Definition at line 159 of file genericTPGVcs.cc.
References out_file, and trace_filename.
bool GenericTPGVcs::GetNewRequest (Request * req) [private]
Definition at line 412 of file genericTPGVcs.cc.
References MSHR_H::lastScheduledIndex, MSHR_H::mshr, mshrHandler, Simulator::Now(), and MSHR_H::writeQueue.
Referenced by GetRequest().
Request * GenericTPGVcs::GetNextRequest () [private]
Definition at line 374 of file genericTPGVcs.cc.
References Request::address, Request::arrivalTime, Request::cmdType, MSHR_H::GlobalAddrMap(), mshrHandler, NetworkComponent::node_ip, Request::threadId, and trace_filename.
Referenced by handle_out_pull_event().
Request * GenericTPGVcs::GetRequest () [private]
Definition at line 444 of file genericTPGVcs.cc.
References GetNewRequest().
Referenced by handle_out_pull_event().
void GenericTPGVcs::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 188 of file genericTPGVcs.cc.
References _DBG, Request::address, HighLevelPacket::avg_network_latency, convertFromBitStream(), DEBUG, IrisEvent::event_data, HighLevelPacket::hop_count, Processor::interface_connections, last_packet_out_cycle, min_pkt_latency, MSHR_DELETE, mshrHandler, Processor::ni_recv, Simulator::Now(), out_file, out_filename, packets_in, NetworkComponent::process_event(), MSHR_H::process_event(), READY_EVENT, HighLevelPacket::req_start_time, Simulator::Schedule(), HighLevelPacket::sent_time, Request::startTime, HighLevelPacket::stat_memory_serviced_time, stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, HighLevelPacket::toString(), IrisEvent::type, IrisEvent::vc, HighLevelPacket::virtual_channel, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
void GenericTPGVcs::handle_out_pull_event (IrisEvent * e) [private]
Definition at line 245 of file genericTPGVcs.cc.
References _DBG, HighLevelPacket::addr, Request::address, Request::arrivalTime, convertToBitStream(), HighLevelPacket::destination, fwd_path_delay, GetNextRequest(), GetRequest(), Processor::interface_connections, last_vc, lastSentTime, Request::mcNo, MSHR_H::mshr, mshrHandler, NEW_PACKET_EVENT, no_nodes, NetworkComponent::node_ip, Simulator::Now(), OUT_PULL_EVENT, packets, NetworkComponent::process_event(), ready, HighLevelPacket::req_start_time, Simulator::Schedule(), sending, HighLevelPacket::sent_time, HighLevelPacket::source, Request::startTime, HighLevelPacket::toString(), HighLevelPacket::transaction_id, IrisEvent::type, vcs, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void GenericTPGVcs::handle_ready_event (IrisEvent * e) [private]
Definition at line 351 of file genericTPGVcs.cc.
References _DBG, max_sim_time, Simulator::Now(), OUT_PULL_EVENT, NetworkComponent::process_event(), ready, Simulator::Schedule(), sending, IrisEvent::vc, and vcs.
Referenced by process_event().
string GenericTPGVcs::print_stats (void) const [virtual]
Implements Processor .
Definition at line 539 of file genericTPGVcs.cc.
References fwd_path_delay, last_packet_out_cycle, min_pkt_latency, mshrHandler, NetworkComponent::node_ip, packets, packets_in, roundTripLat, stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, TotalBLP, and MSHR_H::unsink.
void GenericTPGVcs::process_event (IrisEvent * e) [virtual]
Implements Processor .
Definition at line 167 of file genericTPGVcs.cc.
References NetworkComponent::address, handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), NEW_PACKET_EVENT, OUT_PULL_EVENT, READY_EVENT, and IrisEvent::type.
Referenced by MSHR_H::process_event().
void GenericTPGVcs::set_no_vcs (uint v)
Definition at line 43 of file genericTPGVcs.cc.
References vcs.
void GenericTPGVcs::set_output_path (string outpath) [virtual]
Implements Processor .
Definition at line 141 of file genericTPGVcs.cc.
References NetworkComponent::node_ip, out_file, and out_filename.
void GenericTPGVcs::set_trace_filename (string filename)
Definition at line 36 of file genericTPGVcs.cc.
References trace_name.
void GenericTPGVcs::setup (uint no_nodes, uint vcs, uint max_sim_time) [virtual]
Implements Processor .
Definition at line 49 of file genericTPGVcs.cc.
References Request::address, NetworkComponent::address, Request::arrivalTime, Request::cmdType, MSHR_H::filename, fwd_path_delay, MSHR_H::GlobalAddrMap(), MSHR_H::id, last_packet_out_cycle, last_vc, lastSentTime, max_sim_time, min_pkt_latency, mshrHandler, Component::myId(), no_nodes, NetworkComponent::node_ip, Simulator::Now(), packets, packets_in, MSHR_H::parent, NetworkComponent::process_event(), MSHR_H::process_event(), ready, READY_EVENT, roundTripLat, Simulator::Schedule(), stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, Request::threadId, TotalBLP, MSHR_H::trace_filename, trace_filename, trace_name, and vcs.
string GenericTPGVcs::toString () const [virtual]
Reimplemented from Processor .
Definition at line 526 of file genericTPGVcs.cc.
References NetworkComponent::address, NetworkComponent::node_ip, ready, and trace_name.
Member Data Documentation
ullint GenericTPGVcs::fwd_path_delay
Definition at line 55 of file genericTPGVcs.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
double GenericTPGVcs::last_packet_out_cycle
Definition at line 54 of file genericTPGVcs.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned int GenericTPGVcs::last_vc [private]
Definition at line 37 of file genericTPGVcs.h.
Referenced by GenericTPGVcs(), handle_out_pull_event(), and setup().
ullint GenericTPGVcs::lastSentTime
Definition at line 77 of file genericTPGVcs.h.
Referenced by handle_out_pull_event(), and setup().
ullint GenericTPGVcs::max_sim_time [private]
Definition at line 30 of file genericTPGVcs.h.
Referenced by handle_ready_event(), and setup().
ullint GenericTPGVcs::max_time
Definition at line 66 of file genericTPGVcs.h.
vector<uint> GenericTPGVcs::mc_node_ip
Definition at line 76 of file genericTPGVcs.h.
double GenericTPGVcs::min_pkt_latency
Definition at line 53 of file genericTPGVcs.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
MSHR_H* GenericTPGVcs::mshrHandler
Definition at line 63 of file genericTPGVcs.h.
Referenced by GetNewRequest(), GetNextRequest(), handle_new_packet_event(), handle_out_pull_event(), print_stats(), setup(), and ~GenericTPGVcs().
uint GenericTPGVcs::no_nodes [private]
Definition at line 28 of file genericTPGVcs.h.
Referenced by handle_out_pull_event(), and setup().
uint GenericTPGVcs::no_outstanding [private]
Definition at line 29 of file genericTPGVcs.h.
ofstream GenericTPGVcs::out_file [private]
Definition at line 35 of file genericTPGVcs.h.
Referenced by finish(), handle_new_packet_event(), set_output_path(), and ~GenericTPGVcs().
string GenericTPGVcs::out_filename [private]
Definition at line 33 of file genericTPGVcs.h.
Referenced by GenericTPGVcs(), handle_new_packet_event(), and set_output_path().
deque< HighLevelPacket > GenericTPGVcs::out_packets [private]
Definition at line 31 of file genericTPGVcs.h.
unsigned int GenericTPGVcs::packets
Definition at line 51 of file genericTPGVcs.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
unsigned int GenericTPGVcs::packets_in
Definition at line 52 of file genericTPGVcs.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
vector< bool > GenericTPGVcs::ready
Definition at line 64 of file genericTPGVcs.h.
Referenced by handle_out_pull_event(), handle_ready_event(), setup(), and toString().
ullint GenericTPGVcs::roundTripLat
Definition at line 56 of file genericTPGVcs.h.
Referenced by print_stats(), and setup().
bool GenericTPGVcs::sending
Definition at line 65 of file genericTPGVcs.h.
Referenced by GenericTPGVcs(), handle_out_pull_event(), and handle_ready_event().
deque< HighLevelPacket > GenericTPGVcs::sent_packets [private]
Definition at line 32 of file genericTPGVcs.h.
ullint GenericTPGVcs::stat_round_trip_hop_count
Definition at line 59 of file genericTPGVcs.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
ullint GenericTPGVcs::stat_round_trip_memory_latency
Definition at line 60 of file genericTPGVcs.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
ullint GenericTPGVcs::stat_round_trip_network_latency
Definition at line 58 of file genericTPGVcs.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
ullint GenericTPGVcs::stat_waiting_in_ni
Definition at line 61 of file genericTPGVcs.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
ullint GenericTPGVcs::TotalBLP
Definition at line 57 of file genericTPGVcs.h.
Referenced by print_stats(), and setup().
ifstream* GenericTPGVcs::trace_filename [private]
Definition at line 36 of file genericTPGVcs.h.
Referenced by finish(), GetNextRequest(), and setup().
string GenericTPGVcs::trace_name [private]
Definition at line 34 of file genericTPGVcs.h.
Referenced by set_trace_filename(), setup(), and toString().
uint GenericTPGVcs::vcs [private]
Definition at line 27 of file genericTPGVcs.h.
Referenced by handle_out_pull_event(), handle_ready_event(), set_no_vcs(), and setup().
The documentation for this class was generated from the following files:
genericTPGVcs.h
genericTPGVcs.cc