BankHandler Class Reference
#include <bank_handler.h>
Public Member Functions
BankHandler ()
constructor
~BankHandler ()
deconstructor
void process_event (IrisEvent *e)
Main process function.
bool HasWork ()
bool MainScheduler (Request *req, int *index)
The wrapper for all scheduling algorithms in this class.
bool PARBS (Request *req, int *index)
Function to implement PAR-BS scheduling policy.
bool FRFCFS (Request *req, int *index)
Function to implement FR-FCFS scheduling policy.
bool FCFS (Request *req, int *index)
Function to implement FCFS scheduling policy.
bool OldestFirst (Request *req, int *index)
Schedule oldest request.
bool RowHitFirst (Request *req, int *index)
Schedule row hits.
bool ReadsFirst (Request *req, int *index)
Schedule read request.
bool HighestRankedFirst (Request *req, UInt highest, int *index)
Schedule highest ranked request.
bool ScheduleUnmarked (Request *req, int *index)
Schedule unmarked request.
void FindRank (int priority[])
Set the rank of each request and return it in priority[].
UInt FindHighest ()
Find the highest ranked request.
bool IsBufferFull ()
Check whether the buffer is full or not.
void SetReadsOWrite (CallerType caller, cache_command cmdType)
Set the Reads over write counter in the current rank.
void SetBypasses (unsigned int index)
Set the bypass counter in the current bank.
void SetPrevState ()
Set the previous state.
void RestorePrevState ()
Restore the previous state.
std::string toString ()
Public Attributes
UInt bankId
Id of the bank in current rank.
UInt bufferId
Id of the buffer to look for.
void * myRank
pointer to its rank handler
Component * parent
pointer to its request handler
bool bufferFull
signal to indicate that the buffer is full
UInt myChannel
Id of the channel.
UInt rowBufferIndex
Index of current row in the row buffer.
UInt prevBufferIndex
Index of previous row in the row buffer (A temporary to restore previous state).
bool rowOpen
Signal to indicate a row is open or not.
unsigned int bypassReq
Counter of requests that have bypassed the first one.
bool prevRowOpen
A temporary for row open to restore previous state.
unsigned int prevBypassReq
Temporary of bypass counter.
unsigned int bankTag
Counter to indicate the current tag.
unsigned long long int bufferFullCounter
unsigned long long int bufferOccupancy
unsigned long long int bufferSize
Private Attributes
bool generated
uint address
Detailed Description
Definition at line 49 of file bank_handler.h.
Constructor & Destructor Documentation
BankHandler::BankHandler ()
constructor
Definition at line 29 of file bank_handler.cc.
References bufferFull, bufferFullCounter, bufferOccupancy, bufferSize, bypassReq, generated, prevBufferIndex, prevBypassReq, prevRowOpen, rowBufferIndex, and rowOpen.
BankHandler::~BankHandler ()
deconstructor
Definition at line 52 of file bank_handler.cc.
Member Function Documentation
bool BankHandler::FCFS (Request * req, int * index)
Function to implement FCFS scheduling policy.
Definition at line 355 of file bank_handler.cc.
References bufferId, myRank, OldestFirst(), and RankHandler::rbuffer.
Referenced by MainScheduler().
UInt BankHandler::FindHighest ()
Find the highest ranked request.
Definition at line 550 of file bank_handler.cc.
References MAX_BUFFER_SIZE, myRank, NO_OF_BUFFERS, NO_OF_THREADS, and RankHandler::rbuffer.
Referenced by PARBS().
void BankHandler::FindRank (int priority[])
Set the rank of each request and return it in priority[].
bool BankHandler::FRFCFS (Request * req, int * index)
Function to implement FR-FCFS scheduling policy.
Definition at line 337 of file bank_handler.cc.
References bufferId, myRank, OldestFirst(), RankHandler::rbuffer, ReadsFirst(), and RowHitFirst().
Referenced by MainScheduler().
bool BankHandler::HasWork ()
Definition at line 237 of file bank_handler.cc.
References bankId, and myRank.
Referenced by process_event().
bool BankHandler::HighestRankedFirst (Request * req, UInt highest, int * index)
Schedule highest ranked request.
Definition at line 515 of file bank_handler.cc.
References bankId, Request::bankNo, bufferId, CLOSED, Request::cmdType, CONFLICT, HIGHEST_RANKED_FIRST, myRank, OPEN, RankHandler::rbuffer, rowBufferIndex, Request::rowNo, rowOpen, SetBypasses(), SetPrevState(), SetReadsOWrite(), Request::status, and Request::threadId.
Referenced by PARBS().
bool BankHandler::IsBufferFull ()
Check whether the buffer is full or not.
Definition at line 245 of file bank_handler.cc.
References bufferFull, bufferId, MAX_BUFFER_SIZE, and myRank.
Referenced by process_event().
bool BankHandler::MainScheduler (Request * req, int * index)
The wrapper for all scheduling algorithms in this class.
Definition at line 261 of file bank_handler.cc.
References CLOSE_PAGE_POLICY, dram_page_policy, FC_FS, FCFS(), FR_FCFS, FRFCFS(), mc_scheduling_algorithm, OPEN_PAGE_POLICY, PAR_BS, and PARBS().
Referenced by process_event().
bool BankHandler::OldestFirst (Request * req, int * index)
Schedule oldest request.
Definition at line 372 of file bank_handler.cc.
References bankId, Request::bankNo, bufferId, CLOSE_PAGE_POLICY, CLOSED, Request::cmdType, CONFLICT, dram_page_policy, myRank, OLDEST_FIRST, OPEN, OPEN_PAGE_POLICY, RankHandler::rbuffer, rowBufferIndex, Request::rowNo, rowOpen, SetPrevState(), SetReadsOWrite(), and Request::status.
Referenced by FCFS(), FRFCFS(), and PARBS().
bool BankHandler::PARBS (Request * req, int * index)
Function to implement PAR-BS scheduling policy.
Definition at line 312 of file bank_handler.cc.
References bufferId, FindHighest(), HighestRankedFirst(), myRank, OldestFirst(), RankHandler::rbuffer, ReadsFirst(), RowHitFirst(), and ScheduleUnmarked().
Referenced by MainScheduler().
void BankHandler::process_event (IrisEvent * e)
Main process function.
Definition at line 64 of file bank_handler.cc.
References Request::address, bankId, Request::bankNo, bufferFull, bufferFullCounter, bufferOccupancy, bufferSize, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, Request::cbufferInsertionTime, Request::channelNo, Request::cmdType, CONTINUE, IrisEvent::dst, IrisEvent::event_data, generated, HasWork(), IsBufferFull(), MainScheduler(), myChannel, myRank, Simulator::Now(), parent, RequestHandler::process_event(), ResponseHandler::process_event(), CmdIssuer::process_event(), PUSH_BUFFER, RESPONSE_BUFFER_SIZE, Request::rowNo, Simulator::Schedule(), IrisEvent::src, START, Request::tag, and IrisEvent::type.
Referenced by AddrMap::process_event().
bool BankHandler::ReadsFirst (Request * req, int * index)
Schedule read request.
Definition at line 448 of file bank_handler.cc.
References bankId, Request::bankNo, bufferId, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, CLOSED, Request::cmdType, CONFLICT, MAX_READ_OV_WRITE, myRank, OPEN, RankHandler::rbuffer, READS_FIRST, RankHandler::readsOWrite, rowBufferIndex, Request::rowNo, rowOpen, SetBypasses(), SetPrevState(), SetReadsOWrite(), and Request::status.
Referenced by FRFCFS(), and PARBS().
void BankHandler::RestorePrevState ()
Restore the previous state.
Definition at line 658 of file bank_handler.cc.
References bypassReq, myRank, prevBufferIndex, prevBypassReq, RankHandler::prevReadsOWrite, prevRowOpen, RankHandler::readsOWrite, rowBufferIndex, and rowOpen.
bool BankHandler::RowHitFirst (Request * req, int * index)
Schedule row hits.
Definition at line 413 of file bank_handler.cc.
References bankId, Request::bankNo, bufferId, CLOSED, Request::cmdType, CONFLICT, HIT_FIRST, myRank, OPEN, RankHandler::rbuffer, rowBufferIndex, Request::rowNo, rowOpen, SetBypasses(), SetPrevState(), SetReadsOWrite(), and Request::status.
Referenced by FRFCFS(), and PARBS().
bool BankHandler::ScheduleUnmarked (Request * req, int * index)
Schedule unmarked request.
Definition at line 484 of file bank_handler.cc.
References bankId, Request::bankNo, bufferId, CLOSED, Request::cmdType, CONFLICT, myRank, OPEN, RankHandler::rbuffer, rowBufferIndex, Request::rowNo, rowOpen, SetPrevState(), SetReadsOWrite(), Request::status, and UNMARKED_FIRST.
Referenced by PARBS().
void BankHandler::SetBypasses (unsigned int index)
Set the bypass counter in the current bank.
Definition at line 630 of file bank_handler.cc.
References bankId, bufferId, bypassReq, myRank, and RankHandler::rbuffer.
Referenced by HighestRankedFirst(), ReadsFirst(), and RowHitFirst().
void BankHandler::SetPrevState ()
Set the previous state.
Definition at line 649 of file bank_handler.cc.
References bypassReq, myRank, prevBufferIndex, prevBypassReq, RankHandler::prevReadsOWrite, prevRowOpen, RankHandler::readsOWrite, rowBufferIndex, and rowOpen.
Referenced by HighestRankedFirst(), OldestFirst(), ReadsFirst(), RowHitFirst(), and ScheduleUnmarked().
void BankHandler::SetReadsOWrite (CallerType caller, cache_command cmdType)
Set the Reads over write counter in the current rank.
Definition at line 600 of file bank_handler.cc.
References CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, HIGHEST_RANKED_FIRST, HIT_FIRST, myRank, OLDEST_FIRST, RankHandler::readsOWrite, and UNMARKED_FIRST.
Referenced by HighestRankedFirst(), OldestFirst(), ReadsFirst(), RowHitFirst(), and ScheduleUnmarked().
std::string BankHandler::toString ()
Definition at line 256 of file bank_handler.cc.
Member Data Documentation
uint BankHandler::address [private]
Definition at line 103 of file bank_handler.h.
UInt BankHandler::bankId
Id of the bank in current rank.
Definition at line 54 of file bank_handler.h.
Referenced by HasWork(), HighestRankedFirst(), OldestFirst(), process_event(), ReadsFirst(), RowHitFirst(), ScheduleUnmarked(), and SetBypasses().
unsigned int BankHandler::bankTag
Counter to indicate the current tag.
Definition at line 90 of file bank_handler.h.
bool BankHandler::bufferFull
signal to indicate that the buffer is full
Definition at line 60 of file bank_handler.h.
Referenced by BankHandler(), IsBufferFull(), and process_event().
unsigned long long int BankHandler::bufferFullCounter
Definition at line 95 of file bank_handler.h.
Referenced by BankHandler(), and process_event().
UInt BankHandler::bufferId
Id of the buffer to look for.
Definition at line 55 of file bank_handler.h.
Referenced by FCFS(), FRFCFS(), HighestRankedFirst(), IsBufferFull(), OldestFirst(), PARBS(), ReadsFirst(), RowHitFirst(), ScheduleUnmarked(), and SetBypasses().
unsigned long long int BankHandler::bufferOccupancy
Definition at line 96 of file bank_handler.h.
Referenced by BankHandler(), and process_event().
unsigned long long int BankHandler::bufferSize
Definition at line 97 of file bank_handler.h.
Referenced by BankHandler(), and process_event().
unsigned int BankHandler::bypassReq
Counter of requests that have bypassed the first one.
Definition at line 87 of file bank_handler.h.
Referenced by BankHandler(), RestorePrevState(), SetBypasses(), and SetPrevState().
bool BankHandler::generated [private]
Definition at line 102 of file bank_handler.h.
Referenced by BankHandler(), and process_event().
UInt BankHandler::myChannel
Id of the channel.
Definition at line 83 of file bank_handler.h.
Referenced by process_event().
void* BankHandler::myRank
pointer to its rank handler
Definition at line 56 of file bank_handler.h.
Referenced by FCFS(), FindHighest(), FRFCFS(), HasWork(), HighestRankedFirst(), IsBufferFull(), OldestFirst(), PARBS(), process_event(), ReadsFirst(), RestorePrevState(), RowHitFirst(), ScheduleUnmarked(), SetBypasses(), SetPrevState(), and SetReadsOWrite().
Component* BankHandler::parent
pointer to its request handler
Definition at line 57 of file bank_handler.h.
Referenced by process_event().
UInt BankHandler::prevBufferIndex
Index of previous row in the row buffer (A temporary to restore previous state).
Definition at line 85 of file bank_handler.h.
Referenced by BankHandler(), RestorePrevState(), and SetPrevState().
unsigned int BankHandler::prevBypassReq
Temporary of bypass counter.
Definition at line 89 of file bank_handler.h.
Referenced by BankHandler(), RestorePrevState(), and SetPrevState().
bool BankHandler::prevRowOpen
A temporary for row open to restore previous state.
Definition at line 88 of file bank_handler.h.
Referenced by BankHandler(), RestorePrevState(), and SetPrevState().
UInt BankHandler::rowBufferIndex
Index of current row in the row buffer.
Definition at line 84 of file bank_handler.h.
Referenced by BankHandler(), HighestRankedFirst(), OldestFirst(), ReadsFirst(), RestorePrevState(), RowHitFirst(), ScheduleUnmarked(), and SetPrevState().
bool BankHandler::rowOpen
Signal to indicate a row is open or not.
Definition at line 86 of file bank_handler.h.
Referenced by BankHandler(), HighestRankedFirst(), OldestFirst(), ReadsFirst(), RestorePrevState(), RowHitFirst(), ScheduleUnmarked(), and SetPrevState().
The documentation for this class was generated from the following files:
bank_handler.h
bank_handler.cc