GenericTPG Class Reference
#include <genericTPG.h>
Public Member Functions
GenericTPG ()
~GenericTPG ()
void setup (uint no_nodes, uint vcs, uint max_sim_time)
void finish ()
void process_event (IrisEvent *e)
string toString () const
string print_stats () const
void set_trace_filename (string filename)
void set_no_vcs (uint v)
void set_output_path (string outpath)
bool compare ()
Public Attributes
unsigned int packets
unsigned int packets_in
double min_pkt_latency
double last_packet_out_cycle
unsigned long long int fwd_path_delay
unsigned long long int roundTripLat
unsigned long long int stat_round_trip_network_latency
unsigned long long int stat_round_trip_hop_count
unsigned long long int stat_round_trip_memory_latency
unsigned long long int stat_waiting_in_ni
MSHR_H * mshrHandler
vector< bool > ready
bool sending
unsigned long long int max_time
vector< uint > mc_node_ip
unsigned int bankInfo [8][NO_OF_BUFFERS]
Private Member Functions
Request * GetNextRequest ()
bool GetNewRequest (Request *req)
Request * GetRequest ()
void convertToBitStream (Request *req, HighLevelPacket *hlp)
void convertFromBitStream (Request *req, HighLevelPacket *hlp)
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_out_pull_event (IrisEvent *e)
Private Attributes
uint vcs
uint no_nodes
uint no_outstanding
unsigned long long int max_sim_time
deque< HighLevelPacket > out_packets
deque< HighLevelPacket > sent_packets
string out_filename
string trace_name
ofstream out_file
ifstream * trace_filename
unsigned int last_vc
Detailed Description
Definition at line 25 of file genericTPG.h.
Constructor & Destructor Documentation
GenericTPG::GenericTPG ()
Definition at line 12 of file genericTPG.cc.
References Processor::interface_connections, last_vc, NetworkComponent::name, out_filename, and sending.
GenericTPG::~GenericTPG ()
Definition at line 22 of file genericTPG.cc.
References MSHR_H::mshr, mshrHandler, out_file, and MSHR_H::trace_filename.
Member Function Documentation
bool GenericTPG::compare ()
void GenericTPG::convertFromBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 441 of file genericTPG.cc.
References Request::address, bankInfo, CACHE_BLOCK_SIZE, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, Request::cmdType, Request::data, HighLevelPacket::data, MAX_BUFFER_SIZE, max_phy_link_bits, Request::mcNo, NETWORK_ADDRESS_BITS, NO_OF_BUFFERS, Data::size, HighLevelPacket::source, and Data::value.
Referenced by handle_new_packet_event().
void GenericTPG::convertToBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 404 of file genericTPG.cc.
References Request::address, Request::arrivalTime, bool, CACHE_BLOCK_SIZE, CACHE_WRITEBACK, Request::cmdType, HighLevelPacket::data, HighLevelPacket::data_payload_length, max_phy_link_bits, HighLevelPacket::msg_class, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, ONE_FLIT_REQ, HighLevelPacket::sent_time, Request::threadId, and WRITE_REQ.
Referenced by handle_out_pull_event().
void GenericTPG::finish ()
Definition at line 153 of file genericTPG.cc.
References out_file, and trace_filename.
bool GenericTPG::GetNewRequest (Request * req) [private]
Definition at line 357 of file genericTPG.cc.
References MSHR_H::lastScheduledIndex, MSHR_H::mshr, mshrHandler, Simulator::Now(), and MSHR_H::writeQueue.
Referenced by GetRequest().
Request * GenericTPG::GetNextRequest () [private]
Definition at line 319 of file genericTPG.cc.
References Request::address, Request::arrivalTime, Request::cmdType, MSHR_H::GlobalAddrMap(), mshrHandler, NetworkComponent::node_ip, Request::threadId, and trace_filename.
Referenced by handle_out_pull_event().
Request * GenericTPG::GetRequest () [private]
Definition at line 392 of file genericTPG.cc.
References GetNewRequest().
Referenced by handle_out_pull_event().
void GenericTPG::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 182 of file genericTPG.cc.
References _DBG, Request::address, HighLevelPacket::avg_network_latency, convertFromBitStream(), IrisEvent::event_data, HighLevelPacket::hop_count, Processor::interface_connections, last_packet_out_cycle, min_pkt_latency, MSHR_DELETE, mshrHandler, Simulator::Now(), out_file, out_filename, packets_in, NetworkComponent::process_event(), MSHR_H::process_event(), READY_EVENT, HighLevelPacket::req_start_time, Simulator::Schedule(), HighLevelPacket::sent_time, Request::startTime, HighLevelPacket::stat_memory_serviced_time, stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, HighLevelPacket::toString(), IrisEvent::type, IrisEvent::vc, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
void GenericTPG::handle_out_pull_event (IrisEvent * e) [private]
Definition at line 243 of file genericTPG.cc.
References _DBG, HighLevelPacket::addr, Request::address, Request::arrivalTime, convertToBitStream(), HighLevelPacket::destination, fwd_path_delay, GetNextRequest(), GetRequest(), Processor::interface_connections, MSHR_H::lastScheduledIndex, Request::mcNo, MSHR_H::mshr, mshrHandler, NEW_PACKET_EVENT, no_nodes, NetworkComponent::node_ip, Simulator::Now(), OUT_PULL_EVENT, packets, NetworkComponent::process_event(), ready, HighLevelPacket::req_start_time, Simulator::Schedule(), sending, HighLevelPacket::sent_time, HighLevelPacket::source, Request::startTime, HighLevelPacket::transaction_id, IrisEvent::type, IrisEvent::vc, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void GenericTPG::handle_ready_event (IrisEvent * e) [private]
Definition at line 301 of file genericTPG.cc.
References max_sim_time, Simulator::Now(), OUT_PULL_EVENT, NetworkComponent::process_event(), ready, Simulator::Schedule(), and sending.
Referenced by process_event().
string GenericTPG::print_stats (void) const [virtual]
Implements Processor .
Definition at line 499 of file genericTPG.cc.
References fwd_path_delay, last_packet_out_cycle, min_pkt_latency, mshrHandler, NetworkComponent::node_ip, packets, packets_in, roundTripLat, stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, and MSHR_H::unsink.
void GenericTPG::process_event (IrisEvent * e) [virtual]
Implements Processor .
Definition at line 161 of file genericTPG.cc.
References NetworkComponent::address, handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), NEW_PACKET_EVENT, OUT_PULL_EVENT, READY_EVENT, and IrisEvent::type.
void GenericTPG::set_no_vcs (uint v)
Definition at line 39 of file genericTPG.cc.
References vcs.
void GenericTPG::set_output_path (string outpath) [virtual]
Implements Processor .
Definition at line 135 of file genericTPG.cc.
References NetworkComponent::node_ip, out_file, and out_filename.
void GenericTPG::set_trace_filename (string filename)
Definition at line 32 of file genericTPG.cc.
References trace_name.
void GenericTPG::setup (uint no_nodes, uint vcs, uint max_sim_time) [virtual]
Implements Processor .
Definition at line 45 of file genericTPG.cc.
References Request::address, NetworkComponent::address, Request::arrivalTime, Request::cmdType, MSHR_H::filename, fwd_path_delay, MSHR_H::GlobalAddrMap(), MSHR_H::id, last_packet_out_cycle, max_sim_time, min_pkt_latency, mshrHandler, Component::myId(), no_nodes, NetworkComponent::node_ip, Simulator::Now(), packets, packets_in, MSHR_H::parent, NetworkComponent::process_event(), MSHR_H::process_event(), ready, READY_EVENT, roundTripLat, Simulator::Schedule(), stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, Request::threadId, MSHR_H::trace_filename, trace_filename, trace_name, and vcs.
string GenericTPG::toString () const [virtual]
Reimplemented from Processor .
Definition at line 486 of file genericTPG.cc.
References NetworkComponent::address, NetworkComponent::node_ip, ready, and trace_name.
Member Data Documentation
unsigned int GenericTPG::bankInfo[8][NO_OF_BUFFERS]
Definition at line 78 of file genericTPG.h.
Referenced by convertFromBitStream().
unsigned long long int GenericTPG::fwd_path_delay
Definition at line 57 of file genericTPG.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
double GenericTPG::last_packet_out_cycle
Definition at line 56 of file genericTPG.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned int GenericTPG::last_vc [private]
Definition at line 39 of file genericTPG.h.
Referenced by GenericTPG().
unsigned long long int GenericTPG::max_sim_time [private]
Definition at line 32 of file genericTPG.h.
Referenced by handle_ready_event(), and setup().
unsigned long long int GenericTPG::max_time
Definition at line 67 of file genericTPG.h.
vector<uint> GenericTPG::mc_node_ip
Definition at line 77 of file genericTPG.h.
double GenericTPG::min_pkt_latency
Definition at line 55 of file genericTPG.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
MSHR_H* GenericTPG::mshrHandler
Definition at line 64 of file genericTPG.h.
Referenced by GetNewRequest(), GetNextRequest(), handle_new_packet_event(), handle_out_pull_event(), print_stats(), setup(), and ~GenericTPG().
uint GenericTPG::no_nodes [private]
Definition at line 30 of file genericTPG.h.
Referenced by handle_out_pull_event(), and setup().
uint GenericTPG::no_outstanding [private]
Definition at line 31 of file genericTPG.h.
ofstream GenericTPG::out_file [private]
Definition at line 37 of file genericTPG.h.
Referenced by finish(), handle_new_packet_event(), set_output_path(), and ~GenericTPG().
string GenericTPG::out_filename [private]
Definition at line 35 of file genericTPG.h.
Referenced by GenericTPG(), handle_new_packet_event(), and set_output_path().
deque< HighLevelPacket > GenericTPG::out_packets [private]
Definition at line 33 of file genericTPG.h.
unsigned int GenericTPG::packets
Definition at line 53 of file genericTPG.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
unsigned int GenericTPG::packets_in
Definition at line 54 of file genericTPG.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
vector< bool > GenericTPG::ready
Definition at line 65 of file genericTPG.h.
Referenced by handle_out_pull_event(), handle_ready_event(), setup(), and toString().
unsigned long long int GenericTPG::roundTripLat
Definition at line 58 of file genericTPG.h.
Referenced by print_stats(), and setup().
bool GenericTPG::sending
Definition at line 66 of file genericTPG.h.
Referenced by GenericTPG(), handle_out_pull_event(), and handle_ready_event().
deque< HighLevelPacket > GenericTPG::sent_packets [private]
Definition at line 34 of file genericTPG.h.
unsigned long long int GenericTPG::stat_round_trip_hop_count
Definition at line 60 of file genericTPG.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int GenericTPG::stat_round_trip_memory_latency
Definition at line 61 of file genericTPG.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int GenericTPG::stat_round_trip_network_latency
Definition at line 59 of file genericTPG.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int GenericTPG::stat_waiting_in_ni
Definition at line 62 of file genericTPG.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
ifstream* GenericTPG::trace_filename [private]
Definition at line 38 of file genericTPG.h.
Referenced by finish(), GetNextRequest(), and setup().
string GenericTPG::trace_name [private]
Definition at line 36 of file genericTPG.h.
Referenced by set_trace_filename(), setup(), and toString().
uint GenericTPG::vcs [private]
Definition at line 29 of file genericTPG.h.
Referenced by set_no_vcs(), and setup().
The documentation for this class was generated from the following files:
genericTPG.h
genericTPG.cc