core_fetch_DPM_t Class Reference
Classes
struct byteQ_entry_t
struct jeclear_pipe_t
Public Member Functions
core_fetch_DPM_t (struct core_t *const core)
virtual void reg_stats (struct stat_sdb_t *const sdb)
virtual void update_occupancy (void)
virtual void step (void)
virtual bool Mop_available (void)
virtual struct Mop_t * Mop_peek (void)
virtual void Mop_consume (void)
virtual void jeclear_enqueue (struct Mop_t *const Mop, const md_addr_t New_PC)
virtual void recover (const md_addr_t new_PC)
Protected Member Functions
bool predecode_enqueue (struct Mop_t *const Mop)
void byteQ_request (const md_addr_t lineaddr, const md_addr_t lineaddr_phys)
bool byteQ_is_full (void)
bool byteQ_already_requested (const md_addr_t addr)
Static Protected Member Functions
static void IL1_callback (void *const op)
static void ITLB_callback (void *const op)
static bool translated_callback (void *const op, const seq_t action_id)
static seq_t get_byteQ_action_id (void *const op)
Protected Attributes
int byteQ_num
int IQ_num
int IQ_uop_num
int IQ_eff_uop_num
struct core_fetch_DPM_t::byteQ_entry_t * byteQ
int byteQ_linemask
int byteQ_head
int byteQ_tail
struct Mop_t ** IQ
int IQ_head
int IQ_tail
struct Mop_t *** pipe
struct core_fetch_DPM_t::jeclear_pipe_t * jeclear_pipe
Static Protected Attributes
static const char * fetch_stall_str [FSTALL_num]
Private Types
enum fetch_stall_t {
FSTALL_byteQ_FULL,
FSTALL_TBR,
FSTALL_EOL,
FSTALL_SPLIT,
FSTALL_BOGUS,
FSTALL_SYSCALL,
FSTALL_ZPAGE,
FSTALL_num
 }
Detailed Description
Definition at line 11 of file fetch-DPM.cpp.
Member Enumeration Documentation
enum core_fetch_DPM_t::fetch_stall_t [private]
Enumerator:
FSTALL_byteQ_FULL
FSTALL_TBR
FSTALL_EOL
FSTALL_SPLIT
FSTALL_BOGUS
FSTALL_SYSCALL
FSTALL_ZPAGE
FSTALL_num
Definition at line 13 of file fetch-DPM.cpp.
Constructor & Destructor Documentation
core_fetch_DPM_t::core_fetch_DPM_t (struct core_t *const core)
Definition at line 114 of file fetch-DPM.cpp.
References core_fetch_t::bpred, core_knobs_t::bpred_opt_str, byteQ, byteQ_head, byteQ_linemask, core_knobs_t::byteQ_linesize, core_knobs_t::byteQ_size, byteQ_tail, cache_create(), CACHE_READONLY, core_fetch_t::core, core_knobs_t::depth, core_knobs_t::dirjmpbtb_opt_str, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::DL2_bus, fatal(), core_knobs_t::fetch, core_knobs_t::fusion_opt_str, core_t::core_t::core_memory_t::IL1, core_knobs_t::IL1_high_watermark, core_knobs_t::IL1_low_watermark, core_knobs_t::IL1_num_PF, core_knobs_t::IL1_opt_str, core_knobs_t::IL1_PF_buffer_size, core_knobs_t::IL1_PF_filter_reset, core_knobs_t::IL1_PF_filter_size, core_knobs_t::IL1_PF_on_miss, core_knobs_t::IL1_PFFsize, core_knobs_t::IL1_PFmax, core_knobs_t::IL1_PFthresh, core_knobs_t::IL1_WMinterval, core_knobs_t::IL1PF_opt_str, core_knobs_t::indirjmpbtb_opt_str, IQ, IQ_head, core_knobs_t::IQ_size, IQ_tail, core_t::core_t::core_memory_t::ITLB, core_knobs_t::ITLB_opt_str, core_knobs_t::jeclear_delay, jeclear_pipe, core_t::knobs, knobs, core_knobs_t::latency, uncore_t::LLC, uncore_t::LLC_bus, core_t::memory, core_knobs_t::memory, cache_t::name, core_knobs_t::num_bpred_components, cache_t::num_prefetchers, cache_t::PF_high_watermark, cache_t::PF_low_watermark, cache_t::PF_sample_interval, cache_t::PFF, cache_t::PFF_size, pipe, prefetch_buffer_create(), prefetch_create(), prefetch_filter_create(), cache_t::prefetch_max, cache_t::prefetch_on_miss, cache_t::prefetch_threshold, cache_t::prefetcher, core_knobs_t::ras_opt_str, core_t::uncore, and core_knobs_t::width.
Member Function Documentation
bool core_fetch_DPM_t::byteQ_already_requested (const md_addr_t addr) [protected]
Definition at line 352 of file fetch-DPM.cpp.
References byteQ, byteQ_linemask, byteQ_num, core_knobs_t::byteQ_size, byteQ_tail, core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, knobs, and moddec().
Referenced by step().
bool core_fetch_DPM_t::byteQ_is_full (void) [protected]
Definition at line 345 of file fetch-DPM.cpp.
References byteQ_num, core_knobs_t::byteQ_size, core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, and knobs.
Referenced by step().
void core_fetch_DPM_t::byteQ_request (const md_addr_t lineaddr, const md_addr_t lineaddr_phys) [protected]
Definition at line 363 of file fetch-DPM.cpp.
References core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::action_id, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::addr, byteQ, byteQ_num, core_knobs_t::byteQ_size, byteQ_tail, core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, knobs, modinc(), core_t::new_action_id(), core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::paddr, TICK_T_MAX, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_fetch_requested, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_fetched, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translated, and core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translation_requested.
Referenced by step().
seq_t core_fetch_DPM_t::get_byteQ_action_id (void *const op) [static, protected]
Definition at line 406 of file fetch-DPM.cpp.
References core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::action_id, and byteQ.
Referenced by step().
void core_fetch_DPM_t::IL1_callback (void *const op) [static, protected]
Definition at line 383 of file fetch-DPM.cpp.
References byteQ, sim_cycle, and core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_fetched.
Referenced by step().
void core_fetch_DPM_t::ITLB_callback (void *const op) [static, protected]
Definition at line 390 of file fetch-DPM.cpp.
References byteQ, sim_cycle, and core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translated.
Referenced by step().
void core_fetch_DPM_t::jeclear_enqueue (struct Mop_t *const Mop, const md_addr_t New_PC) [virtual]
Implements core_fetch_t .
Definition at line 816 of file fetch-DPM.cpp.
References core_fetch_DPM_t::core_fetch_DPM_t::jeclear_pipe_t::action_id, core_fetch_t::core, jeclear_pipe, core_fetch_DPM_t::core_fetch_DPM_t::jeclear_pipe_t::Mop, core_t::new_action_id(), core_fetch_DPM_t::core_fetch_DPM_t::jeclear_pipe_t::New_PC, Mop_t::oracle, and Mop_t::seq.
bool core_fetch_DPM_t::Mop_available (void) [virtual]
Implements core_fetch_t .
Definition at line 792 of file fetch-DPM.cpp.
References IQ_num.
void core_fetch_DPM_t::Mop_consume (void) [virtual]
Implements core_fetch_t .
Definition at line 802 of file fetch-DPM.cpp.
References core_fetch_t::core, core_knobs_t::fetch, IQ, IQ_eff_uop_num, IQ_head, IQ_num, core_knobs_t::IQ_size, IQ_uop_num, core_t::knobs, knobs, modinc(), Mop_t::num_eff_uops, Mop_t::num_uops, Mop_t::stat, and zesto_assert.
struct Mop_t * core_fetch_DPM_t::Mop_peek (void) [read, virtual]
Implements core_fetch_t .
Definition at line 797 of file fetch-DPM.cpp.
References IQ, and IQ_head.
bool core_fetch_DPM_t::predecode_enqueue (struct Mop_t *const Mop) [protected]
Definition at line 413 of file fetch-DPM.cpp.
References core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, knobs, pipe, and core_knobs_t::width.
Referenced by step().
void core_fetch_DPM_t::recover (const md_addr_t new_PC) [virtual]
Implements core_fetch_t .
Definition at line 851 of file fetch-DPM.cpp.
References core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::action_id, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::addr, core_fetch_t::bogus, byteQ, byteQ_head, byteQ_num, core_knobs_t::byteQ_size, byteQ_tail, core_fetch_t::core, core_knobs_t::depth, core_knobs_t::fetch, IQ, IQ_eff_uop_num, IQ_head, IQ_num, core_knobs_t::IQ_size, IQ_tail, IQ_uop_num, core_t::knobs, knobs, memzero(), core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::MopQ_first_index, core_t::new_action_id(), core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::num_Mop, core_fetch_t::PC, pipe, TICK_T_MAX, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_fetch_requested, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_fetched, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translated, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translation_requested, and core_knobs_t::width.
Referenced by step().
void core_fetch_DPM_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Implements core_fetch_t .
Definition at line 217 of file fetch-DPM.cpp.
References core_fetch_t::bpred, core_t::core_t::core_stat_t::byteQ_occupancy, cache_reg_stats(), core_fetch_t::core, core_t::current_thread, core_t::core_t::core_stat_t::fetch_bytes, core_t::core_t::core_stat_t::fetch_eff_uops, core_t::core_t::core_stat_t::fetch_insn, core_t::core_t::core_stat_t::fetch_stall, fetch_stall_str, core_t::core_t::core_stat_t::fetch_uops, FSTALL_num, thread_t::id, core_t::core_t::core_memory_t::IL1, core_t::core_t::core_stat_t::IQ_eff_uop_occupancy, core_t::core_t::core_stat_t::IQ_empty_cycles, core_t::core_t::core_stat_t::IQ_full_cycles, core_t::core_t::core_stat_t::IQ_occupancy, core_t::core_t::core_stat_t::IQ_uop_occupancy, core_t::core_t::core_memory_t::ITLB, core_t::memory, PF_COUNT, PF_PDF, core_t::core_t::core_stat_t::predecode_bytes, core_t::core_t::core_stat_t::predecode_eff_uops, core_t::core_t::core_stat_t::predecode_insn, core_t::core_t::core_stat_t::predecode_uops, bpred_t::reg_stats(), core_t::stat, stat_reg_counter, stat_reg_dist(), stat_reg_formula(), and stat_reg_note().
void core_fetch_DPM_t::step (void) [virtual]
Implements core_fetch_t .
Definition at line 450 of file fetch-DPM.cpp.
References core_fetch_DPM_t::core_fetch_DPM_t::jeclear_pipe_t::action_id, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::action_id, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::addr, core_t::alloc, core_fetch_t::bogus, core_fetch_t::bpred, Mop_t::bpred_update, Mop_t::branch_mispred, byteQ, byteQ_already_requested(), byteQ_head, byteQ_is_full(), byteQ_linemask, byteQ_num, byteQ_request(), core_knobs_t::byteQ_size, byteQ_tail, cache_enqueuable(), cache_enqueue(), cache_process(), CACHE_READ, cache_t::check_for_work, Mop_t::commit, core_t::commit, core_oracle_t::consume(), Mop_t::core, core_fetch_t::core, core_t::current_thread, core_t::decode, uop_t::decode, Mop_t::decode, core_knobs_t::depth, uop_t::EOM, core_t::exec, core_oracle_t::exec(), Mop_t::fetch, core_knobs_t::fetch, core_t::core_t::core_stat_t::fetch_bytes, core_t::core_t::core_stat_t::fetch_eff_uops, core_t::core_t::core_stat_t::fetch_insn, core_t::core_t::core_stat_t::fetch_stall, core_t::core_t::core_stat_t::fetch_uops, Mop_t::first_byte_requested, FSTALL_BOGUS, FSTALL_byteQ_FULL, FSTALL_EOL, FSTALL_SPLIT, FSTALL_SYSCALL, FSTALL_TBR, FSTALL_ZPAGE, get_byteQ_action_id(), core_oracle_t::get_index(), core_oracle_t::get_Mop(), bpred_t::get_state_cache(), thread_t::id, core_t::core_t::core_memory_t::IL1, IL1_callback(), Mop_t::inst, IQ, IQ_eff_uop_num, IQ_num, core_knobs_t::IQ_size, IQ_tail, IQ_uop_num, Mop_t::is_ctrl, Mop_t::is_trap, core_t::core_t::core_memory_t::ITLB, ITLB_callback(), Mop_t::jeclear_action_id, core_knobs_t::jeclear_delay, Mop_t::jeclear_in_flight, jeclear_pipe, core_t::knobs, knobs, Mop_t::last_byte_requested, Mop_t::last_uop_index, md_inst_t::len, bpred_t::lookup(), core_t::memory, moddec(), modinc(), core_fetch_DPM_t::core_fetch_DPM_t::jeclear_pipe_t::Mop, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::MopQ_first_index, core_fetch_DPM_t::core_fetch_DPM_t::jeclear_pipe_t::New_PC, core_oracle_t::next_index(), Mop_t::NextPC, NO_MSHR, Mop_t::num_eff_uops, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::num_Mop, Mop_t::num_uops, Mop_t::opflags, uop_t::oracle, Mop_t::oracle, core_t::oracle, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::paddr, md_inst_t::paddr, PAGE_SHIFT, PAGE_TABLE_ADDR, Mop_t::PC, core_fetch_t::PC, pipe, Mop_t::pred_NPC, core_t::core_t::core_stat_t::predecode_bytes, core_t::core_t::core_stat_t::predecode_eff_uops, predecode_enqueue(), core_t::core_t::core_stat_t::predecode_insn, core_t::core_t::core_stat_t::predecode_uops, recover(), core_decode_t::recover(), core_alloc_t::recover(), core_exec_t::recover(), core_commit_t::recover(), core_oracle_t::recover(), bpred_t::recover(), uop_t::recover_inst, Mop_t::recover_inst, thread_t::regs, regs_t::regs_NPC, md_inst_t::rep, sim_cycle, core_oracle_t::spec_mode, bpred_t::spec_update(), Mop_t::stat, core_t::stat, stat_add_sample(), Mop_t::targetPC, TICK_T_MAX, Mop_t::timing, translated_callback(), Mop_t::uop, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_fetch_requested, Mop_t::when_fetch_started, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_fetched, Mop_t::when_fetched, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translated, core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translation_requested, core_knobs_t::width, zesto_assert, and ZESTO_STAT.
bool core_fetch_DPM_t::translated_callback (void *const op, const seq_t action_id) [static, protected]
Definition at line 397 of file fetch-DPM.cpp.
References core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::action_id, byteQ, sim_cycle, and core_fetch_DPM_t::core_fetch_DPM_t::byteQ_entry_t::when_translated.
Referenced by step().
void core_fetch_DPM_t::update_occupancy (void) [virtual]
Implements core_fetch_t .
Definition at line 325 of file fetch-DPM.cpp.
References byteQ_num, core_t::core_t::core_stat_t::byteQ_occupancy, core_fetch_t::core, core_knobs_t::fetch, IQ_eff_uop_num, core_t::core_t::core_stat_t::IQ_eff_uop_occupancy, core_t::core_t::core_stat_t::IQ_empty_cycles, core_t::core_t::core_stat_t::IQ_full_cycles, IQ_num, core_t::core_t::core_stat_t::IQ_occupancy, core_knobs_t::IQ_size, IQ_uop_num, core_t::core_t::core_stat_t::IQ_uop_occupancy, core_t::knobs, and core_t::stat.
Member Data Documentation
struct core_fetch_DPM_t::byteQ_entry_t * core_fetch_DPM_t::byteQ [protected]
Referenced by byteQ_already_requested(), byteQ_request(), core_fetch_DPM_t(), get_byteQ_action_id(), IL1_callback(), ITLB_callback(), recover(), step(), and translated_callback().
int core_fetch_DPM_t::byteQ_head [protected]
Definition at line 68 of file fetch-DPM.cpp.
Referenced by core_fetch_DPM_t(), recover(), and step().
int core_fetch_DPM_t::byteQ_linemask [protected]
Definition at line 67 of file fetch-DPM.cpp.
Referenced by byteQ_already_requested(), core_fetch_DPM_t(), and step().
int core_fetch_DPM_t::byteQ_num [protected]
Definition at line 46 of file fetch-DPM.cpp.
Referenced by byteQ_already_requested(), byteQ_is_full(), byteQ_request(), recover(), step(), and update_occupancy().
int core_fetch_DPM_t::byteQ_tail [protected]
Definition at line 69 of file fetch-DPM.cpp.
Referenced by byteQ_already_requested(), byteQ_request(), core_fetch_DPM_t(), recover(), and step().
const char * core_fetch_DPM_t::fetch_stall_str [static, protected]
Initial value:
 {
  "byteQ full             ",
  "taken branch           ",
  "end of cache line      ",
  "inst split on two lines",
  "wrong-path invalid inst",
  "trap waiting on drain  ",
  "request for page zero  "
}
Definition at line 89 of file fetch-DPM.cpp.
Referenced by reg_stats().
struct Mop_t** core_fetch_DPM_t::IQ [read, protected]
Definition at line 72 of file fetch-DPM.cpp.
Referenced by core_fetch_DPM_t(), Mop_consume(), Mop_peek(), recover(), and step().
int core_fetch_DPM_t::IQ_eff_uop_num [protected]
Definition at line 49 of file fetch-DPM.cpp.
Referenced by Mop_consume(), recover(), step(), and update_occupancy().
int core_fetch_DPM_t::IQ_head [protected]
Definition at line 73 of file fetch-DPM.cpp.
Referenced by core_fetch_DPM_t(), Mop_consume(), Mop_peek(), and recover().
int core_fetch_DPM_t::IQ_num [protected]
Definition at line 47 of file fetch-DPM.cpp.
Referenced by Mop_available(), Mop_consume(), recover(), step(), and update_occupancy().
int core_fetch_DPM_t::IQ_tail [protected]
Definition at line 74 of file fetch-DPM.cpp.
Referenced by core_fetch_DPM_t(), recover(), and step().
int core_fetch_DPM_t::IQ_uop_num [protected]
Definition at line 48 of file fetch-DPM.cpp.
Referenced by Mop_consume(), recover(), step(), and update_occupancy().
struct core_fetch_DPM_t::jeclear_pipe_t * core_fetch_DPM_t::jeclear_pipe [protected]
Referenced by core_fetch_DPM_t(), jeclear_enqueue(), and step().
struct Mop_t*** core_fetch_DPM_t::pipe [read, protected]
Definition at line 78 of file fetch-DPM.cpp.
Referenced by core_fetch_DPM_t(), predecode_enqueue(), recover(), and step().
The documentation for this class was generated from the following file:
fetch-DPM.cpp