AddrMap Class Reference
Class for handling adress translations within the Memory Controller =====================================================================================.
#include <addr_map.h>
Public Member Functions
AddrMap ()
constructor
~AddrMap ()
deconstructor
void process_event (IrisEvent *e)
Main function that handles this class.
void map_addr (Request *req)
Main address translation function.
std::string toString ()
Public Attributes
Component * parent
pointer to the request handler
Detailed Description
Class for handling adress translations within the Memory Controller =====================================================================================.
Description:
Definition at line 44 of file addr_map.h.
Constructor & Destructor Documentation
AddrMap::AddrMap ()
constructor
Definition at line 34 of file addr_map.cc.
AddrMap::~AddrMap ()
deconstructor
Definition at line 46 of file addr_map.cc.
Member Function Documentation
void AddrMap::map_addr (Request * req)
Main address translation function.
Definition at line 121 of file addr_map.cc.
References addr_map_scheme, Request::address, BANK_BITS, Request::bankNo, BLOCKS_PER_ROW, CACHE_BLOCK_SIZE, CACHELINE_INTERLEAVING, Request::channelNo, COLUMN_SIZE, Request::columnNo, DRAM_SIZE, GENERIC, LOCAL_ADDR_MAP, Request::lowerBits, NO_OF_BANKS, NO_OF_CHANNELS, NO_OF_COLUMNS, NO_OF_RANKS, NO_OF_ROWS, NO_SCHEME, PAGE_INTERLEAVING, PERMUTATION, Request::rankNo, ROW_SIZE, Request::rowNo, SWAPPING, and TAG_BITS.
Referenced by process_event().
void AddrMap::process_event (IrisEvent * e)
Main function that handles this class.
Definition at line 58 of file addr_map.cc.
References Request::address, Request::bankNo, Request::channelNo, Request::columnNo, map_addr(), Simulator::Now(), parent, BankHandler::process_event(), Request::rankNo, Request::rbufferInsertionTime, Request::rowNo, Simulator::Schedule(), and START.
Referenced by RequestHandler::process_event().
std::string AddrMap::toString ()
Definition at line 116 of file addr_map.cc.
Member Data Documentation
Component* AddrMap::parent
pointer to the request handler
Definition at line 49 of file addr_map.h.
Referenced by process_event(), and RequestHandler::RequestHandler().
The documentation for this class was generated from the following files:
addr_map.h
addr_map.cc