NI Class Reference
#include <NI.h>
Public Member Functions
NI ()
~NI ()
void setup (uint no_nodes, uint vcs, uint max_sim_time)
void finish ()
void process_event (IrisEvent *e)
string toString () const
void set_no_vcs (uint v)
void set_output_path (string v)
bool compare ()
string print_stats () const
Public Attributes
Component * mc
vector< Request > niQueue
uint node_ip
bool sending
Private Member Functions
void handle_new_packet_event (IrisEvent *e)
void handle_old_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_out_pull_event (IrisEvent *e)
void handle_detect_deadlock_event (IrisEvent *)
void convertToBitStream (Request *req, HighLevelPacket *hlp)
void convertFromBitStream (Request *req, HighLevelPacket *hlp)
bool GetFromNIQueue (Request *req)
void add_mc_bits (Request *req)
void strip_mc_bits (Request *req)
Private Attributes
double last_pkt_out_cycle
ullint last_out_pull_cycle
unsigned long long int total_missed_time
unsigned long long int total_backward_time
uint missed_time
unsigned long long int packets_out
ullint resp_buff_occ_cycles
ullint avg_resp_buff_occ
uint vcs
uint no_nodes
unsigned int packets
unsigned long long int max_sim_time
deque< HighLevelPacket > out_packets
deque< HighLevelPacket > sent_packets
vector< HighLevelPacket * > outstanding_hlp
string out_filename
string trace_name
ofstream out_file
fstream trace_filename
vector< bool > ready
unsigned int last_vc
unsigned int flast_vc
Detailed Description
Definition at line 48 of file NI.h.
Constructor & Destructor Documentation
NI::NI ()
Definition at line 29 of file NI.cc.
References mc, NetworkComponent::name, and Processor::ni_recv.
NI::~NI ()
Definition at line 40 of file NI.cc.
Member Function Documentation
void NI::add_mc_bits (Request * req) [private]
Definition at line 131 of file NI.cc.
References Request::address, MC_ADDR_BITS, mc_positions, no_mcs, and node_ip.
Referenced by handle_out_pull_event().
bool NI::compare ()
void NI::convertFromBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 518 of file NI.cc.
References Request::address, Request::cmdType, HighLevelPacket::data, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, and Request::threadId.
Referenced by handle_new_packet_event().
void NI::convertToBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 479 of file NI.cc.
References Request::address, bool, CACHE_BLOCK_SIZE, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, Request::cmdType, HighLevelPacket::data, HighLevelPacket::data_payload_length, max_phy_link_bits, and NETWORK_ADDRESS_BITS.
Referenced by handle_out_pull_event().
void NI::finish ()
Definition at line 101 of file NI.cc.
References out_file.
bool NI::GetFromNIQueue (Request * req) [private]
Definition at line 465 of file NI.cc.
References niQueue.
Referenced by handle_out_pull_event().
void NI::handle_detect_deadlock_event (IrisEvent *) [private]
void NI::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 186 of file NI.cc.
References _DBG, NetworkComponent::address, Request::arrivalTime, HighLevelPacket::avg_network_latency, Request::avg_network_latency, convertFromBitStream(), IrisEvent::dst, IrisEvent::event_data, flast_vc, HighLevelPacket::hop_count, Request::hop_count, Processor::interface_connections, last_pkt_out_cycle, mc, NEW_PACKET_EVENT, Processor::ni_recv, Simulator::Now(), outstanding_hlp, packets, NetworkComponent::process_event(), RequestHandler::process_event(), READY_EVENT, HighLevelPacket::recv_time, HighLevelPacket::req_start_time, Simulator::Schedule(), IrisEvent::src, IrisEvent::src_id, START, Request::startTime, strip_mc_bits(), IrisEvent::toString(), total_missed_time, IrisEvent::type, IrisEvent::vc, vcs, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void NI::handle_old_packet_event (IrisEvent * e) [private]
void NI::handle_out_pull_event (IrisEvent * e) [private]
Definition at line 289 of file NI.cc.
References add_mc_bits(), HighLevelPacket::addr, Request::address, Request::arrivalTime, Request::avg_network_latency, HighLevelPacket::avg_network_latency, avg_resp_buff_occ, convertToBitStream(), HighLevelPacket::destination, IrisEvent::dst, GetFromNIQueue(), Request::hop_count, HighLevelPacket::hop_count, Processor::interface_connections, last_out_pull_cycle, last_vc, mc, HighLevelPacket::msg_class, NEW_PACKET_EVENT, niQueue, node_ip, Simulator::Now(), packets_out, ResponseHandler::process_event(), NetworkComponent::process_event(), ready, HighLevelPacket::recv_time, HighLevelPacket::req_start_time, resp_buff_occ_cycles, RESPONSE_PKT, Request::retireTime, Simulator::Schedule(), SEND_TO_NI, sending, HighLevelPacket::sent_time, HighLevelPacket::source, Request::startTime, HighLevelPacket::stat_memory_serviced_time, Request::threadId, total_backward_time, HighLevelPacket::transaction_id, IrisEvent::type, vcs, HighLevelPacket::virtual_channel, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
void NI::handle_ready_event (IrisEvent * e) [private]
Definition at line 383 of file NI.cc.
References _DBG, max_sim_time, Simulator::Now(), OUT_PULL_EVENT, NetworkComponent::process_event(), ready, Simulator::Schedule(), sending, IrisEvent::vc, and vcs.
Referenced by process_event().
string NI::print_stats (void) const [virtual]
Implements Processor .
Definition at line 548 of file NI.cc.
References avg_resp_buff_occ, last_pkt_out_cycle, mc, node_ip, packets, packets_out, resp_buff_occ_cycles, total_backward_time, and total_missed_time.
void NI::process_event (IrisEvent * e) [virtual]
Implements Processor .
Definition at line 108 of file NI.cc.
References handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), NEW_PACKET_EVENT, OUT_PULL_EVENT, READY_EVENT, and IrisEvent::type.
Referenced by ResponseHandler::process_event().
void NI::set_no_vcs (uint v)
Definition at line 45 of file NI.cc.
References vcs.
void NI::set_output_path (string v) [virtual]
Implements Processor .
Definition at line 85 of file NI.cc.
References node_ip, out_file, and out_filename.
void NI::setup (uint no_nodes, uint vcs, uint max_sim_time) [virtual]
Implements Processor .
Definition at line 51 of file NI.cc.
References NetworkComponent::address, avg_resp_buff_occ, flast_vc, last_vc, max_sim_time, mc, missed_time, Component::myId(), no_nodes, node_ip, outstanding_hlp, packets, packets_out, ready, resp_buff_occ_cycles, total_backward_time, total_missed_time, and vcs.
void NI::strip_mc_bits (Request * req) [private]
Definition at line 156 of file NI.cc.
References Request::address, MC_ADDR_BITS, mc_positions, no_mcs, NO_OF_THREADS, and node_ip.
Referenced by handle_new_packet_event().
string NI::toString () const [virtual]
Reimplemented from Processor .
Definition at line 453 of file NI.cc.
References NetworkComponent::address, Processor::interface_connections, and out_filename.
Member Data Documentation
ullint NI::avg_resp_buff_occ [private]
Definition at line 76 of file NI.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
unsigned int NI::flast_vc [private]
Definition at line 91 of file NI.h.
Referenced by handle_new_packet_event(), and setup().
ullint NI::last_out_pull_cycle [private]
Definition at line 70 of file NI.h.
Referenced by handle_out_pull_event().
double NI::last_pkt_out_cycle [private]
Definition at line 69 of file NI.h.
Referenced by handle_new_packet_event(), and print_stats().
unsigned int NI::last_vc [private]
Definition at line 90 of file NI.h.
Referenced by handle_out_pull_event(), and setup().
unsigned long long int NI::max_sim_time [private]
Definition at line 81 of file NI.h.
Referenced by handle_ready_event(), and setup().
Component* NI::mc
Definition at line 53 of file NI.h.
Referenced by handle_new_packet_event(), handle_out_pull_event(), NI(), print_stats(), and setup().
uint NI::missed_time [private]
Definition at line 73 of file NI.h.
Referenced by setup().
vector<Request> NI::niQueue
Definition at line 54 of file NI.h.
Referenced by GetFromNIQueue(), and handle_out_pull_event().
uint NI::no_nodes [private]
Definition at line 79 of file NI.h.
Referenced by setup().
uint NI::node_ip
Reimplemented from NetworkComponent .
Definition at line 59 of file NI.h.
Referenced by add_mc_bits(), handle_out_pull_event(), print_stats(), set_output_path(), setup(), and strip_mc_bits().
ofstream NI::out_file [private]
Definition at line 87 of file NI.h.
Referenced by finish(), and set_output_path().
string NI::out_filename [private]
Definition at line 85 of file NI.h.
Referenced by set_output_path(), and toString().
deque< HighLevelPacket > NI::out_packets [private]
Definition at line 82 of file NI.h.
vector<HighLevelPacket*> NI::outstanding_hlp [private]
Definition at line 84 of file NI.h.
Referenced by handle_new_packet_event(), and setup().
unsigned int NI::packets [private]
Definition at line 80 of file NI.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int NI::packets_out [private]
Definition at line 74 of file NI.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
vector< bool > NI::ready [private]
Definition at line 89 of file NI.h.
Referenced by handle_out_pull_event(), handle_ready_event(), and setup().
ullint NI::resp_buff_occ_cycles [private]
Definition at line 75 of file NI.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
bool NI::sending
Definition at line 64 of file NI.h.
Referenced by handle_out_pull_event(), and handle_ready_event().
deque< HighLevelPacket > NI::sent_packets [private]
Definition at line 83 of file NI.h.
unsigned long long int NI::total_backward_time [private]
Definition at line 72 of file NI.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
unsigned long long int NI::total_missed_time [private]
Definition at line 71 of file NI.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
fstream NI::trace_filename [private]
Definition at line 88 of file NI.h.
string NI::trace_name [private]
Definition at line 86 of file NI.h.
uint NI::vcs [private]
Definition at line 78 of file NI.h.
Referenced by handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), set_no_vcs(), and setup().
The documentation for this class was generated from the following files:
NI.h
NI.cc