core_exec_DPM_t Class Reference
Classes
struct ALU_t
struct exec_port_t
struct LDQ_t
struct readyQ_node_t
struct STQ_t
struct uop_action_t
Public Member Functions
core_exec_DPM_t (struct core_t *const core)
virtual void reg_stats (struct stat_sdb_t *const sdb)
virtual void freeze_stats (void)
virtual void update_occupancy (void)
virtual void ALU_exec (void)
virtual void LDST_exec (void)
virtual void RS_schedule (void)
virtual void LDQ_schedule (void)
virtual void recover (const struct Mop_t *const Mop)
virtual void recover (void)
virtual void insert_ready_uop (struct uop_t *const uop)
virtual bool RS_available (void)
virtual void RS_insert (struct uop_t *const uop)
virtual void RS_fuse_insert (struct uop_t *const uop)
virtual void RS_deallocate (struct uop_t *const uop)
virtual bool LDQ_available (void)
virtual void LDQ_insert (struct uop_t *const uop)
virtual void LDQ_deallocate (struct uop_t *const uop)
virtual void LDQ_squash (struct uop_t *const dead_uop)
virtual bool STQ_available (void)
virtual void STQ_insert_sta (struct uop_t *const uop)
virtual void STQ_insert_std (struct uop_t *const uop)
virtual void STQ_deallocate_sta (void)
virtual bool STQ_deallocate_std (struct uop_t *const uop)
virtual void STQ_deallocate_senior (void)
virtual void STQ_squash_sta (struct uop_t *const dead_uop)
virtual void STQ_squash_std (struct uop_t *const dead_uop)
virtual void STQ_squash_senior (void)
virtual void recover_check_assertions (void)
Protected Member Functions
struct readyQ_node_t * get_readyQ_node (void)
void return_readyQ_node (struct readyQ_node_t *const p)
bool check_load_issue_conditions (const struct uop_t *const uop)
void snatch_back (struct uop_t *const replayed_uop)
void load_writeback (struct uop_t *const uop)
Static Protected Member Functions
static void DL1_callback (void *const op)
static void DL1_split_callback (void *const op)
static void DTLB_callback (void *const op)
static bool translated_callback (void *const op, const seq_t)
static seq_t get_uop_action_id (void *const op)
static void load_miss_reschedule (void *const op, const int new_pred_latency)
static void store_dl1_callback (void *const op)
static void store_dl1_split_callback (void *const op)
static void store_dtlb_callback (void *const op)
static bool store_translated_callback (void *const op, const seq_t)
Protected Attributes
struct readyQ_node_t * readyQ_free_pool
struct uop_t ** RS
int RS_num
int RS_eff_num
struct core_exec_DPM_t::LDQ_t * LDQ
int LDQ_head
int LDQ_tail
int LDQ_num
struct core_exec_DPM_t::STQ_t * STQ
int STQ_head
int STQ_tail
int STQ_num
int STQ_senior_num
int STQ_senior_head
bool partial_forward_throttle
struct core_exec_DPM_t::exec_port_t * port
bool check_for_work
struct memdep_t * memdep
Detailed Description
Definition at line 16 of file exec-DPM.cpp.
Constructor & Destructor Documentation
core_exec_DPM_t::core_exec_DPM_t (struct core_t *const core)
Definition at line 187 of file exec-DPM.cpp.
References bus_create(), cache_create(), CACHE_PREFETCH, CACHE_READ, CACHE_READONLY, CACHE_READWRITE, CACHE_WRITE, CACHE_WRITEBACK, check_for_work, core_exec_t::core, core_t::core_t::core_memory_t::DL1, core_knobs_t::DL1_high_watermark, core_knobs_t::DL1_low_watermark, core_knobs_t::DL1_MSHR_cmd, core_knobs_t::DL1_num_PF, core_knobs_t::DL1_opt_str, core_knobs_t::DL1_PF_buffer_size, core_knobs_t::DL1_PF_filter_reset, core_knobs_t::DL1_PF_filter_size, core_knobs_t::DL1_PF_on_miss, core_knobs_t::DL1_PFFsize, core_knobs_t::DL1_PFmax, core_knobs_t::DL1_PFthresh, core_knobs_t::DL1_WMinterval, core_knobs_t::DL1PF_opt_str, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::DL2_bus, core_knobs_t::DL2_high_watermark, core_knobs_t::DL2_low_watermark, core_knobs_t::DL2_MSHR_cmd, core_knobs_t::DL2_num_PF, core_knobs_t::DL2_opt_str, core_knobs_t::DL2_PF_on_miss, core_knobs_t::DL2_PFFsize, core_knobs_t::DL2_PFmax, core_knobs_t::DL2_PFthresh, core_knobs_t::DL2_WMinterval, core_knobs_t::DL2PF_opt_str, core_t::core_t::core_memory_t::DTLB, core_t::core_t::core_memory_t::DTLB2, core_knobs_t::DTLB2_opt_str, core_t::core_t::core_memory_t::DTLB_bus, core_knobs_t::DTLB_opt_str, core_knobs_t::exec, fatal(), core_exec_DPM_t::core_exec_DPM_t::exec_port_t::FU, core_knobs_t::fu_bindings, FU_LD, core_exec_DPM_t::core_exec_DPM_t::ALU_t::issue_rate, core_knobs_t::issue_rate, core_t::knobs, knobs, cache_t::latency, core_exec_DPM_t::core_exec_DPM_t::ALU_t::latency, core_knobs_t::latency, LDQ, core_knobs_t::LDQ_size, cache_t::linesize, uncore_t::LLC, uncore_t::LLC_bus, MD_FU_NAME, memdep, memdep_create(), core_knobs_t::memdep_opt_str, core_t::memory, core_knobs_t::memory, mytoupper(), cache_t::name, core_knobs_t::num_exec_ports, NUM_FU_CLASSES, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::num_FU_types, cache_t::num_prefetchers, core_knobs_t::payload_depth, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::payload_pipe, cache_t::PF_high_watermark, cache_t::PF_low_watermark, cache_t::PF_sample_interval, cache_t::PFF, cache_t::PFF_size, core_exec_DPM_t::core_exec_DPM_t::ALU_t::pipe, port, core_knobs_t::port_binding, prefetch_buffer_create(), prefetch_create(), prefetch_filter_create(), cache_t::prefetch_max, cache_t::prefetch_on_miss, cache_t::prefetch_threshold, cache_t::prefetcher, cache_t::prev_level, RS, core_knobs_t::RS_size, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::STQ, STQ, core_knobs_t::STQ_size, and core_t::uncore.
Member Function Documentation
void core_exec_DPM_t::ALU_exec (void) [virtual]
Implements core_exec_t .
Definition at line 1730 of file exec-DPM.cpp.
References uop_t::action_id, core_exec_DPM_t::core_exec_DPM_t::uop_action_t::action_id, core_exec_DPM_t::core_exec_DPM_t::STQ_t::addr_valid, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::addr_valid, odep_t::aflags, core_t::alloc, uop_t::alloc, BIG_LATENCY, Mop_t::branch_mispred, check_for_work, core_exec_t::core, uop_t::decode, val_t::dw, uop_t::exec, core_knobs_t::exec, core_t::core_t::core_stat_t::exec_uops_replayed, F_FCOMP, Mop_t::fetch, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_requested, core_knobs_t::fp_penalty, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::FU, uop_t::FU_class, uop_t::fusion_head, uop_t::fusion_next, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, uop_t::idep_uop, uop_t::in_fusion, uop_t::is_ctrl, uop_t::is_load, uop_t::is_sta, uop_t::is_std, core_exec_DPM_t::core_exec_DPM_t::ALU_t::issue_rate, uop_t::ivalue, uop_t::ivalue_valid, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_requested, core_exec_t::last_completed, core_exec_DPM_t::core_exec_DPM_t::ALU_t::latency, LDQ, uop_t::LDQ_index, LDQ_num, core_knobs_t::LDQ_size, core_t::core_t::core_stat_t::load_nukes, MAX_IDEPS, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::mem_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::mem_size, memdep, modinc(), uop_t::Mop, core_t::new_action_id(), odep_t::next, core_exec_DPM_t::core_exec_DPM_t::STQ_t::next_load, Mop_t::NextPC, core_knobs_t::num_exec_ports, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::num_FU_types, core_t::core_t::core_stat_t::num_jeclear, uop_t::num_replays, core_t::core_t::core_stat_t::num_wp_jeclear, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::occupancy, core_exec_DPM_t::core_exec_DPM_t::ALU_t::occupancy, uop_t::odep_name, uop_t::odep_uop, uop_t::oflags, odep_t::op_num, uop_t::opflags, core_t::oracle, Mop_t::oracle, uop_t::oracle, uop_t::ovalue, uop_t::ovalue_valid, core_knobs_t::payload_depth, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::payload_pipe, Mop_t::PC, core_exec_DPM_t::core_exec_DPM_t::ALU_t::pipe, core_oracle_t::pipe_flush(), core_oracle_t::pipe_recover(), port, Mop_t::pred_NPC, REG_IS_FPR, RS, core_alloc_t::RS_deallocate(), RS_eff_num, uop_t::RS_index, RS_num, core_knobs_t::RS_size, sim_cycle, snatch_back(), Mop_t::spec_mode, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::speculative_broadcast, core_exec_DPM_t::core_exec_DPM_t::STQ_t::sta, core_t::stat, STQ, uop_t::STQ_index, core_knobs_t::STQ_size, STQ_tail, TICK_T_MAX, uop_t::timing, core_knobs_t::tornado_breaker, odep_t::uop, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::uop, core_exec_DPM_t::core_exec_DPM_t::uop_action_t::uop, uop_t::uop_seq, uop_t::uops_in_RS, memdep_t::update(), core_exec_DPM_t::core_exec_DPM_t::STQ_t::value, core_exec_DPM_t::core_exec_DPM_t::STQ_t::value_valid, core_exec_DPM_t::core_exec_DPM_t::STQ_t::virt_addr, uop_t::virt_addr, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::virt_addr, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::when_bypass_used, uop_t::when_completed, uop_t::when_exec, core_exec_DPM_t::core_exec_DPM_t::ALU_t::when_executable, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::when_issued, uop_t::when_issued, uop_t::when_itag_ready, uop_t::when_ival_ready, uop_t::when_otag_ready, uop_t::when_ready, core_t::core_t::core_stat_t::wp_load_nukes, zesto_assert, zesto_fatal, and ZESTO_STAT.
bool core_exec_DPM_t::check_load_issue_conditions (const struct uop_t *const uop) [protected]
Definition at line 840 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, uop_t::decode, core_knobs_t::exec, Mop_t::fetch, core_t::knobs, knobs, LDQ, uop_t::LDQ_index, core_knobs_t::LDQ_size, memdep_t::lookup(), core_exec_DPM_t::core_exec_DPM_t::STQ_t::mem_size, uop_t::mem_size, memdep, moddec(), modinc(), uop_t::Mop, uop_t::oracle, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::partial_forward, Mop_t::PC, core_exec_DPM_t::core_exec_DPM_t::STQ_t::sta, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::store_color, STQ, STQ_senior_head, STQ_senior_num, core_knobs_t::STQ_size, TICK_T_MAX, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::uop, uop_t::uop_seq, core_exec_DPM_t::core_exec_DPM_t::STQ_t::uop_seq, core_exec_DPM_t::core_exec_DPM_t::STQ_t::virt_addr, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::virt_addr, uop_t::virt_addr, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::when_issued, and zesto_assert.
Referenced by LDQ_schedule().
void core_exec_DPM_t::DL1_callback (void *const op) [static, protected]
Definition at line 1124 of file exec-DPM.cpp.
References uop_t::alloc, uop_t::core, uop_t::exec, core_t::exec, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_arrived, LDQ, uop_t::LDQ_index, load_writeback(), sim_cycle, uop_t::when_addr_translated, and uop_t::when_data_loaded.
Referenced by LDQ_schedule().
void core_exec_DPM_t::DL1_split_callback (void *const op) [static, protected]
Definition at line 1149 of file exec-DPM.cpp.
References uop_t::alloc, uop_t::core, uop_t::exec, core_t::exec, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_arrived, LDQ, uop_t::LDQ_index, load_writeback(), sim_cycle, uop_t::when_addr_translated, and uop_t::when_data_loaded.
Referenced by LDQ_schedule().
void core_exec_DPM_t::DTLB_callback (void *const op) [static, protected]
Definition at line 1172 of file exec-DPM.cpp.
References uop_t::alloc, uop_t::core, core_exec_t::core, uop_t::exec, core_t::exec, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_arrived, LDQ, uop_t::LDQ_index, load_writeback(), sim_cycle, TICK_T_MAX, uop_t::when_addr_translated, and zesto_assert.
Referenced by LDQ_schedule().
void core_exec_DPM_t::freeze_stats (void) [virtual]
Implements core_exec_t .
Definition at line 601 of file exec-DPM.cpp.
References memdep_t::freeze_stats(), and memdep.
core_exec_DPM_t::readyQ_node_t * core_exec_DPM_t::get_readyQ_node (void) [read, protected]
Definition at line 637 of file exec-DPM.cpp.
References fatal(), core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::next, readyQ_free_pool, sim_cycle, and core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::when_assigned.
Referenced by insert_ready_uop().
seq_t core_exec_DPM_t::get_uop_action_id (void *const op) [static, protected]
Definition at line 1206 of file exec-DPM.cpp.
References uop_t::action_id, and uop_t::exec.
Referenced by LDQ_schedule(), and STQ_deallocate_std().
void core_exec_DPM_t::insert_ready_uop (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 675 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::action_id, uop_t::action_id, uop_t::alloc, core_exec_t::core, uop_t::decode, uop_t::exec, core_knobs_t::exec, get_readyQ_node(), uop_t::in_readyQ, core_t::knobs, knobs, core_t::new_action_id(), core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::next, core_knobs_t::num_exec_ports, port, uop_t::port_assignment, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::readyQ, TICK_T_MAX, uop_t::timing, core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::uop, uop_t::uop_seq, core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::uop_seq, uop_t::when_completed, uop_t::when_exec, uop_t::when_issued, and zesto_assert.
Referenced by LDQ_schedule(), LDST_exec(), load_miss_reschedule(), load_writeback(), RS_schedule(), and snatch_back().
bool core_exec_DPM_t::LDQ_available (void) [virtual]
Implements core_exec_t .
Definition at line 2250 of file exec-DPM.cpp.
References core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, LDQ_num, and core_knobs_t::LDQ_size.
void core_exec_DPM_t::LDQ_deallocate (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2271 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, LDQ, LDQ_head, uop_t::LDQ_index, LDQ_num, core_knobs_t::LDQ_size, modinc(), and core_exec_DPM_t::core_exec_DPM_t::LDQ_t::uop.
void core_exec_DPM_t::LDQ_insert (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2256 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, uop_t::decode, core_knobs_t::exec, core_t::knobs, knobs, LDQ, uop_t::LDQ_index, LDQ_num, core_knobs_t::LDQ_size, LDQ_tail, uop_t::mem_size, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::mem_size, memzero(), moddec(), modinc(), core_exec_DPM_t::core_exec_DPM_t::LDQ_t::store_color, core_knobs_t::STQ_size, STQ_tail, TICK_T_MAX, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::uop, and core_exec_DPM_t::core_exec_DPM_t::LDQ_t::when_issued.
void core_exec_DPM_t::LDQ_schedule (void) [virtual]
Implements core_exec_t .
Definition at line 1578 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::uop_action_t::action_id, uop_t::action_id, cache_t::addr_shift, uop_t::alloc, Mop_t::branch_mispred, cache_enqueuable(), cache_enqueue(), CACHE_READ, check_load_issue_conditions(), core_exec_t::core, core_t::current_thread, uop_t::decode, core_t::core_t::core_memory_t::DL1, DL1_callback(), core_t::core_t::core_stat_t::DL1_load_split_accesses, DL1_split_callback(), core_t::core_t::core_memory_t::DTLB, DTLB_callback(), core_knobs_t::exec, uop_t::exec, Mop_t::fetch, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_requested, get_uop_action_id(), core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, thread_t::id, uop_t::in_readyQ, insert_ready_uop(), uop_t::ivalue_valid, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_requested, cache_t::latency, LDQ, LDQ_head, LDQ_num, core_knobs_t::LDQ_size, load_miss_reschedule(), MAX_IDEPS, uop_t::mem_size, core_t::memory, modinc(), uop_t::Mop, odep_t::next, Mop_t::NextPC, NO_MSHR, core_t::core_t::core_stat_t::num_jeclear, core_t::core_t::core_stat_t::num_wp_jeclear, uop_t::odep_uop, odep_t::op_num, Mop_t::oracle, core_t::oracle, uop_t::oracle, PAGE_TABLE_ADDR, partial_forward_throttle, core_knobs_t::payload_depth, Mop_t::PC, uop_t::phys_addr, core_exec_DPM_t::core_exec_DPM_t::ALU_t::pipe, core_oracle_t::pipe_recover(), port, uop_t::port_assignment, sim_cycle, snatch_back(), Mop_t::spec_mode, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::speculative_broadcast, core_t::stat, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::STQ, TICK_T_MAX, uop_t::timing, translated_callback(), odep_t::uop, core_exec_DPM_t::core_exec_DPM_t::uop_action_t::uop, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::uop, uop_t::virt_addr, uop_t::when_addr_translated, uop_t::when_completed, uop_t::when_data_loaded, uop_t::when_exec, uop_t::when_issued, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::when_issued, uop_t::when_itag_ready, uop_t::when_otag_ready, uop_t::when_ready, and ZESTO_STAT.
void core_exec_DPM_t::LDQ_squash (struct uop_t *const dead_uop) [virtual]
Implements core_exec_t .
Definition at line 2280 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, LDQ, uop_t::LDQ_index, LDQ_num, core_knobs_t::LDQ_size, LDQ_tail, memzero(), moddec(), core_exec_DPM_t::core_exec_DPM_t::LDQ_t::uop, and zesto_assert.
void core_exec_DPM_t::LDST_exec (void) [virtual]
Implements core_exec_t .
Definition at line 1284 of file exec-DPM.cpp.
References uop_t::action_id, core_exec_DPM_t::core_exec_DPM_t::STQ_t::action_id, odep_t::aflags, uop_t::alloc, Mop_t::branch_mispred, cache_process(), cache_t::check_for_work, core_exec_t::core, uop_t::decode, core_t::core_t::core_memory_t::DL1, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::DTLB, core_t::core_t::core_memory_t::DTLB2, val_t::dw, uop_t::exec, core_knobs_t::exec, Mop_t::fetch, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_requested, core_knobs_t::fp_penalty, FU_LD, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, uop_t::in_readyQ, insert_ready_uop(), uop_t::is_ctrl, uop_t::ivalue, uop_t::ivalue_valid, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_requested, core_exec_t::last_completed, core_exec_DPM_t::core_exec_DPM_t::ALU_t::latency, LDQ, uop_t::LDQ_index, core_knobs_t::LDQ_size, core_t::core_t::core_stat_t::load_nukes, MAX_IDEPS, uop_t::mem_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::mem_size, memdep, core_t::memory, moddec(), uop_t::Mop, core_t::new_action_id(), odep_t::next, Mop_t::NextPC, core_t::core_t::core_stat_t::num_jeclear, core_t::core_t::core_stat_t::num_wp_jeclear, uop_t::odep_name, uop_t::odep_uop, uop_t::oflags, odep_t::op_num, Mop_t::oracle, core_t::oracle, uop_t::ovalue, uop_t::ovalue_valid, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::partial_forward, partial_forward_throttle, Mop_t::PC, core_exec_DPM_t::core_exec_DPM_t::ALU_t::pipe, core_oracle_t::pipe_flush(), core_oracle_t::pipe_recover(), port, core_knobs_t::port_binding, Mop_t::pred_NPC, REG_IS_FPR, sim_cycle, snatch_back(), Mop_t::spec_mode, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::speculative_broadcast, core_exec_DPM_t::core_exec_DPM_t::STQ_t::sta, core_t::stat, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::store_color, STQ, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::STQ, STQ_senior_num, core_knobs_t::STQ_size, core_knobs_t::throttle_partial, TICK_T_MAX, uop_t::timing, odep_t::uop, core_exec_DPM_t::core_exec_DPM_t::uop_action_t::uop, uop_t::uop_seq, memdep_t::update(), core_exec_DPM_t::core_exec_DPM_t::STQ_t::value, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::virt_addr, core_exec_DPM_t::core_exec_DPM_t::STQ_t::virt_addr, warn(), uop_t::when_completed, uop_t::when_exec, uop_t::when_issued, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::when_issued, uop_t::when_itag_ready, uop_t::when_ival_ready, uop_t::when_otag_ready, uop_t::when_ready, core_t::core_t::core_stat_t::wp_load_nukes, zesto_assert, and ZESTO_STAT.
void core_exec_DPM_t::load_miss_reschedule (void *const op, const int new_pred_latency) [static, protected]
Definition at line 1218 of file exec-DPM.cpp.
References uop_t::alloc, BIG_LATENCY, uop_t::core, core_exec_t::core, uop_t::decode, uop_t::exec, core_knobs_t::exec, core_t::exec, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, uop_t::in_readyQ, insert_ready_uop(), uop_t::is_load, core_t::knobs, knobs, LDQ, uop_t::LDQ_index, core_knobs_t::LDQ_size, MAX_IDEPS, odep_t::next, uop_t::odep_uop, odep_t::op_num, core_knobs_t::payload_depth, sim_cycle, snatch_back(), core_exec_DPM_t::core_exec_DPM_t::LDQ_t::speculative_broadcast, TICK_T_MAX, uop_t::timing, odep_t::uop, uop_t::when_itag_ready, uop_t::when_otag_ready, uop_t::when_ready, and zesto_assert.
Referenced by LDQ_schedule().
void core_exec_DPM_t::load_writeback (struct uop_t *const uop) [protected]
Definition at line 1041 of file exec-DPM.cpp.
References odep_t::aflags, uop_t::alloc, Mop_t::branch_mispred, core_exec_t::core, uop_t::decode, val_t::dw, uop_t::exec, core_knobs_t::exec, Mop_t::fetch, core_knobs_t::fp_penalty, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, uop_t::in_readyQ, insert_ready_uop(), uop_t::is_ctrl, uop_t::ivalue, uop_t::ivalue_valid, core_t::knobs, knobs, core_exec_t::last_completed, LDQ, uop_t::LDQ_index, core_knobs_t::LDQ_size, MAX_IDEPS, uop_t::Mop, odep_t::next, Mop_t::NextPC, core_t::core_t::core_stat_t::num_jeclear, core_t::core_t::core_stat_t::num_wp_jeclear, uop_t::odep_name, uop_t::odep_uop, uop_t::oflags, odep_t::op_num, core_t::oracle, Mop_t::oracle, uop_t::oracle, uop_t::ovalue, uop_t::ovalue_valid, core_oracle_t::pipe_recover(), port, uop_t::port_assignment, Mop_t::pred_NPC, REG_IS_FPR, sim_cycle, Mop_t::spec_mode, core_t::stat, TICK_T_MAX, uop_t::timing, odep_t::uop, warn(), core_exec_DPM_t::core_exec_DPM_t::exec_port_t::when_bypass_used, uop_t::when_completed, uop_t::when_itag_ready, uop_t::when_ival_ready, uop_t::when_otag_ready, uop_t::when_ready, zesto_assert, and ZESTO_STAT.
Referenced by DL1_callback(), DL1_split_callback(), and DTLB_callback().
void core_exec_DPM_t::recover (void) [virtual]
Implements core_exec_t .
Definition at line 2174 of file exec-DPM.cpp.
void core_exec_DPM_t::recover (const struct Mop_t *const Mop) [virtual]
Implements core_exec_t .
Definition at line 2169 of file exec-DPM.cpp.
void core_exec_DPM_t::recover_check_assertions (void) [virtual]
Implements core_exec_t .
Definition at line 2482 of file exec-DPM.cpp.
References LDQ_num, RS_num, STQ_num, STQ_senior_num, and zesto_assert.
void core_exec_DPM_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Implements core_exec_t .
Definition at line 501 of file exec-DPM.cpp.
References cache_reg_stats(), core_exec_t::core, core_t::current_thread, core_t::core_t::core_memory_t::DL1, core_t::core_t::core_stat_t::DL1_load_split_accesses, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::DTLB, core_t::core_t::core_memory_t::DTLB2, core_t::core_t::core_stat_t::exec_uops_issued, core_t::core_t::core_stat_t::exec_uops_replayed, core_t::core_t::core_stat_t::exec_uops_snatched_back, thread_t::id, core_t::core_t::core_stat_t::LDQ_empty_cycles, core_t::core_t::core_stat_t::LDQ_full_cycles, core_t::core_t::core_stat_t::LDQ_occupancy, core_t::core_t::core_stat_t::load_nukes, memdep, core_t::memory, core_t::core_t::core_stat_t::num_jeclear, core_t::core_t::core_stat_t::num_wp_jeclear, memdep_t::reg_stats(), core_t::core_t::core_stat_t::RS_eff_occupancy, core_t::core_t::core_stat_t::RS_empty_cycles, core_t::core_t::core_stat_t::RS_full_cycles, core_t::core_t::core_stat_t::RS_occupancy, core_t::stat, stat_reg_counter, stat_reg_formula(), stat_reg_note(), core_t::core_t::core_stat_t::STQ_empty_cycles, core_t::core_t::core_stat_t::STQ_full_cycles, core_t::core_t::core_stat_t::STQ_occupancy, and core_t::core_t::core_stat_t::wp_load_nukes.
void core_exec_DPM_t::return_readyQ_node (struct readyQ_node_t *const p) [protected]
Definition at line 660 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::next, readyQ_free_pool, core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::uop, and core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::when_assigned.
Referenced by RS_schedule().
bool core_exec_DPM_t::RS_available (void) [virtual]
Implements core_exec_t .
Definition at line 2179 of file exec-DPM.cpp.
References core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, RS_num, and core_knobs_t::RS_size.
void core_exec_DPM_t::RS_deallocate (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2222 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, uop_t::decode, uop_t::exec, core_knobs_t::exec, uop_t::fusion_head, uop_t::in_fusion, uop_t::is_fusion_head, core_t::knobs, knobs, RS, RS_eff_num, uop_t::RS_index, RS_num, core_knobs_t::RS_size, TICK_T_MAX, uop_t::timing, uop_t::uops_in_RS, uop_t::when_exec, and zesto_assert.
void core_exec_DPM_t::RS_fuse_insert (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2212 of file exec-DPM.cpp.
References uop_t::alloc, uop_t::decode, uop_t::exec, uop_t::full_fusion_allocated, uop_t::fusion_head, uop_t::fusion_next, RS_eff_num, uop_t::RS_index, and uop_t::uops_in_RS.
void core_exec_DPM_t::RS_insert (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2187 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, uop_t::decode, uop_t::exec, core_knobs_t::exec, uop_t::full_fusion_allocated, uop_t::in_fusion, core_t::knobs, knobs, RS, RS_eff_num, uop_t::RS_index, RS_num, core_knobs_t::RS_size, uop_t::uops_in_RS, and zesto_fatal.
void core_exec_DPM_t::RS_schedule (void) [virtual]
Implements core_exec_t .
Definition at line 723 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::uop_action_t::action_id, core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::action_id, uop_t::action_id, uop_t::alloc, check_for_work, core_exec_t::core, uop_t::decode, core_t::core_t::core_memory_t::DL1, uop_t::exec, core_knobs_t::exec, core_t::core_t::core_stat_t::exec_uops_issued, F_FCOMP, core_knobs_t::fp_penalty, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::FU, uop_t::FU_class, uop_t::full_fusion_allocated, uop_t::fusion_head, uop_t::in_fusion, uop_t::in_readyQ, insert_ready_uop(), uop_t::is_load, core_exec_DPM_t::core_exec_DPM_t::ALU_t::issue_rate, core_t::knobs, knobs, cache_t::latency, core_exec_DPM_t::core_exec_DPM_t::ALU_t::latency, LDQ, uop_t::LDQ_index, core_knobs_t::LDQ_size, MAX_IDEPS, core_t::memory, odep_t::next, core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::next, core_knobs_t::num_exec_ports, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::occupancy, uop_t::odep_name, uop_t::odep_uop, odep_t::op_num, uop_t::opflags, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::payload_pipe, port, uop_t::port_assignment, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::readyQ, REG_IS_FPR, return_readyQ_node(), sim_cycle, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::speculative_broadcast, core_t::stat, TICK_T_MAX, uop_t::timing, odep_t::uop, core_exec_DPM_t::core_exec_DPM_t::uop_action_t::uop, core_exec_DPM_t::core_exec_DPM_t::readyQ_node_t::uop, uop_t::when_issued, uop_t::when_itag_ready, uop_t::when_otag_ready, uop_t::when_ready, core_exec_DPM_t::core_exec_DPM_t::ALU_t::when_scheduleable, zesto_assert, and ZESTO_STAT.
void core_exec_DPM_t::snatch_back (struct uop_t *const replayed_uop) [protected]
Definition at line 947 of file exec-DPM.cpp.
References uop_t::action_id, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::addr_valid, uop_t::alloc, core_exec_t::core, uop_t::decode, uop_t::exec, core_knobs_t::exec, core_t::core_t::core_stat_t::exec_uops_snatched_back, fatal(), core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::first_byte_requested, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::hit_in_STQ, uop_t::in_readyQ, insert_ready_uop(), uop_t::is_load, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_arrived, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::last_byte_requested, LDQ, uop_t::LDQ_index, core_knobs_t::LDQ_size, MAX_IDEPS, core_t::new_action_id(), odep_t::next, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::occupancy, uop_t::odep_uop, odep_t::op_num, core_knobs_t::payload_depth, core_exec_DPM_t::core_exec_DPM_t::exec_port_t::payload_pipe, port, uop_t::port_assignment, core_knobs_t::RS_size, core_t::stat, TICK_T_MAX, uop_t::timing, odep_t::uop, core_exec_DPM_t::core_exec_DPM_t::uop_action_t::uop, uop_t::when_completed, uop_t::when_exec, core_exec_DPM_t::core_exec_DPM_t::LDQ_t::when_issued, uop_t::when_issued, uop_t::when_itag_ready, uop_t::when_otag_ready, uop_t::when_ready, zesto_assert, and ZESTO_STAT.
Referenced by ALU_exec(), LDQ_schedule(), LDST_exec(), and load_miss_reschedule().
void core_exec_DPM_t::store_dl1_callback (void *const op) [static, protected]
Definition at line 2494 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::STQ_t::action_id, uop_t::action_id, uop_t::alloc, uop_t::core, core_exec_t::core, uop_t::exec, core_knobs_t::exec, core_t::exec, core_exec_DPM_t::core_exec_DPM_t::STQ_t::first_byte_written, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::STQ_t::last_byte_written, core_t::return_uop_array(), STQ, uop_t::STQ_index, core_knobs_t::STQ_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::write_complete, and zesto_assert.
Referenced by STQ_deallocate_std().
void core_exec_DPM_t::store_dl1_split_callback (void *const op) [static, protected]
Definition at line 2516 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::STQ_t::action_id, uop_t::action_id, uop_t::alloc, uop_t::core, core_exec_t::core, uop_t::exec, core_knobs_t::exec, core_t::exec, core_exec_DPM_t::core_exec_DPM_t::STQ_t::first_byte_written, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::STQ_t::last_byte_written, core_t::return_uop_array(), STQ, uop_t::STQ_index, core_knobs_t::STQ_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::write_complete, and zesto_assert.
Referenced by STQ_deallocate_std().
void core_exec_DPM_t::store_dtlb_callback (void *const op) [static, protected]
Definition at line 2537 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::STQ_t::action_id, uop_t::action_id, uop_t::alloc, uop_t::core, core_exec_t::core, uop_t::exec, core_knobs_t::exec, core_t::exec, core_t::knobs, knobs, core_t::return_uop_array(), STQ, uop_t::STQ_index, core_knobs_t::STQ_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::translation_complete, and zesto_assert.
Referenced by STQ_deallocate_std().
bool core_exec_DPM_t::store_translated_callback (void *const op, const seq_t action_id) [static, protected]
Definition at line 2554 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::STQ_t::action_id, uop_t::action_id, uop_t::alloc, uop_t::core, core_exec_t::core, core_knobs_t::exec, uop_t::exec, core_t::exec, core_t::knobs, knobs, STQ, uop_t::STQ_index, core_knobs_t::STQ_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::translation_complete, and zesto_assert.
Referenced by STQ_deallocate_std().
bool core_exec_DPM_t::STQ_available (void) [virtual]
Implements core_exec_t .
Definition at line 2293 of file exec-DPM.cpp.
References core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, STQ_senior_num, and core_knobs_t::STQ_size.
void core_exec_DPM_t::STQ_deallocate_senior (void) [virtual]
Implements core_exec_t .
Definition at line 2423 of file exec-DPM.cpp.
References core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, modinc(), partial_forward_throttle, STQ, STQ_senior_head, STQ_senior_num, core_knobs_t::STQ_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::translation_complete, core_exec_DPM_t::core_exec_DPM_t::STQ_t::write_complete, and zesto_assert.
void core_exec_DPM_t::STQ_deallocate_sta (void) [virtual]
Implements core_exec_t .
Definition at line 2327 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::STQ_t::sta, STQ, and STQ_head.
bool core_exec_DPM_t::STQ_deallocate_std (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2333 of file exec-DPM.cpp.
References uop_t::action_id, core_exec_DPM_t::core_exec_DPM_t::STQ_t::action_id, cache_t::addr_shift, uop_t::alloc, cache_enqueuable(), cache_enqueue(), CACHE_READ, CACHE_WRITE, uop_t::core, core_exec_t::core, core_t::current_thread, uop_t::decode, core_t::core_t::core_memory_t::DL1, core_t::core_t::core_stat_t::DL1_store_split_accesses, core_t::core_t::core_memory_t::DTLB, core_t::core_t::core_memory_t::DTLB2, core_knobs_t::exec, uop_t::exec, Mop_t::fetch, core_exec_DPM_t::core_exec_DPM_t::STQ_t::first_byte_requested, get_uop_action_id(), core_t::get_uop_array(), thread_t::id, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::STQ_t::last_byte_requested, core_exec_DPM_t::core_exec_DPM_t::STQ_t::last_byte_written, uop_t::mem_size, core_t::memory, modinc(), uop_t::Mop, uop_t::Mop_seq, core_t::new_action_id(), NO_MSHR, uop_t::oracle, PAGE_TABLE_ADDR, Mop_t::PC, uop_t::phys_addr, core_t::stat, core_exec_DPM_t::core_exec_DPM_t::STQ_t::std, store_dl1_callback(), store_dl1_split_callback(), store_dtlb_callback(), store_translated_callback(), STQ, STQ_head, uop_t::STQ_index, STQ_num, core_knobs_t::STQ_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::translation_complete, uop_t::uop_seq, uop_t::virt_addr, core_exec_DPM_t::core_exec_DPM_t::STQ_t::write_complete, and ZESTO_STAT.
void core_exec_DPM_t::STQ_insert_sta (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2299 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, uop_t::decode, core_knobs_t::exec, uop_t::is_sta, core_t::knobs, knobs, LDQ_tail, uop_t::mem_size, core_exec_DPM_t::core_exec_DPM_t::STQ_t::mem_size, memzero(), modinc(), core_exec_DPM_t::core_exec_DPM_t::STQ_t::next_load, core_exec_DPM_t::core_exec_DPM_t::STQ_t::sta, STQ, uop_t::STQ_index, STQ_num, STQ_senior_num, core_knobs_t::STQ_size, STQ_tail, uop_t::uop_seq, and core_exec_DPM_t::core_exec_DPM_t::STQ_t::uop_seq.
void core_exec_DPM_t::STQ_insert_std (struct uop_t *const uop) [virtual]
Implements core_exec_t .
Definition at line 2316 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, moddec(), uop_t::Mop, core_exec_DPM_t::core_exec_DPM_t::STQ_t::std, STQ, uop_t::STQ_index, core_knobs_t::STQ_size, STQ_tail, and zesto_assert.
void core_exec_DPM_t::STQ_squash_senior (void) [virtual]
Implements core_exec_t .
Definition at line 2463 of file exec-DPM.cpp.
References core_exec_DPM_t::core_exec_DPM_t::STQ_t::action_id, core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, memzero(), modinc(), core_t::new_action_id(), STQ, STQ_head, STQ_num, STQ_senior_head, STQ_senior_num, and core_knobs_t::STQ_size.
void core_exec_DPM_t::STQ_squash_sta (struct uop_t *const dead_uop) [virtual]
Implements core_exec_t .
Definition at line 2438 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, memzero(), moddec(), core_exec_DPM_t::core_exec_DPM_t::STQ_t::sta, core_exec_DPM_t::core_exec_DPM_t::STQ_t::std, STQ, uop_t::STQ_index, STQ_num, STQ_senior_num, core_knobs_t::STQ_size, STQ_tail, and zesto_assert.
void core_exec_DPM_t::STQ_squash_std (struct uop_t *const dead_uop) [virtual]
Implements core_exec_t .
Definition at line 2454 of file exec-DPM.cpp.
References uop_t::alloc, core_exec_t::core, core_knobs_t::exec, core_t::knobs, knobs, core_exec_DPM_t::core_exec_DPM_t::STQ_t::std, STQ, uop_t::STQ_index, core_knobs_t::STQ_size, and zesto_assert.
bool core_exec_DPM_t::translated_callback (void *const op, const seq_t action_id) [static, protected]
Definition at line 1195 of file exec-DPM.cpp.
References uop_t::action_id, uop_t::alloc, uop_t::exec, uop_t::LDQ_index, sim_cycle, and uop_t::when_addr_translated.
Referenced by LDQ_schedule().
void core_exec_DPM_t::update_occupancy (void) [virtual]
Implements core_exec_t .
Definition at line 606 of file exec-DPM.cpp.
References core_exec_t::core, core_knobs_t::exec, core_t::knobs, core_t::core_t::core_stat_t::LDQ_empty_cycles, core_t::core_t::core_stat_t::LDQ_full_cycles, LDQ_num, core_t::core_t::core_stat_t::LDQ_occupancy, core_knobs_t::LDQ_size, RS_eff_num, core_t::core_t::core_stat_t::RS_eff_occupancy, core_t::core_t::core_stat_t::RS_empty_cycles, core_t::core_t::core_stat_t::RS_full_cycles, RS_num, core_t::core_t::core_stat_t::RS_occupancy, core_knobs_t::RS_size, core_t::stat, core_t::core_t::core_stat_t::STQ_empty_cycles, core_t::core_t::core_stat_t::STQ_full_cycles, STQ_num, core_t::core_t::core_stat_t::STQ_occupancy, and core_knobs_t::STQ_size.
Member Data Documentation
bool core_exec_DPM_t::check_for_work [protected]
Definition at line 153 of file exec-DPM.cpp.
Referenced by ALU_exec(), core_exec_DPM_t(), and RS_schedule().
struct core_exec_DPM_t::LDQ_t * core_exec_DPM_t::LDQ [protected]
Referenced by ALU_exec(), check_load_issue_conditions(), core_exec_DPM_t(), DL1_callback(), DL1_split_callback(), DTLB_callback(), LDQ_deallocate(), LDQ_insert(), LDQ_schedule(), LDQ_squash(), LDST_exec(), load_miss_reschedule(), load_writeback(), RS_schedule(), and snatch_back().
int core_exec_DPM_t::LDQ_head [protected]
Definition at line 110 of file exec-DPM.cpp.
Referenced by LDQ_deallocate(), and LDQ_schedule().
int core_exec_DPM_t::LDQ_num [protected]
Definition at line 112 of file exec-DPM.cpp.
Referenced by ALU_exec(), LDQ_available(), LDQ_deallocate(), LDQ_insert(), LDQ_schedule(), LDQ_squash(), recover_check_assertions(), and update_occupancy().
int core_exec_DPM_t::LDQ_tail [protected]
Definition at line 111 of file exec-DPM.cpp.
Referenced by LDQ_insert(), LDQ_squash(), and STQ_insert_sta().
struct memdep_t* core_exec_DPM_t::memdep [read, protected]
Definition at line 155 of file exec-DPM.cpp.
Referenced by ALU_exec(), check_load_issue_conditions(), core_exec_DPM_t(), freeze_stats(), LDST_exec(), and reg_stats().
bool core_exec_DPM_t::partial_forward_throttle [protected]
Definition at line 140 of file exec-DPM.cpp.
Referenced by LDQ_schedule(), LDST_exec(), and STQ_deallocate_senior().
struct core_exec_DPM_t::exec_port_t * core_exec_DPM_t::port [protected]
Referenced by ALU_exec(), core_exec_DPM_t(), insert_ready_uop(), LDQ_schedule(), LDST_exec(), load_writeback(), RS_schedule(), and snatch_back().
struct readyQ_node_t* core_exec_DPM_t::readyQ_free_pool [read, protected]
Definition at line 85 of file exec-DPM.cpp.
Referenced by get_readyQ_node(), and return_readyQ_node().
struct uop_t** core_exec_DPM_t::RS [read, protected]
Definition at line 90 of file exec-DPM.cpp.
Referenced by ALU_exec(), core_exec_DPM_t(), RS_deallocate(), and RS_insert().
int core_exec_DPM_t::RS_eff_num [protected]
Definition at line 92 of file exec-DPM.cpp.
Referenced by ALU_exec(), RS_deallocate(), RS_fuse_insert(), RS_insert(), and update_occupancy().
int core_exec_DPM_t::RS_num [protected]
Definition at line 91 of file exec-DPM.cpp.
Referenced by ALU_exec(), recover_check_assertions(), RS_available(), RS_deallocate(), RS_insert(), and update_occupancy().
struct core_exec_DPM_t::STQ_t * core_exec_DPM_t::STQ [protected]
Referenced by ALU_exec(), check_load_issue_conditions(), core_exec_DPM_t(), LDST_exec(), store_dl1_callback(), store_dl1_split_callback(), store_dtlb_callback(), store_translated_callback(), STQ_deallocate_senior(), STQ_deallocate_sta(), STQ_deallocate_std(), STQ_insert_sta(), STQ_insert_std(), STQ_squash_senior(), STQ_squash_sta(), and STQ_squash_std().
int core_exec_DPM_t::STQ_head [protected]
Definition at line 135 of file exec-DPM.cpp.
Referenced by STQ_deallocate_sta(), STQ_deallocate_std(), and STQ_squash_senior().
int core_exec_DPM_t::STQ_num [protected]
Definition at line 137 of file exec-DPM.cpp.
Referenced by recover_check_assertions(), STQ_deallocate_std(), STQ_insert_sta(), STQ_squash_senior(), STQ_squash_sta(), and update_occupancy().
int core_exec_DPM_t::STQ_senior_head [protected]
Definition at line 139 of file exec-DPM.cpp.
Referenced by check_load_issue_conditions(), STQ_deallocate_senior(), and STQ_squash_senior().
int core_exec_DPM_t::STQ_senior_num [protected]
Definition at line 138 of file exec-DPM.cpp.
Referenced by check_load_issue_conditions(), LDST_exec(), recover_check_assertions(), STQ_available(), STQ_deallocate_senior(), STQ_insert_sta(), STQ_squash_senior(), and STQ_squash_sta().
int core_exec_DPM_t::STQ_tail [protected]
Definition at line 136 of file exec-DPM.cpp.
Referenced by ALU_exec(), LDQ_insert(), STQ_insert_sta(), STQ_insert_std(), and STQ_squash_sta().
The documentation for this class was generated from the following file:
exec-DPM.cpp