CmdBusHandler Class Reference
The cmd bus class.
#include <cmd_bus_handler.h>
Public Member Functions
CmdBusHandler ()
constructor
~CmdBusHandler ()
deconstructor
void process_event (IrisEvent *e)
main function that handles the operation of cmd bus
std::string toString ()
Public Attributes
Component * parent
pointer to its parent
Component * child
pointer to the corresponding DRAM channel
Detailed Description
The cmd bus class.
Description: This class models an address and command bus. The cmd issuer sends a cmd containing address to this. it takes that command and delivers it to the DRAM after t_CMD cycles.
Definition at line 46 of file cmd_bus_handler.h.
Constructor & Destructor Documentation
CmdBusHandler::CmdBusHandler ()
constructor
Definition at line 33 of file cmd_bus_handler.cc.
CmdBusHandler::~CmdBusHandler ()
deconstructor
Definition at line 45 of file cmd_bus_handler.cc.
Member Function Documentation
void CmdBusHandler::process_event (IrisEvent * e)
main function that handles the operation of cmd bus
Definition at line 57 of file cmd_bus_handler.cc.
References child, IrisEvent::event_data, Simulator::Now(), DRAMChannel::process_event(), Simulator::Schedule(), START_READ, and t_CMD.
Referenced by CmdIssuer::process_event().
std::string CmdBusHandler::toString ()
Member Data Documentation
Component* CmdBusHandler::child
pointer to the corresponding DRAM channel
Definition at line 52 of file cmd_bus_handler.h.
Referenced by process_event(), and Bus::SetLinks().
Component* CmdBusHandler::parent
pointer to its parent
Definition at line 51 of file cmd_bus_handler.h.
Referenced by Bus::SetLinks().
The documentation for this class was generated from the following files:
cmd_bus_handler.h
cmd_bus_handler.cc