GenericRouterVct Class Reference
#include <genericRouterVct.h>
Public Member Functions
GenericRouterVct ()
~GenericRouterVct ()
void init (uint ports, uint vcs, uint credits, uint buffer_size)
void set_no_nodes (uint nodes)
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
void set_grid_x_location (uint a, uint b, uint c)
void set_grid_y_location (uint a, uint b, uint c)
void send_credit_back (uint i)
void process_event (IrisEvent *e)
string toString () const
string print_stats ()
Public Attributes
vector< vector< uint > > downstream_credits
uint packets
uint flits
double total_packet_latency
double last_flit_out_cycle
unsigned long long int stat_sim_total_time
vector< vector< uint > > stat_packet_out
vector< vector< uint > > stat_flit_out
Private Member Functions
void handle_link_arrival_event (IrisEvent *e)
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
void handle_tick_event (IrisEvent *e)
Event handle for the TICK_EVENT. Entry from DES kernel.
void do_switch_traversal ()
void do_switch_allocation ()
Private Attributes
vector< GenericBuffer > in_buffers
vector< GenericRC > decoders
vector< InputBufferState > input_buffer_state
PToPSwitchArbiter swa
GenericCrossbar xbar
bool ticking
Detailed Description
Definition at line 36 of file genericRouterVct.h.
Constructor & Destructor Documentation
GenericRouterVct::GenericRouterVct ()
Definition at line 39 of file genericRouterVct.cc.
References NetworkComponent::name, and ticking.
GenericRouterVct::~GenericRouterVct ()
Definition at line 45 of file genericRouterVct.cc.
Member Function Documentation
void GenericRouterVct::do_switch_allocation () [private]
Definition at line 457 of file genericRouterVct.cc.
References _DBG, PToPSwitchArbiter::clear_requested(), GenericCrossbar::configure_crossbar(), FULL, input_buffer_state, PToPSwitchArbiter::is_empty(), PToPSwitchArbiter::pick_winner(), SA_unit::port, Router::ports, GenericCrossbar::push(), ST, swa, SWA_REQUESTED, ticking, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterVct::do_switch_traversal () [private]
Definition at line 330 of file genericRouterVct.cc.
References _DBG, _DBG_NOARG, NetworkComponent::address, TailFlit::avg_network_latency, HeadFlit::avg_network_latency, BODY, PToPSwitchArbiter::clear_winner(), data, do_two_stage_router, downstream_credits, EMPTY, FLIT_ID, HEAD, TailFlit::hop_count, HeadFlit::hop_count, in_buffers, input_buffer_state, GenericCrossbar::is_empty(), Flit::is_single_flit_pkt, last_flit_out_cycle, LINK_ARRIVAL_EVENT, Simulator::Now(), Router::output_connections, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, GenericCrossbar::pull(), Simulator::Schedule(), send_credit_back(), ST, stat_flit_out, stat_packet_out, swa, TAIL, ticking, toString(), total_packet_latency, Flit::type, LinkArrivalData::type, LinkArrivalData::vc, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterVct::handle_link_arrival_event (IrisEvent * e) [private]
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
Definition at line 223 of file genericRouterVct.cc.
References _DBG, CREDIT_ID, data, decoders, downstream_credits, IrisEvent::event_data, FLIT_ID, flits, FULL, HEAD, in_buffers, input_buffer_state, Router::input_connections, Flit::is_single_flit_pkt, HeadFlit::length, Simulator::Now(), Router::output_connections, packets, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, Simulator::Schedule(), IrisEvent::src_id, TAIL, TICK_EVENT, ticking, Flit::type, LinkArrivalData::type, IrisEvent::vc, LinkArrivalData::vc, and Router::vcs.
Referenced by process_event().
void GenericRouterVct::handle_tick_event (IrisEvent * e) [private]
Event handle for the TICK_EVENT. Entry from DES kernel.
Body and tail flits get written in link arrival and since the message state may already been pushed to ST because of the header we want to ensure that all flits go thru an IB and ST stage. Hence ST is done on the flits_in_ib information and not buffer occupancy.
Definition at line 514 of file genericRouterVct.cc.
References _DBG, _DBG_NOARG, Router::credits, do_switch_allocation(), do_switch_traversal(), downstream_credits, FULL, IB, in_buffers, input_buffer_state, PToPSwitchArbiter::is_requested(), Simulator::Now(), Router::ports, NetworkComponent::process_event(), PToPSwitchArbiter::request(), Simulator::Schedule(), ST, swa, SWA_REQUESTED, TICK_EVENT, ticking, toString(), IrisEvent::vc, and Router::vcs.
Referenced by process_event().
void GenericRouterVct::init (uint ports, uint vcs, uint credits, uint buffer_size) [virtual]
Implements Router .
Definition at line 50 of file genericRouterVct.cc.
References NetworkComponent::address, Router::buffer_size, Router::credits, decoders, downstream_credits, flits, in_buffers, input_buffer_state, Component::myId(), NetworkComponent::node_ip, packets, Router::ports, PToPSwitchArbiter::resize(), GenericCrossbar::set_no_virtual_channels(), stat_flit_out, stat_packet_out, swa, total_packet_latency, Router::vcs, and xbar.
string GenericRouterVct::print_stats (void) [virtual]
Implements Router .
Definition at line 149 of file genericRouterVct.cc.
References flits, last_flit_out_cycle, NetworkComponent::node_ip, packets, Router::ports, stat_flit_out, stat_packet_out, and total_packet_latency.
void GenericRouterVct::process_event (IrisEvent * e) [virtual]
Implements NetworkComponent .
Definition at line 131 of file genericRouterVct.cc.
References _DBG, handle_link_arrival_event(), handle_tick_event(), LINK_ARRIVAL_EVENT, TICK_EVENT, and IrisEvent::type.
void GenericRouterVct::send_credit_back (uint i)
Definition at line 663 of file genericRouterVct.cc.
References _DBG, NetworkComponent::address, CREDIT_ID, data, do_two_stage_router, input_buffer_state, Router::input_connections, LINK_ARRIVAL_EVENT, Simulator::Now(), NetworkComponent::process_event(), Simulator::Schedule(), LinkArrivalData::type, and LinkArrivalData::vc.
Referenced by do_switch_traversal().
void GenericRouterVct::set_grid_x_location (uint a, uint b, uint c) [virtual]
Implements Router .
Definition at line 117 of file genericRouterVct.cc.
References decoders.
void GenericRouterVct::set_grid_y_location (uint a, uint b, uint c) [virtual]
Implements Router .
Definition at line 123 of file genericRouterVct.cc.
References decoders.
void GenericRouterVct::set_no_nodes (uint nodes) [virtual]
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
Implements Router .
Definition at line 107 of file genericRouterVct.cc.
References decoders.
string GenericRouterVct::toString () const [virtual]
Reimplemented from Router .
Definition at line 640 of file genericRouterVct.cc.
References NetworkComponent::address, decoders, in_buffers, NetworkComponent::node_ip, swa, GenericCrossbar::toString(), PToPSwitchArbiter::toString(), and xbar.
Referenced by do_switch_traversal(), and handle_tick_event().
Member Data Documentation
vector<GenericRC> GenericRouterVct::decoders [private]
Definition at line 67 of file genericRouterVct.h.
Referenced by handle_link_arrival_event(), init(), set_grid_x_location(), set_grid_y_location(), set_no_nodes(), and toString().
vector< vector<uint> > GenericRouterVct::downstream_credits
Definition at line 52 of file genericRouterVct.h.
Referenced by do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), and init().
uint GenericRouterVct::flits
Definition at line 56 of file genericRouterVct.h.
Referenced by handle_link_arrival_event(), init(), and print_stats().
vector<GenericBuffer> GenericRouterVct::in_buffers [private]
Definition at line 66 of file genericRouterVct.h.
Referenced by do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), init(), and toString().
vector<InputBufferState> GenericRouterVct::input_buffer_state [private]
Definition at line 68 of file genericRouterVct.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), init(), and send_credit_back().
double GenericRouterVct::last_flit_out_cycle
Definition at line 58 of file genericRouterVct.h.
Referenced by do_switch_traversal(), and print_stats().
uint GenericRouterVct::packets
Definition at line 55 of file genericRouterVct.h.
Referenced by handle_link_arrival_event(), init(), and print_stats().
vector< vector<uint> > GenericRouterVct::stat_flit_out
Definition at line 61 of file genericRouterVct.h.
Referenced by do_switch_traversal(), init(), and print_stats().
vector< vector<uint> > GenericRouterVct::stat_packet_out
Definition at line 60 of file genericRouterVct.h.
Referenced by do_switch_traversal(), init(), and print_stats().
unsigned long long int GenericRouterVct::stat_sim_total_time
Definition at line 59 of file genericRouterVct.h.
PToPSwitchArbiter GenericRouterVct::swa [private]
Definition at line 69 of file genericRouterVct.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_tick_event(), init(), and toString().
bool GenericRouterVct::ticking [private]
Definition at line 72 of file genericRouterVct.h.
Referenced by do_switch_allocation(), do_switch_traversal(), GenericRouterVct(), handle_link_arrival_event(), and handle_tick_event().
double GenericRouterVct::total_packet_latency
Definition at line 57 of file genericRouterVct.h.
Referenced by do_switch_traversal(), init(), and print_stats().
GenericCrossbar GenericRouterVct::xbar [private]
Definition at line 70 of file genericRouterVct.h.
Referenced by do_switch_allocation(), do_switch_traversal(), init(), and toString().
The documentation for this class was generated from the following files:
genericRouterVct.h
genericRouterVct.cc