MC Class Reference
#include <MC.h>
Public Member Functions
void Init ()
void StartRefresh ()
~MC ()
void sim_main (IrisEvent *e)
Public Attributes
NI * ni
RequestHandler * reqH
RefreshMgr * refMgr
Bus * bus
DRAM * dram
ResponseHandler * responseH
Statistic * stats
Component * parent
UInt id
Detailed Description
Definition at line 35 of file MC.h.
Constructor & Destructor Documentation
MC::~MC () [inline]
Definition at line 59 of file MC.h.
References bus, dram, refMgr, reqH, and responseH.
Member Function Documentation
void MC::Init ()
Definition at line 20 of file MC.cc.
References bus, ResponseHandler::child, RequestHandler::child, Bus::child1, Bus::child2, dram, Statistic::InitStats(), Statistic::mc, RefreshMgr::mc, ResponseHandler::mc, DRAM::mc, Bus::mc, RequestHandler::mc, ni, ResponseHandler::parent, DRAM::parent, Bus::parent, RequestHandler::parent, refMgr, reqH, RefreshMgr::reqPtr, ResponseHandler::reqPtr, responseH, RequestHandler::resPtr, DRAM::SetLinks(), Bus::SetLinks(), RequestHandler::SetLinks(), StartRefresh(), and stats.
Referenced by main().
void MC::sim_main (IrisEvent * e)
Definition at line 112 of file manifold_simmc.cc.
References CONTINUE, IrisEvent::dst, IrisEvent::event_data, GetNextRequest(), Simulator::Now(), RequestHandler::oneBufferFull, RequestHandler::process_event(), reqH, Simulator::Schedule(), IrisEvent::src, START, and IrisEvent::type.
Referenced by main().
void MC::StartRefresh ()
Definition at line 48 of file MC.cc.
References RefreshMgr::nextRefresh, Simulator::Now(), RefreshMgr::process_event(), refMgr, REFRESH_INC, and Simulator::Schedule().
Referenced by Init().
Member Data Documentation
Bus* MC::bus
Definition at line 41 of file MC.h.
Referenced by Init(), and ~MC().
DRAM* MC::dram
Definition at line 42 of file MC.h.
Referenced by Init(), and ~MC().
UInt MC::id
Definition at line 49 of file MC.h.
NI* MC::ni
Definition at line 38 of file MC.h.
Referenced by Init(), and main().
Component* MC::parent
Definition at line 45 of file MC.h.
RefreshMgr* MC::refMgr
Definition at line 40 of file MC.h.
Referenced by Init(), StartRefresh(), and ~MC().
RequestHandler* MC::reqH
Definition at line 39 of file MC.h.
Referenced by Init(), main(), sim_main(), and ~MC().
ResponseHandler* MC::responseH
Definition at line 43 of file MC.h.
Referenced by Init(), and ~MC().
Statistic* MC::stats
Definition at line 44 of file MC.h.
Referenced by Init(), and main().
The documentation for this class was generated from the following files:
MC.h
manifold_simmc.cc
MC.cc