DataBusHandler Class Reference
The data bus class.
#include <data_bus_handler.h>
Public Member Functions
DataBusHandler ()
constructor
~DataBusHandler ()
deconstructor
void process_event (IrisEvent *e)
Handles all the operations of the data bus.
std::string toString ()
Public Attributes
Component * parent
pointer to its parent
Component * child1
pointer to corresponding DRAM channel
Component * child2
pointer to response handler
Time prevTime
variable to keep track of the last time data bus was used
Time busBusyTime
total time the bus remained busy
Detailed Description
The data bus class.
Description: This class handles the operation of the data bus. It receives read and write data from the corresponding dram channel or cmd issuer, respectively. It sends them to the response handler or DRAM after burst delay cycles. It also calculates data bus related stats.
Definition at line 47 of file data_bus_handler.h.
Constructor & Destructor Documentation
DataBusHandler::DataBusHandler ()
constructor
Definition at line 34 of file data_bus_handler.cc.
References busBusyTime, and prevTime.
DataBusHandler::~DataBusHandler ()
deconstructor
Definition at line 47 of file data_bus_handler.cc.
Member Function Documentation
void DataBusHandler::process_event (IrisEvent * e)
Handles all the operations of the data bus.
Definition at line 59 of file data_bus_handler.cc.
References Request::bankNo, BUS_CYCLE, busBusyTime, child1, child2, Request::data, DDR_BUS_WIDTH, IrisEvent::event_data, Simulator::Now(), prevTime, DRAMChannel::process_event(), ResponseHandler::process_event(), Request::rankNo, REPLY, DRAMCmdState::req, Simulator::Schedule(), Data::size, START_READ, START_WRITE, t_CMD, and IrisEvent::type.
Referenced by DRAMChannel::process_event(), and CmdIssuer::process_event().
std::string DataBusHandler::toString ()
Member Data Documentation
Time DataBusHandler::busBusyTime
total time the bus remained busy
Definition at line 59 of file data_bus_handler.h.
Referenced by DataBusHandler(), and process_event().
Component* DataBusHandler::child1
pointer to corresponding DRAM channel
Definition at line 53 of file data_bus_handler.h.
Referenced by process_event(), and Bus::SetLinks().
Component* DataBusHandler::child2
pointer to response handler
Definition at line 54 of file data_bus_handler.h.
Referenced by process_event(), and Bus::SetLinks().
Component* DataBusHandler::parent
pointer to its parent
Definition at line 52 of file data_bus_handler.h.
Referenced by Bus::SetLinks().
Time DataBusHandler::prevTime
variable to keep track of the last time data bus was used
Definition at line 58 of file data_bus_handler.h.
Referenced by DataBusHandler(), and process_event().
The documentation for this class was generated from the following files:
data_bus_handler.h
data_bus_handler.cc