GenericRouterAdaptive Class Reference
#include <genericRouterAdaptive.h>
Public Member Functions
GenericRouterAdaptive ()
~GenericRouterAdaptive ()
void init (uint ports, uint vcs, uint credits, uint buffer_size)
void set_no_nodes (uint nodes)
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
void set_grid_x_location (uint a, uint b, uint c)
void set_grid_y_location (uint a, uint b, uint c)
void send_credit_back (uint i)
void process_event (IrisEvent *e)
string toString () const
string print_stats ()
Public Attributes
vector< vector< uint > > downstream_credits
uint packets
uint flits
double total_packet_latency
double last_flit_out_cycle
unsigned long long int stat_sim_total_time
vector< vector< uint > > stat_packet_out
vector< vector< uint > > stat_flit_out
Private Member Functions
void init_buffer_state (uint, uint, HeadFlit *)
void handle_link_arrival_event (IrisEvent *e)
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
void handle_link_arrival_event_one_msg_per_buffer (IrisEvent *)
void handle_link_arrival_event_multiple_flit_in_buffer (IrisEvent *)
void handle_tick_event (IrisEvent *e)
Event handle for the TICK_EVENT. Entry from DES kernel.
void do_switch_traversal ()
void do_switch_allocation ()
bool is_pkt_in_progress (GenericLink *, uint)
Private Attributes
vector< GenericBuffer > in_buffers
vector< GenericBuffer > new_pkt_buffer
vector< GenericRC > decoders
vector< InputBufferState > input_buffer_state
PToPSwitchArbiter swa
GenericCrossbar xbar
vector< uint > available_ports
bool ticking
Detailed Description
Definition at line 38 of file genericRouterAdaptive.h.
Constructor & Destructor Documentation
GenericRouterAdaptive::GenericRouterAdaptive ()
Definition at line 39 of file genericRouterAdaptive.cc.
References NetworkComponent::name, and ticking.
GenericRouterAdaptive::~GenericRouterAdaptive ()
Definition at line 45 of file genericRouterAdaptive.cc.
Member Function Documentation
void GenericRouterAdaptive::do_switch_allocation () [private]
Definition at line 647 of file genericRouterAdaptive.cc.
References PToPSwitchArbiter::clear_requested(), GenericCrossbar::configure_crossbar(), FULL, input_buffer_state, PToPSwitchArbiter::is_empty(), PToPSwitchArbiter::pick_winner(), SA_unit::port, Router::ports, GenericCrossbar::push(), ST, swa, SWA_REQUESTED, ticking, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterAdaptive::do_switch_traversal () [private]
Definition at line 513 of file genericRouterAdaptive.cc.
References _DBG, NetworkComponent::address, TailFlit::avg_network_latency, HeadFlit::avg_network_latency, BODY, PToPSwitchArbiter::clear_winner(), data, do_two_stage_router, downstream_credits, EMPTY, FLIT_ID, HEAD, TailFlit::hop_count, HeadFlit::hop_count, in_buffers, input_buffer_state, GenericCrossbar::is_empty(), is_pkt_in_progress(), Flit::is_single_flit_pkt, last_flit_out_cycle, LINK_ARRIVAL_EVENT, Simulator::Now(), ONE_FLIT_REQ, Router::output_connections, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, GenericCrossbar::pull(), RESPONSE_PKT, Simulator::Schedule(), send_credit_back(), ST, stat_flit_out, stat_packet_out, swa, TAIL, ticking, total_packet_latency, Flit::type, LinkArrivalData::type, LinkArrivalData::vc, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterAdaptive::handle_link_arrival_event (IrisEvent * e) [private]
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
Definition at line 262 of file genericRouterAdaptive.cc.
References handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), and multiple_flit_in_buf.
Referenced by process_event().
void GenericRouterAdaptive::handle_link_arrival_event_multiple_flit_in_buffer (IrisEvent * e) [private]
Definition at line 372 of file genericRouterAdaptive.cc.
References _DBG, BODY, CREDIT_ID, data, decoders, downstream_credits, EMPTY, IrisEvent::event_data, FLIT_ID, flits, HEAD, in_buffers, init_buffer_state(), HeadFlit::inport, input_buffer_state, Router::input_connections, Flit::is_single_flit_pkt, new_pkt_buffer, Simulator::Now(), Router::output_connections, packets, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, Simulator::Schedule(), IrisEvent::src_id, TAIL, TICK_EVENT, ticking, Flit::type, LinkArrivalData::type, IrisEvent::vc, LinkArrivalData::vc, and Router::vcs.
Referenced by handle_link_arrival_event().
void GenericRouterAdaptive::handle_link_arrival_event_one_msg_per_buffer (IrisEvent * e) [private]
Definition at line 273 of file genericRouterAdaptive.cc.
References _DBG, BODY, CREDIT_ID, data, decoders, downstream_credits, IrisEvent::event_data, FLIT_ID, flits, HEAD, in_buffers, init_buffer_state(), HeadFlit::inport, Router::input_connections, Flit::is_single_flit_pkt, Simulator::Now(), Router::output_connections, packets, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, Simulator::Schedule(), IrisEvent::src_id, TAIL, TICK_EVENT, ticking, Flit::type, LinkArrivalData::type, IrisEvent::vc, and LinkArrivalData::vc.
Referenced by handle_link_arrival_event().
void GenericRouterAdaptive::handle_tick_event (IrisEvent * e) [private]
Event handle for the TICK_EVENT. Entry from DES kernel.
Body and tail flits get written in link arrival and since the message state may already been pushed to ST because of the header we want to ensure that all flits go thru an IB and ST stage. Hence ST is done on the flits_in_ib information and not buffer occupancy.
Definition at line 697 of file genericRouterAdaptive.cc.
References _DBG, BODY, Router::credits, decoders, do_switch_allocation(), do_switch_traversal(), downstream_credits, EMPTY, FULL, HEAD, IB, in_buffers, init_buffer_state(), HeadFlit::inport, input_buffer_state, PToPSwitchArbiter::is_requested(), multiple_flit_in_buf, new_pkt_buffer, Simulator::Now(), Router::ports, NetworkComponent::process_event(), PToPSwitchArbiter::request(), Simulator::Schedule(), ST, swa, SWA_REQUESTED, TAIL, TICK_EVENT, ticking, Flit::type, IrisEvent::vc, and Router::vcs.
Referenced by process_event().
void GenericRouterAdaptive::init (uint ports, uint vcs, uint credits, uint buffer_size) [virtual]
Implements Router .
Definition at line 50 of file genericRouterAdaptive.cc.
References PToPSwitchArbiter::address, NetworkComponent::address, Router::buffer_size, Router::credits, decoders, downstream_credits, EMPTY, flits, in_buffers, input_buffer_state, multiple_flit_in_buf, Component::myId(), new_pkt_buffer, PToPSwitchArbiter::node_ip, NetworkComponent::node_ip, packets, Router::ports, PToPSwitchArbiter::resize(), GenericCrossbar::setup(), stat_flit_out, stat_packet_out, swa, total_packet_latency, Router::vcs, and xbar.
void GenericRouterAdaptive::init_buffer_state (uint port, uint vc, HeadFlit * hf) [private]
Definition at line 228 of file genericRouterAdaptive.cc.
References available_ports, decoders, FULL, input_buffer_state, HeadFlit::length, HeadFlit::msg_class, Simulator::Now(), Router::output_connections, and Router::vcs.
Referenced by handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), and handle_tick_event().
bool GenericRouterAdaptive::is_pkt_in_progress (GenericLink * link, uint vc) [private]
Definition at line 918 of file genericRouterAdaptive.cc.
References NetworkComponent::address, input_buffer_state, Router::input_connections, Router::ports, and Router::vcs.
Referenced by do_switch_traversal().
string GenericRouterAdaptive::print_stats (void) [virtual]
Implements Router .
Definition at line 155 of file genericRouterAdaptive.cc.
References flits, last_flit_out_cycle, NetworkComponent::node_ip, packets, Router::ports, stat_flit_out, stat_packet_out, and total_packet_latency.
void GenericRouterAdaptive::process_event (IrisEvent * e) [virtual]
Implements NetworkComponent .
Definition at line 137 of file genericRouterAdaptive.cc.
References _DBG, handle_link_arrival_event(), handle_tick_event(), LINK_ARRIVAL_EVENT, TICK_EVENT, and IrisEvent::type.
void GenericRouterAdaptive::send_credit_back (uint i)
Definition at line 883 of file genericRouterAdaptive.cc.
References _DBG, NetworkComponent::address, CREDIT_ID, data, do_two_stage_router, input_buffer_state, Router::input_connections, LINK_ARRIVAL_EVENT, Simulator::Now(), NetworkComponent::process_event(), Simulator::Schedule(), LinkArrivalData::type, and LinkArrivalData::vc.
Referenced by do_switch_traversal().
void GenericRouterAdaptive::set_grid_x_location (uint a, uint b, uint c) [virtual]
Implements Router .
Definition at line 123 of file genericRouterAdaptive.cc.
References decoders.
void GenericRouterAdaptive::set_grid_y_location (uint a, uint b, uint c) [virtual]
Implements Router .
Definition at line 129 of file genericRouterAdaptive.cc.
References decoders.
void GenericRouterAdaptive::set_no_nodes (uint nodes) [virtual]
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
Implements Router .
Definition at line 113 of file genericRouterAdaptive.cc.
References decoders.
string GenericRouterAdaptive::toString () const [virtual]
Reimplemented from Router .
Definition at line 860 of file genericRouterAdaptive.cc.
References NetworkComponent::address, decoders, in_buffers, NetworkComponent::node_ip, swa, GenericCrossbar::toString(), PToPSwitchArbiter::toString(), and xbar.
Member Data Documentation
vector<uint> GenericRouterAdaptive::available_ports [private]
Definition at line 74 of file genericRouterAdaptive.h.
Referenced by init_buffer_state().
vector<GenericRC> GenericRouterAdaptive::decoders [private]
Definition at line 70 of file genericRouterAdaptive.h.
Referenced by handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), handle_tick_event(), init(), init_buffer_state(), set_grid_x_location(), set_grid_y_location(), set_no_nodes(), and toString().
vector< vector<uint> > GenericRouterAdaptive::downstream_credits
Definition at line 54 of file genericRouterAdaptive.h.
Referenced by do_switch_traversal(), handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), handle_tick_event(), and init().
uint GenericRouterAdaptive::flits
Definition at line 58 of file genericRouterAdaptive.h.
Referenced by handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), init(), and print_stats().
vector<GenericBuffer> GenericRouterAdaptive::in_buffers [private]
Definition at line 68 of file genericRouterAdaptive.h.
Referenced by do_switch_traversal(), handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), handle_tick_event(), init(), and toString().
vector<InputBufferState> GenericRouterAdaptive::input_buffer_state [private]
Definition at line 71 of file genericRouterAdaptive.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_link_arrival_event_multiple_flit_in_buffer(), handle_tick_event(), init(), init_buffer_state(), is_pkt_in_progress(), and send_credit_back().
double GenericRouterAdaptive::last_flit_out_cycle
Definition at line 60 of file genericRouterAdaptive.h.
Referenced by do_switch_traversal(), and print_stats().
vector<GenericBuffer> GenericRouterAdaptive::new_pkt_buffer [private]
Definition at line 69 of file genericRouterAdaptive.h.
Referenced by handle_link_arrival_event_multiple_flit_in_buffer(), handle_tick_event(), and init().
uint GenericRouterAdaptive::packets
Definition at line 57 of file genericRouterAdaptive.h.
Referenced by handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), init(), and print_stats().
vector< vector<uint> > GenericRouterAdaptive::stat_flit_out
Definition at line 63 of file genericRouterAdaptive.h.
Referenced by do_switch_traversal(), init(), and print_stats().
vector< vector<uint> > GenericRouterAdaptive::stat_packet_out
Definition at line 62 of file genericRouterAdaptive.h.
Referenced by do_switch_traversal(), init(), and print_stats().
unsigned long long int GenericRouterAdaptive::stat_sim_total_time
Definition at line 61 of file genericRouterAdaptive.h.
PToPSwitchArbiter GenericRouterAdaptive::swa [private]
Definition at line 72 of file genericRouterAdaptive.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_tick_event(), init(), and toString().
bool GenericRouterAdaptive::ticking [private]
Definition at line 76 of file genericRouterAdaptive.h.
Referenced by do_switch_allocation(), do_switch_traversal(), GenericRouterAdaptive(), handle_link_arrival_event_multiple_flit_in_buffer(), handle_link_arrival_event_one_msg_per_buffer(), and handle_tick_event().
double GenericRouterAdaptive::total_packet_latency
Definition at line 59 of file genericRouterAdaptive.h.
Referenced by do_switch_traversal(), init(), and print_stats().
GenericCrossbar GenericRouterAdaptive::xbar [private]
Definition at line 73 of file genericRouterAdaptive.h.
Referenced by do_switch_allocation(), do_switch_traversal(), init(), and toString().
The documentation for this class was generated from the following files:
genericRouterAdaptive.h
genericRouterAdaptive.cc