GenericInterface Class Reference
#include <genericInterface.h>
Public Member Functions
GenericInterface ()
~GenericInterface ()
uint get_no_credits () const
void set_no_credits (int credits)
void set_no_vcs (uint v)
void set_buffer_size (uint b)
void setup (uint v, uint cr)
string toString () const
void process_event (IrisEvent *e)
string print_stats ()
ullint get_packets_out ()
ullint get_packets ()
ullint get_flits_out ()
Private Member Functions
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_tick_event (IrisEvent *e)
void handle_link_arrival (IrisEvent *e)
bool is_pkt_in_progress (uint vc)
Private Attributes
uint vcs
uint buffer_size
int credits
bool in_packet_cleared
bool in_packet_complete
bool is_for_mc
bool ticking
GenericBuffer out_buffer
GenericBuffer in_buffer
vector< int > downstream_credits
vector< LowLevelPacket > out_packets
vector< uint > out_packet_flit_index
vector< LowLevelPacket > in_packets
vector< uint > in_packets_flit_index
vector< bool > in_packets_valid
vector< bool > pkt_in_progress
vector< bool > in_ready
ullint flits_in
ullint packets_in
ullint flits_out
ullint packets_out
ullint total_packets_in_time
Detailed Description
Definition at line 46 of file genericInterface.h.
Constructor & Destructor Documentation
GenericInterface::GenericInterface ()
Definition at line 31 of file genericInterface.cc.
References NetworkComponent::name, and ticking.
GenericInterface::~GenericInterface ()
Definition at line 37 of file genericInterface.cc.
References in_packets, and out_packets.
Member Function Documentation
ullint GenericInterface::get_flits_out () [virtual]
Implements Interface .
Definition at line 558 of file genericInterface.cc.
References flits_out.
uint GenericInterface::get_no_credits () const
Definition at line 124 of file genericInterface.cc.
References credits.
ullint GenericInterface::get_packets () [virtual]
Implements Interface .
Definition at line 570 of file genericInterface.cc.
References packets_in, and packets_out.
ullint GenericInterface::get_packets_out () [virtual]
Implements Interface .
Definition at line 564 of file genericInterface.cc.
References packets_out.
void GenericInterface::handle_link_arrival (IrisEvent * e) [private]
Definition at line 202 of file genericInterface.cc.
References _DBG, NetworkComponent::address, GenericBuffer::change_push_channel(), CREDIT_ID, do_two_stage_router, downstream_credits, IrisEvent::event_data, FLIT_ID, flits_in, in_buffer, Interface::input_connection, is_for_mc, Flit::is_single_flit_pkt, LINK_ARRIVAL_EVENT, Simulator::Now(), packets_in, process_event(), NetworkComponent::process_event(), LinkArrivalData::ptr, GenericBuffer::push(), Simulator::Schedule(), TAIL, TICK_EVENT, ticking, total_packets_in_time, IrisEvent::type, Flit::type, LinkArrivalData::type, LinkArrivalData::valid, IrisEvent::vc, and LinkArrivalData::vc.
Referenced by process_event().
void GenericInterface::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 292 of file genericInterface.cc.
References _DBG, IrisEvent::event_data, is_for_mc, Simulator::Now(), out_packet_flit_index, out_packets, packets_in, NetworkComponent::process_event(), Simulator::Schedule(), TICK_EVENT, ticking, HighLevelPacket::to_low_level_packet(), IrisEvent::vc, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void GenericInterface::handle_ready_event (IrisEvent * e) [private]
These are credits from the processor and hence do not update flow control state. Flow control state is updated at the link arrival event for a credit.
Definition at line 177 of file genericInterface.cc.
References _DBG, in_ready, Simulator::Now(), NetworkComponent::process_event(), Simulator::Schedule(), TICK_EVENT, ticking, and IrisEvent::vc.
Referenced by process_event().
void GenericInterface::handle_tick_event (IrisEvent * e) [private]
Definition at line 332 of file genericInterface.cc.
References _DBG, NetworkComponent::address, HighLevelPacket::avg_network_latency, GenericBuffer::change_pull_channel(), GenericBuffer::change_push_channel(), CREDIT_ID, credits, do_two_stage_router, downstream_credits, IrisEvent::event_data, FLIT_ID, flits_out, HighLevelPacket::from_low_level_packet(), GenericBuffer::get_occupancy(), HEAD, HighLevelPacket::hop_count, in_buffer, in_packet_complete, in_packets, in_packets_flit_index, in_ready, Interface::input_connection, is_for_mc, Flit::is_single_flit_pkt, LINK_ARRIVAL_EVENT, multiple_flit_in_buf, NEW_PACKET_EVENT, NetworkComponent::node_ip, Simulator::Now(), out_buffer, out_packet_flit_index, out_packets, Interface::output_connection, packets_out, GenericBuffer::peek(), process_event(), NetworkComponent::process_event(), Interface::processor_connection, LinkArrivalData::ptr, GenericBuffer::pull(), GenericBuffer::push(), READY_EVENT, HighLevelPacket::recv_time, HighLevelPacket::req_start_time, Simulator::Schedule(), IrisEvent::src_id, TAIL, TICK_EVENT, ticking, HighLevelPacket::toString(), toString(), IrisEvent::type, LinkArrivalData::type, Flit::type, IrisEvent::vc, LinkArrivalData::vc, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
bool GenericInterface::is_pkt_in_progress (uint vc) [private]
Definition at line 576 of file genericInterface.cc.
References pkt_in_progress.
string GenericInterface::print_stats (void) [virtual]
Implements Interface .
Definition at line 542 of file genericInterface.cc.
References flits_in, flits_out, NetworkComponent::node_ip, packets_in, packets_out, and total_packets_in_time.
void GenericInterface::process_event (IrisEvent * e) [virtual]
Implements Interface .
Definition at line 150 of file genericInterface.cc.
References handle_link_arrival(), handle_new_packet_event(), handle_ready_event(), handle_tick_event(), LINK_ARRIVAL_EVENT, NEW_PACKET_EVENT, READY_EVENT, TICK_EVENT, and IrisEvent::type.
Referenced by handle_link_arrival(), and handle_tick_event().
void GenericInterface::set_buffer_size (uint b) [virtual]
Implements Interface .
Definition at line 116 of file genericInterface.cc.
References buffer_size.
void GenericInterface::set_no_credits (int credits) [virtual]
Implements Interface .
Definition at line 130 of file genericInterface.cc.
References credits.
void GenericInterface::set_no_vcs (uint v) [virtual]
Implements Interface .
Definition at line 110 of file genericInterface.cc.
References vcs.
void GenericInterface::setup (uint v, uint cr) [virtual]
Implements Interface .
Definition at line 45 of file genericInterface.cc.
References NetworkComponent::address, buffer_size, credits, downstream_credits, flits_in, flits_out, in_buffer, in_packet_complete, in_packets, in_packets_flit_index, in_packets_valid, in_ready, is_for_mc, mc_positions, Component::myId(), NetworkComponent::node_ip, out_buffer, out_packet_flit_index, out_packets, packets_in, packets_out, GenericBuffer::resize(), total_packets_in_time, and vcs.
string GenericInterface::toString () const [virtual]
Reimplemented from Interface .
Definition at line 137 of file genericInterface.cc.
References NetworkComponent::address, in_buffer, NetworkComponent::node_ip, out_buffer, out_packets, and GenericBuffer::toString().
Referenced by handle_tick_event().
Member Data Documentation
uint GenericInterface::buffer_size [private]
Definition at line 69 of file genericInterface.h.
Referenced by set_buffer_size(), and setup().
int GenericInterface::credits [private]
Definition at line 70 of file genericInterface.h.
Referenced by get_no_credits(), handle_tick_event(), set_no_credits(), and setup().
vector< int > GenericInterface::downstream_credits [private]
Definition at line 78 of file genericInterface.h.
Referenced by handle_link_arrival(), handle_tick_event(), and setup().
ullint GenericInterface::flits_in [private]
Definition at line 100 of file genericInterface.h.
Referenced by handle_link_arrival(), print_stats(), and setup().
ullint GenericInterface::flits_out [private]
Definition at line 102 of file genericInterface.h.
Referenced by get_flits_out(), handle_tick_event(), print_stats(), and setup().
GenericBuffer GenericInterface::in_buffer [private]
Definition at line 77 of file genericInterface.h.
Referenced by handle_link_arrival(), handle_tick_event(), setup(), and toString().
bool GenericInterface::in_packet_cleared [private]
Definition at line 71 of file genericInterface.h.
bool GenericInterface::in_packet_complete [private]
Definition at line 72 of file genericInterface.h.
Referenced by handle_tick_event(), and setup().
vector< LowLevelPacket> GenericInterface::in_packets [private]
Definition at line 85 of file genericInterface.h.
Referenced by handle_tick_event(), setup(), and ~GenericInterface().
vector< uint > GenericInterface::in_packets_flit_index [private]
Definition at line 86 of file genericInterface.h.
Referenced by handle_tick_event(), and setup().
vector< bool> GenericInterface::in_packets_valid [private]
Definition at line 87 of file genericInterface.h.
Referenced by setup().
vector< bool > GenericInterface::in_ready [private]
Definition at line 90 of file genericInterface.h.
Referenced by handle_ready_event(), handle_tick_event(), and setup().
bool GenericInterface::is_for_mc [private]
Definition at line 73 of file genericInterface.h.
Referenced by handle_link_arrival(), handle_new_packet_event(), handle_tick_event(), and setup().
GenericBuffer GenericInterface::out_buffer [private]
Definition at line 76 of file genericInterface.h.
Referenced by handle_tick_event(), setup(), and toString().
vector< uint > GenericInterface::out_packet_flit_index [private]
Definition at line 82 of file genericInterface.h.
Referenced by handle_new_packet_event(), handle_tick_event(), and setup().
vector< LowLevelPacket> GenericInterface::out_packets [private]
Definition at line 81 of file genericInterface.h.
Referenced by handle_new_packet_event(), handle_tick_event(), setup(), toString(), and ~GenericInterface().
ullint GenericInterface::packets_in [private]
Definition at line 101 of file genericInterface.h.
Referenced by get_packets(), handle_link_arrival(), handle_new_packet_event(), print_stats(), and setup().
ullint GenericInterface::packets_out [private]
Definition at line 103 of file genericInterface.h.
Referenced by get_packets(), get_packets_out(), handle_tick_event(), print_stats(), and setup().
vector< bool> GenericInterface::pkt_in_progress [private]
Definition at line 88 of file genericInterface.h.
Referenced by is_pkt_in_progress().
bool GenericInterface::ticking [private]
Definition at line 75 of file genericInterface.h.
Referenced by GenericInterface(), handle_link_arrival(), handle_new_packet_event(), handle_ready_event(), and handle_tick_event().
ullint GenericInterface::total_packets_in_time [private]
Definition at line 104 of file genericInterface.h.
Referenced by handle_link_arrival(), print_stats(), and setup().
uint GenericInterface::vcs [private]
Definition at line 68 of file genericInterface.h.
Referenced by set_no_vcs(), and setup().
The documentation for this class was generated from the following files:
genericInterface.h
genericInterface.cc