core_alloc_t Class Reference
#include <zesto-alloc.h>
Public Member Functions
core_alloc_t (void)
virtual ~core_alloc_t ()
virtual void reg_stats (struct stat_sdb_t *const sdb)=0
virtual void step (void)=0
virtual void recover (void)=0
virtual void recover (const struct Mop_t *const Mop)=0
virtual void RS_deallocate (const struct uop_t *const uop)=0
virtual void start_drain (void)=0
Public Attributes
bool drain_in_progress
Protected Attributes
struct core_t * core
Detailed Description
Definition at line 78 of file zesto-alloc.h.
Constructor & Destructor Documentation
core_alloc_t::core_alloc_t (void)
Definition at line 101 of file zesto-alloc.cpp.
core_alloc_t::~core_alloc_t () [virtual]
Definition at line 107 of file zesto-alloc.cpp.
Member Function Documentation
virtual void core_alloc_t::recover (const struct Mop_t *const Mop) [pure virtual]
Implemented in core_alloc_DPM_t , and core_alloc_STM_t .
virtual void core_alloc_t::recover (void) [pure virtual]
Implemented in core_alloc_DPM_t , and core_alloc_STM_t .
Referenced by emergency_recovery(), core_oracle_t::pipe_recover(), core_oracle_t::reset_execution(), core_fetch_DPM_t::step(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
virtual void core_alloc_t::reg_stats (struct stat_sdb_t *const sdb) [pure virtual]
Implemented in core_alloc_DPM_t , and core_alloc_STM_t .
virtual void core_alloc_t::RS_deallocate (const struct uop_t *const uop) [pure virtual]
Implemented in core_alloc_DPM_t , and core_alloc_STM_t .
Referenced by core_exec_STM_t::ALU_exec(), core_exec_DPM_t::ALU_exec(), core_commit_STM_t::recover(), and core_commit_DPM_t::recover().
virtual void core_alloc_t::start_drain (void) [pure virtual]
Implemented in core_alloc_DPM_t , and core_alloc_STM_t .
Referenced by core_commit_STM_t::recover(), and core_commit_DPM_t::recover().
virtual void core_alloc_t::step (void) [pure virtual]
Implemented in core_alloc_DPM_t , and core_alloc_STM_t .
Member Data Documentation
struct core_t* core_alloc_t::core [read, protected]
Definition at line 102 of file zesto-alloc.h.
Referenced by core_alloc_DPM_t::core_alloc_DPM_t(), core_alloc_STM_t::core_alloc_STM_t(), core_alloc_DPM_t::recover(), core_alloc_STM_t::reg_stats(), core_alloc_DPM_t::reg_stats(), core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
bool core_alloc_t::drain_in_progress
Definition at line 82 of file zesto-alloc.h.
Referenced by core_alloc_STM_t::start_drain(), core_alloc_DPM_t::start_drain(), core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
The documentation for this class was generated from the following files:
zesto-alloc.h
zesto-alloc.cpp