PToPSwitchArbiter Class Reference
#include <ptop_swa.h>
Public Member Functions
PToPSwitchArbiter ()
~PToPSwitchArbiter ()
void resize (uint p)
bool is_requested (uint outp, uint inp)
void request (uint p, uint inp)
SA_unit pick_winner (uint p)
SA_unit do_round_robin_arbitration (uint p)
SA_unit do_priority_round_robin_arbitration (uint p)
SA_unit do_fcfs_arbitration (uint p)
void clear_winner (uint p, uint ip)
void clear_requested (uint p, uint ip)
void request (uint oport, uint inport, message_class m)
bool is_empty ()
string toString () const
Public Attributes
uint address
string name
uint node_ip
Private Attributes
uint PORTS
uint CHANNELS
vector< bool > locked
vector< bool > done
vector< vector< bool > > requested
vector< vector< bool > > priority_reqs
vector< bool > port_locked
vector< vector< SA_unit > > requesting_inputs
vector< SA_unit > last_winner
vector< uint > last_port_winner
Detailed Description
Definition at line 30 of file ptop_swa.h.
Constructor & Destructor Documentation
PToPSwitchArbiter::PToPSwitchArbiter ()
Definition at line 24 of file ptop_swa.cc.
References name.
PToPSwitchArbiter::~PToPSwitchArbiter ()
Definition at line 29 of file ptop_swa.cc.
Member Function Documentation
void PToPSwitchArbiter::clear_requested (uint p, uint ip)
Definition at line 299 of file ptop_swa.cc.
References priority_reqs, and requested.
Referenced by GenericRouterVct::do_switch_allocation(), and GenericRouterAdaptive::do_switch_allocation().
void PToPSwitchArbiter::clear_winner (uint p, uint ip)
Definition at line 288 of file ptop_swa.cc.
References done, locked, priority_reqs, and requested.
Referenced by GenericRouterVct::do_switch_traversal(), GenericRouterNoVcs::do_switch_traversal(), and GenericRouterAdaptive::do_switch_traversal().
SA_unit PToPSwitchArbiter::do_fcfs_arbitration (uint p)
Definition at line 244 of file ptop_swa.cc.
References _DBG_NOARG, done, last_winner, locked, Simulator::Now(), PORTS, requested, and requesting_inputs.
Referenced by pick_winner().
SA_unit PToPSwitchArbiter::do_priority_round_robin_arbitration (uint p)
Definition at line 176 of file ptop_swa.cc.
References _DBG_NOARG, done, last_port_winner, last_winner, locked, PORTS, priority_reqs, requested, and requesting_inputs.
Referenced by pick_winner().
SA_unit PToPSwitchArbiter::do_round_robin_arbitration (uint p)
Definition at line 120 of file ptop_swa.cc.
References _DBG_NOARG, done, last_port_winner, last_winner, locked, PORTS, requested, and requesting_inputs.
Referenced by pick_winner().
bool PToPSwitchArbiter::is_empty (void)
Definition at line 307 of file ptop_swa.cc.
References PORTS, and requested.
Referenced by GenericRouterVct::do_switch_allocation(), GenericRouterNoVcs::do_switch_allocation(), and GenericRouterAdaptive::do_switch_allocation().
bool PToPSwitchArbiter::is_requested (uint outp, uint inp)
Definition at line 69 of file ptop_swa.cc.
References requested.
Referenced by GenericRouterVct::handle_tick_event(), GenericRouterNoVcs::handle_tick_event(), and GenericRouterAdaptive::handle_tick_event().
SA_unit PToPSwitchArbiter::pick_winner (uint p)
Definition at line 99 of file ptop_swa.cc.
References do_fcfs_arbitration(), do_priority_round_robin_arbitration(), do_round_robin_arbitration(), FCFS, ROUND_ROBIN, ROUND_ROBIN_PRIORITY, and sw_arbitration.
Referenced by GenericRouterVct::do_switch_allocation(), GenericRouterNoVcs::do_switch_allocation(), and GenericRouterAdaptive::do_switch_allocation().
void PToPSwitchArbiter::request (uint oport, uint inport, message_class m)
Definition at line 85 of file ptop_swa.cc.
References done, Simulator::Now(), priority_msg_type, priority_reqs, requested, and requesting_inputs.
void PToPSwitchArbiter::request (uint p, uint inp)
Definition at line 75 of file ptop_swa.cc.
References done, Simulator::Now(), requested, and requesting_inputs.
Referenced by GenericRouterVct::handle_tick_event(), GenericRouterNoVcs::handle_tick_event(), and GenericRouterAdaptive::handle_tick_event().
void PToPSwitchArbiter::resize (uint p)
Definition at line 34 of file ptop_swa.cc.
References done, last_port_winner, last_winner, locked, port_locked, PORTS, priority_reqs, requested, and requesting_inputs.
Referenced by GenericRouterVct::init(), GenericRouterNoVcs::init(), and GenericRouterAdaptive::init().
string PToPSwitchArbiter::toString () const
Definition at line 320 of file ptop_swa.cc.
References requested.
Referenced by GenericRouterVct::toString(), GenericRouterNoVcs::toString(), and GenericRouterAdaptive::toString().
Member Data Documentation
uint PToPSwitchArbiter::address
Definition at line 47 of file ptop_swa.h.
Referenced by GenericRouterAdaptive::init().
uint PToPSwitchArbiter::CHANNELS [private]
Definition at line 55 of file ptop_swa.h.
vector< bool> PToPSwitchArbiter::done [private]
Definition at line 57 of file ptop_swa.h.
Referenced by clear_winner(), do_fcfs_arbitration(), do_priority_round_robin_arbitration(), do_round_robin_arbitration(), request(), and resize().
vector< uint> PToPSwitchArbiter::last_port_winner [private]
Definition at line 63 of file ptop_swa.h.
Referenced by do_priority_round_robin_arbitration(), do_round_robin_arbitration(), and resize().
vector< SA_unit > PToPSwitchArbiter::last_winner [private]
Definition at line 62 of file ptop_swa.h.
Referenced by do_fcfs_arbitration(), do_priority_round_robin_arbitration(), do_round_robin_arbitration(), and resize().
vector< bool> PToPSwitchArbiter::locked [private]
Definition at line 56 of file ptop_swa.h.
Referenced by clear_winner(), do_fcfs_arbitration(), do_priority_round_robin_arbitration(), do_round_robin_arbitration(), and resize().
string PToPSwitchArbiter::name
Definition at line 48 of file ptop_swa.h.
Referenced by PToPSwitchArbiter().
uint PToPSwitchArbiter::node_ip
Definition at line 49 of file ptop_swa.h.
Referenced by GenericRouterAdaptive::init().
vector< bool> PToPSwitchArbiter::port_locked [private]
Definition at line 60 of file ptop_swa.h.
Referenced by resize().
uint PToPSwitchArbiter::PORTS [private]
Definition at line 54 of file ptop_swa.h.
Referenced by do_fcfs_arbitration(), do_priority_round_robin_arbitration(), do_round_robin_arbitration(), is_empty(), and resize().
vector< vector <bool> > PToPSwitchArbiter::priority_reqs [private]
Definition at line 59 of file ptop_swa.h.
Referenced by clear_requested(), clear_winner(), do_priority_round_robin_arbitration(), request(), and resize().
vector< vector <bool> > PToPSwitchArbiter::requested [private]
Definition at line 58 of file ptop_swa.h.
Referenced by clear_requested(), clear_winner(), do_fcfs_arbitration(), do_priority_round_robin_arbitration(), do_round_robin_arbitration(), is_empty(), is_requested(), request(), resize(), and toString().
vector< vector<SA_unit> > PToPSwitchArbiter::requesting_inputs [private]
Definition at line 61 of file ptop_swa.h.
Referenced by do_fcfs_arbitration(), do_priority_round_robin_arbitration(), do_round_robin_arbitration(), request(), and resize().
The documentation for this class was generated from the following files:
ptop_swa.h
ptop_swa.cc