core_fetch_STM_t Class Reference
Classes
struct byteQ_entry_t
Public Member Functions
core_fetch_STM_t (struct core_t *const core)
virtual void reg_stats (struct stat_sdb_t *const sdb)
virtual void update_occupancy (void)
virtual void step (void)
virtual bool Mop_available (void)
virtual struct Mop_t * Mop_peek (void)
virtual void Mop_consume (void)
virtual void jeclear_enqueue (struct Mop_t *const Mop, const md_addr_t New_PC)
virtual void recover (const md_addr_t new_PC)
Protected Member Functions
void byteQ_request (const md_addr_t lineaddr)
bool byteQ_is_full (void)
bool byteQ_already_requested (const md_addr_t addr)
Static Protected Member Functions
static void IL1_callback (void *const op)
static void ITLB_callback (void *const op)
static bool translated_callback (void *const op, const seq_t action_id)
static seq_t get_byteQ_action_id (void *const op)
Protected Attributes
int byteQ_num
struct core_fetch_STM_t::byteQ_entry_t * byteQ
int byteQ_linemask
int byteQ_head
int byteQ_tail
Static Protected Attributes
static const char * fetch_stall_str [FSTALL_num]
Private Types
enum fetch_stall_t {
FSTALL_byteQ_FULL,
FSTALL_TBR,
FSTALL_EOL,
FSTALL_BOGUS,
FSTALL_SYSCALL,
FSTALL_ZPAGE,
FSTALL_num
 }
Detailed Description
Definition at line 11 of file fetch-STM.cpp.
Member Enumeration Documentation
enum core_fetch_STM_t::fetch_stall_t [private]
Enumerator:
FSTALL_byteQ_FULL
FSTALL_TBR
FSTALL_EOL
FSTALL_BOGUS
FSTALL_SYSCALL
FSTALL_ZPAGE
FSTALL_num
Definition at line 13 of file fetch-STM.cpp.
Constructor & Destructor Documentation
core_fetch_STM_t::core_fetch_STM_t (struct core_t *const core)
Definition at line 89 of file fetch-STM.cpp.
References core_fetch_t::bpred, core_knobs_t::bpred_opt_str, byteQ, byteQ_head, byteQ_linemask, core_knobs_t::byteQ_linesize, core_knobs_t::byteQ_size, byteQ_tail, cache_create(), CACHE_READONLY, core_fetch_t::core, core_knobs_t::dirjmpbtb_opt_str, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::DL2_bus, fatal(), core_knobs_t::fetch, core_knobs_t::fusion_opt_str, core_t::core_t::core_memory_t::IL1, core_knobs_t::IL1_high_watermark, core_knobs_t::IL1_low_watermark, core_knobs_t::IL1_num_PF, core_knobs_t::IL1_opt_str, core_knobs_t::IL1_PF_on_miss, core_knobs_t::IL1_PFFsize, core_knobs_t::IL1_PFmax, core_knobs_t::IL1_PFthresh, core_knobs_t::IL1_WMinterval, core_knobs_t::IL1PF_opt_str, core_knobs_t::indirjmpbtb_opt_str, core_t::core_t::core_memory_t::ITLB, core_knobs_t::ITLB_opt_str, core_knobs_t::jeclear_delay, core_t::knobs, knobs, core_knobs_t::latency, uncore_t::LLC, uncore_t::LLC_bus, core_t::memory, core_knobs_t::memory, cache_t::name, core_knobs_t::num_bpred_components, cache_t::num_prefetchers, cache_t::PF_high_watermark, cache_t::PF_low_watermark, cache_t::PF_sample_interval, cache_t::PFF, cache_t::PFF_size, prefetch_create(), cache_t::prefetch_max, cache_t::prefetch_on_miss, cache_t::prefetch_threshold, cache_t::prefetcher, core_knobs_t::ras_opt_str, and core_t::uncore.
Member Function Documentation
bool core_fetch_STM_t::byteQ_already_requested (const md_addr_t addr) [protected]
Definition at line 229 of file fetch-STM.cpp.
References byteQ, byteQ_linemask, byteQ_num, core_knobs_t::byteQ_size, byteQ_tail, core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, knobs, and moddec().
Referenced by step().
bool core_fetch_STM_t::byteQ_is_full (void) [protected]
Definition at line 222 of file fetch-STM.cpp.
References byteQ_num, core_knobs_t::byteQ_size, core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, and knobs.
Referenced by step().
void core_fetch_STM_t::byteQ_request (const md_addr_t lineaddr) [protected]
Definition at line 240 of file fetch-STM.cpp.
References core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::action_id, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::addr, byteQ, byteQ_num, core_knobs_t::byteQ_size, byteQ_tail, core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, knobs, modinc(), core_t::new_action_id(), TICK_T_MAX, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetch_requested, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetched, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translated, and core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translation_requested.
Referenced by step().
seq_t core_fetch_STM_t::get_byteQ_action_id (void *const op) [static, protected]
Definition at line 280 of file fetch-STM.cpp.
References core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::action_id, and byteQ.
Referenced by step().
void core_fetch_STM_t::IL1_callback (void *const op) [static, protected]
Definition at line 259 of file fetch-STM.cpp.
References byteQ, sim_cycle, and core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetched.
Referenced by step().
void core_fetch_STM_t::ITLB_callback (void *const op) [static, protected]
Definition at line 265 of file fetch-STM.cpp.
References byteQ, sim_cycle, and core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translated.
Referenced by step().
void core_fetch_STM_t::jeclear_enqueue (struct Mop_t *const Mop, const md_addr_t New_PC) [virtual]
Implements core_fetch_t .
Definition at line 505 of file fetch-STM.cpp.
References fatal().
bool core_fetch_STM_t::Mop_available (void) [virtual]
Implements core_fetch_t .
Definition at line 459 of file fetch-STM.cpp.
References byteQ, byteQ_head, byteQ_num, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::num_Mop, TICK_T_MAX, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetched, and core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translated.
void core_fetch_STM_t::Mop_consume (void) [virtual]
Implements core_fetch_t .
Definition at line 474 of file fetch-STM.cpp.
References byteQ, byteQ_head, byteQ_num, core_knobs_t::byteQ_size, core_fetch_t::core, uop_t::decode, Mop_t::decode, uop_t::EOM, core_knobs_t::fetch, core_t::core_t::core_stat_t::fetch_insn, core_t::core_t::core_stat_t::fetch_uops, core_oracle_t::get_Mop(), core_t::knobs, knobs, Mop_t::last_uop_index, modinc(), core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::MopQ_first_index, core_oracle_t::next_index(), core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::num_Mop, Mop_t::num_uops, core_t::oracle, sim_cycle, Mop_t::stat, core_t::stat, TICK_T_MAX, Mop_t::timing, Mop_t::uop, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetch_requested, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetched, Mop_t::when_fetched, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translated, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translation_requested, and ZESTO_STAT.
struct Mop_t * core_fetch_STM_t::Mop_peek (void) [read, virtual]
Implements core_fetch_t .
Definition at line 466 of file fetch-STM.cpp.
References byteQ, byteQ_head, core_fetch_t::core, core_oracle_t::get_Mop(), core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::MopQ_first_index, core_t::oracle, and zesto_assert.
void core_fetch_STM_t::recover (const md_addr_t new_PC) [virtual]
Implements core_fetch_t .
Definition at line 512 of file fetch-STM.cpp.
References core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::action_id, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::addr, core_fetch_t::bogus, byteQ, byteQ_head, byteQ_num, core_knobs_t::byteQ_size, byteQ_tail, core_fetch_t::core, core_knobs_t::fetch, core_t::knobs, knobs, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::MopQ_first_index, core_t::new_action_id(), core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::num_Mop, core_fetch_t::PC, TICK_T_MAX, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetch_requested, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetched, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translated, and core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translation_requested.
void core_fetch_STM_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Implements core_fetch_t .
Definition at line 169 of file fetch-STM.cpp.
References core_fetch_t::bpred, core_t::core_t::core_stat_t::byteQ_occupancy, cache_reg_stats(), core_fetch_t::core, core_t::current_thread, core_t::core_t::core_stat_t::fetch_insn, core_t::core_t::core_stat_t::fetch_stall, fetch_stall_str, core_t::core_t::core_stat_t::fetch_uops, FSTALL_num, thread_t::id, core_t::core_t::core_memory_t::IL1, core_t::core_t::core_memory_t::ITLB, core_t::memory, PF_COUNT, PF_PDF, bpred_t::reg_stats(), core_t::stat, stat_reg_counter, stat_reg_dist(), stat_reg_formula(), and stat_reg_note().
void core_fetch_STM_t::step (void) [virtual]
Implements core_fetch_t .
Definition at line 290 of file fetch-STM.cpp.
References core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::action_id, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::addr, core_fetch_t::bogus, core_fetch_t::bpred, Mop_t::bpred_update, byteQ, byteQ_already_requested(), byteQ_head, byteQ_is_full(), byteQ_linemask, byteQ_num, byteQ_request(), core_knobs_t::byteQ_size, byteQ_tail, cache_enqueuable(), cache_enqueue(), cache_process(), CACHE_READ, cache_t::check_for_work, core_oracle_t::consume(), core_fetch_t::core, core_t::current_thread, Mop_t::decode, core_oracle_t::exec(), Mop_t::fetch, core_knobs_t::fetch, core_t::core_t::core_stat_t::fetch_stall, Mop_t::first_byte_requested, FSTALL_BOGUS, FSTALL_byteQ_FULL, FSTALL_EOL, FSTALL_SYSCALL, FSTALL_TBR, FSTALL_ZPAGE, get_byteQ_action_id(), core_oracle_t::get_index(), bpred_t::get_state_cache(), thread_t::id, core_t::core_t::core_memory_t::IL1, IL1_callback(), Mop_t::inst, Mop_t::is_ctrl, core_t::core_t::core_memory_t::ITLB, ITLB_callback(), core_t::knobs, knobs, Mop_t::last_byte_requested, Mop_t::last_uop_index, md_inst_t::len, bpred_t::lookup(), core_t::memory, moddec(), modinc(), core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::MopQ_first_index, Mop_t::NextPC, NO_MSHR, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::num_Mop, Mop_t::opflags, uop_t::oracle, Mop_t::oracle, core_t::oracle, PAGE_SHIFT, PAGE_TABLE_ADDR, Mop_t::PC, core_fetch_t::PC, Mop_t::pred_NPC, uop_t::recover_inst, Mop_t::recover_inst, md_inst_t::rep, sim_cycle, core_oracle_t::spec_mode, bpred_t::spec_update(), core_t::stat, stat_add_sample(), Mop_t::targetPC, TICK_T_MAX, Mop_t::timing, translated_callback(), Mop_t::uop, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetch_requested, Mop_t::when_fetch_started, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_fetched, Mop_t::when_fetched, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translated, core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translation_requested, zesto_assert, and ZESTO_STAT.
bool core_fetch_STM_t::translated_callback (void *const op, const seq_t action_id) [static, protected]
Definition at line 271 of file fetch-STM.cpp.
References core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::action_id, byteQ, sim_cycle, and core_fetch_STM_t::core_fetch_STM_t::byteQ_entry_t::when_translated.
Referenced by step().
void core_fetch_STM_t::update_occupancy (void) [virtual]
Implements core_fetch_t .
Definition at line 212 of file fetch-STM.cpp.
References byteQ_num, core_t::core_t::core_stat_t::byteQ_occupancy, core_fetch_t::core, and core_t::stat.
Member Data Documentation
struct core_fetch_STM_t::byteQ_entry_t * core_fetch_STM_t::byteQ [protected]
Referenced by byteQ_already_requested(), byteQ_request(), core_fetch_STM_t(), get_byteQ_action_id(), IL1_callback(), ITLB_callback(), Mop_available(), Mop_consume(), Mop_peek(), recover(), step(), and translated_callback().
int core_fetch_STM_t::byteQ_head [protected]
Definition at line 63 of file fetch-STM.cpp.
Referenced by core_fetch_STM_t(), Mop_available(), Mop_consume(), Mop_peek(), recover(), and step().
int core_fetch_STM_t::byteQ_linemask [protected]
Definition at line 62 of file fetch-STM.cpp.
Referenced by byteQ_already_requested(), core_fetch_STM_t(), and step().
int core_fetch_STM_t::byteQ_num [protected]
Definition at line 45 of file fetch-STM.cpp.
Referenced by byteQ_already_requested(), byteQ_is_full(), byteQ_request(), Mop_available(), Mop_consume(), recover(), step(), and update_occupancy().
int core_fetch_STM_t::byteQ_tail [protected]
Definition at line 64 of file fetch-STM.cpp.
Referenced by byteQ_already_requested(), byteQ_request(), core_fetch_STM_t(), recover(), and step().
const char * core_fetch_STM_t::fetch_stall_str [static, protected]
Initial value:
 {
  "byteQ full             ",
  "taken branch           ",
  "end of cache line      ",
  "wrong-path invalid inst",
  "trap waiting on drain  ",
  "request for page zero  "
}
Definition at line 66 of file fetch-STM.cpp.
Referenced by reg_stats().
The documentation for this class was generated from the following file:
fetch-STM.cpp