core_commit_DPM_t Class Reference
Public Member Functions
core_commit_DPM_t (struct core_t *const core)
virtual void reg_stats (struct stat_sdb_t *const sdb)
virtual void update_occupancy (void)
virtual void step (void)
virtual void recover (const struct Mop_t *const Mop)
virtual void recover (void)
virtual bool ROB_available (void)
virtual bool ROB_empty (void)
virtual void ROB_insert (struct uop_t *const uop)
virtual void ROB_fuse_insert (struct uop_t *const uop)
Protected Attributes
struct uop_t ** ROB
int ROB_head
int ROB_tail
int ROB_num
int ROB_eff_num
tick_t when_rep_fetch_started
tick_t when_rep_fetched
tick_t when_rep_decode_started
tick_t when_rep_commit_started
Static Protected Attributes
static const char * commit_stall_str [CSTALL_num]
Private Types
enum commit_stall_t {
CSTALL_NONE,
CSTALL_NOT_READY,
CSTALL_PARTIAL,
CSTALL_EMPTY,
CSTALL_JECLEAR_INFLIGHT,
CSTALL_MAX_BRANCHES,
CSTALL_num
 }
Detailed Description
Definition at line 11 of file commit-DPM.cpp.
Member Enumeration Documentation
enum core_commit_DPM_t::commit_stall_t [private]
Enumerator:
CSTALL_NONE
CSTALL_NOT_READY
CSTALL_PARTIAL
CSTALL_EMPTY
CSTALL_JECLEAR_INFLIGHT
CSTALL_MAX_BRANCHES
CSTALL_num
Reimplemented from core_commit_t .
Definition at line 13 of file commit-DPM.cpp.
Constructor & Destructor Documentation
core_commit_DPM_t::core_commit_DPM_t (struct core_t *const core)
Definition at line 72 of file commit-DPM.cpp.
References core_knobs_t::commit, core_commit_t::core, fatal(), core_t::knobs, knobs, ROB, and core_knobs_t::ROB_size.
Member Function Documentation
void core_commit_DPM_t::recover (void) [virtual]
Implements core_commit_t .
Definition at line 817 of file commit-DPM.cpp.
References uop_t::action_id, core_t::alloc, uop_t::alloc, core_knobs_t::commit, core_commit_t::core, uop_t::decode, core_t::exec, uop_t::exec, uop_t::fusion_head, uop_t::fusion_next, uop_t::idep_uop, uop_t::in_fusion, uop_t::is_fusion_head, uop_t::is_load, uop_t::is_sta, uop_t::is_std, core_t::knobs, knobs, core_exec_t::LDQ_squash(), MAX_IDEPS, moddec(), core_t::new_action_id(), odep_t::next, uop_t::odep_uop, odep_t::op_num, uop_t::port_assignment, core_exec_t::recover_check_assertions(), core_t::return_odep_link(), ROB, ROB_eff_num, ROB_num, core_knobs_t::ROB_size, ROB_tail, core_exec_t::RS_deallocate(), core_alloc_t::RS_deallocate(), uop_t::RS_index, core_exec_t::STQ_squash_senior(), core_exec_t::STQ_squash_sta(), core_exec_t::STQ_squash_std(), TICK_T_MAX, uop_t::timing, odep_t::uop, uop_t::when_allocated, uop_t::when_exec, and zesto_assert.
Referenced by step().
void core_commit_DPM_t::recover (const struct Mop_t *const Mop) [virtual]
Implements core_commit_t .
Definition at line 687 of file commit-DPM.cpp.
References uop_t::action_id, uop_t::alloc, core_t::alloc, core_knobs_t::alloc, core_knobs_t::commit, core_commit_t::core, uop_t::decode, core_knobs_t::drain_flush, core_t::exec, uop_t::exec, uop_t::fusion_head, uop_t::fusion_next, uop_t::idep_uop, uop_t::in_fusion, uop_t::is_fusion_head, uop_t::is_load, uop_t::is_sta, uop_t::is_std, core_t::knobs, knobs, core_exec_t::LDQ_squash(), MAX_IDEPS, moddec(), uop_t::Mop, core_t::new_action_id(), odep_t::next, uop_t::odep_uop, odep_t::op_num, uop_t::port_assignment, core_t::return_odep_link(), ROB, ROB_eff_num, ROB_num, core_knobs_t::ROB_size, ROB_tail, core_exec_t::RS_deallocate(), core_alloc_t::RS_deallocate(), uop_t::RS_index, core_alloc_t::start_drain(), core_exec_t::STQ_squash_sta(), core_exec_t::STQ_squash_std(), TICK_T_MAX, uop_t::timing, odep_t::uop, uop_t::when_allocated, uop_t::when_exec, and zesto_assert.
void core_commit_DPM_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Implements core_commit_t .
Definition at line 85 of file commit-DPM.cpp.
References core_t::core_t::core_stat_t::commit_branches, core_t::core_t::core_stat_t::commit_bytes, core_t::core_t::core_stat_t::commit_deadlock_flushes, core_t::core_t::core_stat_t::commit_eff_uops, core_t::core_t::core_stat_t::commit_fusions, core_t::core_t::core_stat_t::commit_insn, core_t::core_t::core_stat_t::commit_loads, core_t::core_t::core_stat_t::commit_refs, core_t::core_t::core_stat_t::commit_rep_insn, core_t::core_t::core_stat_t::commit_rep_iterations, core_t::core_t::core_stat_t::commit_rep_uops, core_t::core_t::core_stat_t::commit_stall, commit_stall_str, core_t::core_t::core_stat_t::commit_traps, core_t::core_t::core_stat_t::commit_uops, core_t::core_t::core_stat_t::commit_UROM_eff_uops, core_t::core_t::core_stat_t::commit_UROM_insn, core_t::core_t::core_stat_t::commit_UROM_uops, core_commit_t::core, CSTALL_num, core_t::current_thread, core_t::core_t::core_stat_t::DL1_store_split_accesses, core_t::core_t::core_stat_t::eff_flow_histo, core_t::core_t::core_stat_t::final_sim_cycle, core_t::core_t::core_stat_t::flow_histo, FLOW_HISTO_SIZE, thread_t::id, core_t::core_t::core_stat_t::Mop_commit_slip, core_t::core_t::core_stat_t::Mop_decode2commit_slip, core_t::core_t::core_stat_t::Mop_decode_slip, core_t::core_t::core_stat_t::Mop_fetch2decode_slip, core_t::core_t::core_stat_t::Mop_fetch_slip, PF_COUNT, PF_PDF, core_t::core_t::core_stat_t::ROB_eff_occupancy, core_t::core_t::core_stat_t::ROB_empty_cycles, core_t::core_t::core_stat_t::ROB_full_cycles, core_t::core_t::core_stat_t::ROB_occupancy, core_t::stat, stat_reg_counter, stat_reg_dist(), stat_reg_formula(), stat_reg_note(), stat_reg_qword(), core_t::core_t::core_stat_t::uop_alloc2ready_slip, core_t::core_t::core_stat_t::uop_complete2commit_slip, core_t::core_t::core_stat_t::uop_decode2alloc_slip, core_t::core_t::core_stat_t::uop_exec2complete_slip, core_t::core_t::core_stat_t::uop_issue2exec_slip, and core_t::core_t::core_stat_t::uop_ready2issue_slip.
bool core_commit_DPM_t::ROB_available (void) [virtual]
Implements core_commit_t .
Definition at line 948 of file commit-DPM.cpp.
References core_knobs_t::commit, core_commit_t::core, core_t::knobs, knobs, ROB_num, and core_knobs_t::ROB_size.
bool core_commit_DPM_t::ROB_empty (void) [virtual]
Implements core_commit_t .
Definition at line 954 of file commit-DPM.cpp.
References ROB_num.
void core_commit_DPM_t::ROB_fuse_insert (struct uop_t *const uop) [virtual]
Implements core_commit_t .
Definition at line 969 of file commit-DPM.cpp.
References uop_t::alloc, uop_t::decode, uop_t::fusion_head, ROB_eff_num, and uop_t::ROB_index.
void core_commit_DPM_t::ROB_insert (struct uop_t *const uop) [virtual]
Implements core_commit_t .
Definition at line 959 of file commit-DPM.cpp.
References uop_t::alloc, core_knobs_t::commit, core_commit_t::core, core_t::knobs, knobs, modinc(), ROB, ROB_eff_num, uop_t::ROB_index, ROB_num, core_knobs_t::ROB_size, and ROB_tail.
void core_commit_DPM_t::step (void) [virtual]
Implements core_commit_t .
Definition at line 328 of file commit-DPM.cpp.
References uop_t::action_id, thread_t::active, uop_t::alloc, core_t::alloc, uop_t::BOM, core_fetch_t::bpred, Mop_t::bpred_update, core_knobs_t::branch_limit, cache_freeze_stats(), core_oracle_t::commit(), Mop_t::commit, core_knobs_t::commit, core_t::core_t::core_stat_t::commit_branches, core_t::core_t::core_stat_t::commit_bytes, core_t::core_t::core_stat_t::commit_deadlock_flushes, core_t::core_t::core_stat_t::commit_eff_uops, core_t::core_t::core_stat_t::commit_fusions, Mop_t::commit_index, core_t::core_t::core_stat_t::commit_insn, core_t::core_t::core_stat_t::commit_loads, core_t::core_t::core_stat_t::commit_refs, core_t::core_t::core_stat_t::commit_rep_insn, core_t::core_t::core_stat_t::commit_rep_iterations, core_t::core_t::core_stat_t::commit_rep_uops, core_t::core_t::core_stat_t::commit_stall, core_t::core_t::core_stat_t::commit_traps, core_oracle_t::commit_uop(), core_t::core_t::core_stat_t::commit_uops, core_t::core_t::core_stat_t::commit_UROM_eff_uops, core_t::core_t::core_stat_t::commit_UROM_insn, core_t::core_t::core_stat_t::commit_UROM_uops, core_oracle_t::complete_flush(), Mop_t::complete_index, core_commit_t::core, CSTALL_EMPTY, CSTALL_JECLEAR_INFLIGHT, CSTALL_MAX_BRANCHES, CSTALL_NONE, CSTALL_NOT_READY, CSTALL_PARTIAL, core_t::current_thread, core_commit_t::deadlock_threshold, core_knobs_t::decode, uop_t::decode, Mop_t::decode, core_t::decode, core_t::core_t::core_stat_t::eff_flow_count, core_t::core_t::core_stat_t::eff_flow_histo, core_t::core_t::core_stat_t::eio_commit_insn, uop_t::EOM, uop_t::exec, core_t::exec, core_t::fetch, Mop_t::fetch, core_t::core_t::core_stat_t::final_sim_cycle, core_t::core_t::core_stat_t::flow_count, core_t::core_t::core_stat_t::flow_histo, Mop_t::flow_length, core_exec_t::freeze_stats(), bpred_t::freeze_stats(), uop_t::fusion_next, uop_t::has_imm, thread_t::id, uop_t::in_fusion, Mop_t::inst, Mop_t::is_ctrl, uop_t::is_load, uop_t::is_sta, uop_t::is_std, Mop_t::is_trap, Mop_t::jeclear_in_flight, core_t::knobs, knobs, core_exec_t::last_completed, core_exec_t::last_completed_count, Mop_t::last_uop_index, core_exec_t::LDQ_deallocate(), md_inst_t::len, max_cycles, max_insts, max_uops, core_knobs_t::max_uops, modinc(), uop_t::Mop, core_t::core_t::core_stat_t::Mop_commit_slip, core_t::core_t::core_stat_t::Mop_decode2commit_slip, core_t::core_t::core_stat_t::Mop_decode_slip, core_t::core_t::core_stat_t::Mop_fetch2decode_slip, core_t::core_t::core_stat_t::Mop_fetch_slip, core_t::new_action_id(), Mop_t::NextPC, Mop_t::num_branches, Mop_t::num_eff_uops, Mop_t::num_loads, Mop_t::num_refs, Mop_t::num_uops, Mop_t::opflags, Mop_t::oracle, core_t::oracle, Mop_t::PC, md_inst_t::qemu_len, core_fetch_t::recover(), core_decode_t::recover(), core_alloc_t::recover(), core_exec_t::recover(), recover(), thread_t::regs, regs_t::regs_NPC, md_inst_t::rep, core_oracle_t::reset_execution(), bpred_t::return_state_cache(), ROB, ROB_eff_num, ROB_head, uop_t::ROB_index, ROB_num, core_knobs_t::ROB_size, sim_cycle, sim_exit_buf, simulated_processes_remaining, Mop_t::spec_mode, Mop_t::stat, core_t::stat, stat_add_sample(), core_exec_t::STQ_deallocate_senior(), core_exec_t::STQ_deallocate_sta(), core_exec_t::STQ_deallocate_std(), Mop_t::targetPC, TICK_T_MAX, Mop_t::timing, uop_t::timing, total_commit_eff_uops, total_commit_insn, total_commit_uops, trace_limit, Mop_t::uop, core_t::core_t::core_stat_t::uop_alloc2ready_slip, core_t::core_t::core_stat_t::uop_complete2commit_slip, core_t::core_t::core_stat_t::uop_decode2alloc_slip, core_t::core_t::core_stat_t::uop_exec2complete_slip, core_t::core_t::core_stat_t::uop_issue2exec_slip, core_t::core_t::core_stat_t::uop_ready2issue_slip, bpred_t::update(), warn(), uop_t::when_allocated, Mop_t::when_commit_finished, Mop_t::when_commit_started, uop_t::when_completed, Mop_t::when_decode_finished, Mop_t::when_decode_started, uop_t::when_decoded, uop_t::when_exec, Mop_t::when_fetch_started, Mop_t::when_fetched, uop_t::when_issued, uop_t::when_ready, when_rep_commit_started, when_rep_decode_started, when_rep_fetch_started, when_rep_fetched, core_knobs_t::width, Mop_t::zero_rep, zesto_assert, zesto_fatal, and ZESTO_STAT.
void core_commit_DPM_t::update_occupancy (void) [virtual]
Implements core_commit_t .
Definition at line 310 of file commit-DPM.cpp.
References core_knobs_t::commit, core_commit_t::core, core_t::knobs, ROB_eff_num, core_t::core_t::core_stat_t::ROB_eff_occupancy, core_t::core_t::core_stat_t::ROB_empty_cycles, core_t::core_t::core_stat_t::ROB_full_cycles, ROB_num, core_t::core_t::core_stat_t::ROB_occupancy, core_knobs_t::ROB_size, and core_t::stat.
Member Data Documentation
const char * core_commit_DPM_t::commit_stall_str [static, protected]
Initial value:
 {
  "no stall                   ",
  "oldest inst not done       ",
  "oldest inst partially done ",
  "ROB is empty               ",
  "Mop done, jeclear in flight",
  "branch commit limit        "
}
Definition at line 45 of file commit-DPM.cpp.
Referenced by reg_stats().
struct uop_t** core_commit_DPM_t::ROB [read, protected]
Definition at line 39 of file commit-DPM.cpp.
Referenced by core_commit_DPM_t(), recover(), ROB_insert(), and step().
int core_commit_DPM_t::ROB_eff_num [protected]
Definition at line 43 of file commit-DPM.cpp.
Referenced by recover(), ROB_fuse_insert(), ROB_insert(), step(), and update_occupancy().
int core_commit_DPM_t::ROB_head [protected]
Definition at line 40 of file commit-DPM.cpp.
Referenced by step().
int core_commit_DPM_t::ROB_num [protected]
Definition at line 42 of file commit-DPM.cpp.
Referenced by recover(), ROB_available(), ROB_empty(), ROB_insert(), step(), and update_occupancy().
int core_commit_DPM_t::ROB_tail [protected]
Definition at line 41 of file commit-DPM.cpp.
Referenced by recover(), and ROB_insert().
tick_t core_commit_DPM_t::when_rep_commit_started [protected]
Definition at line 51 of file commit-DPM.cpp.
Referenced by step().
tick_t core_commit_DPM_t::when_rep_decode_started [protected]
Definition at line 50 of file commit-DPM.cpp.
Referenced by step().
tick_t core_commit_DPM_t::when_rep_fetch_started [protected]
Definition at line 48 of file commit-DPM.cpp.
Referenced by step().
tick_t core_commit_DPM_t::when_rep_fetched [protected]
Definition at line 49 of file commit-DPM.cpp.
Referenced by step().
The documentation for this class was generated from the following file:
commit-DPM.cpp