core_oracle_t Class Reference
#include <zesto-oracle.h>
Classes
struct map_node_t
struct spec_mem_t
struct syscall_mem_req_t
Public Member Functions
core_oracle_t (struct core_t *const core)
void reg_stats (struct stat_sdb_t *const sdb)
void update_occupancy (void)
struct Mop_t * get_Mop (const int index)
int get_index (const struct Mop_t *const Mop)
int next_index (const int index)
bool spec_read_byte (const md_addr_t addr, byte_t *const valp)
struct spec_byte_t * spec_write_byte (const md_addr_t addr, const byte_t val)
struct Mop_t * exec (const md_addr_t requested_PC)
void consume (const struct Mop_t *const Mop)
void commit_uop (struct uop_t *const uop)
void commit (const struct Mop_t *const commit_Mop)
void recover (const struct Mop_t *const Mop)
void pipe_recover (struct Mop_t *const Mop, const md_addr_t New_PC)
void pipe_flush (struct Mop_t *const Mop)
void complete_flush (void)
void reset_execution (void)
Static Public Member Functions
static enum md_fault_type syscall_mem_access (int thread_id, struct mem_t *mem, enum mem_cmd cmd, md_addr_t addr, void *vp, int nbytes)
Public Attributes
bool spec_mode
bool hosed
bool trap_on
struct map_node_t * head [MD_TOTAL_REGS]
struct map_node_t * tail [MD_TOTAL_REGS]
Protected Member Functions
void undo (struct Mop_t *const Mop)
void install_mapping (struct uop_t *const uop)
void commit_mapping (const struct uop_t *const uop)
void undo_mapping (const struct uop_t *const uop)
struct map_node_t * get_map_node (void)
void return_map_node (struct map_node_t *const p)
void install_dependencies (struct uop_t *const uop)
void commit_dependencies (struct uop_t *const uop)
void undo_dependencies (struct uop_t *const uop)
struct spec_byte_t * get_spec_mem_node (void)
void return_spec_mem_node (struct spec_byte_t *const p)
void commit_write_byte (struct spec_byte_t *const p)
void squash_write_byte (struct spec_byte_t *const p)
void cleanup_aborted_mop (struct Mop_t *const Mop)
Static Protected Member Functions
static void syscall_callback (void *const op)
static bool syscall_translated_callback (void *const op, const seq_t)
static seq_t syscall_get_action_id (void *const op)
Protected Attributes
struct Mop_t * MopQ
int MopQ_head
int MopQ_tail
int MopQ_num
int MopQ_size
struct Mop_t * current_Mop
struct syscall_mem_req_t * mem_req_free_pool
struct core_t * core
struct spec_mem_t spec_mem_map
xx xx xx xx xx xx xx xx xx
struct {
 struct map_node_t * head [MD_TOTAL_REGS]
 struct map_node_t * tail [MD_TOTAL_REGS]
} dep_map
struct syscall_mem_req_t * syscall_mem_req_head
struct syscall_mem_req_t * syscall_mem_req_tail
int syscall_mem_reqs
int syscall_remaining_delay
Static Protected Attributes
static bool static_members_initialized = false
static struct map_node_t * map_free_pool = NULL
static int map_free_pool_debt = 0
static struct spec_byte_t * spec_mem_free_pool = NULL
static int spec_mem_pool_debt = 0
static const seq_t DUMMY_SYSCALL_ACTION_ID = ULL(0x2E570515CA111D)
static const unsigned DUMMY_SYSCALL_OP = 0x515CA11
Detailed Description
Definition at line 179 of file zesto-oracle.h.
Constructor & Destructor Documentation
core_oracle_t::core_oracle_t (struct core_t *const core)
Definition at line 178 of file zesto-oracle.cpp.
References core_knobs_t::alloc, core_knobs_t::byteQ_size, core_knobs_t::commit, core, core_knobs_t::decode, dep_map, core_knobs_t::depth, fatal(), core_knobs_t::fetch, core_knobs_t::IQ_size, core_t::knobs, knobs, MopQ, MopQ_size, core_knobs_t::ROB_size, spec_mem_map, core_knobs_t::uopQ_size, and core_knobs_t::width.
Member Function Documentation
void core_oracle_t::cleanup_aborted_mop (struct Mop_t *const Mop) [protected]
Definition at line 2203 of file zesto-oracle.cpp.
References uop_t::decode, Mop_t::decode, Mop_t::flow_length, uop_t::is_imm, uop_t::oracle, uop_t::spec_mem, and Mop_t::uop.
void core_oracle_t::commit (const struct Mop_t *const commit_Mop)
Definition at line 1562 of file zesto-oracle.cpp.
References fatal(), modinc(), MopQ, MopQ_head, MopQ_num, MopQ_size, Mop_t::oracle, Mop_t::spec_mode, and Mop_t::valid.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
void core_oracle_t::commit_dependencies (struct uop_t *const uop) [protected]
Definition at line 1848 of file zesto-oracle.cpp.
References core, uop_t::idep_uop, odep_t::next, uop_t::odep_uop, odep_t::op_num, uop_t::oracle, core_t::return_odep_link(), and odep_t::uop.
Referenced by commit_uop().
void core_oracle_t::commit_mapping (const struct uop_t *const uop) [protected]
Definition at line 1798 of file zesto-oracle.cpp.
References DCREG, uop_t::decode, dep_map, DGPR, DNA, MD_REG_AFLAGS, MD_REG_ZERO, core_oracle_t::core_oracle_t::map_node_t::next, uop_t::odep_name, uop_t::oflags, core_oracle_t::core_oracle_t::map_node_t::prev, return_map_node(), and core_oracle_t::core_oracle_t::map_node_t::uop.
Referenced by commit_uop().
void core_oracle_t::commit_uop (struct uop_t *const uop)
Definition at line 1527 of file zesto-oracle.cpp.
References commit_dependencies(), commit_mapping(), core, uop_t::exec, uop_t::idep_uop, odep_t::next, uop_t::odep_uop, odep_t::op_num, core_t::return_odep_link(), odep_t::uop, and zesto_assert.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
void core_oracle_t::commit_write_byte (struct spec_byte_t *const p) [protected]
Definition at line 1870 of file zesto-oracle.cpp.
References spec_byte_t::addr, core_oracle_t::core_oracle_t::spec_mem_t::hash, core_oracle_t::core_oracle_t::spec_mem_t::head, MEM_HASH_MASK, spec_byte_t::next, spec_byte_t::prev, return_spec_mem_node(), spec_mem_map, and core_oracle_t::core_oracle_t::spec_mem_t::tail.
void core_oracle_t::complete_flush (void)
Definition at line 1747 of file zesto-oracle.cpp.
References core_fetch_t::bpred, Mop_t::bpred_update, core, current_Mop, core_t::current_thread, core_t::fetch, Mop_t::fetch, bpred_t::flush(), moddec(), MopQ, MopQ_head, MopQ_num, MopQ_size, MopQ_tail, Mop_t::PC, thread_t::regs, regs_t::regs_NPC, regs_t::regs_PC, bpred_t::return_state_cache(), spec_mode, undo(), and Mop_t::valid.
Referenced by emergency_recovery(), reset_execution(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
void core_oracle_t::consume (const struct Mop_t *const Mop)
Definition at line 1519 of file zesto-oracle.cpp.
References current_Mop.
Referenced by core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
struct Mop_t * core_oracle_t::exec (const md_addr_t requested_PC) [read]
Definition at line 669 of file zesto-oracle.cpp.
References core_fetch_t::bogus, uop_t::BOM, md_inst_t::code, Mop_t::core, core, current_Mop, core_t::current_thread, core_knobs_t::decode, uop_t::decode, Mop_t::decode, DNA, uop_t::EOM, F_COND, F_CTRL, F_FENCE, F_LOAD, F_MEM, F_STORE, F_TRAP, F_UCODE, fatal(), uop_t::fault, Mop_t::fetch, core_t::fetch, Mop_t::first_rep, uop_t::flow_index, Mop_t::flow_length, FPSTACK_IMPL, Mop_t::fpstack_op, fpstk_nop, uop_t::FU_class, uop_t::fusion_head, core_knobs_t::fusion_mode, uop_t::fusion_next, uop_t::fusion_size, FUSION_TYPE, core_t::get_uop_array(), core_t::global_seq, uop_t::has_imm, core_t::id, uop_t::idep_name, md_inst_t::imm, uop_t::in_fusion, Mop_t::inst, install_dependencies(), install_mapping(), uop_t::is_ctrl, Mop_t::is_ctrl, uop_t::is_fusion_head, uop_t::is_imm, uop_t::is_load, uop_t::is_nop, uop_t::is_sta, uop_t::is_std, Mop_t::is_trap, core_t::knobs, knobs, Mop_t::last_uop_index, mem_ops::ld_dequeued, mem_ops::ld_size, md_inst_t::len, uncore_t::log_trace, md_fault_none, MD_FETCH_INST, MD_FETCH_NEXT_PC, md_get_flow(), MD_INC_FLOW, MD_INST_SIZE, MD_MAX_FLOWLEN, MD_NOP_INST, MD_OP_FLAGS, MD_OP_FUCLASS, MD_SET_OPCODE_DURING_FETCH, MD_SET_UOPCODE, MD_STA_OP_INDEX, MD_TOTAL_REGS, md_uop_immb(), md_uop_opc(), md_uop_reg(), thread_t::mem, md_inst_t::mem_ops, mem_ops::mem_paddr_ld, mem_ops::mem_paddr_str, uop_t::mem_size, mem_ops::mem_vaddr_ld, mem_ops::mem_vaddr_str, mem_ops::memops, md_inst_t::mode, MODE_ADDR32, modinc(), uop_t::Mop, uop_t::Mop_seq, MopQ, MopQ_num, MopQ_size, MopQ_tail, Mop_t::NextPC, Mop_t::num_branches, Mop_t::num_eff_uops, thread_t::num_insn, Mop_t::num_loads, Mop_t::num_refs, Mop_t::num_uops, uop_t::odep_name, uop_t::op, Mop_t::op, OP_NA, uop_t::opflags, Mop_t::opflags, uop_t::oracle, Mop_t::oracle, core_t::core_t::core_stat_t::oracle_bogus_cycles, core_t::core_t::core_stat_t::oracle_num_branches, core_t::core_t::core_stat_t::oracle_num_loads, core_t::core_t::core_stat_t::oracle_num_refs, core_t::core_t::core_stat_t::oracle_total_branches, core_t::core_t::core_stat_t::oracle_total_eff_uops, core_t::core_t::core_stat_t::oracle_total_insn, core_t::core_t::core_stat_t::oracle_total_loads, core_t::core_t::core_stat_t::oracle_total_refs, core_t::core_t::core_stat_t::oracle_total_uops, md_inst_t::paddr, panic(), Mop_t::PC, uop_t::phys_addr, Mop_t::pred_NPC, md_inst_t::qemu_len, R, uop_t::raw_op, thread_t::regs, regs_t::regs_NPC, regs_t::regs_PC, md_inst_t::rep, REP_REP, REP_REPNZ, REP_REPZ, Mop_t::rep_seq, thread_t::rep_sequence, core_t::return_uop_array(), RM, Mop_t::seq, Mop_t::spec_mode, spec_mode, thread_t::stat, Mop_t::stat, core_t::stat, mem_ops::str_dequeued, mem_ops::str_size, Mop_t::targetPC, TICK_T_MAX, Mop_t::timing, uop_t::timing, UHASIMM, core_t::uncore, Mop_t::uop, uop_t::uop_seq, UOP_SEQ_SHIFT, UP, md_inst_t::vaddr, Mop_t::valid, uop_t::virt_addr, warn(), Mop_t::when_commit_finished, Mop_t::when_commit_started, uop_t::when_completed, Mop_t::when_decode_finished, Mop_t::when_decode_started, uop_t::when_exec, Mop_t::when_fetch_started, Mop_t::when_fetched, uop_t::when_issued, Mop_t::when_MS_started, uop_t::when_ready, XE_ONE, XR_CX, XR_ECX, core_t::zero_Mop(), Mop_t::zero_rep, and ZESTO_STAT.
Referenced by core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
int core_oracle_t::get_index (const struct Mop_t *const Mop)
Definition at line 340 of file zesto-oracle.cpp.
References MopQ.
Referenced by core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
struct core_oracle_t::map_node_t * core_oracle_t::get_map_node (void) [read, protected]
Definition at line 2014 of file zesto-oracle.cpp.
References fatal(), map_free_pool, map_free_pool_debt, and core_oracle_t::core_oracle_t::map_node_t::next.
Referenced by install_mapping().
struct Mop_t * core_oracle_t::get_Mop (const int index) [read]
Definition at line 335 of file zesto-oracle.cpp.
References MopQ.
Referenced by core_fetch_STM_t::Mop_consume(), core_fetch_STM_t::Mop_peek(), and core_fetch_DPM_t::step().
struct spec_byte_t * core_oracle_t::get_spec_mem_node (void) [read, protected]
Definition at line 2150 of file zesto-oracle.cpp.
References fatal(), spec_byte_t::next, and spec_mem_free_pool.
Referenced by spec_write_byte().
void core_oracle_t::install_dependencies (struct uop_t *const uop) [protected]
Definition at line 2049 of file zesto-oracle.cpp.
References odep_t::aflags, core, DCREG, uop_t::decode, dep_map, DNA, core_t::get_odep_link(), uop_t::idep_name, uop_t::idep_uop, uop_t::iflags, MAX_IDEPS, MD_REG_AFLAGS, MD_REG_ZERO, uop_t::Mop, odep_t::next, uop_t::odep_uop, odep_t::op_num, Mop_t::oracle, uop_t::oracle, Mop_t::seq, and odep_t::uop.
Referenced by exec().
void core_oracle_t::install_mapping (struct uop_t *const uop) [protected]
Definition at line 1906 of file zesto-oracle.cpp.
References DCREG, uop_t::decode, dep_map, DGPR, DNA, get_map_node(), MD_REG_AFLAGS, MD_REG_ZERO, core_oracle_t::core_oracle_t::map_node_t::next, uop_t::odep_name, uop_t::oflags, core_oracle_t::core_oracle_t::map_node_t::prev, and core_oracle_t::core_oracle_t::map_node_t::uop.
Referenced by exec().
int core_oracle_t::next_index (const int index)
Definition at line 345 of file zesto-oracle.cpp.
References modinc(), and MopQ_size.
Referenced by core_fetch_STM_t::Mop_consume(), and core_fetch_DPM_t::step().
void core_oracle_t::pipe_flush (struct Mop_t *const Mop)
Definition at line 1716 of file zesto-oracle.cpp.
References Mop_t::core, core_t::current_thread, Mop_t::fetch, core_t::id, md_fetch_next_pc(), moddec(), MopQ, MopQ_head, MopQ_num, MopQ_size, Mop_t::NextPC, Mop_t::oracle, pipe_recover(), Mop_t::pred_NPC, thread_t::regs, regs_t::regs_NPC, spec_mode, store_nextPC, and zesto_assert.
Referenced by core_exec_DPM_t::ALU_exec(), and core_exec_DPM_t::LDST_exec().
void core_oracle_t::pipe_recover (struct Mop_t *const Mop, const md_addr_t New_PC)
Definition at line 1696 of file zesto-oracle.cpp.
References core_t::alloc, core_fetch_t::bpred, Mop_t::bpred_update, core_t::commit, core, core_t::decode, core_t::exec, Mop_t::fetch, core_t::fetch, core_knobs_t::fetch, Mop_t::inst, core_knobs_t::jeclear_delay, core_fetch_t::jeclear_enqueue(), core_t::knobs, knobs, md_inst_t::len, Mop_t::PC, core_fetch_t::recover(), core_decode_t::recover(), core_alloc_t::recover(), core_exec_t::recover(), core_commit_t::recover(), recover(), and bpred_t::recover().
Referenced by core_exec_STM_t::ALU_exec(), core_exec_DPM_t::ALU_exec(), core_exec_DPM_t::LDQ_schedule(), core_exec_STM_t::LDST_exec(), core_exec_DPM_t::LDST_exec(), core_exec_STM_t::load_writeback(), core_exec_DPM_t::load_writeback(), and pipe_flush().
void core_oracle_t::recover (const struct Mop_t *const Mop)
Definition at line 1658 of file zesto-oracle.cpp.
References core_fetch_t::bpred, Mop_t::bpred_update, Mop_t::branch_mispred, core, current_Mop, core_t::current_thread, fatal(), Mop_t::fetch, core_t::fetch, bpred_t::flush(), moddec(), MopQ, MopQ_head, MopQ_num, MopQ_size, MopQ_tail, Mop_t::NextPC, Mop_t::oracle, Mop_t::PC, thread_t::regs, regs_t::regs_NPC, regs_t::regs_PC, bpred_t::return_state_cache(), Mop_t::spec_mode, spec_mode, undo(), and Mop_t::valid.
Referenced by core_decode_STM_t::check_target(), core_decode_DPM_t::check_target(), pipe_recover(), and core_fetch_DPM_t::step().
void core_oracle_t::reg_stats (struct stat_sdb_t *const sdb)
Definition at line 224 of file zesto-oracle.cpp.
References core, core_t::current_thread, thread_t::id, core_t::core_t::core_stat_t::MopQ_full_cycles, core_t::core_t::core_stat_t::MopQ_occupancy, core_t::num_emergency_recoveries, core_t::core_t::core_stat_t::oracle_bogus_cycles, core_t::core_t::core_stat_t::oracle_eff_uop_undo, core_t::core_t::core_stat_t::oracle_inst_undo, core_t::core_t::core_stat_t::oracle_num_branches, core_t::core_t::core_stat_t::oracle_num_loads, core_t::core_t::core_stat_t::oracle_num_refs, core_t::core_t::core_stat_t::oracle_total_branches, core_t::core_t::core_stat_t::oracle_total_eff_uops, core_t::core_t::core_stat_t::oracle_total_insn, core_t::core_t::core_stat_t::oracle_total_loads, core_t::core_t::core_stat_t::oracle_total_refs, core_t::core_t::core_stat_t::oracle_total_uops, core_t::core_t::core_stat_t::oracle_uop_undo, core_t::stat, stat_reg_counter, stat_reg_formula(), stat_reg_note(), and syscall_mem_accesses.
void core_oracle_t::reset_execution (void)
Definition at line 1781 of file zesto-oracle.cpp.
References core_t::alloc, core_fetch_t::bogus, core_t::commit, complete_flush(), core, core_t::current_thread, core_t::decode, core_t::exec, core_t::fetch, core_t::core_t::core_stat_t::oracle_resets, core_fetch_t::PC, core_fetch_t::recover(), core_decode_t::recover(), core_alloc_t::recover(), core_exec_t::recover(), core_commit_t::recover(), thread_t::regs, regs_t::regs_PC, and core_t::stat.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
void core_oracle_t::return_map_node (struct map_node_t *const p) [protected]
Definition at line 2035 of file zesto-oracle.cpp.
References map_free_pool, map_free_pool_debt, core_oracle_t::core_oracle_t::map_node_t::next, core_oracle_t::core_oracle_t::map_node_t::prev, and core_oracle_t::core_oracle_t::map_node_t::uop.
Referenced by commit_mapping(), and undo_mapping().
void core_oracle_t::return_spec_mem_node (struct spec_byte_t *const p) [protected]
Definition at line 2170 of file zesto-oracle.cpp.
References spec_byte_t::addr, spec_byte_t::next, spec_byte_t::prev, spec_mem_free_pool, and spec_byte_t::val.
Referenced by commit_write_byte(), and squash_write_byte().
bool core_oracle_t::spec_read_byte (const md_addr_t addr, byte_t *const valp)
Definition at line 372 of file zesto-oracle.cpp.
References spec_byte_t::addr, core_oracle_t::core_oracle_t::spec_mem_t::hash, MEM_HASH_MASK, spec_byte_t::prev, spec_mem_map, core_oracle_t::core_oracle_t::spec_mem_t::tail, and spec_byte_t::val.
struct spec_byte_t * core_oracle_t::spec_write_byte (const md_addr_t addr, const byte_t val) [read]
Definition at line 352 of file zesto-oracle.cpp.
References spec_byte_t::addr, get_spec_mem_node(), core_oracle_t::core_oracle_t::spec_mem_t::hash, core_oracle_t::core_oracle_t::spec_mem_t::head, MEM_HASH_MASK, spec_byte_t::next, spec_byte_t::prev, spec_mem_map, core_oracle_t::core_oracle_t::spec_mem_t::tail, and spec_byte_t::val.
void core_oracle_t::squash_write_byte (struct spec_byte_t *const p) [protected]
Definition at line 2182 of file zesto-oracle.cpp.
References spec_byte_t::addr, core_oracle_t::core_oracle_t::spec_mem_t::hash, core_oracle_t::core_oracle_t::spec_mem_t::head, MEM_HASH_MASK, spec_byte_t::next, spec_byte_t::prev, return_spec_mem_node(), spec_mem_map, and core_oracle_t::core_oracle_t::spec_mem_t::tail.
void core_oracle_t::syscall_callback (void *const op) [static, protected]
Definition at line 464 of file zesto-oracle.cpp.
seq_t core_oracle_t::syscall_get_action_id (void *const op) [static, protected]
Definition at line 474 of file zesto-oracle.cpp.
References DUMMY_SYSCALL_ACTION_ID.
enum md_fault_type core_oracle_t::syscall_mem_access (int thread_id, struct mem_t * mem, enum mem_cmd cmd, md_addr_t addr, void * vp, int nbytes) [static]
Definition at line 395 of file zesto-oracle.cpp.
References core_oracle_t::core_oracle_t::syscall_mem_req_t::addr, CACHE_READ, CACHE_WRITE, core_oracle_t::core_oracle_t::syscall_mem_req_t::cmd, core, cores, thread_t::current_core, fatal(), core_t::knobs, mem_access(), mem_req_free_pool, core_knobs_t::memory, core_oracle_t::core_oracle_t::syscall_mem_req_t::next, core_t::oracle, Read, syscall_mem_accesses, syscall_mem_req_head, syscall_mem_req_tail, syscall_mem_reqs, core_knobs_t::syscall_memory_latency, core_oracle_t::core_oracle_t::syscall_mem_req_t::thread_id, and threads.
bool core_oracle_t::syscall_translated_callback (void *const op, const seq_t action_id) [static, protected]
Definition at line 469 of file zesto-oracle.cpp.
void core_oracle_t::undo (struct Mop_t *const Mop) [protected]
Definition at line 1587 of file zesto-oracle.cpp.
References uop_t::action_id, core, core_t::current_thread, uop_t::decode, Mop_t::decode, uop_t::EOM, uop_t::exec, Mop_t::fetch, Mop_t::flow_length, uop_t::in_fusion, uop_t::is_fusion_head, uop_t::is_imm, Mop_t::jeclear_action_id, core_t::new_action_id(), thread_t::num_insn, Mop_t::oracle, core_t::core_t::core_stat_t::oracle_eff_uop_undo, core_t::core_t::core_stat_t::oracle_inst_undo, core_t::core_t::core_stat_t::oracle_uop_undo, Mop_t::rep_seq, thread_t::rep_sequence, Mop_t::spec_mode, core_t::stat, thread_t::stat, undo_dependencies(), undo_mapping(), Mop_t::uop, and ZESTO_STAT.
Referenced by complete_flush(), and recover().
void core_oracle_t::undo_dependencies (struct uop_t *const uop) [protected]
Definition at line 2105 of file zesto-oracle.cpp.
References core, uop_t::idep_uop, MAX_IDEPS, odep_t::next, uop_t::odep_uop, odep_t::op_num, uop_t::oracle, core_t::return_odep_link(), and odep_t::uop.
Referenced by undo().
void core_oracle_t::undo_mapping (const struct uop_t *const uop) [protected]
Definition at line 1959 of file zesto-oracle.cpp.
References DCREG, uop_t::decode, dep_map, DNA, MD_REG_AFLAGS, MD_REG_ZERO, core_oracle_t::core_oracle_t::map_node_t::next, uop_t::odep_name, uop_t::oflags, core_oracle_t::core_oracle_t::map_node_t::prev, return_map_node(), and core_oracle_t::core_oracle_t::map_node_t::uop.
Referenced by undo().
void core_oracle_t::update_occupancy (void)
Definition at line 327 of file zesto-oracle.cpp.
References core, core_t::core_t::core_stat_t::MopQ_full_cycles, MopQ_num, core_t::core_t::core_stat_t::MopQ_occupancy, MopQ_size, and core_t::stat.
Referenced by zesto_component::downtick_handler().
Member Data Documentation
struct core_t* core_oracle_t::core [read, protected]
Definition at line 262 of file zesto-oracle.h.
Referenced by commit_dependencies(), commit_uop(), complete_flush(), core_oracle_t(), exec(), install_dependencies(), pipe_recover(), recover(), reg_stats(), reset_execution(), syscall_mem_access(), undo(), undo_dependencies(), and update_occupancy().
struct Mop_t* core_oracle_t::current_Mop [read, protected]
Definition at line 254 of file zesto-oracle.h.
Referenced by complete_flush(), consume(), exec(), and recover().
struct { ... } core_oracle_t::dep_map [protected]
Referenced by commit_mapping(), core_oracle_t(), install_dependencies(), install_mapping(), and undo_mapping().
const seq_t core_oracle_t::DUMMY_SYSCALL_ACTION_ID = ULL(0x2E570515CA111D) [static, protected]
Definition at line 295 of file zesto-oracle.h.
Referenced by syscall_get_action_id().
const unsigned core_oracle_t::DUMMY_SYSCALL_OP = 0x515CA11 [static, protected]
Definition at line 296 of file zesto-oracle.h.
struct map_node_t* core_oracle_t::head[MD_TOTAL_REGS] [read]
Definition at line 266 of file zesto-oracle.h.
bool core_oracle_t::hosed
Definition at line 211 of file zesto-oracle.h.
Referenced by emergency_recovery().
struct core_oracle_t::map_node_t * core_oracle_t::map_free_pool = NULL [static, read, protected]
Definition at line 256 of file zesto-oracle.h.
Referenced by get_map_node(), and return_map_node().
int core_oracle_t::map_free_pool_debt = 0 [static, protected]
Definition at line 257 of file zesto-oracle.h.
Referenced by get_map_node(), and return_map_node().
struct syscall_mem_req_t* core_oracle_t::mem_req_free_pool [read, protected]
Definition at line 260 of file zesto-oracle.h.
Referenced by syscall_mem_access().
struct Mop_t* core_oracle_t::MopQ [read, protected]
Definition at line 249 of file zesto-oracle.h.
Referenced by commit(), complete_flush(), core_oracle_t(), exec(), get_index(), get_Mop(), pipe_flush(), and recover().
int core_oracle_t::MopQ_head [protected]
Definition at line 250 of file zesto-oracle.h.
Referenced by commit(), complete_flush(), pipe_flush(), and recover().
int core_oracle_t::MopQ_num [protected]
Definition at line 252 of file zesto-oracle.h.
Referenced by commit(), complete_flush(), exec(), pipe_flush(), recover(), and update_occupancy().
int core_oracle_t::MopQ_size [protected]
Definition at line 253 of file zesto-oracle.h.
Referenced by commit(), complete_flush(), core_oracle_t(), exec(), next_index(), pipe_flush(), recover(), and update_occupancy().
int core_oracle_t::MopQ_tail [protected]
Definition at line 251 of file zesto-oracle.h.
Referenced by complete_flush(), exec(), and recover().
struct spec_byte_t * core_oracle_t::spec_mem_free_pool = NULL [static, read, protected]
Definition at line 258 of file zesto-oracle.h.
Referenced by get_spec_mem_node(), and return_spec_mem_node().
struct spec_mem_t core_oracle_t::spec_mem_map [read, protected]
Definition at line 263 of file zesto-oracle.h.
Referenced by commit_write_byte(), core_oracle_t(), spec_read_byte(), spec_write_byte(), and squash_write_byte().
int core_oracle_t::spec_mem_pool_debt = 0 [static, protected]
Definition at line 259 of file zesto-oracle.h.
bool core_oracle_t::spec_mode
Definition at line 209 of file zesto-oracle.h.
Referenced by complete_flush(), exec(), pipe_flush(), recover(), core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
bool core_oracle_t::static_members_initialized = false [static, protected]
Definition at line 247 of file zesto-oracle.h.
struct syscall_mem_req_t* core_oracle_t::syscall_mem_req_head [read, protected]
Definition at line 270 of file zesto-oracle.h.
Referenced by syscall_mem_access().
struct syscall_mem_req_t* core_oracle_t::syscall_mem_req_tail [read, protected]
Definition at line 271 of file zesto-oracle.h.
Referenced by syscall_mem_access().
int core_oracle_t::syscall_mem_reqs [protected]
Definition at line 272 of file zesto-oracle.h.
Referenced by syscall_mem_access().
int core_oracle_t::syscall_remaining_delay [protected]
Definition at line 273 of file zesto-oracle.h.
struct map_node_t* core_oracle_t::tail[MD_TOTAL_REGS] [read]
Definition at line 267 of file zesto-oracle.h.
bool core_oracle_t::trap_on
Definition at line 214 of file zesto-oracle.h.
The documentation for this class was generated from the following files:
zesto-oracle.h
zesto-oracle.cpp