GenericRouterVcs Class Reference
#include <genericRouterVcs.h>
Public Member Functions
GenericRouterVcs ()
~GenericRouterVcs ()
void init (uint ports, uint vcs, uint credits, uint buffer_size)
void set_no_nodes (uint nodes)
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
void set_grid_x_location (uint a, uint b, uint c)
void set_grid_y_location (uint a, uint b, uint c)
void send_credit_back (uint i)
void process_event (IrisEvent *e)
string toString () const
string print_stats ()
void set_edge_links ()
void dump_buffer_state ()
Public Attributes
vector< vector< uint > > downstream_credits
uint packets
uint flits
double total_packet_latency
double last_flit_out_cycle
unsigned long long int stat_sim_total_time
vector< vector< uint > > stat_packet_out
vector< vector< uint > > stat_flit_out
bool is_mc_router
Private Member Functions
void handle_link_arrival_event (IrisEvent *e)
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
void handle_tick_event (IrisEvent *e)
Event handle for the TICK_EVENT. Entry from DES kernel.
void handle_detect_deadlock_event (IrisEvent *)
void do_switch_traversal ()
void do_switch_allocation ()
Private Attributes
vector< GenericBuffer > in_buffers
vector< GenericRC > decoders
vector< InputBufferState > input_buffer_state
GenericVcAllocator vca
PToPSwitchArbiterVcs swa
GenericCrossbar xbar
vector< uint > available_ports
vector< uint > available_vcs
vector< vector< uint > > cr_time
bool ticking
Detailed Description
===================================================================================== Class: Description: Implementing a generic 4 stage physical router model BW->RC->VCA->SA->ST->LT Buffer write(BW) Route Computation (RC) Virtual Channel Allocation (VCA) Switch Allocation (SA) Switch Traversal (ST) Link Traversal (LT)
Model Description in cycles: --------------------------- BW and RC stages happen in the same cycle (BW pushes the flits into the input buffer and the RC unit.) VCA: Head flits request for an output virtual channel and max(pxv) requesting input ports/vcs. On winning the grant the packet requests for SA. The winner is cleared when the tail exits. SA: Pick one output port from n requesting input ports (0<n<p) for the pxp crossbar ST: Move the flits across the crossbar and push it out on the link LT: This is not modelled within the router and is part of the link component. =====================================================================================
Definition at line 64 of file genericRouterVcs.h.
Constructor & Destructor Documentation
GenericRouterVcs::GenericRouterVcs ()
Definition at line 24 of file genericRouterVcs.cc.
References NetworkComponent::name, and ticking.
GenericRouterVcs::~GenericRouterVcs ()
constructor
Definition at line 30 of file genericRouterVcs.cc.
Member Function Documentation
void GenericRouterVcs::do_switch_allocation () [private]
Definition at line 541 of file genericRouterVcs.cc.
References SA_unit::ch, PToPSwitchArbiterVcs::clear_requestor(), GenericCrossbar::configure_crossbar(), Router::credits, downstream_credits, in_buffers, input_buffer_state, PToPSwitchArbiterVcs::is_empty(), PToPSwitchArbiterVcs::pick_winner(), SA_unit::port, Router::ports, GenericCrossbar::push(), ST, swa, SWA_REQUESTED, ticking, VCA_COMPLETE, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterVcs::do_switch_traversal () [private]
The do_two_stage_router flag is used here to model variable router pipeline delay depending on system clock and router complexity.
Send a credit back and update buffer state for the downstream router buffer
Definition at line 423 of file genericRouterVcs.cc.
References _DBG, NetworkComponent::address, TailFlit::avg_network_latency, HeadFlit::avg_network_latency, PToPSwitchArbiterVcs::clear_requestor(), GenericVcAllocator::clear_winner(), cr_time, data, do_two_stage_router, downstream_credits, EMPTY, FLIT_ID, HEAD, TailFlit::hop_count, HeadFlit::hop_count, in_buffers, input_buffer_state, GenericCrossbar::is_empty(), is_mc_router, Flit::is_single_flit_pkt, last_flit_out_cycle, LINK_ARRIVAL_EVENT, Simulator::Now(), Router::output_connections, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, GenericCrossbar::pull(), PToPSwitchArbiterVcs::request(), Simulator::Schedule(), send_credit_back(), ST, stat_flit_out, stat_packet_out, swa, SWA_REQUESTED, TAIL, total_packet_latency, Flit::type, LinkArrivalData::type, LinkArrivalData::vc, Flit::vc, vca, VCA_COMPLETE, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterVcs::dump_buffer_state ()
Definition at line 177 of file genericRouterVcs.cc.
References EMPTY, input_buffer_state, INVALID, NetworkComponent::node_ip, Router::ports, and Router::vcs.
void GenericRouterVcs::handle_detect_deadlock_event (IrisEvent * e) [private]
Definition at line 148 of file genericRouterVcs.cc.
References _DBG_NOARG, cr_time, DETECT_DEADLOCK_EVENT, input_buffer_state, Simulator::Now(), Router::ports, NetworkComponent::process_event(), Simulator::Schedule(), IrisEvent::type, and Router::vcs.
Referenced by process_event().
void GenericRouterVcs::handle_link_arrival_event (IrisEvent * e) [private]
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
Definition at line 265 of file genericRouterVcs.cc.
References _DBG, HeadFlit::addr, cr_time, CREDIT_ID, data, decoders, downstream_credits, HeadFlit::dst_address, IrisEvent::event_data, FLIT_ID, flits, FULL, HEAD, in_buffers, HeadFlit::inport, input_buffer_state, Router::input_connections, is_mc_router, Flit::is_single_flit_pkt, HeadFlit::length, HeadFlit::msg_class, Simulator::Now(), Router::output_connections, packets, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, Simulator::Schedule(), HeadFlit::src_address, IrisEvent::src_id, TAIL, TICK_EVENT, ticking, Flit::type, LinkArrivalData::type, IrisEvent::vc, LinkArrivalData::vc, and Router::vcs.
Referenced by process_event().
void GenericRouterVcs::handle_tick_event (IrisEvent * e) [private]
Event handle for the TICK_EVENT. Entry from DES kernel.
Body and tail flits get written in link arrival and since the message state may already been pushed to ST because of the header we want to ensure that all flits go thru an IB and ST stage. Hence ST is done on the flits_in_ib information and not buffer occupancy. for(uint i=0; i<(ports*vcs); i++) { uint ip = input_buffer_state[i].input_port; uint ic = input_buffer_state[i].input_channel;
if ((input_buffer_state[i].pipe_stage == ST || input_buffer_state[i].pipe_stage == IB) && (input_buffer_state[i].flits_in_ib < in_buffers[ip].get_occupancy(ivc))) { input_buffer_state[i].flits_in_ib++; ticking = true; } }
Definition at line 600 of file genericRouterVcs.cc.
References Router::credits, GenericVcAllocator::current_winners, do_switch_allocation(), do_switch_traversal(), downstream_credits, FULL, IB, in_buffers, input_buffer_state, GenericVcAllocator::is_empty(), GenericVcAllocator::is_requested(), Simulator::Now(), GenericVcAllocator::pick_winner(), Router::ports, NetworkComponent::process_event(), GenericVcAllocator::request(), PToPSwitchArbiterVcs::request(), Simulator::Schedule(), GenericVcAllocator::squash_requests(), ST, swa, SWA_REQUESTED, TICK_EVENT, ticking, IrisEvent::vc, vca, VCA_COMPLETE, VCA_REQUESTED, and Router::vcs.
Referenced by process_event().
void GenericRouterVcs::init (uint ports, uint vcs, uint credits, uint buffer_size) [virtual]
destructor
Implements Router .
Definition at line 35 of file genericRouterVcs.cc.
References GenericVcAllocator::address, PToPSwitchArbiterVcs::address, NetworkComponent::address, Router::buffer_size, cr_time, Router::credits, decoders, DETECT_DEADLOCK_EVENT, downstream_credits, flits, in_buffers, input_buffer_state, Component::myId(), GenericVcAllocator::node_ip, PToPSwitchArbiterVcs::node_ip, NetworkComponent::node_ip, Simulator::Now(), packets, Router::ports, NetworkComponent::process_event(), PToPSwitchArbiterVcs::resize(), Simulator::Schedule(), GenericCrossbar::setup(), GenericVcAllocator::setup(), stat_flit_out, stat_packet_out, swa, total_packet_latency, vca, Router::vcs, and xbar.
string GenericRouterVcs::print_stats (void) [virtual]
Implements Router .
Definition at line 190 of file genericRouterVcs.cc.
References flits, last_flit_out_cycle, NetworkComponent::node_ip, packets, Router::ports, stat_flit_out, stat_packet_out, and total_packet_latency.
void GenericRouterVcs::process_event (IrisEvent * e) [virtual]
Implements NetworkComponent .
Definition at line 127 of file genericRouterVcs.cc.
References _DBG, DETECT_DEADLOCK_EVENT, handle_detect_deadlock_event(), handle_link_arrival_event(), handle_tick_event(), LINK_ARRIVAL_EVENT, TICK_EVENT, and IrisEvent::type.
void GenericRouterVcs::send_credit_back (uint i)
Definition at line 798 of file genericRouterVcs.cc.
References NetworkComponent::address, CREDIT_ID, data, do_two_stage_router, input_buffer_state, Router::input_connections, LINK_ARRIVAL_EVENT, Simulator::Now(), NetworkComponent::process_event(), Simulator::Schedule(), LinkArrivalData::type, and LinkArrivalData::vc.
Referenced by do_switch_traversal().
void GenericRouterVcs::set_edge_links ()
void GenericRouterVcs::set_grid_x_location (uint a, uint b, uint c) [virtual]
For DOR the no of nodes in the network and the grid sizes are to be set and passed to RC.
Implements Router .
Definition at line 113 of file genericRouterVcs.cc.
References decoders.
void GenericRouterVcs::set_grid_y_location (uint a, uint b, uint c) [virtual]
Implements Router .
Definition at line 119 of file genericRouterVcs.cc.
References decoders.
void GenericRouterVcs::set_no_nodes (uint nodes) [virtual]
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
Initialise the router for ports, vcs and credits. TODO buffer size not used right now. Just make sure its larger than credits.
Implements Router .
Definition at line 103 of file genericRouterVcs.cc.
References decoders.
string GenericRouterVcs::toString () const [virtual]
Reimplemented from Router .
Definition at line 775 of file genericRouterVcs.cc.
References NetworkComponent::address, decoders, in_buffers, NetworkComponent::node_ip, swa, GenericCrossbar::toString(), PToPSwitchArbiterVcs::toString(), and xbar.
Member Data Documentation
vector<uint> GenericRouterVcs::available_ports [private]
Definition at line 108 of file genericRouterVcs.h.
vector<uint> GenericRouterVcs::available_vcs [private]
Definition at line 109 of file genericRouterVcs.h.
vector< vector<uint> > GenericRouterVcs::cr_time [private]
Definition at line 110 of file genericRouterVcs.h.
Referenced by do_switch_traversal(), handle_detect_deadlock_event(), handle_link_arrival_event(), and init().
vector<GenericRC> GenericRouterVcs::decoders [private]
Definition at line 103 of file genericRouterVcs.h.
Referenced by handle_link_arrival_event(), init(), set_grid_x_location(), set_grid_y_location(), set_no_nodes(), and toString().
vector< vector<uint> > GenericRouterVcs::downstream_credits
Definition at line 86 of file genericRouterVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), and init().
uint GenericRouterVcs::flits
Definition at line 91 of file genericRouterVcs.h.
Referenced by handle_link_arrival_event(), init(), and print_stats().
vector<GenericBuffer> GenericRouterVcs::in_buffers [private]
Definition at line 102 of file genericRouterVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), init(), and toString().
vector<InputBufferState> GenericRouterVcs::input_buffer_state [private]
Definition at line 104 of file genericRouterVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), dump_buffer_state(), handle_detect_deadlock_event(), handle_link_arrival_event(), handle_tick_event(), init(), and send_credit_back().
bool GenericRouterVcs::is_mc_router
Definition at line 97 of file genericRouterVcs.h.
Referenced by do_switch_traversal(), and handle_link_arrival_event().
double GenericRouterVcs::last_flit_out_cycle
Definition at line 93 of file genericRouterVcs.h.
Referenced by do_switch_traversal(), and print_stats().
uint GenericRouterVcs::packets
These are the statistics variables
Definition at line 90 of file genericRouterVcs.h.
Referenced by handle_link_arrival_event(), init(), and print_stats().
vector< vector<uint> > GenericRouterVcs::stat_flit_out
Definition at line 96 of file genericRouterVcs.h.
Referenced by do_switch_traversal(), init(), and print_stats().
vector< vector<uint> > GenericRouterVcs::stat_packet_out
Definition at line 95 of file genericRouterVcs.h.
Referenced by do_switch_traversal(), init(), and print_stats().
unsigned long long int GenericRouterVcs::stat_sim_total_time
Definition at line 94 of file genericRouterVcs.h.
PToPSwitchArbiterVcs GenericRouterVcs::swa [private]
Definition at line 106 of file genericRouterVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_tick_event(), init(), and toString().
bool GenericRouterVcs::ticking [private]
Definition at line 112 of file genericRouterVcs.h.
Referenced by do_switch_allocation(), GenericRouterVcs(), handle_link_arrival_event(), and handle_tick_event().
double GenericRouterVcs::total_packet_latency
Definition at line 92 of file genericRouterVcs.h.
Referenced by do_switch_traversal(), init(), and print_stats().
GenericVcAllocator GenericRouterVcs::vca [private]
Definition at line 105 of file genericRouterVcs.h.
Referenced by do_switch_traversal(), handle_tick_event(), and init().
GenericCrossbar GenericRouterVcs::xbar [private]
Definition at line 107 of file genericRouterVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), init(), and toString().
The documentation for this class was generated from the following files:
genericRouterVcs.h
genericRouterVcs.cc