core_decode_STM_t Class Reference
Public Member Functions
core_decode_STM_t (struct core_t *const core)
virtual void reg_stats (struct stat_sdb_t *const sdb)
virtual void update_occupancy (void)
virtual void step (void)
virtual void recover (void)
virtual void recover (struct Mop_t *const Mop)
virtual bool uop_available (void)
virtual struct uop_t * uop_peek (void)
virtual void uop_consume (void)
Protected Member Functions
enum decode_stall_t check_target (struct Mop_t *const Mop)
bool check_flush (const int stage, const int idx)
Protected Attributes
struct Mop_t *** pipe
int * occupancy
Static Protected Attributes
static const char * decode_stall_str [DSTALL_num]
Private Types
enum decode_stall_t {
DSTALL_NONE,
DSTALL_FULL,
DSTALL_EMPTY,
DSTALL_TARGET,
DSTALL_num
 }
Detailed Description
Definition at line 11 of file decode-STM.cpp.
Member Enumeration Documentation
enum core_decode_STM_t::decode_stall_t [private]
Enumerator:
DSTALL_NONE
DSTALL_FULL
DSTALL_EMPTY
DSTALL_TARGET
DSTALL_num
Definition at line 13 of file decode-STM.cpp.
Constructor & Destructor Documentation
core_decode_STM_t::core_decode_STM_t (struct core_t *const core)
Definition at line 54 of file decode-STM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::depth, fatal(), core_knobs_t::fusion_all, core_knobs_t::fusion_load_op, core_knobs_t::fusion_mode, core_knobs_t::fusion_none, core_knobs_t::fusion_partial, core_knobs_t::fusion_sta_std, core_t::knobs, knobs, MAX_DECODE_WIDTH, occupancy, pipe, core_knobs_t::target_stage, and core_knobs_t::width.
Member Function Documentation
bool core_decode_STM_t::check_flush (const int stage, const int idx) [protected]
Definition at line 169 of file decode-STM.cpp.
References check_target(), core_decode_t::core, core_knobs_t::decode, core_t::core_t::core_stat_t::decode_stall, core_t::knobs, knobs, occupancy, pipe, core_t::stat, stat_add_sample(), core_knobs_t::target_stage, core_knobs_t::width, zesto_assert, and ZESTO_STAT.
Referenced by step().
enum core_decode_STM_t::decode_stall_t core_decode_STM_t::check_target (struct Mop_t *const Mop) [protected]
Definition at line 144 of file decode-STM.cpp.
References core_fetch_t::bpred, Mop_t::bpred_update, core_decode_t::core, Mop_t::decode, DSTALL_NONE, DSTALL_TARGET, F_UNCOND, core_t::fetch, Mop_t::fetch, Mop_t::inst, Mop_t::is_ctrl, md_inst_t::len, Mop_t::opflags, core_t::oracle, Mop_t::PC, Mop_t::pred_NPC, core_fetch_t::recover(), recover(), core_oracle_t::recover(), bpred_t::recover(), core_t::stat, core_t::core_t::core_stat_t::target_resteers, Mop_t::targetPC, and ZESTO_STAT.
Referenced by check_flush().
void core_decode_STM_t::recover (struct Mop_t *const Mop) [virtual]
Implements core_decode_t .
Definition at line 264 of file decode-STM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::depth, core_t::knobs, knobs, occupancy, pipe, core_knobs_t::width, and zesto_assert.
void core_decode_STM_t::recover (void) [virtual]
Implements core_decode_t .
Definition at line 291 of file decode-STM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::depth, core_t::knobs, knobs, occupancy, pipe, core_knobs_t::width, and zesto_assert.
Referenced by check_target().
void core_decode_STM_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Implements core_decode_t .
Definition at line 98 of file decode-STM.cpp.
References core_decode_t::core, core_t::current_thread, core_t::core_t::core_stat_t::decode_insn, core_t::core_t::core_stat_t::decode_stall, decode_stall_str, core_t::core_t::core_stat_t::decode_uops, DSTALL_num, thread_t::id, PF_COUNT, PF_PDF, core_t::stat, stat_reg_counter, stat_reg_dist(), stat_reg_formula(), stat_reg_note(), and core_t::core_t::core_stat_t::target_resteers.
void core_decode_STM_t::step (void) [virtual]
Implements core_decode_t .
Definition at line 202 of file decode-STM.cpp.
References check_flush(), core_decode_t::core, core_knobs_t::decode, core_t::core_t::core_stat_t::decode_stall, core_knobs_t::depth, DSTALL_EMPTY, DSTALL_FULL, DSTALL_NONE, core_t::fetch, core_t::knobs, knobs, core_fetch_t::Mop_available(), core_fetch_t::Mop_consume(), core_fetch_t::Mop_peek(), occupancy, pipe, core_t::stat, stat_add_sample(), core_knobs_t::width, zesto_assert, and ZESTO_STAT.
bool core_decode_STM_t::uop_available (void) [virtual]
Implements core_decode_t .
Definition at line 313 of file decode-STM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::depth, core_t::knobs, knobs, and occupancy.
void core_decode_STM_t::uop_consume (void) [virtual]
Implements core_decode_t .
Definition at line 350 of file decode-STM.cpp.
References uop_t::BOM, core_decode_t::core, uop_t::decode, Mop_t::decode, core_knobs_t::decode, core_t::core_t::core_stat_t::decode_insn, core_t::core_t::core_stat_t::decode_uops, core_knobs_t::depth, uop_t::EOM, fatal(), Mop_t::flow_length, uop_t::has_imm, core_t::knobs, knobs, Mop_t::last_stage_index, Mop_t::last_uop_index, uop_t::Mop, occupancy, pipe, sim_cycle, core_t::stat, Mop_t::timing, uop_t::timing, Mop_t::uop, Mop_t::when_decode_finished, Mop_t::when_decode_started, uop_t::when_decoded, core_knobs_t::width, zesto_assert, and ZESTO_STAT.
struct uop_t * core_decode_STM_t::uop_peek (void) [read, virtual]
Implements core_decode_t .
Definition at line 320 of file decode-STM.cpp.
References core_decode_t::core, uop_t::decode, Mop_t::decode, core_knobs_t::decode, core_knobs_t::depth, F_LOAD, F_STORE, fatal(), uop_t::flow_index, uop_t::is_load, uop_t::is_std, core_t::knobs, knobs, Mop_t::last_stage_index, uop_t::Mop_seq, uop_t::opflags, Mop_t::oracle, pipe, Mop_t::seq, Mop_t::uop, uop_t::uop_seq, UOP_SEQ_SHIFT, core_knobs_t::width, and zesto_assert.
void core_decode_STM_t::update_occupancy (void) [virtual]
Implements core_decode_t .
Definition at line 131 of file decode-STM.cpp.
Member Data Documentation
const char * core_decode_STM_t::decode_stall_str [static, protected]
Initial value:
 {
  "no stall                   ",
  "next decode stage is full  ",
  "no insts to decode         ",
  "target correction          ",
}
Definition at line 41 of file decode-STM.cpp.
Referenced by reg_stats().
int* core_decode_STM_t::occupancy [protected]
Definition at line 39 of file decode-STM.cpp.
Referenced by check_flush(), core_decode_STM_t(), recover(), step(), uop_available(), and uop_consume().
struct Mop_t*** core_decode_STM_t::pipe [read, protected]
Definition at line 38 of file decode-STM.cpp.
Referenced by check_flush(), core_decode_STM_t(), recover(), step(), uop_consume(), and uop_peek().
The documentation for this class was generated from the following file:
decode-STM.cpp