GenericTPG_clubbed Class Reference
#include <genericTPG_clubbed.h>
Public Member Functions
GenericTPG_clubbed ()
~GenericTPG_clubbed ()
void setup (uint no_nodes, uint vcs, uint max_sim_time)
void finish ()
void process_event (IrisEvent *e)
string toString () const
string print_stats () const
void set_trace_filename (string filename)
void set_no_vcs (uint v)
void set_output_path (string outpath)
bool compare ()
Public Attributes
unsigned int packets
unsigned int packets_in
double min_pkt_latency
double last_packet_out_cycle
unsigned long long int fwd_path_delay
unsigned long long int roundTripLat
unsigned long long int stat_round_trip_network_latency
unsigned long long int stat_round_trip_hop_count
unsigned long long int stat_round_trip_memory_latency
unsigned long long int stat_waiting_in_ni
MSHR_H_clubbed * mshrHandler
vector< bool > ready
bool sending
unsigned long long int max_time
vector< uint > mc_node_ip
unsigned int bankInfo [8][NO_OF_BUFFERS]
unsigned int respInfo [8]
Private Member Functions
Request * GetNextRequest ()
bool GetNewRequest (Request **req)
Request * GetRequest ()
void convertToBitStream (Request *req, HighLevelPacket *hlp)
void convertFromBitStream (Request *req, HighLevelPacket *hlp)
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_out_pull_event (IrisEvent *e)
void convertToBitStream2 (Request *req, HighLevelPacket *hlp)
Private Attributes
uint vcs
uint no_nodes
uint no_outstanding
unsigned long long int max_sim_time
deque< HighLevelPacket > out_packets
deque< HighLevelPacket > sent_packets
string out_filename
string trace_name
ofstream out_file
ifstream * trace_filename
unsigned int last_vc
Detailed Description
Definition at line 25 of file genericTPG_clubbed.h.
Constructor & Destructor Documentation
GenericTPG_clubbed::GenericTPG_clubbed ()
Definition at line 12 of file genericTPG_clubbed.cc.
References Processor::interface_connections, last_vc, NetworkComponent::name, out_filename, and sending.
GenericTPG_clubbed::~GenericTPG_clubbed ()
Definition at line 22 of file genericTPG_clubbed.cc.
References MSHR_H_clubbed::mshr, mshrHandler, out_file, and MSHR_H_clubbed::trace_filename.
Member Function Documentation
bool GenericTPG_clubbed::compare ()
void GenericTPG_clubbed::convertFromBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 577 of file genericTPG_clubbed.cc.
References Request::address, bankInfo, CACHE_BLOCK_SIZE, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, Request::cmdType, Request::data, HighLevelPacket::data, MAX_BUFFER_SIZE, max_phy_link_bits, Request::mcNo, NETWORK_ADDRESS_BITS, NO_OF_BUFFERS, respInfo, RESPONSE_BUFFER_SIZE, Data::size, HighLevelPacket::source, and Data::value.
Referenced by handle_new_packet_event().
void GenericTPG_clubbed::convertToBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 441 of file genericTPG_clubbed.cc.
References Request::address, Request::arrivalTime, CACHE_BLOCK_SIZE, CACHE_WRITEBACK, Request::cmdType, HighLevelPacket::data, HighLevelPacket::data_payload_length, max_phy_link_bits, HighLevelPacket::msg_class, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, ONE_FLIT_REQ, RESPONSE_PKT, HighLevelPacket::sent_time, and Request::threadId.
void GenericTPG_clubbed::convertToBitStream2 (Request * req, HighLevelPacket * hlp) [private]
Definition at line 478 of file genericTPG_clubbed.cc.
References Request::address, Request::arrivalTime, Request::bankNo, CACHE_WRITEBACK, Request::channelNo, Request::child_req, Request::cmdType, COLUMN_SIZE, Request::columnNo, HighLevelPacket::data, HighLevelPacket::data_payload_length, head_and_tail_length, Request::lowerBits, max_phy_link_bits, Request::mcNo, HighLevelPacket::msg_class, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, NO_OF_BANKS, NO_OF_CHANNELS, NO_OF_COLUMNS, NO_OF_RANKS, NO_OF_ROWS, NetworkComponent::node_ip, ONE_FLIT_REQ, packets, HighLevelPacket::pkt_cnt, Request::rankNo, REQUEST_PKT, RESPONSE_PKT, Request::rowNo, Request::scheduledInMSHR, HighLevelPacket::sent_time, and Request::threadId.
Referenced by handle_out_pull_event().
void GenericTPG_clubbed::finish ()
Definition at line 161 of file genericTPG_clubbed.cc.
References out_file, and trace_filename.
bool GenericTPG_clubbed::GetNewRequest (Request ** req) [private]
Definition at line 373 of file genericTPG_clubbed.cc.
References bankInfo, CLUBBED_BANK_LIM, CLUBBED_RESPONSE_LIM, MSHR_H_clubbed::mshr, mshrHandler, NetworkComponent::node_ip, Simulator::Now(), respInfo, Request::scheduledInMSHR, STALL_TIME, UPPER_STALL_TIME, and MSHR_H_clubbed::writeQueue.
Referenced by GetRequest().
Request * GenericTPG_clubbed::GetNextRequest () [private]
Definition at line 335 of file genericTPG_clubbed.cc.
References Request::address, Request::arrivalTime, Request::cmdType, MSHR_H_clubbed::GlobalAddrMap(), mshrHandler, NetworkComponent::node_ip, Request::threadId, and trace_filename.
Referenced by handle_out_pull_event().
Request * GenericTPG_clubbed::GetRequest () [private]
Definition at line 429 of file genericTPG_clubbed.cc.
References GetNewRequest().
Referenced by handle_out_pull_event().
void GenericTPG_clubbed::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 190 of file genericTPG_clubbed.cc.
References _DBG, HighLevelPacket::avg_network_latency, convertFromBitStream(), IrisEvent::event_data, HighLevelPacket::hop_count, Processor::interface_connections, last_packet_out_cycle, min_pkt_latency, MSHR_DELETE, mshrHandler, NetworkComponent::node_ip, Simulator::Now(), out_file, out_filename, packets_in, NetworkComponent::process_event(), MSHR_H_clubbed::process_event(), READY_EVENT, HighLevelPacket::req_start_time, Simulator::Schedule(), HighLevelPacket::sent_time, Request::startTime, HighLevelPacket::stat_memory_serviced_time, stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, HighLevelPacket::toString(), IrisEvent::type, IrisEvent::vc, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
void GenericTPG_clubbed::handle_out_pull_event (IrisEvent * e) [private]
Definition at line 247 of file genericTPG_clubbed.cc.
References _DBG, HighLevelPacket::addr, Request::address, NetworkComponent::address, Request::arrivalTime, CACHE_WRITEBACK, Request::cmdType, convertToBitStream2(), HighLevelPacket::destination, fwd_path_delay, GetNextRequest(), GetRequest(), Processor::interface_connections, Request::mcNo, NEW_PACKET_EVENT, no_nodes, NetworkComponent::node_ip, Simulator::Now(), OUT_PULL_EVENT, packets, NetworkComponent::process_event(), ready, HighLevelPacket::req_start_time, Simulator::Schedule(), sending, HighLevelPacket::sent_time, HighLevelPacket::source, Request::startTime, HighLevelPacket::toString(), HighLevelPacket::transaction_id, IrisEvent::type, IrisEvent::vc, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void GenericTPG_clubbed::handle_ready_event (IrisEvent * e) [private]
Definition at line 317 of file genericTPG_clubbed.cc.
References max_sim_time, Simulator::Now(), OUT_PULL_EVENT, NetworkComponent::process_event(), ready, Simulator::Schedule(), and sending.
Referenced by process_event().
string GenericTPG_clubbed::print_stats () const [virtual]
Implements Processor .
Definition at line 642 of file genericTPG_clubbed.cc.
References fwd_path_delay, last_packet_out_cycle, min_pkt_latency, mshrHandler, NetworkComponent::node_ip, MSHR_H_clubbed::nonEmptyCycles, packets, packets_in, roundTripLat, stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, MSHR_H_clubbed::TotalBLP, and MSHR_H_clubbed::unsink.
void GenericTPG_clubbed::process_event (IrisEvent * e) [virtual]
Implements Processor .
Definition at line 169 of file genericTPG_clubbed.cc.
References NetworkComponent::address, handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), NEW_PACKET_EVENT, OUT_PULL_EVENT, READY_EVENT, and IrisEvent::type.
Referenced by MSHR_H_clubbed::process_event().
void GenericTPG_clubbed::set_no_vcs (uint v)
Definition at line 39 of file genericTPG_clubbed.cc.
References vcs.
void GenericTPG_clubbed::set_output_path (string outpath) [virtual]
Implements Processor .
Definition at line 143 of file genericTPG_clubbed.cc.
References NetworkComponent::node_ip, out_file, and out_filename.
void GenericTPG_clubbed::set_trace_filename (string filename)
Definition at line 32 of file genericTPG_clubbed.cc.
References trace_name.
void GenericTPG_clubbed::setup (uint no_nodes, uint vcs, uint max_sim_time) [virtual]
Implements Processor .
Definition at line 45 of file genericTPG_clubbed.cc.
References Request::address, NetworkComponent::address, Request::arrivalTime, bankInfo, Request::cmdType, MSHR_H_clubbed::filename, fwd_path_delay, MSHR_H_clubbed::GlobalAddrMap(), MSHR_H_clubbed::id, last_packet_out_cycle, max_sim_time, min_pkt_latency, mshrHandler, Component::myId(), no_mcs, no_nodes, NO_OF_BUFFERS, NetworkComponent::node_ip, Simulator::Now(), packets, packets_in, MSHR_H_clubbed::parent, NetworkComponent::process_event(), MSHR_H_clubbed::process_event(), ready, READY_EVENT, respInfo, roundTripLat, Simulator::Schedule(), Request::scheduleTime, STALL_TIME, stat_round_trip_hop_count, stat_round_trip_memory_latency, stat_round_trip_network_latency, stat_waiting_in_ni, Request::threadId, MSHR_H_clubbed::trace_filename, trace_filename, trace_name, and vcs.
string GenericTPG_clubbed::toString () const [virtual]
Reimplemented from Processor .
Definition at line 629 of file genericTPG_clubbed.cc.
References NetworkComponent::address, NetworkComponent::node_ip, ready, and trace_name.
Member Data Documentation
unsigned int GenericTPG_clubbed::bankInfo[8][NO_OF_BUFFERS]
Definition at line 79 of file genericTPG_clubbed.h.
Referenced by convertFromBitStream(), GetNewRequest(), and setup().
unsigned long long int GenericTPG_clubbed::fwd_path_delay
Definition at line 58 of file genericTPG_clubbed.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
double GenericTPG_clubbed::last_packet_out_cycle
Definition at line 57 of file genericTPG_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned int GenericTPG_clubbed::last_vc [private]
Definition at line 39 of file genericTPG_clubbed.h.
Referenced by GenericTPG_clubbed().
unsigned long long int GenericTPG_clubbed::max_sim_time [private]
Definition at line 32 of file genericTPG_clubbed.h.
Referenced by handle_ready_event(), and setup().
unsigned long long int GenericTPG_clubbed::max_time
Definition at line 68 of file genericTPG_clubbed.h.
vector<uint> GenericTPG_clubbed::mc_node_ip
Definition at line 78 of file genericTPG_clubbed.h.
double GenericTPG_clubbed::min_pkt_latency
Definition at line 56 of file genericTPG_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
MSHR_H_clubbed* GenericTPG_clubbed::mshrHandler
Definition at line 65 of file genericTPG_clubbed.h.
Referenced by GetNewRequest(), GetNextRequest(), handle_new_packet_event(), print_stats(), setup(), and ~GenericTPG_clubbed().
uint GenericTPG_clubbed::no_nodes [private]
Definition at line 30 of file genericTPG_clubbed.h.
Referenced by handle_out_pull_event(), and setup().
uint GenericTPG_clubbed::no_outstanding [private]
Definition at line 31 of file genericTPG_clubbed.h.
ofstream GenericTPG_clubbed::out_file [private]
Definition at line 37 of file genericTPG_clubbed.h.
Referenced by finish(), handle_new_packet_event(), set_output_path(), and ~GenericTPG_clubbed().
string GenericTPG_clubbed::out_filename [private]
Definition at line 35 of file genericTPG_clubbed.h.
Referenced by GenericTPG_clubbed(), handle_new_packet_event(), and set_output_path().
deque< HighLevelPacket > GenericTPG_clubbed::out_packets [private]
Definition at line 33 of file genericTPG_clubbed.h.
unsigned int GenericTPG_clubbed::packets
Definition at line 54 of file genericTPG_clubbed.h.
Referenced by convertToBitStream2(), handle_out_pull_event(), print_stats(), and setup().
unsigned int GenericTPG_clubbed::packets_in
Definition at line 55 of file genericTPG_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
vector< bool > GenericTPG_clubbed::ready
Definition at line 66 of file genericTPG_clubbed.h.
Referenced by handle_out_pull_event(), handle_ready_event(), setup(), and toString().
unsigned int GenericTPG_clubbed::respInfo[8]
Definition at line 80 of file genericTPG_clubbed.h.
Referenced by convertFromBitStream(), GetNewRequest(), and setup().
unsigned long long int GenericTPG_clubbed::roundTripLat
Definition at line 59 of file genericTPG_clubbed.h.
Referenced by print_stats(), and setup().
bool GenericTPG_clubbed::sending
Definition at line 67 of file genericTPG_clubbed.h.
Referenced by GenericTPG_clubbed(), handle_out_pull_event(), and handle_ready_event().
deque< HighLevelPacket > GenericTPG_clubbed::sent_packets [private]
Definition at line 34 of file genericTPG_clubbed.h.
unsigned long long int GenericTPG_clubbed::stat_round_trip_hop_count
Definition at line 61 of file genericTPG_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int GenericTPG_clubbed::stat_round_trip_memory_latency
Definition at line 62 of file genericTPG_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int GenericTPG_clubbed::stat_round_trip_network_latency
Definition at line 60 of file genericTPG_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int GenericTPG_clubbed::stat_waiting_in_ni
Definition at line 63 of file genericTPG_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
ifstream* GenericTPG_clubbed::trace_filename [private]
Definition at line 38 of file genericTPG_clubbed.h.
Referenced by finish(), GetNextRequest(), and setup().
string GenericTPG_clubbed::trace_name [private]
Definition at line 36 of file genericTPG_clubbed.h.
Referenced by set_trace_filename(), setup(), and toString().
uint GenericTPG_clubbed::vcs [private]
Definition at line 29 of file genericTPG_clubbed.h.
Referenced by set_no_vcs(), and setup().
The documentation for this class was generated from the following files:
genericTPG_clubbed.h
genericTPG_clubbed.cc