RefreshMgr Class Reference
#include <refresh_manager.h>
Public Member Functions
RefreshMgr ()
~RefreshMgr ()
void process_event (IrisEvent *e)
std::string toString ()
Public Attributes
Component * mc
Time nextRefresh
RequestHandler * reqPtr
unsigned int currentRankNo
unsigned int currentRowNo
Detailed Description
Definition at line 44 of file refresh_manager.h.
Constructor & Destructor Documentation
RefreshMgr::RefreshMgr ()
Definition at line 39 of file refresh_manager.cc.
References currentRankNo, currentRowNo, and nextRefresh.
RefreshMgr::~RefreshMgr ()
Definition at line 53 of file refresh_manager.cc.
Member Function Documentation
void RefreshMgr::process_event (IrisEvent * e)
Definition at line 65 of file refresh_manager.cc.
References RequestHandler::busHandler, BusHandler::cmdIssuer, Request::cmdType, currentRankNo, currentRowNo, IrisEvent::dst, BusHandler::LowLevelCmdGen(), nextRefresh, NO_OF_CHANNELS, NO_OF_RANKS, NO_OF_ROWS, Simulator::Now(), CmdIssuer::process_event(), Request::rankNo, REFRESH, REFRESH_INC, reqPtr, ROW_SIZE, Request::rowNo, Simulator::Schedule(), IrisEvent::src, and START.
Referenced by MC::StartRefresh().
std::string RefreshMgr::toString ()
Member Data Documentation
unsigned int RefreshMgr::currentRankNo
Definition at line 53 of file refresh_manager.h.
Referenced by process_event(), and RefreshMgr().
unsigned int RefreshMgr::currentRowNo
Definition at line 54 of file refresh_manager.h.
Referenced by process_event(), and RefreshMgr().
Component* RefreshMgr::mc
Definition at line 49 of file refresh_manager.h.
Referenced by MC::Init().
Time RefreshMgr::nextRefresh
Definition at line 50 of file refresh_manager.h.
Referenced by process_event(), RefreshMgr(), and MC::StartRefresh().
RequestHandler* RefreshMgr::reqPtr
Definition at line 51 of file refresh_manager.h.
Referenced by MC::Init(), and process_event().
The documentation for this class was generated from the following files:
refresh_manager.h
refresh_manager.cc