GenericRouterNoVcs Class Reference
#include <genericRouterNoVcs.h>
Public Member Functions
GenericRouterNoVcs ()
~GenericRouterNoVcs ()
void init (uint ports, uint vcs, uint credits, uint buffer_size)
void set_no_nodes (uint nodes)
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
void set_grid_x_location (uint a, uint b, uint c)
void set_grid_y_location (uint a, uint b, uint c)
void send_credit_back (uint i)
void process_event (IrisEvent *e)
string toString () const
string print_stats ()
Public Attributes
vector< vector< uint > > downstream_credits
uint packets
uint flits
double total_packet_latency
double last_flit_out_cycle
Private Member Functions
void handle_link_arrival_event (IrisEvent *e)
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
void handle_tick_event (IrisEvent *e)
Event handle for the TICK_EVENT. Entry from DES kernel.
void do_switch_traversal ()
void do_switch_allocation ()
Private Attributes
vector< GenericBuffer > in_buffers
vector< GenericRC > decoders
vector< InputBufferState > input_buffer_state
PToPSwitchArbiter swa
GenericCrossbar xbar
bool ticking
Detailed Description
Definition at line 35 of file genericRouterNoVcs.h.
Constructor & Destructor Documentation
GenericRouterNoVcs::GenericRouterNoVcs ()
Definition at line 39 of file genericRouterNoVcs.cc.
References NetworkComponent::name, and ticking.
GenericRouterNoVcs::~GenericRouterNoVcs ()
Definition at line 45 of file genericRouterNoVcs.cc.
Member Function Documentation
void GenericRouterNoVcs::do_switch_allocation () [private]
Definition at line 367 of file genericRouterNoVcs.cc.
References _DBG, GenericCrossbar::configure_crossbar(), input_buffer_state, PToPSwitchArbiter::is_empty(), PToPSwitchArbiter::pick_winner(), SA_unit::port, Router::ports, GenericCrossbar::push(), ST, swa, SWA_REQUESTED, ticking, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterNoVcs::do_switch_traversal () [private]
Definition at line 267 of file genericRouterNoVcs.cc.
References _DBG, _DBG_NOARG, NetworkComponent::address, BODY, PToPSwitchArbiter::clear_winner(), data, downstream_credits, EMPTY, FLIT_ID, HEAD, in_buffers, input_buffer_state, GenericCrossbar::is_empty(), Flit::is_single_flit_pkt, last_flit_out_cycle, LINK_ARRIVAL_EVENT, Simulator::Now(), Router::output_connections, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, GenericCrossbar::pull(), Simulator::Schedule(), send_credit_back(), ST, swa, TAIL, toString(), total_packet_latency, Flit::type, LinkArrivalData::type, LinkArrivalData::vc, Router::vcs, and xbar.
Referenced by handle_tick_event().
void GenericRouterNoVcs::handle_link_arrival_event (IrisEvent * e) [private]
Event handle for the LINK_ARRIVAL_EVENT event. Entry from DES kernel.
Definition at line 159 of file genericRouterNoVcs.cc.
References _DBG, CREDIT_ID, data, decoders, downstream_credits, IrisEvent::event_data, FLIT_ID, flits, FULL, HEAD, in_buffers, input_buffer_state, Router::input_connections, Flit::is_single_flit_pkt, HeadFlit::length, Simulator::Now(), Router::output_connections, packets, Router::ports, NetworkComponent::process_event(), LinkArrivalData::ptr, Simulator::Schedule(), IrisEvent::src_id, TAIL, TICK_EVENT, ticking, Flit::type, LinkArrivalData::type, IrisEvent::vc, LinkArrivalData::vc, and Router::vcs.
Referenced by process_event().
void GenericRouterNoVcs::handle_tick_event (IrisEvent * e) [private]
Event handle for the TICK_EVENT. Entry from DES kernel.
Body and tail flits get written in link arrival and since the message state may already been pushed to ST because of the header we want to ensure that all flits go thru an IB and ST stage. Hence ST is done on the flits_in_ib information and not buffer occupancy.
Sending credits back for body+tail: Condition being HEAD in ST and having downstream credits
Definition at line 420 of file genericRouterNoVcs.cc.
References _DBG, _DBG_NOARG, do_switch_allocation(), do_switch_traversal(), downstream_credits, FULL, IB, in_buffers, input_buffer_state, PToPSwitchArbiter::is_requested(), Simulator::Now(), Router::ports, NetworkComponent::process_event(), PToPSwitchArbiter::request(), Simulator::Schedule(), ST, swa, SWA_REQUESTED, TICK_EVENT, ticking, toString(), IrisEvent::vc, and Router::vcs.
Referenced by process_event().
void GenericRouterNoVcs::init (uint ports, uint vcs, uint credits, uint buffer_size) [virtual]
Implements Router .
Definition at line 50 of file genericRouterNoVcs.cc.
References NetworkComponent::address, Router::buffer_size, Router::credits, decoders, downstream_credits, flits, in_buffers, input_buffer_state, Component::myId(), NetworkComponent::node_ip, packets, Router::ports, PToPSwitchArbiter::resize(), GenericCrossbar::set_no_virtual_channels(), swa, total_packet_latency, Router::vcs, and xbar.
string GenericRouterNoVcs::print_stats (void) [virtual]
Implements Router .
Definition at line 143 of file genericRouterNoVcs.cc.
References flits, last_flit_out_cycle, NetworkComponent::node_ip, packets, and total_packet_latency.
void GenericRouterNoVcs::process_event (IrisEvent * e) [virtual]
Implements NetworkComponent .
Definition at line 125 of file genericRouterNoVcs.cc.
References _DBG, handle_link_arrival_event(), handle_tick_event(), LINK_ARRIVAL_EVENT, TICK_EVENT, and IrisEvent::type.
void GenericRouterNoVcs::send_credit_back (uint i)
Definition at line 567 of file genericRouterNoVcs.cc.
References _DBG, NetworkComponent::address, CREDIT_ID, data, input_buffer_state, Router::input_connections, LINK_ARRIVAL_EVENT, Simulator::Now(), NetworkComponent::process_event(), Simulator::Schedule(), LinkArrivalData::type, and LinkArrivalData::vc.
Referenced by do_switch_traversal().
void GenericRouterNoVcs::set_grid_x_location (uint a, uint b, uint c) [virtual]
Implements Router .
Definition at line 111 of file genericRouterNoVcs.cc.
References decoders.
void GenericRouterNoVcs::set_grid_y_location (uint a, uint b, uint c) [virtual]
Implements Router .
Definition at line 117 of file genericRouterNoVcs.cc.
References decoders.
void GenericRouterNoVcs::set_no_nodes (uint nodes) [virtual]
These functions are mainly for DOR routing and are seperated so as to not force DOR modelling in all designs.
Implements Router .
Definition at line 101 of file genericRouterNoVcs.cc.
References decoders.
string GenericRouterNoVcs::toString () const [virtual]
Reimplemented from Router .
Definition at line 544 of file genericRouterNoVcs.cc.
References NetworkComponent::address, decoders, in_buffers, NetworkComponent::node_ip, swa, GenericCrossbar::toString(), PToPSwitchArbiter::toString(), and xbar.
Referenced by do_switch_traversal(), and handle_tick_event().
Member Data Documentation
vector<GenericRC> GenericRouterNoVcs::decoders [private]
Definition at line 63 of file genericRouterNoVcs.h.
Referenced by handle_link_arrival_event(), init(), set_grid_x_location(), set_grid_y_location(), set_no_nodes(), and toString().
vector< vector<uint> > GenericRouterNoVcs::downstream_credits
Definition at line 51 of file genericRouterNoVcs.h.
Referenced by do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), and init().
uint GenericRouterNoVcs::flits
Definition at line 55 of file genericRouterNoVcs.h.
Referenced by handle_link_arrival_event(), init(), and print_stats().
vector<GenericBuffer> GenericRouterNoVcs::in_buffers [private]
Definition at line 62 of file genericRouterNoVcs.h.
Referenced by do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), init(), and toString().
vector<InputBufferState> GenericRouterNoVcs::input_buffer_state [private]
Definition at line 64 of file genericRouterNoVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_link_arrival_event(), handle_tick_event(), init(), and send_credit_back().
double GenericRouterNoVcs::last_flit_out_cycle
Definition at line 57 of file genericRouterNoVcs.h.
Referenced by do_switch_traversal(), and print_stats().
uint GenericRouterNoVcs::packets
Definition at line 54 of file genericRouterNoVcs.h.
Referenced by handle_link_arrival_event(), init(), and print_stats().
PToPSwitchArbiter GenericRouterNoVcs::swa [private]
Definition at line 65 of file genericRouterNoVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), handle_tick_event(), init(), and toString().
bool GenericRouterNoVcs::ticking [private]
Definition at line 68 of file genericRouterNoVcs.h.
Referenced by do_switch_allocation(), GenericRouterNoVcs(), handle_link_arrival_event(), and handle_tick_event().
double GenericRouterNoVcs::total_packet_latency
Definition at line 56 of file genericRouterNoVcs.h.
Referenced by do_switch_traversal(), init(), and print_stats().
GenericCrossbar GenericRouterNoVcs::xbar [private]
Definition at line 66 of file genericRouterNoVcs.h.
Referenced by do_switch_allocation(), do_switch_traversal(), init(), and toString().
The documentation for this class was generated from the following files:
genericRouterNoVcs.h
genericRouterNoVcs.cc