GenericCrossbar Class Reference
#include <genericCrossbar.h>
Classes
class CrossbarUnit
Public Member Functions
GenericCrossbar ()
~GenericCrossbar ()
void setup (uint ports, uint vcs)
uint get_no_input_ports ()
uint get_no_output_ports ()
void set_no_virtual_channels (uint no)
uint get_no_channels ()
uint get_map (uint in_port, uint ch)
void configure_crossbar (uint in_port, uint out_port, uint ch)
void push (uint in_port, uint ch)
void pull (uint out_port, uint ch)
bool is_full (uint in_port, uint ch)
bool is_empty (uint out_port, uint ch)
string toString () const
Private Member Functions
void clear ()
Private Attributes
vector< vector< uint > > map
uint input_ports
uint output_ports
uint vcs
vector< vector< bool > > busy
Detailed Description
Definition at line 33 of file genericCrossbar.h.
Constructor & Destructor Documentation
GenericCrossbar::GenericCrossbar ()
Definition at line 25 of file genericCrossbar.cc.
References input_ports, and output_ports.
GenericCrossbar::~GenericCrossbar ()
Definition at line 31 of file genericCrossbar.cc.
Member Function Documentation
void GenericCrossbar::clear () [private]
Definition at line 37 of file genericCrossbar.cc.
void GenericCrossbar::configure_crossbar (uint in_port, uint out_port, uint ch) [virtual]
Implements Crossbar .
Definition at line 99 of file genericCrossbar.cc.
References busy, and map.
Referenced by GenericRouterVct::do_switch_allocation(), GenericRouterVcs::do_switch_allocation(), GenericRouterNoVcs::do_switch_allocation(), and GenericRouterAdaptive::do_switch_allocation().
uint GenericCrossbar::get_map (uint in_port, uint ch) [virtual]
Implements Crossbar .
Definition at line 87 of file genericCrossbar.cc.
References input_ports, and map.
uint GenericCrossbar::get_no_channels () [virtual]
Implements Crossbar .
Definition at line 81 of file genericCrossbar.cc.
References map.
uint GenericCrossbar::get_no_input_ports () [virtual]
Implements Crossbar .
Definition at line 43 of file genericCrossbar.cc.
References input_ports.
uint GenericCrossbar::get_no_output_ports () [virtual]
Implements Crossbar .
Definition at line 49 of file genericCrossbar.cc.
References output_ports.
bool GenericCrossbar::is_empty (uint out_port, uint ch) [virtual]
Implements Crossbar .
Definition at line 131 of file genericCrossbar.cc.
References busy.
Referenced by GenericRouterVct::do_switch_traversal(), GenericRouterVcs::do_switch_traversal(), GenericRouterNoVcs::do_switch_traversal(), and GenericRouterAdaptive::do_switch_traversal().
bool GenericCrossbar::is_full (uint in_port, uint ch) [virtual]
Implements Crossbar .
Definition at line 121 of file genericCrossbar.cc.
References busy, and map.
void GenericCrossbar::pull (uint out_port, uint ch)
Definition at line 114 of file genericCrossbar.cc.
References busy.
Referenced by GenericRouterVct::do_switch_traversal(), GenericRouterVcs::do_switch_traversal(), GenericRouterNoVcs::do_switch_traversal(), and GenericRouterAdaptive::do_switch_traversal().
void GenericCrossbar::push (uint in_port, uint ch)
Definition at line 107 of file genericCrossbar.cc.
References busy.
Referenced by GenericRouterVct::do_switch_allocation(), GenericRouterVcs::do_switch_allocation(), GenericRouterNoVcs::do_switch_allocation(), and GenericRouterAdaptive::do_switch_allocation().
void GenericCrossbar::set_no_virtual_channels (uint no)
Referenced by GenericRouterVct::init(), and GenericRouterNoVcs::init().
void GenericCrossbar::setup (uint ports, uint vcs)
Definition at line 55 of file genericCrossbar.cc.
References busy, input_ports, map, output_ports, and vcs.
Referenced by GenericRouterVcs::init(), and GenericRouterAdaptive::init().
string GenericCrossbar::toString () const
Definition at line 143 of file genericCrossbar.cc.
References map, and output_ports.
Referenced by GenericRouterVct::toString(), GenericRouterVcs::toString(), GenericRouterNoVcs::toString(), and GenericRouterAdaptive::toString().
Member Data Documentation
vector< vector<bool> > GenericCrossbar::busy [private]
Definition at line 76 of file genericCrossbar.h.
Referenced by configure_crossbar(), is_empty(), is_full(), pull(), push(), and setup().
uint GenericCrossbar::input_ports [private]
Definition at line 55 of file genericCrossbar.h.
Referenced by GenericCrossbar(), get_map(), get_no_input_ports(), and setup().
vector< vector<uint> > GenericCrossbar::map [private]
Definition at line 54 of file genericCrossbar.h.
Referenced by configure_crossbar(), get_map(), get_no_channels(), is_full(), setup(), and toString().
uint GenericCrossbar::output_ports [private]
Definition at line 56 of file genericCrossbar.h.
Referenced by GenericCrossbar(), get_no_output_ports(), setup(), and toString().
uint GenericCrossbar::vcs [private]
Definition at line 57 of file genericCrossbar.h.
Referenced by setup().
The documentation for this class was generated from the following files:
genericCrossbar.h
genericCrossbar.cc