Simulator Class Reference
#include <simulator.h>
Static Public Member Functions
static void Run ()
static void Stop ()
static void StopAt (double)
static double Now ()
static bool Cancel (EventId &)
static EventId Peek ()
static EventBase * GetEarliestEvent ()
static int MyRank ()
template<typename T , typename OBJ >
static EventId Schedule (double t, void(T::*handler)(void), OBJ *obj)
template<typename T , typename OBJ , typename U1 , typename T1 >
static EventId Schedule (double t, void(T::*handler)(U1), OBJ *obj, T1 t1)
template<typename T , typename OBJ , typename U1 , typename T1 , typename U2 , typename T2 >
static EventId Schedule (double t, void(T::*handler)(U1, U2), OBJ *obj, T1 t1, T2 t2)
template<typename T , typename OBJ , typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 >
static EventId Schedule (double t, void(T::*handler)(U1, U2, U3), OBJ *obj, T1 t1, T2 t2, T3 t3)
template<typename T , typename OBJ , typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 , typename U4 , typename T4 >
static EventId Schedule (double t, void(T::*handler)(U1, U2, U3, U4), OBJ *obj, T1 t1, T2 t2, T3 t3, T4 t4)
static EventId Schedule (double t, void(*handler)(void))
template<typename U1 , typename T1 >
static EventId Schedule (double t, void(*handler)(U1), T1 t1)
template<typename U1 , typename T1 , typename U2 , typename T2 >
static EventId Schedule (double t, void(*handler)(U1, U2), T1 t1, T2 t2)
template<typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 >
static EventId Schedule (double t, void(*handler)(U1, U2, U3), T1 t1, T2 t2, T3 t3)
template<typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 , typename U4 , typename T4 >
static EventId Schedule (double t, void(*handler)(U1, U2, U3, U4), T1 t1, T2 t2, T3 t3, T4 t4)
static void registerComponent (Component *obj, int lp)
static ComponentDescription * getComponentDesc (int)
Static Private Attributes
static EventSet_t events
static double simTime
static ComponentMap_t components
static int nextComponentID
static int rank
static bool halted = false
Detailed Description
Definition at line 296 of file simulator.h.
Member Function Documentation
bool Simulator::Cancel (EventId & evid) [static]
Definition at line 56 of file simulator.cc.
References events.
ComponentDescription * Simulator::getComponentDesc (int compId) [static]
Definition at line 101 of file simulator.cc.
References components.
Referenced by Link::Link(), and Link::Send().
EventBase * Simulator::GetEarliestEvent () [static]
Definition at line 71 of file simulator.cc.
References events.
int Simulator::MyRank () [static]
Definition at line 78 of file simulator.cc.
References rank.
Referenced by Link::Link(), and Link::Send().
double Simulator::Now () [static]
Definition at line 51 of file simulator.cc.
References simTime.
Referenced by CmdIssuer::BankNotBusy(), CmdIssuer::BusNotBusy(), Statistic::CalculateAggregateStats(), CmdIssuer::CanSchedule(), Clock::Clock(), Statistic::CollectStatsPerRequest(), MSHR_SA_H::DeleteInMSHR(), MSHR_H::DeleteInMSHR(), MSHR_SA_H::demap_addr(), MSHR_H::demap_addr(), PToPSwitchArbiter::do_fcfs_arbitration(), PToPSwitchArbiterVcs::do_round_robin_arbitration(), GenericRouterVct::do_switch_traversal(), GenericRouterVcs::do_switch_traversal(), GenericRouterNoVcs::do_switch_traversal(), GenericRouterAdaptive::do_switch_traversal(), uncore_t::enqueue(), Clock::fallingEdge(), GenericTPGVcs::GetNewRequest(), GenericTPG::GetNewRequest(), GenericRouterVcs::handle_detect_deadlock_event(), GenericInterfaceVcs::handle_link_arrival(), GenericInterface::handle_link_arrival(), GenericRouterVct::handle_link_arrival_event(), GenericRouterVcs::handle_link_arrival_event(), GenericRouterNoVcs::handle_link_arrival_event(), GenericLink::handle_link_arrival_event(), GenericRouterAdaptive::handle_link_arrival_event_multiple_flit_in_buffer(), GenericRouterAdaptive::handle_link_arrival_event_one_msg_per_buffer(), uncore_t::handle_new_packet_event(), NI::handle_new_packet_event(), GenericTPGVcs::handle_new_packet_event(), GenericTPG::handle_new_packet_event(), GenericSink::handle_new_packet_event(), GenericRPG::handle_new_packet_event(), GenericInterfaceVcs::handle_new_packet_event(), GenericInterface::handle_new_packet_event(), GenericFlatMc::handle_new_packet_event(), NI::handle_out_pull_event(), GenericTPGVcs::handle_out_pull_event(), GenericTPG::handle_out_pull_event(), GenericRPG::handle_out_pull_event(), GenericFlatMc::handle_out_pull_event(), GenericSink::handle_outpull_event(), NI::handle_ready_event(), GenericTPGVcs::handle_ready_event(), GenericTPG::handle_ready_event(), GenericSink::handle_ready_event(), GenericRPG::handle_ready_event(), GenericInterfaceVcs::handle_ready_event(), GenericInterface::handle_ready_event(), GenericFlatMc::handle_ready_event(), GenericRouterVct::handle_tick_event(), GenericRouterVcs::handle_tick_event(), GenericRouterNoVcs::handle_tick_event(), GenericRouterAdaptive::handle_tick_event(), GenericInterfaceVcs::handle_tick_event(), GenericInterface::handle_tick_event(), HighLevelPacket::HighLevelPacket(), GenericRouterVcs::init(), GenericRouterAdaptive::init_buffer_state(), main(), Statistic::PrintAggregateStats(), ResponseHandler::process_event(), RequestHandler::process_event(), RefreshMgr::process_event(), MSHR_SA_H::process_event(), MSHR_H::process_event(), DRAMChannel::process_event(), DataBusHandler::process_event(), CmdIssuer::process_event(), CmdBusHandler::process_event(), BankHandler::process_event(), AddrMap::process_event(), PToPSwitchArbiterVcs::request(), PToPSwitchArbiter::request(), Clock::risingEdge(), Link::Send(), GenericRouterVct::send_credit_back(), GenericRouterVcs::send_credit_back(), GenericRouterNoVcs::send_credit_back(), GenericRouterAdaptive::send_credit_back(), CmdIssuer::SetBusBusyTime(), CmdIssuer::SetPrevState(), GenericTPGVcs::setup(), GenericTPG::setup(), GenericSink::setup(), GenericRPG::setup(), GenericFlatMc::setup(), MC::sim_main(), MC::StartRefresh(), TailFlit::TailFlit(), and IrisEvent::toString().
EventId Simulator::Peek () [static]
Definition at line 64 of file simulator.cc.
References events.
void Simulator::registerComponent (Component * obj, int lp) [static]
Definition at line 85 of file simulator.cc.
References components, nextComponentID, rank, and Component::setComponentId().
Referenced by Component::Component().
void Simulator::Run () [static]
Definition at line 21 of file simulator.cc.
References EventBase::CallHandler(), events, halted, rank, simTime, and EventBase::time.
Referenced by main().
template<typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 , typename U4 , typename T4 > static EventId Simulator::Schedule (double t, void(*)(U1, U2, U3, U4) handler, T1 t1, T2 t2, T3 t3, T4 t4) [inline, static]
Definition at line 397 of file simulator.h.
References events, and EventBase::uid.
template<typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 > static EventId Simulator::Schedule (double t, void(*)(U1, U2, U3) handler, T1 t1, T2 t2, T3 t3) [inline, static]
Definition at line 386 of file simulator.h.
References events, and EventBase::uid.
template<typename U1 , typename T1 , typename U2 , typename T2 > static EventId Simulator::Schedule (double t, void(*)(U1, U2) handler, T1 t1, T2 t2) [inline, static]
Definition at line 376 of file simulator.h.
References events, and EventBase::uid.
template<typename U1 , typename T1 > static EventId Simulator::Schedule (double t, void(*)(U1) handler, T1 t1) [inline, static]
Definition at line 367 of file simulator.h.
References events, and EventBase::uid.
static EventId Simulator::Schedule (double t, void(*)(void) handler) [inline, static]
Definition at line 359 of file simulator.h.
References events, and EventBase::uid.
template<typename T , typename OBJ , typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 , typename U4 , typename T4 > static EventId Simulator::Schedule (double t, void(T::*)(U1, U2, U3, U4) handler, OBJ * obj, T1 t1, T2 t2, T3 t3, T4 t4) [inline, static]
Definition at line 351 of file simulator.h.
References events, and EventBase::uid.
template<typename T , typename OBJ , typename U1 , typename T1 , typename U2 , typename T2 , typename U3 , typename T3 > static EventId Simulator::Schedule (double t, void(T::*)(U1, U2, U3) handler, OBJ * obj, T1 t1, T2 t2, T3 t3) [inline, static]
Definition at line 339 of file simulator.h.
References events, and EventBase::uid.
template<typename T , typename OBJ , typename U1 , typename T1 , typename U2 , typename T2 > static EventId Simulator::Schedule (double t, void(T::*)(U1, U2) handler, OBJ * obj, T1 t1, T2 t2) [inline, static]
Definition at line 328 of file simulator.h.
References events, and EventBase::uid.
template<typename T , typename OBJ , typename U1 , typename T1 > static EventId Simulator::Schedule (double t, void(T::*)(U1) handler, OBJ * obj, T1 t1) [inline, static]
Definition at line 318 of file simulator.h.
References events, and EventBase::uid.
template<typename T , typename OBJ > static EventId Simulator::Schedule (double t, void(T::*)(void) handler, OBJ * obj) [inline, static]
Definition at line 309 of file simulator.h.
References events, and EventBase::uid.
Referenced by Clock::Clock(), GenericRouterVct::do_switch_traversal(), GenericRouterVcs::do_switch_traversal(), GenericRouterNoVcs::do_switch_traversal(), GenericRouterAdaptive::do_switch_traversal(), uncore_t::enqueue(), Clock::fallingEdge(), GenericRouterVcs::handle_detect_deadlock_event(), GenericInterfaceVcs::handle_link_arrival(), GenericInterface::handle_link_arrival(), GenericRouterVct::handle_link_arrival_event(), GenericRouterVcs::handle_link_arrival_event(), GenericRouterNoVcs::handle_link_arrival_event(), GenericLink::handle_link_arrival_event(), GenericRouterAdaptive::handle_link_arrival_event_multiple_flit_in_buffer(), GenericRouterAdaptive::handle_link_arrival_event_one_msg_per_buffer(), uncore_t::handle_new_packet_event(), NI::handle_new_packet_event(), GenericTPGVcs::handle_new_packet_event(), GenericTPG::handle_new_packet_event(), GenericSink::handle_new_packet_event(), GenericRPG::handle_new_packet_event(), GenericInterfaceVcs::handle_new_packet_event(), GenericInterface::handle_new_packet_event(), GenericFlatMc::handle_new_packet_event(), NI::handle_out_pull_event(), GenericTPGVcs::handle_out_pull_event(), GenericTPG::handle_out_pull_event(), GenericRPG::handle_out_pull_event(), GenericFlatMc::handle_out_pull_event(), GenericSink::handle_outpull_event(), NI::handle_ready_event(), GenericTPGVcs::handle_ready_event(), GenericTPG::handle_ready_event(), GenericSink::handle_ready_event(), GenericRPG::handle_ready_event(), GenericInterfaceVcs::handle_ready_event(), GenericInterface::handle_ready_event(), GenericFlatMc::handle_ready_event(), GenericRouterVct::handle_tick_event(), GenericRouterVcs::handle_tick_event(), GenericRouterNoVcs::handle_tick_event(), GenericRouterAdaptive::handle_tick_event(), GenericInterfaceVcs::handle_tick_event(), GenericInterface::handle_tick_event(), GenericRouterVcs::init(), main(), ResponseHandler::process_event(), RequestHandler::process_event(), RefreshMgr::process_event(), MSHR_SA_H::process_event(), MSHR_H::process_event(), DRAMChannel::process_event(), DataBusHandler::process_event(), CmdIssuer::process_event(), CmdBusHandler::process_event(), BankHandler::process_event(), AddrMap::process_event(), Clock::risingEdge(), Link::Send(), GenericRouterVct::send_credit_back(), GenericRouterVcs::send_credit_back(), GenericRouterNoVcs::send_credit_back(), GenericRouterAdaptive::send_credit_back(), GenericTPGVcs::setup(), GenericTPG::setup(), GenericSink::setup(), GenericRPG::setup(), GenericFlatMc::setup(), MC::sim_main(), MC::StartRefresh(), and StopAt().
void Simulator::Stop () [static]
Definition at line 41 of file simulator.cc.
References halted.
Referenced by StopAt().
void Simulator::StopAt (double stopTime) [static]
Definition at line 46 of file simulator.cc.
References Schedule(), and Stop().
Referenced by main().
Member Data Documentation
ComponentMap_t Simulator::components [static, private]
Definition at line 410 of file simulator.h.
Referenced by getComponentDesc(), and registerComponent().
EventSet_t Simulator::events [static, private]
Definition at line 408 of file simulator.h.
Referenced by Cancel(), GetEarliestEvent(), Peek(), Run(), and Schedule().
bool Simulator::halted = false [static, private]
Definition at line 413 of file simulator.h.
Referenced by main(), Run(), and Stop().
int Simulator::nextComponentID [static, private]
Definition at line 411 of file simulator.h.
Referenced by registerComponent().
int Simulator::rank [static, private]
Definition at line 412 of file simulator.h.
Referenced by MyRank(), registerComponent(), and Run().
double Simulator::simTime [static, private]
Definition at line 409 of file simulator.h.
Referenced by Now(), and Run().
The documentation for this class was generated from the following files:
simulator.h
simulator.cc