NI_clubbed Class Reference
#include <NI_clubbed.h>
Public Member Functions
NI_clubbed ()
~NI_clubbed ()
void setup (uint no_nodes, uint vcs, uint max_sim_time)
void finish ()
void process_event (IrisEvent *e)
string toString () const
void set_no_vcs (uint v)
void set_output_path (string v)
bool compare ()
string print_stats () const
Public Attributes
Component * mc
vector< Request > niQueue
uint node_ip
bool sending
Private Member Functions
void handle_new_packet_event (IrisEvent *e)
void handle_old_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_out_pull_event (IrisEvent *e)
void convertToBitStream (Request *req, HighLevelPacket *hlp)
void convertFromBitStream (Request *req, HighLevelPacket *hlp)
void convertFromBitStream2 (Request *req, HighLevelPacket *hlp, unsigned int *startIndex)
bool GetFromNIQueue (Request *req)
void local_demap_addr (Request *req)
Private Attributes
double last_pkt_out_cycle
unsigned long long int total_missed_time
unsigned long long int total_backward_time
uint missed_time
unsigned long long int packets_out
uint vcs
uint no_nodes
unsigned int packets
unsigned long long int max_sim_time
deque< HighLevelPacket > out_packets
deque< HighLevelPacket > sent_packets
HighLevelPacket * outstanding_hlp
string out_filename
string trace_name
ofstream out_file
fstream trace_filename
vector< bool > ready
unsigned int last_vc
Detailed Description
Definition at line 43 of file NI_clubbed.h.
Constructor & Destructor Documentation
NI_clubbed::NI_clubbed ()
Definition at line 27 of file NI_clubbed.cc.
References Processor::interface_connections, mc, and NetworkComponent::name.
NI_clubbed::~NI_clubbed ()
Definition at line 37 of file NI_clubbed.cc.
Member Function Documentation
bool NI_clubbed::compare ()
void NI_clubbed::convertFromBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 501 of file NI_clubbed.cc.
References Request::address, Request::cmdType, HighLevelPacket::data, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, and Request::threadId.
void NI_clubbed::convertFromBitStream2 (Request * req, HighLevelPacket * hlp, unsigned int * startIndex) [private]
Definition at line 530 of file NI_clubbed.cc.
References Request::bankNo, Request::channelNo, Request::cmdType, COLUMN_SIZE, Request::columnNo, HighLevelPacket::data, local_demap_addr(), Request::lowerBits, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, NO_OF_BANKS, NO_OF_CHANNELS, NO_OF_COLUMNS, NO_OF_RANKS, NO_OF_ROWS, Request::rankNo, Request::rowNo, and Request::threadId.
Referenced by handle_new_packet_event().
void NI_clubbed::convertToBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 443 of file NI_clubbed.cc.
References Request::address, CACHE_BLOCK_SIZE, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, Request::cmdType, HighLevelPacket::data, HighLevelPacket::data_payload_length, MAX_BUFFER_SIZE, max_phy_link_bits, mc, NETWORK_ADDRESS_BITS, NO_OF_BUFFERS, and RESPONSE_BUFFER_SIZE.
Referenced by handle_out_pull_event().
void NI_clubbed::finish ()
Definition at line 104 of file NI_clubbed.cc.
References out_file.
bool NI_clubbed::GetFromNIQueue (Request * req) [private]
Definition at line 429 of file NI_clubbed.cc.
References niQueue.
Referenced by handle_out_pull_event().
void NI_clubbed::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 132 of file NI_clubbed.cc.
References _DBG_NOARG, Request::address, NetworkComponent::address, Request::arrivalTime, HighLevelPacket::avg_network_latency, Request::avg_network_latency, Request::bankNo, Request::channelNo, Request::columnNo, convertFromBitStream2(), IrisEvent::event_data, HighLevelPacket::hop_count, Request::hop_count, Processor::interface_connections, last_pkt_out_cycle, Request::lowerBits, MAX_BUFFER_SIZE, mc, node_ip, Simulator::Now(), outstanding_hlp, packets, HighLevelPacket::pkt_cnt, NetworkComponent::process_event(), BankHandler::process_event(), Request::rankNo, Request::rbufferInsertionTime, READY_EVENT, HighLevelPacket::recv_time, HighLevelPacket::req_start_time, HighLevelPacket::reqs_left, Request::rowNo, Simulator::Schedule(), IrisEvent::src_id, START, HighLevelPacket::startIndex, Request::startTime, Request::threadId, total_missed_time, IrisEvent::type, and IrisEvent::vc.
Referenced by process_event().
void NI_clubbed::handle_old_packet_event (IrisEvent * e) [private]
void NI_clubbed::handle_out_pull_event (IrisEvent * e) [private]
Definition at line 307 of file NI_clubbed.cc.
References _DBG, HighLevelPacket::addr, Request::address, NetworkComponent::address, Request::arrivalTime, Request::avg_network_latency, HighLevelPacket::avg_network_latency, convertToBitStream(), HighLevelPacket::destination, IrisEvent::dst, GetFromNIQueue(), Request::hop_count, HighLevelPacket::hop_count, Processor::interface_connections, mc, HighLevelPacket::msg_class, NEW_PACKET_EVENT, niQueue, Simulator::Now(), packets_out, ResponseHandler::process_event(), NetworkComponent::process_event(), ready, HighLevelPacket::recv_time, HighLevelPacket::req_start_time, RESPONSE_PKT, Request::retireTime, Simulator::Schedule(), SEND_TO_NI, sending, HighLevelPacket::sent_time, HighLevelPacket::source, Request::startTime, HighLevelPacket::stat_memory_serviced_time, Request::threadId, total_backward_time, HighLevelPacket::transaction_id, IrisEvent::type, HighLevelPacket::virtual_channel, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
void NI_clubbed::handle_ready_event (IrisEvent * e) [private]
Definition at line 359 of file NI_clubbed.cc.
References max_sim_time, Simulator::Now(), OUT_PULL_EVENT, NetworkComponent::process_event(), ready, Simulator::Schedule(), and sending.
Referenced by process_event().
void NI_clubbed::local_demap_addr (Request * req) [private]
Definition at line 623 of file NI_clubbed.cc.
References Request::address, Request::bankNo, Request::channelNo, COLUMN_SIZE, Request::columnNo, DRAM_SIZE, Request::lowerBits, NO_OF_BANKS, NO_OF_CHANNELS, NO_OF_ROWS, Request::rankNo, ROW_SIZE, and Request::rowNo.
Referenced by convertFromBitStream2().
string NI_clubbed::print_stats (void) const [virtual]
Implements Processor .
Definition at line 605 of file NI_clubbed.cc.
References last_pkt_out_cycle, mc, node_ip, packets, packets_out, total_backward_time, and total_missed_time.
void NI_clubbed::process_event (IrisEvent * e) [virtual]
Implements Processor .
Definition at line 111 of file NI_clubbed.cc.
References handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), NEW_PACKET_EVENT, OUT_PULL_EVENT, READY_EVENT, and IrisEvent::type.
Referenced by ResponseHandler::process_event(), and RequestHandler::process_event().
void NI_clubbed::set_no_vcs (uint v)
Definition at line 42 of file NI_clubbed.cc.
References vcs.
void NI_clubbed::set_output_path (string v) [virtual]
Implements Processor .
Definition at line 86 of file NI_clubbed.cc.
References node_ip, out_file, and out_filename.
void NI_clubbed::setup (uint no_nodes, uint vcs, uint max_sim_time) [virtual]
Implements Processor .
Definition at line 48 of file NI_clubbed.cc.
References NetworkComponent::address, max_sim_time, mc, missed_time, Component::myId(), no_nodes, node_ip, Simulator::Now(), packets, packets_out, NetworkComponent::process_event(), ready, READY_EVENT, Simulator::Schedule(), total_backward_time, total_missed_time, VirtualChannelDescription::vc, and vcs.
string NI_clubbed::toString (void) const [virtual]
Reimplemented from Processor .
Definition at line 419 of file NI_clubbed.cc.
References NetworkComponent::address, and out_filename.
Member Data Documentation
double NI_clubbed::last_pkt_out_cycle [private]
Definition at line 64 of file NI_clubbed.h.
Referenced by handle_new_packet_event(), and print_stats().
unsigned int NI_clubbed::last_vc [private]
Definition at line 82 of file NI_clubbed.h.
unsigned long long int NI_clubbed::max_sim_time [private]
Definition at line 73 of file NI_clubbed.h.
Referenced by handle_ready_event(), and setup().
Component* NI_clubbed::mc
Definition at line 48 of file NI_clubbed.h.
Referenced by convertToBitStream(), handle_new_packet_event(), handle_out_pull_event(), NI_clubbed(), print_stats(), and setup().
uint NI_clubbed::missed_time [private]
Definition at line 67 of file NI_clubbed.h.
Referenced by setup().
vector<Request> NI_clubbed::niQueue
Definition at line 49 of file NI_clubbed.h.
Referenced by GetFromNIQueue(), and handle_out_pull_event().
uint NI_clubbed::no_nodes [private]
Definition at line 71 of file NI_clubbed.h.
Referenced by setup().
uint NI_clubbed::node_ip
Reimplemented from NetworkComponent .
Definition at line 54 of file NI_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), set_output_path(), and setup().
ofstream NI_clubbed::out_file [private]
Definition at line 79 of file NI_clubbed.h.
Referenced by finish(), and set_output_path().
string NI_clubbed::out_filename [private]
Definition at line 77 of file NI_clubbed.h.
Referenced by set_output_path(), and toString().
deque< HighLevelPacket > NI_clubbed::out_packets [private]
Definition at line 74 of file NI_clubbed.h.
HighLevelPacket* NI_clubbed::outstanding_hlp [private]
Definition at line 76 of file NI_clubbed.h.
Referenced by handle_new_packet_event().
unsigned int NI_clubbed::packets [private]
Definition at line 72 of file NI_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
unsigned long long int NI_clubbed::packets_out [private]
Definition at line 68 of file NI_clubbed.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
vector< bool > NI_clubbed::ready [private]
Definition at line 81 of file NI_clubbed.h.
Referenced by handle_out_pull_event(), handle_ready_event(), and setup().
bool NI_clubbed::sending
Definition at line 59 of file NI_clubbed.h.
Referenced by handle_out_pull_event(), and handle_ready_event().
deque< HighLevelPacket > NI_clubbed::sent_packets [private]
Definition at line 75 of file NI_clubbed.h.
unsigned long long int NI_clubbed::total_backward_time [private]
Definition at line 66 of file NI_clubbed.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
unsigned long long int NI_clubbed::total_missed_time [private]
Definition at line 65 of file NI_clubbed.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
fstream NI_clubbed::trace_filename [private]
Definition at line 80 of file NI_clubbed.h.
string NI_clubbed::trace_name [private]
Definition at line 78 of file NI_clubbed.h.
uint NI_clubbed::vcs [private]
Definition at line 70 of file NI_clubbed.h.
Referenced by set_no_vcs(), and setup().
The documentation for this class was generated from the following files:
NI_clubbed.h
NI_clubbed.cc