zesto_component Class Reference
#include <sim.h>
Public Member Functions
zesto_component ()
void uptick_handler ()
void downtick_handler ()
~zesto_component ()
Public Attributes
Clock * clock
Detailed Description
Definition at line 162 of file sim.h.
Constructor & Destructor Documentation
zesto_component::zesto_component () [inline]
Definition at line 165 of file sim.h.
References clock, downtick_handler(), registerClock(), and uptick_handler().
Referenced by main().
zesto_component::~zesto_component () [inline]
Definition at line 175 of file sim.h.
References clock.
Member Function Documentation
void zesto_component::downtick_handler ()
Definition at line 1137 of file sim-zesto.cpp.
References cache_process_llc(), core_t::commit, Mop_t::commit, core_t::decode, Mop_t::decode, emergency_recovery(), core_t::exec, core_t::fetch, core_t::core_t::core_stat_t::final_sim_cycle, heartbeat_count, heartbeat_frequency, core_exec_t::LDST_exec(), mod2m(), modinc(), no_mcs, no_nodes, num_threads, Mop_t::oracle, core_t::oracle, prefetch_core_caches(), prefetch_LLC(), sim_cycle, start_pos, Mop_t::stat, core_t::stat, core_fetch_t::step(), step_core_PF_controllers(), step_LLC_PF_controller(), core_commit_t::update_occupancy(), core_exec_t::update_occupancy(), core_decode_t::update_occupancy(), core_fetch_t::update_occupancy(), and core_oracle_t::update_occupancy().
Referenced by zesto_component().
void zesto_component::uptick_handler ()
Definition at line 1131 of file sim-zesto.cpp.
Referenced by zesto_component().
Member Data Documentation
Clock* zesto_component::clock
Definition at line 171 of file sim.h.
Referenced by zesto_component(), and ~zesto_component().
The documentation for this class was generated from the following files:
sim.h
sim-zesto.cpp