dram_t Class Reference
#include <zesto-dram.h>
Public Member Functions
dram_t (void)
virtual ~dram_t (void)
virtual unsigned int access (const enum cache_command cmd, const md_paddr_t baddr, const int bsize)=0
virtual void refresh (void)
virtual void reg_stats (struct stat_sdb_t *const sdb)
Protected Member Functions
void init (void)
Protected Attributes
counter_t total_accesses
counter_t total_latency
int best_latency
int worst_latency
counter_t total_burst
Detailed Description
Definition at line 85 of file zesto-dram.h.
Constructor & Destructor Documentation
dram_t::dram_t (void)
Definition at line 110 of file zesto-dram.cpp.
References init().
dram_t::~dram_t (void) [virtual]
Definition at line 115 of file zesto-dram.cpp.
Member Function Documentation
virtual unsigned int dram_t::access (const enum cache_command cmd, const md_paddr_t baddr, const int bsize) [pure virtual]
void dram_t::init (void) [protected]
Definition at line 101 of file zesto-dram.cpp.
References best_latency, total_accesses, total_burst, total_latency, and worst_latency.
Referenced by dram_simplescalar_t::dram_simplescalar_t(), dram_simplesdram_t::dram_simplesdram_t(), and dram_t().
void dram_t::refresh (void) [virtual]
Definition at line 119 of file zesto-dram.cpp.
void dram_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Definition at line 123 of file zesto-dram.cpp.
References best_latency, stat_reg_counter, stat_reg_formula(), stat_reg_int(), total_accesses, total_burst, total_latency, and worst_latency.
Member Data Documentation
int dram_t::best_latency [protected]
Definition at line 90 of file zesto-dram.h.
Referenced by dram_simplescalar_t::dram_simplescalar_t(), dram_simplesdram_t::dram_simplesdram_t(), init(), and reg_stats().
counter_t dram_t::total_accesses [protected]
Definition at line 88 of file zesto-dram.h.
Referenced by init(), and reg_stats().
counter_t dram_t::total_burst [protected]
Definition at line 92 of file zesto-dram.h.
Referenced by init(), and reg_stats().
counter_t dram_t::total_latency [protected]
Definition at line 89 of file zesto-dram.h.
Referenced by init(), and reg_stats().
int dram_t::worst_latency [protected]
Definition at line 91 of file zesto-dram.h.
Referenced by init(), and reg_stats().
The documentation for this class was generated from the following files:
zesto-dram.h
zesto-dram.cpp