bpred_t Class Reference
#include <zesto-bpred.h>
Public Member Functions
bpred_t (int, char **, char *, char *, char *, char *)
~bpred_t ()
md_addr_t lookup (class bpred_state_cache_t *const scvp, const unsigned int opflags, const md_addr_t PC, const md_addr_t fallthruPC, const md_addr_t targetPC, const md_addr_t oraclePC, const bool outcome)
void update (class bpred_state_cache_t *const scvp, const unsigned int opflags, const md_addr_t PC, const md_addr_t targetPC, const md_addr_t oraclePC, const bool outcome)
void spec_update (class bpred_state_cache_t *const scvp, const unsigned int opflags, const md_addr_t PC, const md_addr_t targetPC, const md_addr_t oraclePC, const bool outcome)
void recover (class bpred_state_cache_t *const scvp, bool outcome)
void flush (class bpred_state_cache_t *const scvp)
void reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core)
void reset_stats ()
void freeze_stats ()
class bpred_state_cache_t * get_state_cache (void)
void return_state_cache (class bpred_state_cache_t *const)
Protected Attributes
unsigned int num_pred
class bpred_dir_t ** bpreds
class fusion_t * fusion
class RAS_t * ras
class BTB_t * dirjmp_BTB
class BTB_t * indirjmp_BTB
int bpredSCC_size
int bpredSCC_head
class bpred_state_cache_t ** bpredSCC
int SC_debt
counter_t num_lookups
counter_t num_updates
counter_t num_spec_updates
counter_t num_cond
counter_t num_call
counter_t num_ret
counter_t num_uncond
counter_t num_dir_hits
counter_t num_addr_hits
bool frozen
Private Member Functions
void init_state_cache_pool (int)
void destroy_state_cache_pool (void)
Detailed Description
Definition at line 82 of file zesto-bpred.h.
Constructor & Destructor Documentation
bpred_t::bpred_t (int arg_num_pred, char ** bpred_opts, char * fusion_opt, char * dirjmp_BTB_opt, char * indirjmp_BTB_opt, char * RAS_opt)
Definition at line 818 of file zesto-bpred.cpp.
References bpred_from_string(), bpreds, BTB_from_string(), dirjmp_BTB, fatal(), frozen, fusion, fusion_from_string(), indirjmp_BTB, init_state_cache_pool(), num_addr_hits, num_call, num_cond, num_dir_hits, num_lookups, num_pred, num_ret, num_spec_updates, num_uncond, num_updates, ras, and RAS_from_string().
bpred_t::~bpred_t ()
Definition at line 868 of file zesto-bpred.cpp.
References bpreds, destroy_state_cache_pool(), dirjmp_BTB, fusion, indirjmp_BTB, num_pred, and ras.
Member Function Documentation
void bpred_t::destroy_state_cache_pool (void) [private]
Definition at line 1298 of file zesto-bpred.cpp.
References bpreds, bpredSCC, bpredSCC_head, bpredSCC_size, bpred_state_cache_t::dirjmp, dirjmp_BTB, bpred_state_cache_t::fcache, fusion, bpred_state_cache_t::indirjmp, indirjmp_BTB, num_pred, bpred_state_cache_t::pcache, bpred_state_cache_t::preds, ras, bpred_state_cache_t::ras_checkpoint, fusion_t::ret_cache(), BTB_t::ret_cache(), RAS_t::ret_state(), and SC_debt.
Referenced by ~bpred_t().
void bpred_t::flush (class bpred_state_cache_t *const scvp)
Definition at line 1076 of file zesto-bpred.cpp.
References bpreds, bpred_state_cache_t::dirjmp, dirjmp_BTB, bpred_state_cache_t::fcache, BTB_t::flush(), fusion_t::flush(), fusion, bpred_state_cache_t::indirjmp, indirjmp_BTB, num_pred, bpred_state_cache_t::pcache, ras, bpred_state_cache_t::ras_checkpoint, and RAS_t::recover().
Referenced by core_oracle_t::complete_flush(), and core_oracle_t::recover().
void bpred_t::freeze_stats (void)
Definition at line 1182 of file zesto-bpred.cpp.
References bpreds, dirjmp_BTB, BTB_t::frozen, RAS_t::frozen, fusion_t::frozen, frozen, fusion, indirjmp_BTB, num_pred, and ras.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
class bpred_state_cache_t * bpred_t::get_state_cache (void)
Definition at line 1230 of file zesto-bpred.cpp.
References bpred_state_cache_t::bpred_state_cache_t(), bpreds, bpredSCC, bpredSCC_head, bpred_state_cache_t::dirjmp, dirjmp_BTB, fatal(), bpred_state_cache_t::fcache, fusion, BTB_t::get_cache(), fusion_t::get_cache(), bpred_dir_t::get_cache(), RAS_t::get_state(), bpred_state_cache_t::indirjmp, indirjmp_BTB, num_pred, bpred_state_cache_t::pcache, bpred_state_cache_t::preds, ras, bpred_state_cache_t::ras_checkpoint, and SC_debt.
Referenced by sim_fastfwd(), core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
void bpred_t::init_state_cache_pool (int start_size) [private]
Definition at line 1213 of file zesto-bpred.cpp.
References bpredSCC, bpredSCC_head, bpredSCC_size, and fatal().
Referenced by bpred_t().
md_addr_t bpred_t::lookup (class bpred_state_cache_t *const scvp, const unsigned int opflags, const md_addr_t PC, const md_addr_t fallthruPC, const md_addr_t targetPC, const md_addr_t oraclePC, const bool outcome)
Definition at line 895 of file zesto-bpred.cpp.
References BPRED_STAT, bpreds, bpred_state_cache_t::dirjmp, dirjmp_BTB, F_COND, F_INDIRJMP, bpred_state_cache_t::fcache, fusion, bpred_state_cache_t::indirjmp, indirjmp_BTB, BTB_t::lookup(), fusion_t::lookup(), bpred_dir_t::lookup(), MD_IS_CALL, MD_IS_RETURN, num_lookups, num_pred, bpred_state_cache_t::our_pred, bpred_state_cache_t::our_target, bpred_state_cache_t::pcache, RAS_t::pop(), bpred_state_cache_t::preds, RAS_t::push(), ras, bpred_state_cache_t::ras_checkpoint, and RAS_t::recover_state().
Referenced by sim_fastfwd(), core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
void bpred_t::recover (class bpred_state_cache_t *const scvp, bool outcome)
Definition at line 1054 of file zesto-bpred.cpp.
References bpreds, bpred_state_cache_t::dirjmp, dirjmp_BTB, bpred_state_cache_t::fcache, fusion, bpred_state_cache_t::indirjmp, indirjmp_BTB, num_pred, bpred_state_cache_t::pcache, ras, bpred_state_cache_t::ras_checkpoint, BTB_t::recover(), RAS_t::recover(), and fusion_t::recover().
Referenced by core_decode_STM_t::check_target(), core_decode_DPM_t::check_target(), core_oracle_t::pipe_recover(), sim_fastfwd(), and core_fetch_DPM_t::step().
void bpred_t::reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core)
Definition at line 1094 of file zesto-bpred.cpp.
References bpreds, core_t::current_thread, dirjmp_BTB, fusion, thread_t::id, indirjmp_BTB, num_addr_hits, num_call, num_cond, num_dir_hits, num_lookups, num_pred, num_ret, num_uncond, num_updates, ras, RAS_t::reg_stats(), BTB_t::reg_stats(), fusion_t::reg_stats(), stat_reg_counter, and stat_reg_formula().
Referenced by core_fetch_STM_t::reg_stats(), and core_fetch_DPM_t::reg_stats().
void bpred_t::reset_stats (void)
Definition at line 1160 of file zesto-bpred.cpp.
References bpreds, dirjmp_BTB, fusion, indirjmp_BTB, num_addr_hits, num_call, num_cond, num_dir_hits, num_lookups, num_pred, num_ret, num_spec_updates, num_uncond, num_updates, ras, BTB_t::reset_stats(), RAS_t::reset_stats(), and fusion_t::reset_stats().
Referenced by emergency_recovery(), and sim_fastfwd().
void bpred_t::return_state_cache (class bpred_state_cache_t * const sc)
Definition at line 1271 of file zesto-bpred.cpp.
References bpredSCC, bpredSCC_head, bpredSCC_size, and fatal().
Referenced by core_oracle_t::complete_flush(), core_oracle_t::recover(), sim_fastfwd(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
void bpred_t::spec_update (class bpred_state_cache_t *const scvp, const unsigned int opflags, const md_addr_t PC, const md_addr_t targetPC, const md_addr_t oraclePC, const bool outcome)
Definition at line 1021 of file zesto-bpred.cpp.
References BPRED_STAT, bpreds, bpred_state_cache_t::dirjmp, dirjmp_BTB, bpred_state_cache_t::fcache, fusion, bpred_state_cache_t::indirjmp, indirjmp_BTB, num_pred, num_spec_updates, bpred_state_cache_t::our_pred, bpred_state_cache_t::our_target, bpred_state_cache_t::pcache, bpred_state_cache_t::preds, BTB_t::spec_update(), and fusion_t::spec_update().
Referenced by core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
void bpred_t::update (class bpred_state_cache_t *const scvp, const unsigned int opflags, const md_addr_t PC, const md_addr_t targetPC, const md_addr_t oraclePC, const bool outcome)
Definition at line 964 of file zesto-bpred.cpp.
References BPRED_STAT, bpreds, bpred_state_cache_t::dirjmp, dirjmp_BTB, F_COND, F_INDIRJMP, bpred_state_cache_t::fcache, fusion, bpred_state_cache_t::indirjmp, indirjmp_BTB, MD_IS_CALL, MD_IS_RETURN, num_addr_hits, num_call, num_cond, num_dir_hits, RAS_t::num_hits, RAS_t::num_pops, num_pred, RAS_t::num_pushes, num_ret, num_uncond, num_updates, bpred_state_cache_t::our_pred, bpred_state_cache_t::our_target, bpred_state_cache_t::pcache, bpred_state_cache_t::preds, ras, BTB_t::update(), and fusion_t::update().
Referenced by sim_fastfwd(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
Member Data Documentation
class bpred_dir_t** bpred_t::bpreds [protected]
Definition at line 87 of file zesto-bpred.h.
Referenced by bpred_t(), destroy_state_cache_pool(), flush(), freeze_stats(), get_state_cache(), lookup(), recover(), reg_stats(), reset_stats(), spec_update(), update(), and ~bpred_t().
class bpred_state_cache_t** bpred_t::bpredSCC [protected]
Definition at line 97 of file zesto-bpred.h.
Referenced by destroy_state_cache_pool(), get_state_cache(), init_state_cache_pool(), and return_state_cache().
int bpred_t::bpredSCC_head [protected]
Definition at line 96 of file zesto-bpred.h.
Referenced by destroy_state_cache_pool(), get_state_cache(), init_state_cache_pool(), and return_state_cache().
int bpred_t::bpredSCC_size [protected]
Definition at line 95 of file zesto-bpred.h.
Referenced by destroy_state_cache_pool(), init_state_cache_pool(), and return_state_cache().
class BTB_t* bpred_t::dirjmp_BTB [protected]
Definition at line 91 of file zesto-bpred.h.
Referenced by bpred_t(), destroy_state_cache_pool(), flush(), freeze_stats(), get_state_cache(), lookup(), recover(), reg_stats(), reset_stats(), spec_update(), update(), and ~bpred_t().
bool bpred_t::frozen [protected]
Definition at line 110 of file zesto-bpred.h.
Referenced by bpred_t(), and freeze_stats().
class fusion_t* bpred_t::fusion [protected]
Definition at line 88 of file zesto-bpred.h.
Referenced by bpred_t(), destroy_state_cache_pool(), flush(), freeze_stats(), get_state_cache(), lookup(), recover(), reg_stats(), reset_stats(), spec_update(), update(), and ~bpred_t().
class BTB_t* bpred_t::indirjmp_BTB [protected]
Definition at line 92 of file zesto-bpred.h.
Referenced by bpred_t(), destroy_state_cache_pool(), flush(), freeze_stats(), get_state_cache(), lookup(), recover(), reg_stats(), reset_stats(), spec_update(), update(), and ~bpred_t().
counter_t bpred_t::num_addr_hits [protected]
Definition at line 109 of file zesto-bpred.h.
Referenced by bpred_t(), reg_stats(), reset_stats(), and update().
counter_t bpred_t::num_call [protected]
Definition at line 105 of file zesto-bpred.h.
Referenced by bpred_t(), reg_stats(), reset_stats(), and update().
counter_t bpred_t::num_cond [protected]
Definition at line 104 of file zesto-bpred.h.
Referenced by bpred_t(), reg_stats(), reset_stats(), and update().
counter_t bpred_t::num_dir_hits [protected]
Definition at line 108 of file zesto-bpred.h.
Referenced by bpred_t(), reg_stats(), reset_stats(), and update().
counter_t bpred_t::num_lookups [protected]
Definition at line 101 of file zesto-bpred.h.
Referenced by bpred_t(), lookup(), reg_stats(), and reset_stats().
unsigned int bpred_t::num_pred [protected]
Definition at line 86 of file zesto-bpred.h.
Referenced by bpred_t(), destroy_state_cache_pool(), flush(), freeze_stats(), get_state_cache(), lookup(), recover(), reg_stats(), reset_stats(), spec_update(), update(), and ~bpred_t().
counter_t bpred_t::num_ret [protected]
Definition at line 106 of file zesto-bpred.h.
Referenced by bpred_t(), reg_stats(), reset_stats(), and update().
counter_t bpred_t::num_spec_updates [protected]
Definition at line 103 of file zesto-bpred.h.
Referenced by bpred_t(), reset_stats(), and spec_update().
counter_t bpred_t::num_uncond [protected]
Definition at line 107 of file zesto-bpred.h.
Referenced by bpred_t(), reg_stats(), reset_stats(), and update().
counter_t bpred_t::num_updates [protected]
Definition at line 102 of file zesto-bpred.h.
Referenced by bpred_t(), reg_stats(), reset_stats(), and update().
class RAS_t* bpred_t::ras [protected]
Definition at line 90 of file zesto-bpred.h.
Referenced by bpred_t(), destroy_state_cache_pool(), flush(), freeze_stats(), get_state_cache(), lookup(), recover(), reg_stats(), reset_stats(), update(), and ~bpred_t().
int bpred_t::SC_debt [protected]
Definition at line 98 of file zesto-bpred.h.
Referenced by destroy_state_cache_pool(), and get_state_cache().
The documentation for this class was generated from the following files:
zesto-bpred.h
zesto-bpred.cpp