GenericSink Class Reference
#include <genericSink.h>
Public Member Functions
GenericSink ()
void setup (uint v, uint time, uint no_nodes)
void process_event (IrisEvent *e)
string toString () const
Public Attributes
ofstream out_file
uint address
vector< bool > ready
unsigned int packets
bool sending
Private Member Functions
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_outpull_event (IrisEvent *e)
Private Attributes
deque< HighLevelPacket * > out_packets
string out_filename
uint last_vc
uint no_nodes
uint vcs
uint max_sim_time
Detailed Description
Definition at line 37 of file genericSink.h.
Constructor & Destructor Documentation
GenericSink::GenericSink ()
Definition at line 33 of file genericSink.cc.
References NetworkComponent::name, and out_filename.
Member Function Documentation
void GenericSink::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 92 of file genericSink.cc.
References IrisEvent::event_data, Processor::interface_connections, Simulator::Now(), out_file, NetworkComponent::process_event(), READY_EVENT, Simulator::Schedule(), HighLevelPacket::sent_time, HighLevelPacket::toString(), VirtualChannelDescription::vc, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void GenericSink::handle_outpull_event (IrisEvent * e) [private]
Definition at line 115 of file genericSink.cc.
References _DBG, address, HighLevelPacket::destination, Processor::interface_connections, last_vc, NEW_PACKET_EVENT, no_nodes, NetworkComponent::node_ip, Simulator::Now(), out_file, packets, NetworkComponent::process_event(), ready, Simulator::Schedule(), sending, HighLevelPacket::sent_time, HighLevelPacket::source, HighLevelPacket::toString(), HighLevelPacket::transaction_id, and HighLevelPacket::virtual_channel.
Referenced by process_event().
void GenericSink::handle_ready_event (IrisEvent * e) [private]
Definition at line 177 of file genericSink.cc.
References IrisEvent::event_data, Simulator::Now(), OUT_PULL_EVENT, NetworkComponent::process_event(), ready, Simulator::Schedule(), sending, IrisEvent::vc, and VirtualChannelDescription::vc.
Referenced by process_event().
void GenericSink::process_event (IrisEvent * e) [virtual]
Implements Processor .
Definition at line 70 of file genericSink.cc.
References handle_new_packet_event(), handle_outpull_event(), handle_ready_event(), NEW_PACKET_EVENT, OUT_PULL_EVENT, READY_EVENT, and IrisEvent::type.
void GenericSink::setup (uint v, uint time, uint no_nodes) [virtual]
Implements Processor .
Definition at line 40 of file genericSink.cc.
References address, IrisEvent::event_data, Processor::interface_connections, max_sim_time, Component::myId(), no_nodes, Simulator::Now(), out_file, out_filename, ready, READY_EVENT, Simulator::Schedule(), IrisEvent::type, VirtualChannelDescription::vc, and vcs.
string GenericSink::toString () const [virtual]
Reimplemented from Processor .
Definition at line 199 of file genericSink.cc.
References address, and out_filename.
Member Data Documentation
uint GenericSink::address
Reimplemented from NetworkComponent .
Definition at line 45 of file genericSink.h.
Referenced by handle_outpull_event(), setup(), and toString().
uint GenericSink::last_vc [private]
Definition at line 55 of file genericSink.h.
Referenced by handle_outpull_event().
uint GenericSink::max_sim_time [private]
Definition at line 58 of file genericSink.h.
Referenced by setup().
uint GenericSink::no_nodes [private]
Definition at line 56 of file genericSink.h.
Referenced by handle_outpull_event(), and setup().
ofstream GenericSink::out_file
Definition at line 44 of file genericSink.h.
Referenced by handle_new_packet_event(), handle_outpull_event(), and setup().
string GenericSink::out_filename [private]
Definition at line 54 of file genericSink.h.
Referenced by GenericSink(), setup(), and toString().
deque<HighLevelPacket*> GenericSink::out_packets [private]
Definition at line 53 of file genericSink.h.
unsigned int GenericSink::packets
Definition at line 47 of file genericSink.h.
Referenced by handle_outpull_event().
vector<bool> GenericSink::ready
Definition at line 46 of file genericSink.h.
Referenced by handle_outpull_event(), handle_ready_event(), and setup().
bool GenericSink::sending
Definition at line 48 of file genericSink.h.
Referenced by handle_outpull_event(), and handle_ready_event().
uint GenericSink::vcs [private]
Definition at line 57 of file genericSink.h.
Referenced by setup().
The documentation for this class was generated from the following files:
genericSink.h
genericSink.cc