GenericFlatMc Class Reference
#include <genericFlatMc.h>
Public Member Functions
GenericFlatMc ()
~GenericFlatMc ()
void setup (uint no_nodes, uint vcs, uint max_sim_time)
void finish ()
void process_event (IrisEvent *e)
string toString () const
string print_stats () const
void set_output_path (string outpath)
Public Attributes
unsigned int packets
double min_pkt_latency
unsigned long long int waiting_at_injection
unsigned long long int max_time
vector< uint > mc_node_ip
HighLevelPacket * outstanding_hlp
Private Member Functions
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void handle_out_pull_event (IrisEvent *e)
void convertFromBitStream (Request *req, HighLevelPacket *hlp)
Private Attributes
uint vcs
uint no_nodes
unsigned long long int max_sim_time
deque< HighLevelPacket > out_packets
string out_filename
ofstream out_file
vector< bool > ready
bool sending
long int packets_pending
deque< unsigned long long int > pending_packets_time
deque< HighLevelPacket * > pending_packets
Detailed Description
Definition at line 21 of file genericFlatMc.h.
Constructor & Destructor Documentation
GenericFlatMc::GenericFlatMc ()
Definition at line 8 of file genericFlatMc.cc.
References Processor::interface_connections, NetworkComponent::name, and sending.
GenericFlatMc::~GenericFlatMc ()
Definition at line 15 of file genericFlatMc.cc.
References out_file, pending_packets, and pending_packets_time.
Member Function Documentation
void GenericFlatMc::convertFromBitStream (Request * req, HighLevelPacket * hlp) [private]
Definition at line 316 of file genericFlatMc.cc.
References Request::address, Request::cmdType, HighLevelPacket::data, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, and Request::threadId.
Referenced by handle_new_packet_event().
void GenericFlatMc::finish ()
Definition at line 67 of file genericFlatMc.cc.
void GenericFlatMc::handle_new_packet_event (IrisEvent * e) [private]
Definition at line 93 of file genericFlatMc.cc.
References CACHE_WRITEBACK, Request::cmdType, convertFromBitStream(), IrisEvent::event_data, Processor::interface_connections, min_pkt_latency, MSHR_SIZE, Simulator::Now(), out_file, out_filename, OUT_PULL_EVENT, outstanding_hlp, packets_pending, pending_packets, NetworkComponent::process_event(), READY_EVENT, Simulator::Schedule(), sending, HighLevelPacket::sent_time, HighLevelPacket::toString(), IrisEvent::type, and IrisEvent::vc.
Referenced by process_event().
void GenericFlatMc::handle_out_pull_event (IrisEvent * e) [private]
Definition at line 188 of file genericFlatMc.cc.
References NetworkComponent::address, HighLevelPacket::data, HighLevelPacket::data_payload_length, HighLevelPacket::destination, Processor::interface_connections, max_phy_link_bits, HighLevelPacket::msg_class, NEW_PACKET_EVENT, Simulator::Now(), OUT_PULL_EVENT, packets, packets_pending, pending_packets, NetworkComponent::process_event(), ready, RESPONSE_PKT, Simulator::Schedule(), sending, HighLevelPacket::sent_time, HighLevelPacket::source, HighLevelPacket::stat_memory_serviced_time, HighLevelPacket::transaction_id, HighLevelPacket::virtual_channel, waiting_at_injection, and HighLevelPacket::waiting_in_ni.
Referenced by process_event().
void GenericFlatMc::handle_ready_event (IrisEvent * e) [private]
Definition at line 270 of file genericFlatMc.cc.
References _DBG_NOARG, max_sim_time, MSHR_SIZE, NEW_PACKET_EVENT, Simulator::Now(), OUT_PULL_EVENT, outstanding_hlp, packets_pending, NetworkComponent::process_event(), ready, Simulator::Schedule(), and sending.
Referenced by process_event().
string GenericFlatMc::print_stats (void) const [virtual]
Implements Processor .
Definition at line 345 of file genericFlatMc.cc.
References min_pkt_latency, NetworkComponent::node_ip, packets, and waiting_at_injection.
void GenericFlatMc::process_event (IrisEvent * e) [virtual]
Implements Processor .
Definition at line 72 of file genericFlatMc.cc.
References NetworkComponent::address, handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), NEW_PACKET_EVENT, OUT_PULL_EVENT, READY_EVENT, and IrisEvent::type.
void GenericFlatMc::set_output_path (string outpath) [virtual]
Implements Processor .
Definition at line 53 of file genericFlatMc.cc.
References NetworkComponent::address, out_file, and out_filename.
void GenericFlatMc::setup (uint no_nodes, uint vcs, uint max_sim_time) [virtual]
Implements Processor .
Definition at line 24 of file genericFlatMc.cc.
References NetworkComponent::address, max_sim_time, min_pkt_latency, Component::myId(), no_nodes, Simulator::Now(), packets, packets_pending, NetworkComponent::process_event(), ready, READY_EVENT, Simulator::Schedule(), and vcs.
string GenericFlatMc::toString () const [virtual]
Reimplemented from Processor .
Definition at line 304 of file genericFlatMc.cc.
References NetworkComponent::address, NetworkComponent::node_ip, and ready.
Member Data Documentation
unsigned long long int GenericFlatMc::max_sim_time [private]
Definition at line 27 of file genericFlatMc.h.
Referenced by handle_ready_event(), and setup().
unsigned long long int GenericFlatMc::max_time
Definition at line 50 of file genericFlatMc.h.
vector<uint> GenericFlatMc::mc_node_ip
Definition at line 57 of file genericFlatMc.h.
double GenericFlatMc::min_pkt_latency
Definition at line 47 of file genericFlatMc.h.
Referenced by handle_new_packet_event(), print_stats(), and setup().
uint GenericFlatMc::no_nodes [private]
Definition at line 26 of file genericFlatMc.h.
Referenced by setup().
ofstream GenericFlatMc::out_file [private]
Definition at line 30 of file genericFlatMc.h.
Referenced by handle_new_packet_event(), set_output_path(), and ~GenericFlatMc().
string GenericFlatMc::out_filename [private]
Definition at line 29 of file genericFlatMc.h.
Referenced by handle_new_packet_event(), and set_output_path().
deque< HighLevelPacket > GenericFlatMc::out_packets [private]
Definition at line 28 of file genericFlatMc.h.
HighLevelPacket* GenericFlatMc::outstanding_hlp
Definition at line 58 of file genericFlatMc.h.
Referenced by handle_new_packet_event(), and handle_ready_event().
unsigned int GenericFlatMc::packets
Definition at line 46 of file genericFlatMc.h.
Referenced by handle_out_pull_event(), print_stats(), and setup().
long int GenericFlatMc::packets_pending [private]
Definition at line 37 of file genericFlatMc.h.
Referenced by handle_new_packet_event(), handle_out_pull_event(), handle_ready_event(), and setup().
deque<HighLevelPacket*> GenericFlatMc::pending_packets [private]
Definition at line 39 of file genericFlatMc.h.
Referenced by handle_new_packet_event(), handle_out_pull_event(), and ~GenericFlatMc().
deque<unsigned long long int> GenericFlatMc::pending_packets_time [private]
Definition at line 38 of file genericFlatMc.h.
Referenced by ~GenericFlatMc().
vector< bool > GenericFlatMc::ready [private]
Definition at line 31 of file genericFlatMc.h.
Referenced by handle_out_pull_event(), handle_ready_event(), setup(), and toString().
bool GenericFlatMc::sending [private]
Definition at line 32 of file genericFlatMc.h.
Referenced by GenericFlatMc(), handle_new_packet_event(), handle_out_pull_event(), and handle_ready_event().
uint GenericFlatMc::vcs [private]
Definition at line 25 of file genericFlatMc.h.
Referenced by setup().
unsigned long long int GenericFlatMc::waiting_at_injection
Definition at line 48 of file genericFlatMc.h.
Referenced by handle_out_pull_event(), and print_stats().
The documentation for this class was generated from the following files:
genericFlatMc.h
genericFlatMc.cc