ResponseHandler Class Reference
#include <response_handler.h>
Public Member Functions
ResponseHandler ()
~ResponseHandler ()
bool IsBufferFull ()
bool CanStart ()
unsigned int SearchBuffer (DRAMCmdState *cmd)
unsigned int SendServiced ()
void process_event (IrisEvent *e)
std::string toString ()
Public Attributes
Component * mc
Component * parent
Component * child
vector< Request > responseBuffer
bool bufferFull
vector< bool > serviced
Component * reqPtr
bool stoppedQueue
Private Attributes
bool out_pull_scheduled
Detailed Description
Definition at line 47 of file response_handler.h.
Constructor & Destructor Documentation
ResponseHandler::ResponseHandler ()
Definition at line 33 of file response_handler.cc.
References bufferFull, RESPONSE_BUFFER_SIZE, responseBuffer, serviced, and stoppedQueue.
ResponseHandler::~ResponseHandler ()
Definition at line 52 of file response_handler.cc.
Member Function Documentation
bool ResponseHandler::CanStart ()
Definition at line 203 of file response_handler.cc.
References RESPONSE_BUFFER_SIZE, and responseBuffer.
bool ResponseHandler::IsBufferFull ()
Definition at line 189 of file response_handler.cc.
References bufferFull, RESPONSE_BUFFER_SIZE, and responseBuffer.
void ResponseHandler::process_event (IrisEvent * e)
Definition at line 64 of file response_handler.cc.
References Request::address, Request::arrivalTime, Request::busInsertionTime, Request::cmdType, IrisEvent::dst, IrisEvent::event_data, mc, MSHR_DELETE, mshrHandler, Simulator::Now(), OUT_PULL_EVENT, parent, NI::process_event(), MSHR_SA_H::process_event(), PUSH_BUFFER, REPLY, DRAMCmdState::req, responseBuffer, Request::retireTime, Simulator::Schedule(), SearchBuffer(), SEND_TO_NI, SendServiced(), serviced, Request::tag, Request::threadId, and IrisEvent::type.
Referenced by NI::handle_out_pull_event(), DataBusHandler::process_event(), and BankHandler::process_event().
unsigned int ResponseHandler::SearchBuffer (DRAMCmdState * cmd)
Definition at line 176 of file response_handler.cc.
References DRAMCmdState::req, responseBuffer, and Request::tag.
Referenced by process_event().
unsigned int ResponseHandler::SendServiced ()
Definition at line 163 of file response_handler.cc.
References responseBuffer, and serviced.
Referenced by process_event().
std::string ResponseHandler::toString ()
Definition at line 211 of file response_handler.cc.
Member Data Documentation
bool ResponseHandler::bufferFull
Definition at line 56 of file response_handler.h.
Referenced by IsBufferFull(), and ResponseHandler().
Component* ResponseHandler::child
Definition at line 54 of file response_handler.h.
Referenced by MC::Init().
Component* ResponseHandler::mc
Definition at line 52 of file response_handler.h.
Referenced by MC::Init(), and process_event().
bool ResponseHandler::out_pull_scheduled [private]
Definition at line 70 of file response_handler.h.
Component* ResponseHandler::parent
Definition at line 53 of file response_handler.h.
Referenced by MC::Init(), and process_event().
Component* ResponseHandler::reqPtr
Definition at line 59 of file response_handler.h.
Referenced by MC::Init().
vector<Request> ResponseHandler::responseBuffer
Definition at line 55 of file response_handler.h.
Referenced by CanStart(), IsBufferFull(), process_event(), ResponseHandler(), SearchBuffer(), and SendServiced().
vector<bool> ResponseHandler::serviced
Definition at line 57 of file response_handler.h.
Referenced by process_event(), ResponseHandler(), and SendServiced().
bool ResponseHandler::stoppedQueue
Definition at line 60 of file response_handler.h.
Referenced by ResponseHandler().
The documentation for this class was generated from the following files:
response_handler.h
response_handler.cc