memdep_t Class Reference
#include <zesto-memdep.h>
Public Member Functions
memdep_t ()
virtual ~memdep_t ()
virtual int lookup (const md_addr_t PC, const bool sta_unknown, const bool conflict_exists, const bool partial_match)=0
virtual void update (const md_addr_t PC)
virtual void reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core)
void freeze_stats (void)
Protected Member Functions
void init (void)
Protected Attributes
char * name
char * type
int bits
counter_t lookups
counter_t updates
bool frozen
Detailed Description
Definition at line 83 of file zesto-memdep.h.
Constructor & Destructor Documentation
memdep_t::memdep_t ()
Definition at line 93 of file zesto-memdep.cpp.
References fatal(), init(), name, and type.
memdep_t::~memdep_t () [virtual]
Definition at line 102 of file zesto-memdep.cpp.
References name, and type.
Member Function Documentation
void memdep_t::freeze_stats (void)
Definition at line 139 of file zesto-memdep.cpp.
References frozen.
Referenced by core_exec_DPM_t::freeze_stats().
void memdep_t::init (void) [protected]
Definition at line 85 of file zesto-memdep.cpp.
References bits, frozen, lookups, and updates.
Referenced by memdep_blind_t::memdep_blind_t(), memdep_lwt_t::memdep_lwt_t(), memdep_none_t::memdep_none_t(), memdep_oracle_t::memdep_oracle_t(), and memdep_t().
virtual int memdep_t::lookup (const md_addr_t PC, const bool sta_unknown, const bool conflict_exists, const bool partial_match) [pure virtual]
Referenced by core_exec_DPM_t::check_load_issue_conditions().
void memdep_t::reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core) [virtual]
Definition at line 114 of file zesto-memdep.cpp.
References bits, core_t::current_thread, thread_t::id, lookups, name, stat_reg_counter, stat_reg_formula(), stat_reg_int(), stat_reg_string(), type, and updates.
Referenced by core_exec_DPM_t::reg_stats().
void memdep_t::update (const md_addr_t PC) [virtual]
Definition at line 109 of file zesto-memdep.cpp.
References MEMDEP_STAT, and updates.
Referenced by core_exec_DPM_t::ALU_exec(), and core_exec_DPM_t::LDST_exec().
Member Data Documentation
int memdep_t::bits [protected]
Definition at line 88 of file zesto-memdep.h.
Referenced by init(), memdep_lwt_t::memdep_lwt_t(), and reg_stats().
bool memdep_t::frozen [protected]
Definition at line 91 of file zesto-memdep.h.
Referenced by freeze_stats(), and init().
counter_t memdep_t::lookups [protected]
Definition at line 89 of file zesto-memdep.h.
Referenced by init(), and reg_stats().
char* memdep_t::name [protected]
Definition at line 86 of file zesto-memdep.h.
Referenced by memdep_blind_t::memdep_blind_t(), memdep_create(), memdep_lwt_t::memdep_lwt_t(), memdep_none_t::memdep_none_t(), memdep_oracle_t::memdep_oracle_t(), memdep_t(), reg_stats(), and ~memdep_t().
char* memdep_t::type [protected]
Definition at line 87 of file zesto-memdep.h.
Referenced by memdep_blind_t::memdep_blind_t(), memdep_create(), memdep_lwt_t::memdep_lwt_t(), memdep_none_t::memdep_none_t(), memdep_oracle_t::memdep_oracle_t(), memdep_t(), reg_stats(), and ~memdep_t().
counter_t memdep_t::updates [protected]
Definition at line 90 of file zesto-memdep.h.
Referenced by init(), reg_stats(), and update().
The documentation for this class was generated from the following files:
zesto-memdep.h
zesto-memdep.cpp