core_exec_t Class Reference
#include <zesto-exec.h>
Public Member Functions
core_exec_t (void)
virtual ~core_exec_t ()
virtual void reg_stats (struct stat_sdb_t *const sdb)=0
virtual void freeze_stats (void)=0
virtual void update_occupancy (void)=0
void update_last_completed (tick_t now)
virtual void ALU_exec (void)=0
virtual void LDST_exec (void)=0
virtual void RS_schedule (void)=0
virtual void LDQ_schedule (void)=0
virtual void recover (const struct Mop_t *const Mop)=0
virtual void recover (void)=0
virtual void insert_ready_uop (struct uop_t *const uop)=0
virtual bool RS_available (void)=0
virtual void RS_insert (struct uop_t *const uop)=0
virtual void RS_fuse_insert (struct uop_t *const uop)=0
virtual void RS_deallocate (struct uop_t *const uop)=0
virtual bool LDQ_available (void)=0
virtual void LDQ_insert (struct uop_t *const uop)=0
virtual void LDQ_deallocate (struct uop_t *const uop)=0
virtual void LDQ_squash (struct uop_t *const dead_uop)=0
virtual bool STQ_available (void)=0
virtual void STQ_insert_sta (struct uop_t *const uop)=0
virtual void STQ_insert_std (struct uop_t *const uop)=0
virtual void STQ_deallocate_sta (void)=0
virtual bool STQ_deallocate_std (struct uop_t *const uop)=0
virtual void STQ_deallocate_senior (void)=0
virtual void STQ_squash_sta (struct uop_t *const dead_uop)=0
virtual void STQ_squash_std (struct uop_t *const dead_uop)=0
virtual void STQ_squash_senior (void)=0
virtual void recover_check_assertions (void)=0
Public Attributes
tick_t last_completed
counter_t last_completed_count
Protected Attributes
struct core_t * core
Detailed Description
Definition at line 78 of file zesto-exec.h.
Constructor & Destructor Documentation
core_exec_t::core_exec_t (void)
Definition at line 275 of file zesto-exec.cpp.
core_exec_t::~core_exec_t () [virtual]
Definition at line 281 of file zesto-exec.cpp.
Member Function Documentation
virtual void core_exec_t::ALU_exec (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
virtual void core_exec_t::freeze_stats (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
virtual void core_exec_t::insert_ready_uop (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual bool core_exec_t::LDQ_available (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_exec_t::LDQ_deallocate (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
virtual void core_exec_t::LDQ_insert (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_exec_t::LDQ_schedule (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
virtual void core_exec_t::LDQ_squash (struct uop_t *const dead_uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::recover(), and core_commit_DPM_t::recover().
virtual void core_exec_t::LDST_exec (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by zesto_component::downtick_handler().
virtual void core_exec_t::recover (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
virtual void core_exec_t::recover (const struct Mop_t *const Mop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by emergency_recovery(), core_oracle_t::pipe_recover(), core_oracle_t::reset_execution(), core_fetch_DPM_t::step(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
virtual void core_exec_t::recover_check_assertions (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::recover(), and core_commit_DPM_t::recover().
virtual void core_exec_t::reg_stats (struct stat_sdb_t *const sdb) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
virtual bool core_exec_t::RS_available (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_exec_t::RS_deallocate (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_exec_STM_t::ALU_exec(), core_commit_STM_t::recover(), and core_commit_DPM_t::recover().
virtual void core_exec_t::RS_fuse_insert (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_DPM_t::step().
virtual void core_exec_t::RS_insert (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_exec_t::RS_schedule (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
virtual bool core_exec_t::STQ_available (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_exec_t::STQ_deallocate_senior (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_DPM_t::step().
virtual void core_exec_t::STQ_deallocate_sta (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
virtual bool core_exec_t::STQ_deallocate_std (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
virtual void core_exec_t::STQ_insert_sta (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_exec_t::STQ_insert_std (struct uop_t *const uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_exec_t::STQ_squash_senior (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_DPM_t::recover().
virtual void core_exec_t::STQ_squash_sta (struct uop_t *const dead_uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::recover(), and core_commit_DPM_t::recover().
virtual void core_exec_t::STQ_squash_std (struct uop_t *const dead_uop) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by core_commit_STM_t::recover(), and core_commit_DPM_t::recover().
void core_exec_t::update_last_completed (tick_t now)
Definition at line 286 of file zesto-exec.cpp.
References last_completed.
virtual void core_exec_t::update_occupancy (void) [pure virtual]
Implemented in core_exec_DPM_t , and core_exec_STM_t .
Referenced by zesto_component::downtick_handler().
Member Data Documentation
struct core_t* core_exec_t::core [read, protected]
Definition at line 156 of file zesto-exec.h.
Referenced by core_exec_STM_t::ALU_exec(), core_exec_DPM_t::ALU_exec(), core_exec_STM_t::check_load_issue_conditions(), core_exec_DPM_t::check_load_issue_conditions(), core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_exec_STM_t::DL1_callback(), core_exec_STM_t::DTLB_callback(), core_exec_DPM_t::DTLB_callback(), core_exec_STM_t::insert_ready_uop(), core_exec_DPM_t::insert_ready_uop(), core_exec_STM_t::LDQ_available(), core_exec_DPM_t::LDQ_available(), core_exec_STM_t::LDQ_deallocate(), core_exec_DPM_t::LDQ_deallocate(), core_exec_STM_t::LDQ_insert(), core_exec_DPM_t::LDQ_insert(), core_exec_STM_t::LDQ_schedule(), core_exec_DPM_t::LDQ_schedule(), core_exec_STM_t::LDQ_squash(), core_exec_DPM_t::LDQ_squash(), core_exec_STM_t::LDST_exec(), core_exec_DPM_t::LDST_exec(), core_exec_DPM_t::load_miss_reschedule(), core_exec_STM_t::load_writeback(), core_exec_DPM_t::load_writeback(), core_exec_STM_t::reg_stats(), core_exec_DPM_t::reg_stats(), core_exec_STM_t::RS_available(), core_exec_DPM_t::RS_available(), core_exec_STM_t::RS_deallocate(), core_exec_DPM_t::RS_deallocate(), core_exec_STM_t::RS_insert(), core_exec_DPM_t::RS_insert(), core_exec_STM_t::RS_schedule(), core_exec_DPM_t::RS_schedule(), core_exec_DPM_t::snatch_back(), core_exec_STM_t::store_dl1_callback(), core_exec_DPM_t::store_dl1_callback(), core_exec_DPM_t::store_dl1_split_callback(), core_exec_STM_t::store_dtlb_callback(), core_exec_DPM_t::store_dtlb_callback(), core_exec_DPM_t::store_translated_callback(), core_exec_STM_t::STQ_available(), core_exec_DPM_t::STQ_available(), core_exec_DPM_t::STQ_deallocate_senior(), core_exec_STM_t::STQ_deallocate_std(), core_exec_DPM_t::STQ_deallocate_std(), core_exec_STM_t::STQ_insert_sta(), core_exec_DPM_t::STQ_insert_sta(), core_exec_STM_t::STQ_insert_std(), core_exec_DPM_t::STQ_insert_std(), core_exec_DPM_t::STQ_squash_senior(), core_exec_STM_t::STQ_squash_sta(), core_exec_DPM_t::STQ_squash_sta(), core_exec_STM_t::STQ_squash_std(), core_exec_DPM_t::STQ_squash_std(), core_exec_STM_t::update_occupancy(), and core_exec_DPM_t::update_occupancy().
tick_t core_exec_t::last_completed
Definition at line 83 of file zesto-exec.h.
Referenced by core_exec_STM_t::ALU_exec(), core_exec_DPM_t::ALU_exec(), core_exec_STM_t::LDST_exec(), core_exec_DPM_t::LDST_exec(), core_exec_STM_t::load_writeback(), core_exec_DPM_t::load_writeback(), core_commit_STM_t::step(), core_commit_DPM_t::step(), and update_last_completed().
counter_t core_exec_t::last_completed_count
Definition at line 84 of file zesto-exec.h.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
The documentation for this class was generated from the following files:
zesto-exec.h
zesto-exec.cpp