CmdIssuer Class Reference
#include <cmd_issuer.h>
Public Member Functions
CmdIssuer ()
~CmdIssuer ()
void process_event (IrisEvent *e)
bool HasWork ()
std::string toString ()
bool IssueCmd (bool *isWrite, DRAMCmdState *scheduledCmd)
bool BankNotBusy (DRAMCmdState currentCmd)
bool BanksFirstReq (DRAMCmdState currentCmd, unsigned int index)
bool BusNotBusy (DRAMCmdState currentCmd)
bool CanSchedule (DRAMCmdState currentCmd, DRAMCmdState prevCmd)
void SetBusBusyTime (DRAMCmdState currentCmd)
Time CmdDelay (DRAMCmd cmd)
Time CalculateDataDelay (DRAMCmdState cmdS)
Time CalculateBurstL (DRAMCmdState prevCmd)
Time CalculateBusyTime (DRAMCmd curCmd, DRAMCmd prevCmd, RankBankComb rankC, RankBankComb bankC, Time prevBurstL)
void SetPrevState (DRAMCmdState currentCmd)
Time Max (Time t1, Time t2)
Public Attributes
Component * parent
DataBusHandler * dataBus
CmdBusHandler * cmdBus
short Id
short bufferId
ChannelState prevState
Time busBusy
bool generated_start_event
DRAMCmd prevBusCmd
Detailed Description
Definition at line 114 of file cmd_issuer.h.
Constructor & Destructor Documentation
CmdIssuer::CmdIssuer ()
Definition at line 27 of file cmd_issuer.cc.
References busBusy, ChannelState::cmd, generated_start_event, NO_OF_BANKS, NO_OF_RANKS, NORMAL, PRECHARGE, ChannelState::prevCmdBank, ChannelState::prevCmdRank, ChannelState::prevCmdTime, prevState, and DRAMCmdState::set().
CmdIssuer::~CmdIssuer ()
Definition at line 46 of file cmd_issuer.cc.
Member Function Documentation
bool CmdIssuer::BankNotBusy (DRAMCmdState currentCmd)
Definition at line 244 of file cmd_issuer.cc.
References ALL_BANK_REFRESH, Request::bankNo, CalculateBurstL(), CalculateBusyTime(), ChannelState::cmd, DRAMCmdState::cmd, NO_OF_BANKS, Simulator::Now(), prevState, ChannelState::rank, Request::rankNo, DRAMCmdState::req, and SAME.
Referenced by IssueCmd().
bool CmdIssuer::BanksFirstReq (DRAMCmdState currentCmd, unsigned int index)
Definition at line 233 of file cmd_issuer.cc.
References Request::bankNo, bufferId, BusHandler::cmdQueue, parent, and DRAMCmdState::req.
Referenced by IssueCmd().
bool CmdIssuer::BusNotBusy (DRAMCmdState currentCmd)
Definition at line 197 of file cmd_issuer.cc.
References busBusy, DRAMCmdState::cmd, Simulator::Now(), prevBusCmd, READ, t_CMD, and WRITE.
Referenced by IssueCmd().
Time CmdIssuer::CalculateBurstL (DRAMCmdState prevCmd)
Definition at line 334 of file cmd_issuer.cc.
References DRAMCmdState::burst, BUS_CYCLE, DDR_BUS_WIDTH, PREFETCH_SIZE, PREFETCHL, READ_SIZE, READL, WRITE_SIZE, WRITEBACK_SIZE, WRITEBACKL, and WRITEL.
Referenced by BankNotBusy(), CanSchedule(), and SetBusBusyTime().
Time CmdIssuer::CalculateBusyTime (DRAMCmd curCmd, DRAMCmd prevCmd, RankBankComb rankC, RankBankComb bankC, Time prevBurstL)
Definition at line 357 of file cmd_issuer.cc.
References ACTIVATE, ALL_BANK_REFRESH, CLOSE_PAGE_POLICY, DIFF, dram_page_policy, Max(), OPEN_PAGE_POLICY, PRECHARGE, READ, SAME, t_AL, t_CAS, t_CCD, t_CMD, t_CWD, t_OST, t_RAS, t_RCD, t_RFC, t_RP, t_RRD, t_RTP, t_RTRS, t_WR, t_WTR, and WRITE.
Referenced by BankNotBusy(), and CanSchedule().
Time CmdIssuer::CalculateDataDelay (DRAMCmdState cmdS)
Definition at line 297 of file cmd_issuer.cc.
References DRAMCmdState::cmd, t_CMD, t_CWD, and WRITE.
Referenced by process_event().
bool CmdIssuer::CanSchedule (DRAMCmdState currentCmd, DRAMCmdState prevCmd)
Definition at line 309 of file cmd_issuer.cc.
References Request::bankNo, CalculateBurstL(), CalculateBusyTime(), DRAMCmdState::cmd, DIFF, Simulator::Now(), ChannelState::prevCmdTime, prevState, Request::rankNo, DRAMCmdState::req, and SAME.
Referenced by IssueCmd().
Time CmdIssuer::CmdDelay (DRAMCmd cmd)
Definition at line 281 of file cmd_issuer.cc.
References ACTIVATE, ALL_BANK_REFRESH, PRECHARGE, READ, t_CAS, t_RCD, t_RFC, t_RP, and WRITE.
bool CmdIssuer::HasWork ()
Definition at line 149 of file cmd_issuer.cc.
References bufferId, and parent.
Referenced by process_event().
bool CmdIssuer::IssueCmd (bool * isWrite, DRAMCmdState * scheduledCmd)
Definition at line 159 of file cmd_issuer.cc.
References BankNotBusy(), BanksFirstReq(), bufferId, BusNotBusy(), CanSchedule(), ChannelState::cmd, BusHandler::cmdQueue, parent, prevState, SetBusBusyTime(), SetPrevState(), and WRITE.
Referenced by process_event().
Time CmdIssuer::Max (Time t1, Time t2)
Definition at line 731 of file cmd_issuer.cc.
Referenced by CalculateBusyTime().
void CmdIssuer::process_event (IrisEvent * e)
Definition at line 58 of file cmd_issuer.cc.
References Request::address, Request::bankNo, Request::busInsertionTime, CalculateDataDelay(), Request::channelNo, CLOSE_PAGE_POLICY, DRAMCmdState::cmd, cmdBus, dataBus, dram_page_policy, IrisEvent::dst, IrisEvent::event_data, generated_start_event, HasWork(), Id, IssueCmd(), Simulator::Now(), OPEN_PAGE_POLICY, parent, PRECHARGE, DataBusHandler::process_event(), CmdBusHandler::process_event(), Request::rankNo, READ, DRAMCmdState::req, Simulator::Schedule(), IrisEvent::src, START, START_WRITE, IrisEvent::type, and WRITE.
Referenced by RefreshMgr::process_event(), and BankHandler::process_event().
void CmdIssuer::SetBusBusyTime (DRAMCmdState currentCmd)
Definition at line 220 of file cmd_issuer.cc.
References busBusy, CalculateBurstL(), DRAMCmdState::cmd, Simulator::Now(), prevBusCmd, READ, and WRITE.
Referenced by IssueCmd().
void CmdIssuer::SetPrevState (DRAMCmdState currentCmd)
Definition at line 719 of file cmd_issuer.cc.
References Request::bankNo, DRAMCmdState::cmd, ChannelState::cmd, Simulator::Now(), ChannelState::prevCmdBank, ChannelState::prevCmdRank, ChannelState::prevCmdTime, prevState, ChannelState::rank, Request::rankNo, DRAMCmdState::req, and Request::rowNo.
Referenced by IssueCmd().
std::string CmdIssuer::toString ()
Definition at line 154 of file cmd_issuer.cc.
Member Data Documentation
short CmdIssuer::bufferId
Definition at line 123 of file cmd_issuer.h.
Referenced by BanksFirstReq(), BusHandler::BusHandler(), HasWork(), and IssueCmd().
Time CmdIssuer::busBusy
Definition at line 125 of file cmd_issuer.h.
Referenced by BusNotBusy(), CmdIssuer(), and SetBusBusyTime().
CmdBusHandler* CmdIssuer::cmdBus
Definition at line 121 of file cmd_issuer.h.
Referenced by process_event(), and RequestHandler::SetLinks().
DataBusHandler* CmdIssuer::dataBus
Definition at line 120 of file cmd_issuer.h.
Referenced by process_event(), and RequestHandler::SetLinks().
bool CmdIssuer::generated_start_event
Definition at line 142 of file cmd_issuer.h.
Referenced by CmdIssuer(), and process_event().
short CmdIssuer::Id
Definition at line 122 of file cmd_issuer.h.
Referenced by BusHandler::BusHandler(), and process_event().
Component* CmdIssuer::parent
Definition at line 119 of file cmd_issuer.h.
Referenced by BanksFirstReq(), BusHandler::BusHandler(), HasWork(), IssueCmd(), and process_event().
DRAMCmd CmdIssuer::prevBusCmd
Definition at line 143 of file cmd_issuer.h.
Referenced by BusNotBusy(), and SetBusBusyTime().
ChannelState CmdIssuer::prevState
Definition at line 124 of file cmd_issuer.h.
Referenced by BankNotBusy(), CanSchedule(), CmdIssuer(), IssueCmd(), and SetPrevState().
The documentation for this class was generated from the following files:
cmd_issuer.h
cmd_issuer.cc