core_alloc_DPM_t Class Reference
Public Member Functions
core_alloc_DPM_t (struct core_t *const core)
virtual void reg_stats (struct stat_sdb_t *const sdb)
virtual void step (void)
virtual void recover (void)
virtual void recover (const struct Mop_t *const Mop)
virtual void RS_deallocate (const struct uop_t *const uop)
virtual void start_drain (void)
Protected Attributes
struct uop_t *** pipe
int * occupancy
int * port_loading
Static Protected Attributes
static const char * alloc_stall_str [ASTALL_num]
Private Types
enum alloc_stall_t {
ASTALL_NONE,
ASTALL_EMPTY,
ASTALL_ROB,
ASTALL_LDQ,
ASTALL_STQ,
ASTALL_RS,
ASTALL_DRAIN,
ASTALL_num
 }
Detailed Description
Definition at line 12 of file alloc-DPM.cpp.
Member Enumeration Documentation
enum core_alloc_DPM_t::alloc_stall_t [private]
Enumerator:
ASTALL_NONE
ASTALL_EMPTY
ASTALL_ROB
ASTALL_LDQ
ASTALL_STQ
ASTALL_RS
ASTALL_DRAIN
ASTALL_num
Definition at line 14 of file alloc-DPM.cpp.
Constructor & Destructor Documentation
core_alloc_DPM_t::core_alloc_DPM_t (struct core_t *const core)
Definition at line 60 of file alloc-DPM.cpp.
References core_knobs_t::alloc, core_alloc_t::core, core_knobs_t::depth, core_knobs_t::exec, fatal(), core_t::knobs, knobs, core_knobs_t::num_exec_ports, occupancy, pipe, port_loading, and core_knobs_t::width.
Member Function Documentation
void core_alloc_DPM_t::recover (const struct Mop_t *const Mop) [virtual]
Implements core_alloc_t .
Definition at line 430 of file alloc-DPM.cpp.
References core_knobs_t::alloc, core_alloc_t::core, core_knobs_t::depth, core_t::knobs, knobs, occupancy, pipe, core_knobs_t::width, and zesto_assert.
void core_alloc_DPM_t::recover (void) [virtual]
Implements core_alloc_t .
Definition at line 454 of file alloc-DPM.cpp.
References core_knobs_t::alloc, core_alloc_t::core, core_knobs_t::depth, core_t::knobs, knobs, occupancy, pipe, core_knobs_t::width, and zesto_assert.
void core_alloc_DPM_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Implements core_alloc_t .
Definition at line 92 of file alloc-DPM.cpp.
References core_t::core_t::core_stat_t::alloc_eff_uops, core_t::core_t::core_stat_t::alloc_insn, core_t::core_t::core_stat_t::alloc_stall, alloc_stall_str, core_t::core_t::core_stat_t::alloc_uops, ASTALL_num, core_alloc_t::core, core_t::current_thread, thread_t::id, PF_COUNT, PF_PDF, core_t::stat, stat_reg_counter, stat_reg_dist(), stat_reg_formula(), and stat_reg_note().
void core_alloc_DPM_t::RS_deallocate (const struct uop_t *const uop) [virtual]
Implements core_alloc_t .
Definition at line 475 of file alloc-DPM.cpp.
References uop_t::alloc, uop_t::port_assignment, port_loading, and zesto_assert.
void core_alloc_DPM_t::start_drain (void) [virtual]
Implements core_alloc_t .
Definition at line 481 of file alloc-DPM.cpp.
References core_alloc_t::drain_in_progress.
void core_alloc_DPM_t::step (void) [virtual]
Implements core_alloc_t .
Definition at line 131 of file alloc-DPM.cpp.
References odep_t::aflags, uop_t::alloc, core_knobs_t::alloc, core_t::core_t::core_stat_t::alloc_eff_uops, core_t::core_t::core_stat_t::alloc_insn, core_t::core_t::core_stat_t::alloc_stall, core_t::core_t::core_stat_t::alloc_uops, ASTALL_DRAIN, ASTALL_EMPTY, ASTALL_LDQ, ASTALL_NONE, ASTALL_ROB, ASTALL_RS, ASTALL_STQ, core_t::commit, core_alloc_t::core, DCREG, core_t::decode, Mop_t::decode, uop_t::decode, core_knobs_t::depth, DNA, core_knobs_t::drain_flush, core_alloc_t::drain_in_progress, val_t::dw, uop_t::EOM, uop_t::exec, core_knobs_t::exec, core_t::exec, F_LOAD, F_STORE, uop_t::FU_class, uop_t::fusion_head, uop_t::fusion_next, uop_t::fusion_size, core_t::get_odep_link(), uop_t::idep_name, uop_t::idep_uop, uop_t::in_fusion, core_exec_t::insert_ready_uop(), uop_t::is_fusion_head, uop_t::is_load, uop_t::is_nop, uop_t::is_sta, uop_t::is_std, Mop_t::is_trap, uop_t::ivalue, uop_t::ivalue_valid, core_t::knobs, knobs, core_exec_t::LDQ_available(), uop_t::LDQ_index, core_exec_t::LDQ_insert(), MAX_IDEPS, MD_REG_AFLAGS, uop_t::Mop, odep_t::next, occupancy, uop_t::odep_uop, uop_t::oflags, odep_t::op_num, uop_t::opflags, uop_t::oracle, uop_t::ovalue, uop_t::ovalue_valid, pipe, uop_t::port_assignment, core_knobs_t::port_binding, port_loading, core_commit_t::ROB_available(), core_commit_t::ROB_empty(), core_commit_t::ROB_fuse_insert(), uop_t::ROB_index, core_commit_t::ROB_insert(), core_exec_t::RS_available(), core_exec_t::RS_fuse_insert(), uop_t::RS_index, core_exec_t::RS_insert(), sim_cycle, core_t::stat, stat_add_sample(), core_exec_t::STQ_available(), uop_t::STQ_index, core_exec_t::STQ_insert_sta(), core_exec_t::STQ_insert_std(), TICK_T_MAX, uop_t::timing, odep_t::uop, core_decode_t::uop_available(), core_decode_t::uop_consume(), core_decode_t::uop_peek(), uop_t::when_allocated, uop_t::when_completed, uop_t::when_issued, uop_t::when_itag_ready, uop_t::when_ival_ready, uop_t::when_otag_ready, uop_t::when_ready, core_knobs_t::width, zesto_assert, and ZESTO_STAT.
Member Data Documentation
const char * core_alloc_DPM_t::alloc_stall_str [static, protected]
Initial value:
 {
  "no stall                   ",
  "no uops to allocate        ",
  "ROB is full                ",
  "LDQ is full                ",
  "STQ is full                ",
  "RS is full                 ",
  "OOO core draining          "
}
Definition at line 43 of file alloc-DPM.cpp.
Referenced by reg_stats().
int* core_alloc_DPM_t::occupancy [protected]
Definition at line 39 of file alloc-DPM.cpp.
Referenced by core_alloc_DPM_t(), recover(), and step().
struct uop_t*** core_alloc_DPM_t::pipe [read, protected]
Definition at line 38 of file alloc-DPM.cpp.
Referenced by core_alloc_DPM_t(), recover(), and step().
int* core_alloc_DPM_t::port_loading [protected]
Definition at line 41 of file alloc-DPM.cpp.
Referenced by core_alloc_DPM_t(), RS_deallocate(), and step().
The documentation for this class was generated from the following file:
alloc-DPM.cpp