uncore_t Class Reference
#include <zesto-uncore.h>
Classes
struct uncore_stat_t
Public Member Functions
bool enqueuable (const md_paddr_t addr, const enum cache_command cmd, tick_t when_enqueued)
void enqueue (struct cache_t *const prev_cp, const enum cache_command cmd, const md_paddr_t addr, const int linesize, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*const cb)(void *), seq_t(*const get_action_id)(void *))
bool compare ()
void uncore_reg_stats (struct uncore_t *uncore, struct stat_sdb_t *const sdb)
void setup (uint no_nodes, uint vcs, uint max_sim_time)
string toString () const
string print_stats () const
void set_output_path (string outpath_name)
uncore_t (unsigned int arg_id, const double arg_cpu_speed, unsigned int arg_virtual_channels, unsigned int arg_tile_count)
virtual ~uncore_t ()
Public Attributes
uint32_t virtual_channels
uint32_t tile_count
unsigned int num_cores
double cpu_speed
int cpu_ratio
struct core_t * core [4]
unsigned int id
struct bus_t * LLC_bus
struct cache_t * LLC
tick_t LLC_cycle_mask
int creq_size
int creq_num
int creq_head
int creq_tail
struct coherence_req * creq
struct uncore_t::uncore_stat_t stat
vector< bool > ready
bool sending
uint sending_vc
ullint lastSentTime
vector< unsigned int > mc_node_ip
FILE * app_mem_trace
bool log_trace
Protected Member Functions
void convertToBitStream (Request *req, HighLevelPacket *hlp)
void convertFromBitStream (Request *req, HighLevelPacket *hlp)
void handle_new_packet_event (IrisEvent *e)
void handle_ready_event (IrisEvent *e)
void process_event (IrisEvent *e)
Protected Attributes
unsigned int last_vc
Detailed Description
Definition at line 94 of file zesto-uncore.h.
Constructor & Destructor Documentation
uncore_t::uncore_t (unsigned int arg_id, const double arg_cpu_speed, unsigned int arg_virtual_channels, unsigned int arg_tile_count)
Definition at line 115 of file zesto-uncore.cpp.
References bus_create(), cache_create_llc(), CACHE_PREFETCH, CACHE_READ, CACHE_READWRITE, CACHE_WRITE, CACHE_WRITEBACK, cores_per_node, fatal(), uncore_t::uncore_t::uncore_stat_t::fwd_path_delay, uncore_t::uncore_t::uncore_stat_t::last_packet_out_cycle, lastSentTime, cache_t::linesize, LLC, LLC_access_rate, LLC_bus, LLC_bus_ratio, LLC_cycle_mask, LLC_high_watermark, LLC_low_watermark, LLC_MSHR_cmd, LLC_num_PF, LLC_opt_str, LLC_PF_buffer_size, LLC_PF_filter_reset, LLC_PF_filter_size, LLC_PF_opt_str, LLC_PFFsize, LLC_PFmax, LLC_PFthresh, LLC_WMinterval, uncore_t::uncore_t::uncore_stat_t::min_pkt_latency, mytoupper(), cache_t::name, NetworkComponent::name, num_cores, cache_t::num_prefetchers, uncore_t::uncore_t::uncore_stat_t::packets_in, uncore_t::uncore_t::uncore_stat_t::packets_out, cache_t::PF_high_watermark, cache_t::PF_low_watermark, cache_t::PF_sample_interval, cache_t::PFF, cache_t::PFF_size, prefetch_buffer_create(), prefetch_create(), prefetch_filter_create(), cache_t::prefetch_max, cache_t::prefetch_threshold, cache_t::prefetcher, ready, uncore_t::uncore_t::uncore_stat_t::round_trip_hop_count, uncore_t::uncore_t::uncore_stat_t::round_trip_lat, uncore_t::uncore_t::uncore_stat_t::round_trip_memory_latency, uncore_t::uncore_t::uncore_stat_t::round_trip_network_latency, stat, cache_t::uncore, virtual_channels, and uncore_t::uncore_t::uncore_stat_t::waiting_in_ni.
Referenced by sim_post_init().
uncore_t::~uncore_t () [virtual]
Definition at line 229 of file zesto-uncore.cpp.
Member Function Documentation
bool uncore_t::compare ()
void uncore_t::convertFromBitStream (Request * req, HighLevelPacket * hlp) [protected]
Definition at line 653 of file zesto-uncore.cpp.
References Request::address, CACHE_BLOCK_SIZE, CACHE_PREFETCH, CACHE_READ, CACHE_WRITE, Request::cmdType, Request::data, HighLevelPacket::data, max_phy_link_bits, Request::mcNo, NETWORK_ADDRESS_BITS, Data::size, HighLevelPacket::source, and Data::value.
Referenced by handle_new_packet_event().
void uncore_t::convertToBitStream (Request * req, HighLevelPacket * hlp) [protected]
Definition at line 615 of file zesto-uncore.cpp.
References Request::address, Request::arrivalTime, bool, CACHE_BLOCK_SIZE, CACHE_WRITEBACK, Request::cmdType, HighLevelPacket::data, HighLevelPacket::data_payload_length, max_phy_link_bits, HighLevelPacket::msg_class, NETWORK_ADDRESS_BITS, NETWORK_COMMAND_BITS, NETWORK_THREADID_BITS, ONE_FLIT_REQ, RESPONSE_PKT, HighLevelPacket::sent_time, and Request::threadId.
Referenced by enqueue().
bool uncore_t::enqueuable (const md_paddr_t addr, const enum cache_command cmd, tick_t when_enqueued)
Definition at line 449 of file zesto-uncore.cpp.
References last_vc, ready, sending, sending_vc, and vcs.
Referenced by cache_process_llc().
void uncore_t::enqueue (struct cache_t *const prev_cp, const enum cache_command cmd, const md_paddr_t addr, const int linesize, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*)(void *) cb, seq_t(*)(void *) get_action_id)
Definition at line 488 of file zesto-uncore.cpp.
References HighLevelPacket::addr, NetworkComponent::address, Request::address, app_mem_trace, Request::arrivalTime, Request::cmdType, convertToBitStream(), HighLevelPacket::destination, uncore_t::uncore_t::uncore_stat_t::fwd_path_delay, get_mcNo(), GlobalAddrMap(), Processor::interface_connections, log_trace, mc_node_ip, Request::mcNo, NEW_PACKET_EVENT, NetworkComponent::node_ip, Simulator::Now(), uncore_t::uncore_t::uncore_stat_t::packets_out, NetworkComponent::process_event(), ready, HighLevelPacket::req_start_time, Simulator::Schedule(), sending_vc, HighLevelPacket::sent_time, sim_cycle, HighLevelPacket::source, stat, Request::threadId, HighLevelPacket::transaction_id, and HighLevelPacket::virtual_channel.
Referenced by cache_process_llc().
void uncore_t::handle_new_packet_event (IrisEvent * e) [protected]
Definition at line 402 of file zesto-uncore.cpp.
References HighLevelPacket::avg_network_latency, convertFromBitStream(), IrisEvent::event_data, fill_arrived_llc(), GlobalAddrRip(), HighLevelPacket::hop_count, Processor::interface_connections, uncore_t::uncore_t::uncore_stat_t::last_packet_out_cycle, LLC, uncore_t::uncore_t::uncore_stat_t::min_pkt_latency, Processor::ni_recv, NetworkComponent::node_ip, Simulator::Now(), uncore_t::uncore_t::uncore_stat_t::packets_in, NetworkComponent::process_event(), READY_EVENT, HighLevelPacket::req_start_time, uncore_t::uncore_t::uncore_stat_t::round_trip_hop_count, uncore_t::uncore_t::uncore_stat_t::round_trip_lat, uncore_t::uncore_t::uncore_stat_t::round_trip_memory_latency, uncore_t::uncore_t::uncore_stat_t::round_trip_network_latency, Simulator::Schedule(), HighLevelPacket::sent_time, stat, HighLevelPacket::stat_memory_serviced_time, IrisEvent::type, IrisEvent::vc, HighLevelPacket::virtual_channel, HighLevelPacket::waiting_in_ni, and uncore_t::uncore_t::uncore_stat_t::waiting_in_ni.
Referenced by process_event().
void uncore_t::handle_ready_event (IrisEvent * e) [protected]
Definition at line 376 of file zesto-uncore.cpp.
References ready, and IrisEvent::vc.
Referenced by process_event().
string uncore_t::print_stats (void) const [virtual]
Implements Processor .
Definition at line 255 of file zesto-uncore.cpp.
void uncore_t::process_event (IrisEvent * e) [protected, virtual]
Implements Processor .
Definition at line 385 of file zesto-uncore.cpp.
References handle_new_packet_event(), handle_ready_event(), NEW_PACKET_EVENT, READY_EVENT, and IrisEvent::type.
void uncore_t::set_output_path (string outpath_name) [virtual]
Implements Processor .
Definition at line 261 of file zesto-uncore.cpp.
void uncore_t::setup (uint no_nodes, uint vcs, uint max_sim_time) [virtual]
Implements Processor .
Definition at line 234 of file zesto-uncore.cpp.
References NetworkComponent::address, app_mem_trace, fatal(), log_trace, Component::myId(), and NetworkComponent::node_ip.
string uncore_t::toString (void) const [virtual]
Reimplemented from Processor .
Definition at line 693 of file zesto-uncore.cpp.
References NetworkComponent::address, Processor::interface_connections, NetworkComponent::node_ip, and ready.
void uncore_t::uncore_reg_stats (struct uncore_t * uncore, struct stat_sdb_t *const sdb)
Definition at line 305 of file zesto-uncore.cpp.
References bus_reg_stats(), uncore_t::uncore_t::uncore_stat_t::fwd_path_delay, uncore_t::uncore_t::uncore_stat_t::last_packet_out_cycle, LLC, LLC_bus, LLC_reg_stats(), uncore_t::uncore_t::uncore_stat_t::min_pkt_latency, NetworkComponent::node_ip, uncore_t::uncore_t::uncore_stat_t::packets_in, uncore_t::uncore_t::uncore_stat_t::packets_out, uncore_t::uncore_t::uncore_stat_t::round_trip_hop_count, uncore_t::uncore_t::uncore_stat_t::round_trip_lat, uncore_t::uncore_t::uncore_stat_t::round_trip_memory_latency, uncore_t::uncore_t::uncore_stat_t::round_trip_network_latency, stat, stat_reg_counter, stat_reg_formula(), stat_reg_note(), and uncore_t::uncore_t::uncore_stat_t::waiting_in_ni.
Member Data Documentation
FILE* uncore_t::app_mem_trace
Definition at line 167 of file zesto-uncore.h.
Referenced by enqueue(), and setup().
struct core_t* uncore_t::core[4] [read]
Definition at line 120 of file zesto-uncore.h.
Referenced by LLC_reg_stats(), and sim_post_init().
int uncore_t::cpu_ratio
Definition at line 117 of file zesto-uncore.h.
double uncore_t::cpu_speed
Definition at line 116 of file zesto-uncore.h.
struct coherence_req* uncore_t::creq [read]
Definition at line 136 of file zesto-uncore.h.
int uncore_t::creq_head
Definition at line 134 of file zesto-uncore.h.
int uncore_t::creq_num
Definition at line 133 of file zesto-uncore.h.
int uncore_t::creq_size
Definition at line 132 of file zesto-uncore.h.
int uncore_t::creq_tail
Definition at line 135 of file zesto-uncore.h.
unsigned int uncore_t::id
Definition at line 124 of file zesto-uncore.h.
unsigned int uncore_t::last_vc [protected]
Definition at line 97 of file zesto-uncore.h.
Referenced by enqueuable().
ullint uncore_t::lastSentTime
Definition at line 162 of file zesto-uncore.h.
Referenced by uncore_t().
struct cache_t* uncore_t::LLC [read]
Definition at line 128 of file zesto-uncore.h.
Referenced by cache_process_llc(), core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), core_fetch_STM_t::core_fetch_STM_t(), handle_new_packet_event(), prefetch_LLC(), sim_fastfwd(), step_LLC_PF_controller(), uncore_reg_stats(), and uncore_t().
struct bus_t* uncore_t::LLC_bus [read]
Definition at line 127 of file zesto-uncore.h.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), core_fetch_STM_t::core_fetch_STM_t(), uncore_reg_stats(), and uncore_t().
tick_t uncore_t::LLC_cycle_mask
Definition at line 129 of file zesto-uncore.h.
Referenced by uncore_t().
bool uncore_t::log_trace
Definition at line 168 of file zesto-uncore.h.
Referenced by enqueue(), core_oracle_t::exec(), and setup().
vector<unsigned int> uncore_t::mc_node_ip
Definition at line 163 of file zesto-uncore.h.
Referenced by enqueue().
unsigned int uncore_t::num_cores
Definition at line 114 of file zesto-uncore.h.
Referenced by LLC_reg_stats(), and uncore_t().
vector<bool> uncore_t::ready
Definition at line 158 of file zesto-uncore.h.
Referenced by enqueuable(), enqueue(), handle_ready_event(), toString(), and uncore_t().
bool uncore_t::sending
Definition at line 159 of file zesto-uncore.h.
Referenced by enqueuable().
uint uncore_t::sending_vc
Definition at line 161 of file zesto-uncore.h.
Referenced by enqueuable(), and enqueue().
struct uncore_t::uncore_stat_t uncore_t::stat
Referenced by enqueue(), handle_new_packet_event(), uncore_reg_stats(), and uncore_t().
uint32_t uncore_t::tile_count
Definition at line 113 of file zesto-uncore.h.
uint32_t uncore_t::virtual_channels
Definition at line 112 of file zesto-uncore.h.
Referenced by uncore_t().
The documentation for this class was generated from the following files:
zesto-uncore.h
zesto-uncore.cpp