Qsim::Params Class Reference
#include <qsim.h>
Public Member Functions
Params ()
template<typename T >
Params (std::string k, const T &v)
template<typename T >
Params & operator() (std::string k, const T &v)
Detailed Description
Definition at line 34 of file qsim.h.
Constructor & Destructor Documentation
Qsim::Params::Params () [inline]
Definition at line 36 of file qsim.h.
template<typename T > Qsim::Params::Params (std::string k, const T & v) [inline]
Definition at line 37 of file qsim.h.
References operator()().
Member Function Documentation
template<typename T > Params& Qsim::Params::operator() (std::string k, const T & v) [inline]
Definition at line 41 of file qsim.h.
Referenced by Params().
The documentation for this class was generated from the following file:
qsim.h