core_decode_DPM_t Class Reference
Public Member Functions
core_decode_DPM_t (struct core_t *const core)
virtual void reg_stats (struct stat_sdb_t *const sdb)
virtual void update_occupancy (void)
virtual void step (void)
virtual void recover (void)
virtual void recover (struct Mop_t *const Mop)
virtual bool uop_available (void)
virtual struct uop_t * uop_peek (void)
virtual void uop_consume (void)
Protected Member Functions
enum decode_stall_t check_target (struct Mop_t *const Mop)
bool check_flush (const int stage, const int idx)
void recover_decode_pipe (const struct Mop_t *const Mop)
void recover_decode_pipe (void)
void recover_uopQ (const struct Mop_t *const Mop)
void recover_uopQ (void)
Protected Attributes
struct Mop_t *** pipe
int * occupancy
struct uop_t ** uopQ
int uopQ_head
int uopQ_tail
int uopQ_num
int uopQ_eff_num
Static Protected Attributes
static const char * decode_stall_str [DSTALL_num]
Private Types
enum decode_stall_t {
DSTALL_NONE,
DSTALL_FULL,
DSTALL_REP,
DSTALL_UROM,
DSTALL_SMALL,
DSTALL_EMPTY,
DSTALL_PHANTOM,
DSTALL_TARGET,
DSTALL_MAX_BRANCHES,
DSTALL_num
 }
Detailed Description
Definition at line 11 of file decode-DPM.cpp.
Member Enumeration Documentation
enum core_decode_DPM_t::decode_stall_t [private]
Enumerator:
DSTALL_NONE
DSTALL_FULL
DSTALL_REP
DSTALL_UROM
DSTALL_SMALL
DSTALL_EMPTY
DSTALL_PHANTOM
DSTALL_TARGET
DSTALL_MAX_BRANCHES
DSTALL_num
Definition at line 13 of file decode-DPM.cpp.
Constructor & Destructor Documentation
core_decode_DPM_t::core_decode_DPM_t (struct core_t *const core)
Definition at line 74 of file decode-DPM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::decoders, core_knobs_t::depth, fatal(), core_knobs_t::fusion_all, FUSION_LOAD_OP, core_knobs_t::fusion_load_op, core_knobs_t::fusion_mode, FUSION_NONE, core_knobs_t::fusion_none, FUSION_PARTIAL, core_knobs_t::fusion_partial, FUSION_STA_STD, core_knobs_t::fusion_sta_std, core_t::knobs, knobs, MAX_DECODE_WIDTH, core_knobs_t::max_uops, core_knobs_t::num_decoder_specs, occupancy, pipe, core_knobs_t::target_stage, uopQ, core_knobs_t::uopQ_size, and core_knobs_t::width.
Member Function Documentation
bool core_decode_DPM_t::check_flush (const int stage, const int idx) [protected]
Definition at line 254 of file decode-DPM.cpp.
References check_target(), core_decode_t::core, core_knobs_t::decode, core_t::core_t::core_stat_t::decode_stall, core_t::knobs, knobs, occupancy, pipe, core_t::stat, stat_add_sample(), core_knobs_t::target_stage, core_knobs_t::width, zesto_assert, and ZESTO_STAT.
Referenced by step().
enum core_decode_DPM_t::decode_stall_t core_decode_DPM_t::check_target (struct Mop_t *const Mop) [protected]
Definition at line 215 of file decode-DPM.cpp.
References core_fetch_t::bpred, Mop_t::bpred_update, core_decode_t::core, Mop_t::decode, DSTALL_NONE, DSTALL_PHANTOM, DSTALL_TARGET, F_UNCOND, core_t::fetch, Mop_t::fetch, Mop_t::inst, Mop_t::is_ctrl, md_inst_t::len, Mop_t::opflags, core_t::oracle, Mop_t::PC, core_t::core_t::core_stat_t::phantom_resteers, Mop_t::pred_NPC, bpred_t::recover(), core_fetch_t::recover(), core_oracle_t::recover(), recover_decode_pipe(), core_t::stat, core_t::core_t::core_stat_t::target_resteers, Mop_t::targetPC, and ZESTO_STAT.
Referenced by check_flush().
void core_decode_DPM_t::recover (struct Mop_t *const Mop) [virtual]
Implements core_decode_t .
Definition at line 474 of file decode-DPM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::depth, core_t::knobs, knobs, occupancy, pipe, recover_uopQ(), core_knobs_t::width, and zesto_assert.
void core_decode_DPM_t::recover (void) [virtual]
Implements core_decode_t .
Definition at line 467 of file decode-DPM.cpp.
References recover_decode_pipe(), and recover_uopQ().
void core_decode_DPM_t::recover_decode_pipe (void) [protected]
Definition at line 572 of file decode-DPM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::depth, core_t::knobs, knobs, occupancy, pipe, core_knobs_t::width, and zesto_assert.
Referenced by check_target(), and recover().
void core_decode_DPM_t::recover_decode_pipe (const struct Mop_t *const Mop) [protected]
Definition at line 545 of file decode-DPM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_knobs_t::depth, core_t::knobs, knobs, occupancy, pipe, core_knobs_t::width, and zesto_assert.
void core_decode_DPM_t::recover_uopQ (void) [protected]
Definition at line 524 of file decode-DPM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_t::knobs, knobs, memzero(), uopQ, uopQ_eff_num, uopQ_head, uopQ_num, core_knobs_t::uopQ_size, and uopQ_tail.
Referenced by recover().
void core_decode_DPM_t::recover_uopQ (const struct Mop_t *const Mop) [protected]
Definition at line 502 of file decode-DPM.cpp.
References core_decode_t::core, uop_t::decode, core_knobs_t::decode, uop_t::fusion_size, core_t::knobs, knobs, moddec(), uopQ, uopQ_eff_num, uopQ_num, core_knobs_t::uopQ_size, and uopQ_tail.
void core_decode_DPM_t::reg_stats (struct stat_sdb_t *const sdb) [virtual]
Implements core_decode_t .
Definition at line 134 of file decode-DPM.cpp.
References core_decode_t::core, core_t::current_thread, core_t::core_t::core_stat_t::decode_eff_uops, core_t::core_t::core_stat_t::decode_insn, core_t::core_t::core_stat_t::decode_stall, decode_stall_str, core_t::core_t::core_stat_t::decode_uops, DSTALL_num, thread_t::id, PF_COUNT, PF_PDF, core_t::core_t::core_stat_t::phantom_resteers, core_t::stat, stat_reg_counter, stat_reg_dist(), stat_reg_formula(), stat_reg_note(), core_t::core_t::core_stat_t::target_resteers, core_t::core_t::core_stat_t::uopQ_eff_occupancy, core_t::core_t::core_stat_t::uopQ_empty_cycles, core_t::core_t::core_stat_t::uopQ_full_cycles, and core_t::core_t::core_stat_t::uopQ_occupancy.
void core_decode_DPM_t::step (void) [virtual]
Implements core_decode_t .
Definition at line 290 of file decode-DPM.cpp.
References uop_t::BOM, core_knobs_t::branch_decode_limit, check_flush(), core_decode_t::core, uop_t::decode, Mop_t::decode, core_knobs_t::decode, core_t::core_t::core_stat_t::decode_eff_uops, core_t::core_t::core_stat_t::decode_insn, core_t::core_t::core_stat_t::decode_stall, core_t::core_t::core_stat_t::decode_uops, core_knobs_t::depth, DSTALL_EMPTY, DSTALL_FULL, DSTALL_MAX_BRANCHES, DSTALL_NONE, DSTALL_REP, DSTALL_SMALL, DSTALL_UROM, uop_t::EOM, F_LOAD, F_STORE, Mop_t::fetch, core_t::fetch, Mop_t::flow_length, uop_t::fusion_size, uop_t::has_imm, uop_t::in_fusion, Mop_t::inst, Mop_t::is_ctrl, uop_t::is_fusion_head, uop_t::is_load, uop_t::is_std, core_t::knobs, knobs, Mop_t::last_stage_index, Mop_t::last_uop_index, core_knobs_t::max_uops, modinc(), uop_t::Mop, core_fetch_t::Mop_available(), core_fetch_t::Mop_consume(), core_fetch_t::Mop_peek(), core_knobs_t::MS_latency, Mop_t::num_uops, occupancy, uop_t::opflags, pipe, md_inst_t::rep, sim_cycle, Mop_t::stat, core_t::stat, stat_add_sample(), TICK_T_MAX, Mop_t::timing, uop_t::timing, Mop_t::uop, uopQ, uopQ_eff_num, uopQ_num, core_knobs_t::uopQ_size, uopQ_tail, Mop_t::when_decode_finished, Mop_t::when_decode_started, uop_t::when_decoded, Mop_t::when_MS_started, core_knobs_t::width, zesto_assert, and ZESTO_STAT.
bool core_decode_DPM_t::uop_available (void) [virtual]
Implements core_decode_t .
Definition at line 591 of file decode-DPM.cpp.
References uopQ_num.
void core_decode_DPM_t::uop_consume (void) [virtual]
Implements core_decode_t .
Definition at line 601 of file decode-DPM.cpp.
References core_decode_t::core, core_knobs_t::decode, uop_t::decode, uop_t::fusion_size, uop_t::is_fusion_head, core_t::knobs, knobs, modinc(), uopQ, uopQ_eff_num, uopQ_head, uopQ_num, and core_knobs_t::uopQ_size.
struct uop_t * core_decode_DPM_t::uop_peek (void) [read, virtual]
Implements core_decode_t .
Definition at line 596 of file decode-DPM.cpp.
References uopQ, and uopQ_head.
void core_decode_DPM_t::update_occupancy (void) [virtual]
Implements core_decode_t .
Definition at line 194 of file decode-DPM.cpp.
References core_decode_t::core, core_knobs_t::decode, core_t::knobs, core_t::stat, uopQ_eff_num, core_t::core_t::core_stat_t::uopQ_eff_occupancy, core_t::core_t::core_stat_t::uopQ_empty_cycles, core_t::core_t::core_stat_t::uopQ_full_cycles, uopQ_num, core_t::core_t::core_stat_t::uopQ_occupancy, and core_knobs_t::uopQ_size.
Member Data Documentation
const char * core_decode_DPM_t::decode_stall_str [static, protected]
Initial value:
 {
  "no stall                   ",
  "next decode stage is full  ",
  "REP inst waiting for MS    ",
  "long flow waiting for UROM ",
  "available decoder too small",
  "no insts to decode         ",
  "phantom taken branch       ",
  "target correction          ",
  "branch decode limit        ",
}
Definition at line 52 of file decode-DPM.cpp.
Referenced by reg_stats().
int* core_decode_DPM_t::occupancy [protected]
Definition at line 44 of file decode-DPM.cpp.
Referenced by check_flush(), core_decode_DPM_t(), recover(), recover_decode_pipe(), and step().
struct Mop_t*** core_decode_DPM_t::pipe [read, protected]
Definition at line 43 of file decode-DPM.cpp.
Referenced by check_flush(), core_decode_DPM_t(), recover(), recover_decode_pipe(), and step().
struct uop_t** core_decode_DPM_t::uopQ [read, protected]
Definition at line 46 of file decode-DPM.cpp.
Referenced by core_decode_DPM_t(), recover_uopQ(), step(), uop_consume(), and uop_peek().
int core_decode_DPM_t::uopQ_eff_num [protected]
Definition at line 50 of file decode-DPM.cpp.
Referenced by recover_uopQ(), step(), uop_consume(), and update_occupancy().
int core_decode_DPM_t::uopQ_head [protected]
Definition at line 47 of file decode-DPM.cpp.
Referenced by recover_uopQ(), uop_consume(), and uop_peek().
int core_decode_DPM_t::uopQ_num [protected]
Definition at line 49 of file decode-DPM.cpp.
Referenced by recover_uopQ(), step(), uop_available(), uop_consume(), and update_occupancy().
int core_decode_DPM_t::uopQ_tail [protected]
Definition at line 48 of file decode-DPM.cpp.
Referenced by recover_uopQ(), and step().
The documentation for this class was generated from the following file:
decode-DPM.cpp