core_decode_t Class Reference
#include <zesto-decode.h>
Public Member Functions
core_decode_t (void)
virtual ~core_decode_t ()
virtual void reg_stats (struct stat_sdb_t *const sdb)=0
virtual void update_occupancy (void)=0
virtual void step (void)=0
virtual void recover (void)=0
virtual void recover (struct Mop_t *const Mop)=0
virtual bool uop_available (void)=0
virtual struct uop_t * uop_peek (void)=0
virtual void uop_consume (void)=0
Protected Attributes
struct core_t * core
Detailed Description
Definition at line 79 of file zesto-decode.h.
Constructor & Destructor Documentation
core_decode_t::core_decode_t (void)
Definition at line 130 of file zesto-decode.cpp.
core_decode_t::~core_decode_t () [virtual]
Definition at line 135 of file zesto-decode.cpp.
Member Function Documentation
virtual void core_decode_t::recover (struct Mop_t *const Mop) [pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
virtual void core_decode_t::recover (void) [pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
Referenced by emergency_recovery(), core_oracle_t::pipe_recover(), core_oracle_t::reset_execution(), core_fetch_DPM_t::step(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
virtual void core_decode_t::reg_stats (struct stat_sdb_t *const sdb) [pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
virtual void core_decode_t::step (void) [pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
virtual bool core_decode_t::uop_available (void) [pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_decode_t::uop_consume (void) [pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual struct uop_t* core_decode_t::uop_peek (void) [read, pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_decode_t::update_occupancy (void) [pure virtual]
Implemented in core_decode_DPM_t , and core_decode_STM_t .
Referenced by zesto_component::downtick_handler().
Member Data Documentation
struct core_t* core_decode_t::core [read, protected]
Definition at line 100 of file zesto-decode.h.
Referenced by core_decode_STM_t::check_flush(), core_decode_DPM_t::check_flush(), core_decode_STM_t::check_target(), core_decode_DPM_t::check_target(), core_decode_DPM_t::core_decode_DPM_t(), core_decode_STM_t::core_decode_STM_t(), core_decode_STM_t::recover(), core_decode_DPM_t::recover(), core_decode_DPM_t::recover_decode_pipe(), core_decode_DPM_t::recover_uopQ(), core_decode_STM_t::reg_stats(), core_decode_DPM_t::reg_stats(), core_decode_STM_t::step(), core_decode_DPM_t::step(), core_decode_STM_t::uop_available(), core_decode_STM_t::uop_consume(), core_decode_DPM_t::uop_consume(), core_decode_STM_t::uop_peek(), and core_decode_DPM_t::update_occupancy().
The documentation for this class was generated from the following files:
zesto-decode.h
zesto-decode.cpp