core_commit_t Class Reference
#include <zesto-commit.h>
Public Member Functions
core_commit_t (void)
virtual ~core_commit_t ()
virtual void reg_stats (struct stat_sdb_t *const sdb)=0
virtual void update_occupancy (void)=0
virtual void step (void)=0
virtual void recover (const struct Mop_t *const Mop)=0
virtual void recover (void)=0
virtual bool ROB_available (void)=0
virtual bool ROB_empty (void)=0
virtual void ROB_insert (struct uop_t *const uop)=0
virtual void ROB_fuse_insert (struct uop_t *const uop)=0
Protected Attributes
struct core_t * core
Static Protected Attributes
static const int deadlock_threshold = 250000
Private Types
enum commit_stall_t {
CSTALL_NONE,
CSTALL_NOT_READY,
CSTALL_PARTIAL,
CSTALL_EMPTY,
CSTALL_JECLEAR_INFLIGHT,
CSTALL_MAX_BRANCHES,
CSTALL_num
 }
Detailed Description
Definition at line 78 of file zesto-commit.h.
Member Enumeration Documentation
enum core_commit_t::commit_stall_t [private]
Enumerator:
CSTALL_NONE
CSTALL_NOT_READY
CSTALL_PARTIAL
CSTALL_EMPTY
CSTALL_JECLEAR_INFLIGHT
CSTALL_MAX_BRANCHES
CSTALL_num
Reimplemented in core_commit_DPM_t , and core_commit_STM_t .
Definition at line 80 of file zesto-commit.h.
Constructor & Destructor Documentation
core_commit_t::core_commit_t (void)
Definition at line 102 of file zesto-commit.cpp.
core_commit_t::~core_commit_t () [virtual]
Definition at line 107 of file zesto-commit.cpp.
Member Function Documentation
virtual void core_commit_t::recover (void) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
virtual void core_commit_t::recover (const struct Mop_t *const Mop) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
Referenced by emergency_recovery(), core_oracle_t::pipe_recover(), core_oracle_t::reset_execution(), and core_fetch_DPM_t::step().
virtual void core_commit_t::reg_stats (struct stat_sdb_t *const sdb) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
virtual bool core_commit_t::ROB_available (void) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual bool core_commit_t::ROB_empty (void) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_commit_t::ROB_fuse_insert (struct uop_t *const uop) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
Referenced by core_alloc_DPM_t::step().
virtual void core_commit_t::ROB_insert (struct uop_t *const uop) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
Referenced by core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
virtual void core_commit_t::step (void) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
virtual void core_commit_t::update_occupancy (void) [pure virtual]
Implemented in core_commit_DPM_t , and core_commit_STM_t .
Referenced by zesto_component::downtick_handler().
Member Data Documentation
struct core_t* core_commit_t::core [read, protected]
Definition at line 114 of file zesto-commit.h.
Referenced by core_commit_DPM_t::core_commit_DPM_t(), core_commit_STM_t::core_commit_STM_t(), core_commit_STM_t::recover(), core_commit_DPM_t::recover(), core_commit_STM_t::reg_stats(), core_commit_DPM_t::reg_stats(), core_commit_STM_t::ROB_available(), core_commit_DPM_t::ROB_available(), core_commit_STM_t::ROB_insert(), core_commit_DPM_t::ROB_insert(), core_commit_STM_t::step(), core_commit_DPM_t::step(), core_commit_STM_t::update_occupancy(), and core_commit_DPM_t::update_occupancy().
const int core_commit_t::deadlock_threshold = 250000 [static, protected]
Definition at line 115 of file zesto-commit.h.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
The documentation for this class was generated from the following files:
zesto-commit.h
zesto-commit.cpp