RequestHandler Class Reference
#include <request_handler.h>
Public Member Functions
RequestHandler ()
~RequestHandler ()
void SetLinks ()
void FormBatch ()
void MarkAll ()
void MarkBatchOnly ()
void PushPipeline (Request *req)
void process_event (IrisEvent *e)
std::string toString ()
Public Attributes
Component * mc
Component * parent
Component * child
ChannelHandler chan [NO_OF_CHANNELS]
BusHandler * busHandler
AddrMap * addrMap
Component * resPtr
Time lastBatchFormTime
Request pipeline
int reqTag
bool oneBufferFull
bool pipelineFilled
Detailed Description
Definition at line 49 of file request_handler.h.
Constructor & Destructor Documentation
RequestHandler::RequestHandler ()
Definition at line 36 of file request_handler.cc.
References addrMap, busHandler, chan, ChannelHandler::chanId, lastBatchFormTime, NO_OF_BANKS, NO_OF_BUFFERS, NO_OF_CHANNELS, NO_OF_RANKS, oneBufferFull, BusHandler::parent, AddrMap::parent, pipelineFilled, ChannelHandler::rank, and reqTag.
RequestHandler::~RequestHandler ()
Definition at line 71 of file request_handler.cc.
References addrMap, and busHandler.
Member Function Documentation
void RequestHandler::FormBatch ()
Definition at line 198 of file request_handler.cc.
References BATCH_FORM_TIME, lastBatchFormTime, and MarkBatchOnly().
Referenced by process_event().
void RequestHandler::MarkAll ()
Definition at line 209 of file request_handler.cc.
References chan, NO_OF_BUFFERS, NO_OF_CHANNELS, NO_OF_RANKS, and ChannelHandler::rank.
void RequestHandler::MarkBatchOnly ()
Definition at line 218 of file request_handler.cc.
References chan, MAX_BATCH_SIZE, NO_OF_BUFFERS, NO_OF_CHANNELS, NO_OF_RANKS, NO_OF_THREADS, and ChannelHandler::rank.
Referenced by FormBatch().
void RequestHandler::process_event (IrisEvent * e)
Definition at line 86 of file request_handler.cc.
References Request::address, addrMap, BATCH_FORM_TIME, busHandler, CONTINUE, IrisEvent::event_data, FormBatch(), BusHandler::full, lastBatchFormTime, NO_OF_CHANNELS, Simulator::Now(), oneBufferFull, pipeline, pipelineFilled, AddrMap::process_event(), PushPipeline(), Simulator::Schedule(), START, START_CMD_QUEUE, STOP_CMD_QUEUE, BusHandler::stopSignal, and IrisEvent::type.
Referenced by NI::handle_new_packet_event(), main(), BankHandler::process_event(), and MC::sim_main().
void RequestHandler::PushPipeline (Request * req)
Definition at line 188 of file request_handler.cc.
References pipeline.
Referenced by process_event().
void RequestHandler::SetLinks ()
Definition at line 77 of file request_handler.cc.
References busHandler, child, CmdIssuer::cmdBus, BusHandler::cmdIssuer, CmdIssuer::dataBus, and NO_OF_CHANNELS.
Referenced by MC::Init().
std::string RequestHandler::toString ()
Definition at line 193 of file request_handler.cc.
Member Data Documentation
AddrMap* RequestHandler::addrMap
Definition at line 59 of file request_handler.h.
Referenced by process_event(), RequestHandler(), and ~RequestHandler().
BusHandler* RequestHandler::busHandler
Definition at line 58 of file request_handler.h.
Referenced by process_event(), RefreshMgr::process_event(), RequestHandler(), SetLinks(), and ~RequestHandler().
ChannelHandler RequestHandler::chan[NO_OF_CHANNELS]
Definition at line 57 of file request_handler.h.
Referenced by MarkAll(), MarkBatchOnly(), and RequestHandler().
Component* RequestHandler::child
Definition at line 56 of file request_handler.h.
Referenced by MC::Init(), and SetLinks().
Time RequestHandler::lastBatchFormTime
Definition at line 61 of file request_handler.h.
Referenced by FormBatch(), process_event(), and RequestHandler().
Component* RequestHandler::mc
Definition at line 54 of file request_handler.h.
Referenced by MC::Init().
bool RequestHandler::oneBufferFull
Definition at line 64 of file request_handler.h.
Referenced by main(), process_event(), RequestHandler(), and MC::sim_main().
Component* RequestHandler::parent
Definition at line 55 of file request_handler.h.
Referenced by MC::Init().
Request RequestHandler::pipeline
Definition at line 62 of file request_handler.h.
Referenced by process_event(), and PushPipeline().
bool RequestHandler::pipelineFilled
Definition at line 65 of file request_handler.h.
Referenced by process_event(), and RequestHandler().
int RequestHandler::reqTag
Definition at line 63 of file request_handler.h.
Referenced by RequestHandler().
Component* RequestHandler::resPtr
Definition at line 60 of file request_handler.h.
Referenced by MC::Init().
The documentation for this class was generated from the following files:
request_handler.h
request_handler.cc