zesto-llc.cpp File Reference
#include <limits.h>
#include `thread.h`
#include `stats.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-cache.h`
#include `zesto-prefetch.h`
#include `zesto-uncore.h`
#include `zesto-exec.h`
#include `zesto-commit.h`
Functions
struct cache_t * cache_create_llc (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, const int begin_index, const int end_index, struct cache_t *const next_level_cache, struct bus_t *const next_bus)
void LLC_reg_stats (struct stat_sdb_t *const sdb, struct cache_t *const cp)
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr)
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful)
struct cache_line_t * cache_is_hit_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
static struct cache_line_t * cache_peek_llc (const struct cache_t *const cp, const md_paddr_t addr)
void cache_insert_block_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
struct cache_line_t * cache_get_evictee_llc (struct cache_t *const cp, const md_paddr_t addr, core_t *const core)
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position)
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num)
int cache_enqueuable_llc (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
void cache_enqueue_llc (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*const cb)(void *), void(*const miss_cb)(void *, int), bool(*const translated_cb)(void *, seq_t), seq_t(*const get_action_id)(void *))
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr)
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr)
static struct cache_action_t * MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd)
static void dummy_callback (void *p)
void fill_arrived_llc (struct cache_t *const cp, unsigned long long int address)
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position)
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num)
static bool cache_fillable_llc (const struct cache_t *const cp, const md_paddr_t paddr)
static void cache_fill_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t *core)
void cache_process_llc (struct cache_t *const cp)
static void cache_prefetch_llc (struct cache_t *const cp)
static void prefetch_controller_update_llc (struct cache_t *const cp)
void step_LLC_PF_controller (struct uncore_t *const uncore)
void prefetch_LLC (struct uncore_t *const uncore)
void uncore_utilize (struct cache_t *const cp)
Function Documentation
struct cache_t* cache_create_llc (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, const int begin_index, const int end_index, struct cache_t *const next_level_cache, struct bus_t *const next_bus) [read]
Definition at line 87 of file config/zesto-llc.cpp.
int cache_enqueuable_llc (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
Definition at line 989 of file config/zesto-llc.cpp.
void cache_enqueue_llc (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*)(void *) cb, void(*)(void *, int) miss_cb, bool(*)(void *, seq_t) translated_cb, seq_t(*)(void *) get_action_id)
Definition at line 1008 of file config/zesto-llc.cpp.
static void cache_fill_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t * core) [inline, static]
Definition at line 1391 of file config/zesto-llc.cpp.
References cache_assert, cache_t::check_for_fill_work, cache_t::check_for_work, cache_fill_t::cmd, cache_fill_t::core, fill_heap_balance(), cache_t::fill_num, cache_t::fill_pipe, GET_BANK, cache_t::latency, cache_fill_t::paddr, cache_fill_t::pipe_exit_time, sim_cycle, and cache_fill_t::valid.
Referenced by cache_process_llc().
static bool cache_fillable_llc (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1379 of file config/zesto-llc.cpp.
References cache_t::fill_num, GET_BANK, and cache_t::latency.
Referenced by cache_process_llc().
struct cache_line_t* cache_get_evictee_llc (struct cache_t *const cp, const md_paddr_t addr, core_t *const core) [read]
Definition at line 751 of file config/zesto-llc.cpp.
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position) [static]
Definition at line 893 of file config/zesto-llc.cpp.
References memswap().
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num) [static]
Definition at line 919 of file config/zesto-llc.cpp.
References cache_action_t::cb, memswap(), cache_action_t::pipe_exit_time, and TICK_T_MAX.
void cache_insert_block_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
Definition at line 653 of file config/zesto-llc.cpp.
struct cache_line_t* cache_is_hit_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 529 of file config/zesto-llc.cpp.
static struct cache_line_t* cache_peek_llc (const struct cache_t *const cp, const md_paddr_t addr) [static, read]
Definition at line 628 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_line_t::next, cache_t::sets, cache_line_t::tag, and cache_line_t::valid.
Referenced by cache_process_llc().
static void cache_prefetch_llc (struct cache_t *const cp) [static]
Definition at line 2179 of file config/zesto-llc.cpp.
References cache_t::cache_t::PFF_t::addr, cache_assert, cache_enqueuable(), cache_enqueue(), CACHE_PREFETCH, cache_t::cache_t::PFF_t::core, DO_NOT_TRANSLATE, dummy_callback(), GET_MSHR_BANK, modinc(), NO_MSHR, cache_t::cache_t::PFF_t::PC, PF_OK, cache_t::PF_sample_interval, cache_t::PF_state, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::prefetch_max, and cache_t::prefetch_threshold.
Referenced by prefetch_LLC().
void cache_process_llc (struct cache_t *const cp)
Definition at line 1422 of file config/zesto-llc.cpp.
static void dummy_callback (void * p) [static]
Definition at line 1238 of file config/zesto-llc.cpp.
void fill_arrived_llc (struct cache_t *const cp, unsigned long long int address)
Definition at line 1245 of file config/zesto-llc.cpp.
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position) [static]
Definition at line 1286 of file config/zesto-llc.cpp.
References memswap(), and cache_action_t::pipe_exit_time.
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num) [static]
Definition at line 1310 of file config/zesto-llc.cpp.
References memswap(), cache_fill_t::pipe_exit_time, TICK_T_MAX, and cache_fill_t::valid.
void LLC_reg_stats (struct stat_sdb_t *const sdb, struct cache_t *const cp)
Definition at line 281 of file config/zesto-llc.cpp.
static struct cache_action_t* MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd) [static, read]
Definition at line 1184 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_assert, cache_action_t::cb, cache_t::check_for_MSHR_work, cache_t::check_for_work, fatal(), GET_MSHR_BANK, cache_t::MSHR, cache_t::MSHR_combos, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, cache_t::MSHR_size, cache_action_t::paddr, cache_t::stat, TICK_T_MAX, and cache_action_t::when_returned.
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1174 of file config/zesto-llc.cpp.
References GET_MSHR_BANK, and cache_t::MSHR_size.
static void prefetch_controller_update_llc (struct cache_t *const cp) [static]
Definition at line 2208 of file config/zesto-llc.cpp.
References cache_t::PF_high_watermark, cache_t::PF_last_sample, PF_OK, PF_REFRAIN, cache_t::PF_sample_interval, cache_t::PF_state, sim_cycle, cache_t::stat, and cache_t::uncore_utilization.
Referenced by step_LLC_PF_controller().
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr) [static]
Definition at line 483 of file config/zesto-llc.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful) [static]
Definition at line 500 of file config/zesto-llc.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
void prefetch_LLC (struct uncore_t *const uncore)
Definition at line 2229 of file config/zesto-llc.cpp.
void step_LLC_PF_controller (struct uncore_t *const uncore)
Definition at line 2223 of file config/zesto-llc.cpp.
void uncore_utilize (struct cache_t *const cp)
Definition at line 2235 of file config/zesto-llc.cpp.
References cache_t::stat, and cache_t::uncore_utilization.
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1082 of file config/zesto-llc.cpp.
References GET_MSHR_BANK, cache_t::WBB_num, and cache_t::WBB_size.
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1092 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_assert, CACHE_STAT, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), modinc(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_combines, cache_t::WBB_head, cache_t::WBB_insertions, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, and cache_t::write_combining.
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1135 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_assert, CACHE_STAT, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, and cache_t::WBB_victim_insertions.