zesto-cache.cpp File Reference
#include <limits.h>
#include `thread.h`
#include `stats.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-cache.h`
#include `zesto-prefetch.h`
#include `zesto-uncore.h`
#include `zesto-exec.h`
#include `zesto-commit.h`
Functions
struct cache_t * cache_create (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, struct cache_t *const next_level_cache, struct bus_t *const next_bus)
void cache_reg_stats (struct stat_sdb_t *const sdb, const struct core_t *const core, struct cache_t *const cp)
void cache_reset_stats (struct cache_t *const cp)
void prefetch_buffer_create (struct cache_t *const cp, const int num_entries)
void prefetch_filter_create (struct cache_t *const cp, const int num_entries, const int reset_interval)
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr)
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful)
struct cache_line_t * cache_is_hit (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
static struct cache_line_t * cache_peek (const struct cache_t *const cp, const md_paddr_t addr)
void cache_insert_block (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
struct cache_line_t * cache_get_evictee (struct cache_t *const cp, const md_paddr_t addr, core_t *const core)
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position)
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num)
int cache_enqueuable (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
void cache_enqueue (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*const cb)(void *), void(*const miss_cb)(void *, int), bool(*const translated_cb)(void *, seq_t), seq_t(*const get_action_id)(void *))
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr)
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr)
static struct cache_action_t * MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd)
static void dummy_callback (void *p)
void fill_arrived (struct cache_t *const cp, const int MSHR_bank, const int MSHR_index)
void print_heap (const struct cache_t *const cp)
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position)
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num)
static bool cache_fillable (const struct cache_t *const cp, const md_paddr_t paddr)
static void cache_fill (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t *core)
void cache_process (struct cache_t *const cp)
static void cache_prefetch (struct cache_t *const cp)
static void prefetch_controller_update (struct cache_t *const cp)
void step_core_PF_controllers (struct core_t *const core)
void prefetch_core_caches (struct core_t *const core)
void cache_freeze_stats (struct core_t *const core)
void cache_print (const struct cache_t *const cp)
struct bus_t * bus_create (const char *const name, const int width, const int ratio)
void bus_reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core, struct bus_t *const bus)
int bus_free (const struct bus_t *const bus)
void bus_use (struct bus_t *const bus, const int transfer_size, const int prefetch)
Function Documentation
struct bus_t* bus_create (const char *const name, const int width, const int ratio) [read]
Definition at line 2465 of file config/zesto-cache.cpp.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), and uncore_t::uncore_t().
int bus_free (const struct bus_t *const bus)
Definition at line 2518 of file config/zesto-cache.cpp.
Referenced by cache_process(), and cache_process_llc().
void bus_reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core, struct bus_t *const bus)
Definition at line 2479 of file config/zesto-cache.cpp.
Referenced by core_exec_STM_t::reg_stats(), and uncore_t::uncore_reg_stats().
void bus_use (struct bus_t *const bus, const int transfer_size, const int prefetch)
Definition at line 2529 of file config/zesto-cache.cpp.
Referenced by cache_process(), and cache_process_llc().
struct cache_t* cache_create (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, struct cache_t *const next_level_cache, struct bus_t *const next_bus) [read]
Definition at line 88 of file config/zesto-cache.cpp.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), and core_fetch_STM_t::core_fetch_STM_t().
int cache_enqueuable (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
Definition at line 1076 of file config/zesto-cache.cpp.
Referenced by cache_prefetch(), cache_prefetch_llc(), cache_process(), core_exec_STM_t::LDQ_schedule(), core_exec_DPM_t::LDQ_schedule(), core_fetch_STM_t::step(), core_fetch_DPM_t::step(), core_exec_STM_t::STQ_deallocate_std(), and core_exec_DPM_t::STQ_deallocate_std().
void cache_enqueue (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*)(void *) cb, void(*)(void *, int) miss_cb, bool(*)(void *, seq_t) translated_cb, seq_t(*)(void *) get_action_id)
Definition at line 1095 of file config/zesto-cache.cpp.
Referenced by cache_prefetch(), cache_prefetch_llc(), cache_process(), core_exec_STM_t::LDQ_schedule(), core_exec_DPM_t::LDQ_schedule(), core_fetch_STM_t::step(), core_fetch_DPM_t::step(), core_exec_STM_t::STQ_deallocate_std(), and core_exec_DPM_t::STQ_deallocate_std().
static void cache_fill (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t * core) [inline, static]
Definition at line 1486 of file config/zesto-cache.cpp.
References cache_assert, cache_t::check_for_fill_work, cache_t::check_for_work, cache_fill_t::cmd, cache_fill_t::core, fill_heap_balance(), cache_t::fill_num, cache_t::fill_pipe, GET_BANK, cache_t::latency, cache_fill_t::paddr, cache_fill_t::pipe_exit_time, sim_cycle, and cache_fill_t::valid.
Referenced by cache_process().
static bool cache_fillable (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1474 of file config/zesto-cache.cpp.
References cache_t::fill_num, GET_BANK, and cache_t::latency.
Referenced by cache_process().
void cache_freeze_stats (struct core_t *const core)
Definition at line 2402 of file config/zesto-cache.cpp.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
struct cache_line_t* cache_get_evictee (struct cache_t *const cp, const md_paddr_t addr, core_t *const core) [read]
Definition at line 840 of file config/zesto-cache.cpp.
Referenced by cache_process(), and sim_fastfwd().
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position) [static]
Definition at line 981 of file config/zesto-cache.cpp.
References memswap().
Referenced by cache_enqueue(), and cache_enqueue_llc().
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num) [static]
Definition at line 1007 of file config/zesto-cache.cpp.
References cache_action_t::cb, memswap(), cache_action_t::pipe_exit_time, and TICK_T_MAX.
Referenced by cache_process(), and cache_process_llc().
void cache_insert_block (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
Definition at line 742 of file config/zesto-cache.cpp.
Referenced by cache_process(), and sim_fastfwd().
struct cache_line_t* cache_is_hit (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 618 of file config/zesto-cache.cpp.
Referenced by cache_process(), and sim_fastfwd().
static struct cache_line_t* cache_peek (const struct cache_t *const cp, const md_paddr_t addr) [static, read]
Definition at line 717 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_line_t::next, cache_t::sets, cache_line_t::tag, and cache_line_t::valid.
Referenced by cache_invalidate(), and cache_process().
static void cache_prefetch (struct cache_t *const cp) [static]
Definition at line 2343 of file config/zesto-cache.cpp.
References cache_t::cache_t::PFF_t::addr, cache_assert, cache_enqueuable(), cache_enqueue(), CACHE_PREFETCH, cache_t::cache_t::PFF_t::core, DO_NOT_TRANSLATE, dummy_callback(), GET_MSHR_BANK, modinc(), NO_MSHR, cache_t::cache_t::PFF_t::PC, PF_OK, cache_t::PF_sample_interval, cache_t::PF_state, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::prefetch_max, and cache_t::prefetch_threshold.
Referenced by prefetch_core_caches().
void cache_print (const struct cache_t *const cp)
Definition at line 2412 of file config/zesto-cache.cpp.
References cache_t::banks, CACHE_READ, CACHE_WRITE, CACHE_WRITEBACK, cache_action_t::cb, cache_action_t::cmd, cache_t::fill_pipe, cache_t::latency, cache_t::MSHR, cache_t::MSHR_size, cache_t::name, cache_action_t::op, cache_fill_t::paddr, cache_t::pipe, and cache_fill_t::valid.
void cache_process (struct cache_t *const cp)
Definition at line 1523 of file config/zesto-cache.cpp.
Referenced by core_exec_STM_t::LDST_exec(), core_exec_DPM_t::LDST_exec(), core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
void cache_reg_stats (struct stat_sdb_t *const sdb, const struct core_t *const core, struct cache_t *const cp)
Definition at line 280 of file config/zesto-cache.cpp.
Referenced by core_fetch_STM_t::reg_stats(), core_fetch_DPM_t::reg_stats(), core_exec_STM_t::reg_stats(), and core_exec_DPM_t::reg_stats().
void cache_reset_stats (struct cache_t *const cp)
Definition at line 515 of file config/zesto-cache.cpp.
Referenced by emergency_recovery(), and sim_fastfwd().
static void dummy_callback (void * p) [static]
Definition at line 1325 of file config/zesto-cache.cpp.
Referenced by cache_prefetch(), cache_prefetch_llc(), and cache_process().
void fill_arrived (struct cache_t *const cp, const int MSHR_bank, const int MSHR_index)
Definition at line 1333 of file config/zesto-cache.cpp.
Referenced by cache_process(), and cache_process_llc().
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position) [static]
Definition at line 1383 of file config/zesto-cache.cpp.
References memswap(), and cache_action_t::pipe_exit_time.
Referenced by cache_fill(), and cache_fill_llc().
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num) [static]
Definition at line 1407 of file config/zesto-cache.cpp.
References memswap(), cache_fill_t::pipe_exit_time, TICK_T_MAX, and cache_fill_t::valid.
Referenced by cache_process(), and cache_process_llc().
static struct cache_action_t* MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd) [static, read]
Definition at line 1271 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_assert, cache_action_t::cb, cache_t::check_for_MSHR_work, cache_t::check_for_work, fatal(), GET_MSHR_BANK, cache_t::MSHR, cache_t::MSHR_combos, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, cache_t::MSHR_size, cache_action_t::paddr, cache_t::stat, TICK_T_MAX, and cache_action_t::when_returned.
Referenced by cache_process(), and cache_process_llc().
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1261 of file config/zesto-cache.cpp.
References GET_MSHR_BANK, and cache_t::MSHR_size.
Referenced by cache_process(), and cache_process_llc().
void prefetch_buffer_create (struct cache_t *const cp, const int num_entries)
Definition at line 531 of file config/zesto-cache.cpp.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), and uncore_t::uncore_t().
static void prefetch_controller_update (struct cache_t *const cp) [static]
Definition at line 2372 of file config/zesto-cache.cpp.
References cache_t::next_bus, cache_t::PF_high_watermark, cache_t::PF_last_sample, PF_OK, PF_REFRAIN, cache_t::PF_sample_interval, cache_t::PF_state, sim_cycle, bus_t::stat, and bus_t::utilization.
Referenced by step_core_PF_controllers().
void prefetch_core_caches (struct core_t *const core)
Definition at line 2395 of file config/zesto-cache.cpp.
Referenced by zesto_component::downtick_handler().
void prefetch_filter_create (struct cache_t *const cp, const int num_entries, const int reset_interval)
Definition at line 552 of file config/zesto-cache.cpp.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), and uncore_t::uncore_t().
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr) [static]
Definition at line 574 of file config/zesto-cache.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
Referenced by cache_process(), and cache_process_llc().
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful) [static]
Definition at line 591 of file config/zesto-cache.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
Referenced by cache_process(), and cache_process_llc().
void print_heap (const struct cache_t *const cp)
Definition at line 1367 of file config/zesto-cache.cpp.
References cache_t::banks, cache_t::name, cache_t::pipe, cache_action_t::pipe_exit_time, and cache_t::pipe_num.
void step_core_PF_controllers (struct core_t *const core)
Definition at line 2387 of file config/zesto-cache.cpp.
Referenced by zesto_component::downtick_handler().
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1169 of file config/zesto-cache.cpp.
References GET_MSHR_BANK, cache_t::WBB_num, and cache_t::WBB_size.
Referenced by cache_process(), and cache_process_llc().
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1179 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_assert, CACHE_STAT, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), modinc(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_combines, cache_t::WBB_head, cache_t::WBB_insertions, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, and cache_t::write_combining.
Referenced by cache_process(), and cache_process_llc().
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1222 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_assert, CACHE_STAT, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, and cache_t::WBB_victim_insertions.
Referenced by cache_process().