main.cc File Reference
#include <string>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <fstream>
#include <map>
#include `../kernel/component.h`
#include `../kernel/simulator.h`
#include `../data_types/impl/irisEvent.h`
#include `../MemCtrl/request.h`
#include `../MemCtrl/request_handler.h`
#include `../MemCtrl/bus_handler.h`
#include `../MemCtrl/bus.h`
#include `../MemCtrl/dram.h`
#include `../MemCtrl/NI.h`
#include `../MemCtrl/refresh_manager.h`
#include `../MemCtrl/response_handler.h`
#include `../MemCtrl/MC.h`
#include `../MemCtrl/mshr.h`
Functions
bool GetNextRequest (MSHR_H mshrHandler[], Request *req, unsigned int *index)
int main (int argc, char **argv)
Function Documentation
bool GetNextRequest (MSHR_H mshrHandler[], Request * req, unsigned int * index)
Definition at line 43 of file main.cc.
References MSHR_H::lastScheduledIndex, MSHR_H::mshr, NO_OF_THREADS, and MSHR_H::writeQueue.
int main (int argc, char ** argv)
Definition at line 100 of file main.cc.
References Request::address, Request::arrivalTime, Statistic::CalculateAggregateStats(), Request::cmdType, Statistic::CollectStatsPerCycle(), MSHR_H::done, Statistic::doneOnce, IrisEvent::dst, IrisEvent::event_data, MSHR_H::filename, GetNextRequest(), MSHR_H::GlobalAddrMap(), MSHR_H::globalUnSink, Simulator::halted, MSHR_H::id, mshrHandler, MC::ni, NO_OF_THREADS, Simulator::Now(), RequestHandler::oneBufferFull, Statistic::PrintAggregateStats(), RequestHandler::process_event(), MSHR_H::process_event(), MC::reqH, Simulator::Run(), Simulator::Schedule(), IrisEvent::src, START, MC::stats, Simulator::StopAt(), Request::threadId, MSHR_H::trace_filename, IrisEvent::type, and MSHR_H::unsink.