manifold_fullsim.cc File Reference
#include `mesh.h`
#include `../../zesto/zesto-uncore.h`
#include `../../util/config_params.h`
Functions
void print_state_at_deadlock (void)
static void signal_sim_stats (int sigtype)
static void signal_exit_now (int sigtype)
static int orphan_fn (int i, int argc, char **argv)
static void banner (FILE *fd, int argc, char **argv)
static void usage (FILE *fd, int argc, char **argv)
void sim_print_stats (FILE *fd)
static void exit_now (int exit_code)
unsigned int iris_process_options (int argc, char *argv[])
void iris_init ()
int main (int argc, char *argv[])
Variables
string data
string word
unsigned int cores_per_node = 1
Mesh * mesh
char * s
int exit_code
time_t sim_start_time
time_t sim_end_time
int sim_elapsed_time
int sim_swap_bytes
int sim_swap_words
int sim_exit_now = FALSE
jmp_buf sim_exit_buf
int sim_dump_stats = FALSE
struct opt_odb_t * sim_odb
struct stat_sdb_t * sim_sdb
char * sim_simout = NULL
char * sim_progout = NULL
FILE * sim_progfd = NULL
static int exec_index = -1
bool help_me
int rand_seed
bool init_quit
int nice_priority
static int running = FALSE
Function Documentation
static void banner (FILE * fd, int argc, char ** argv) [static]
Definition at line 128 of file manifold_fullsim.cc.
References s, VER_MAJOR, VER_MINOR, and VER_UPDATE.
Referenced by main().
static void exit_now (int exit_code) [static]
Definition at line 237 of file manifold_fullsim.cc.
References sim_print_stats(), and sim_uninit().
Referenced by main().
void iris_init ()
Definition at line 422 of file manifold_fullsim.cc.
References buffer_size, Mesh::connect_interface_processor(), Mesh::connect_interface_routers(), Mesh::connect_routers(), credits, grid_size, Mesh::init(), Mesh::interfaces, Mesh::link_a, Mesh::link_b, links, max_sim_time, Mesh::max_sim_time, mc_positions, no_nodes, ports, print_setup, Mesh::processors, Mesh::routers, Mesh::setup(), uncores, and vcs.
Referenced by main().
unsigned int iris_process_options (int argc, char * argv[])
Definition at line 250 of file manifold_fullsim.cc.
References BANK_BITS, buffer_size, cores_per_node, credits, data, do_two_stage_router, FCFS, grid_size, links, max_phy_link_bits, max_sim_time, MC_ADDR_BITS, mc_positions, msg_type_string, NEGATIVE_FIRST, no_mcs, no_nodes, NORTH_LAST, NORTH_LAST_NON_MINIMAL, ODD_EVEN, ONE_FLIT_REQ, output_path, ports, print_setup, priority_msg_type, PRIORITY_REQ, rc_method, RESPONSE_PKT, ROUND_ROBIN, ROUND_ROBIN_PRIORITY, routing_scheme, sw_arbitration, sw_arbitration_scheme, THREAD_BITS_POSITION, traces, vcs, WEST_FIRST, word, and XY.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 558 of file manifold_fullsim.cc.
References banner(), cores_per_node, exec_index, exit_code, exit_now(), fatal(), fatal_hook(), help_me, init_quit, iris_init(), iris_process_options(), md_init_decoder(), mysrand(), nice_priority, no_nodes, num_threads, opt_new(), opt_print_options(), opt_process_options(), orphan_fn(), rand_seed, Simulator::Run(), running, signal_exit_now(), signal_sim_stats(), sim_aux_config(), sim_check_options(), sim_exit_buf, sim_main(), sim_post_init(), sim_pre_init(), sim_print_stats(), sim_progfd, sim_progout, sim_reg_options(), sim_reg_stats(), sim_simout, sim_start_time, stat_new(), Simulator::StopAt(), threads, TRUE, usage(), and zesto_component::zesto_component().
static int orphan_fn (int i, int argc, char ** argv) [static]
Definition at line 121 of file manifold_fullsim.cc.
References exec_index, and FALSE.
Referenced by main().
void print_state_at_deadlock (void)
Definition at line 154 of file manifold_fullsim.cc.
References no_nodes, and Mesh::routers.
static void signal_exit_now (int sigtype) [static]
Definition at line 70 of file manifold_fullsim.cc.
References sim_exit_now, and TRUE.
Referenced by main().
static void signal_sim_stats (int sigtype) [static]
Definition at line 63 of file manifold_fullsim.cc.
References sim_dump_stats, and TRUE.
Referenced by main().
void sim_print_stats (FILE * fd)
Definition at line 164 of file manifold_fullsim.cc.
References Mesh::interfaces, Mesh::link_a, Mesh::link_b, links, MAX, max_phy_link_bits, max_sim_time, no_nodes, running, sim_aux_stats(), sim_elapsed_time, sim_end_time, and sim_start_time.
Referenced by exit_now(), and main().
static void usage (FILE * fd, int argc, char ** argv) [static]
Definition at line 144 of file manifold_fullsim.cc.
References opt_print_help().
Referenced by main().
Variable Documentation
unsigned int cores_per_node = 1
Definition at line 48 of file manifold_fullsim.cc.
Referenced by iris_process_options(), main(), sim_post_init(), and uncore_t::uncore_t().
string data
Definition at line 47 of file manifold_fullsim.cc.
Referenced by GenericRouterVct::do_switch_traversal(), GenericRouterVcs::do_switch_traversal(), GenericRouterNoVcs::do_switch_traversal(), GenericRouterAdaptive::do_switch_traversal(), GenericRouterVct::handle_link_arrival_event(), GenericRouterVcs::handle_link_arrival_event(), GenericRouterNoVcs::handle_link_arrival_event(), GenericLink::handle_link_arrival_event(), GenericRouterAdaptive::handle_link_arrival_event_multiple_flit_in_buffer(), GenericRouterAdaptive::handle_link_arrival_event_one_msg_per_buffer(), iris_process_options(), main(), HeadFlit::populate_head_flit(), TailFlit::populate_tail_flit(), GenericRouterVct::send_credit_back(), GenericRouterVcs::send_credit_back(), GenericRouterNoVcs::send_credit_back(), and GenericRouterAdaptive::send_credit_back().
int exec_index = -1 [static]
Definition at line 105 of file manifold_fullsim.cc.
Referenced by main(), and orphan_fn().
int exit_code
Definition at line 59 of file manifold_fullsim.cc.
Referenced by main().
bool help_me
Definition at line 108 of file manifold_fullsim.cc.
Referenced by main().
bool init_quit
Definition at line 114 of file manifold_fullsim.cc.
Referenced by main().
Mesh* mesh
Definition at line 55 of file manifold_fullsim.cc.
int nice_priority
Definition at line 117 of file manifold_fullsim.cc.
Referenced by main().
int rand_seed
Definition at line 111 of file manifold_fullsim.cc.
Referenced by main().
int running = FALSE [static]
Definition at line 150 of file manifold_fullsim.cc.
Referenced by main(), and sim_print_stats().
char* s
Definition at line 58 of file manifold_fullsim.cc.
Referenced by banner().
int sim_dump_stats = FALSE
Definition at line 91 of file manifold_fullsim.cc.
Referenced by signal_sim_stats().
int sim_elapsed_time
Definition at line 78 of file manifold_fullsim.cc.
Referenced by sim_print_stats().
time_t sim_end_time
Definition at line 77 of file manifold_fullsim.cc.
Referenced by sim_print_stats().
jmp_buf sim_exit_buf
Definition at line 88 of file manifold_fullsim.cc.
Referenced by main(), md_fetch_inst(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
int sim_exit_now = FALSE
Definition at line 85 of file manifold_fullsim.cc.
Referenced by signal_exit_now().
struct opt_odb_t* sim_odb
Definition at line 94 of file manifold_fullsim.cc.
FILE* sim_progfd = NULL
Definition at line 102 of file manifold_fullsim.cc.
Referenced by main().
char* sim_progout = NULL
Definition at line 101 of file manifold_fullsim.cc.
Referenced by main().
struct stat_sdb_t* sim_sdb
Definition at line 97 of file manifold_fullsim.cc.
char* sim_simout = NULL
Definition at line 100 of file manifold_fullsim.cc.
Referenced by main().
time_t sim_start_time
Definition at line 76 of file manifold_fullsim.cc.
Referenced by main(), sim_main(), and sim_print_stats().
int sim_swap_bytes
Definition at line 81 of file manifold_fullsim.cc.
int sim_swap_words
Definition at line 82 of file manifold_fullsim.cc.
string word
Definition at line 47 of file manifold_fullsim.cc.
Referenced by iris_process_options(), and main().