misc.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <sys/types.h>
Defines
#define TRUE 1
#define FALSE 0
#define MAX(a, b) (((a) < (b)) ? (b) : (a))
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
#define LLHIGH(L) ((int)(((L)>>32) & 0xffffffff))
#define LLLOW(L) ((int)((L) & 0xffffffff))
#define N_ELT(ARR) (sizeof(ARR)/sizeof((ARR)[0]))
#define ROUND_UP(N, ALIGN) (((N) + ((ALIGN)-1)) & ~((ALIGN)-1))
#define ROUND_DOWN(N, ALIGN) ((N) & ~((ALIGN)-1))
Functions
void fatal_hook (void(*hook_fn)(FILE *stream))
void fatal (const char *fmt,...)
void panic (const char *fmt,...)
void warn (const char *fmt,...)
void info (const char *fmt,...)
static void debug (const char *fmt,...)
void mysrand (const unsigned int seed)
int myrand (void)
char mytoupper (char c)
char mytolower (char c)
bool myisalpha (char c)
bool myisdigit (char c)
bool myisspace (char c)
bool myisprint (char c)
char * mystrdup (const char *s)
const char * mystrrchr (const char *s, const char c)
int mystricmp (const char *s1, const char *s2)
int log_base2 (const int n)
char * elapsed_time (long sec)
char * myvsprintf (char *obuf, const char *format, va_list v)
char * mysprintf (char *obuf, const char *format,...)
void myvfprintf (FILE *stream, const char *format, va_list v)
void myfprintf (FILE *stream, const char *format,...)
FILE * gzopen (const char *fname, const char *type)
void gzclose (FILE *fd)
int modinc (int x, int m)
int moddec (int x, int m)
int mod2m (int x, int m)
void memzero (void *base, int bytes)
void clear_page (void *base)
void memswap (void *p1, void *p2, size_t num_bytes)
Define Documentation
#define FALSE 0
Definition at line 139 of file misc.h.
Referenced by orphan_fn().
#define LLHIGH(L) ((int)(((L)>>32) & 0xffffffff))
Definition at line 151 of file misc.h.
#define LLLOW(L) ((int)((L) & 0xffffffff))
Definition at line 152 of file misc.h.
#define MAX(a, b) (((a) < (b)) ? (b) : (a))
Definition at line 144 of file misc.h.
#define MIN(a, b) (((a) < (b)) ? (a) : (b))
Definition at line 147 of file misc.h.
#define N_ELT(ARR) (sizeof(ARR)/sizeof((ARR)[0]))
Definition at line 155 of file misc.h.
#define ROUND_DOWN(N, ALIGN) ((N) & ~((ALIGN)-1))
Definition at line 159 of file misc.h.
#define ROUND_UP(N, ALIGN) (((N) + ((ALIGN)-1)) & ~((ALIGN)-1))
Definition at line 158 of file misc.h.
#define TRUE 1
Definition at line 136 of file misc.h.
Referenced by main(), signal_exit_now(), and signal_sim_stats().
Function Documentation
void clear_page (void * base)
static void debug (const char * fmt, ...) [static]
Definition at line 258 of file misc.h.
char* elapsed_time (long sec)
void fatal (const char * fmt, ...)
Referenced by alloc_create(), bpred_2bC_t::bpred_2bC_t(), bpred_2lev_t::bpred_2lev_t(), bpred_alloyedperceptron_t::bpred_alloyedperceptron_t(), bpred_bimode_t::bpred_bimode_t(), bpred_blg_t::bpred_blg_t(), bpred_btfnt_t::bpred_btfnt_t(), bpred_from_string(), bpred_nottaken_t::bpred_nottaken_t(), bpred_pathneural_t::bpred_pathneural_t(), bpred_perceptron_t::bpred_perceptron_t(), bpred_perfect_t::bpred_perfect_t(), bpred_pwl_t::bpred_pwl_t(), bpred_random_t::bpred_random_t(), bpred_skewed_t::bpred_skewed_t(), bpred_t::bpred_t(), bpred_tage_t::bpred_tage_t(), bpred_taken_t::bpred_taken_t(), bpred_yags_t::bpred_yags_t(), BTB_2levbtac_t::BTB_2levbtac_t(), BTB_btac_t::BTB_btac_t(), BTB_from_string(), BTB_perfect_t::BTB_perfect_t(), bus_create(), cache_create(), cache_create_llc(), cache_get_evictee(), cache_get_evictee_llc(), cache_insert_block(), cache_insert_block_llc(), cache_invalidate(), cache_is_hit(), cache_is_hit_llc(), cache_process(), cache_process_llc(), cache_reg_stats(), core_oracle_t::commit(), commit_create(), core_alloc_DPM_t::core_alloc_DPM_t(), core_alloc_STM_t::core_alloc_STM_t(), core_commit_DPM_t::core_commit_DPM_t(), core_commit_STM_t::core_commit_STM_t(), core_decode_DPM_t::core_decode_DPM_t(), core_decode_STM_t::core_decode_STM_t(), core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), core_fetch_STM_t::core_fetch_STM_t(), core_oracle_t::core_oracle_t(), decode_create(), dram_from_string(), dram_simplescalar_t::dram_simplescalar_t(), dram_simplesdram_t::dram_simplesdram_t(), emergency_recovery(), core_oracle_t::exec(), exec_create(), fetch_create(), fusion_colt_t::fusion_colt_t(), fusion_from_string(), fusion_mcfarling_t::fusion_mcfarling_t(), fusion_multihybrid_t::fusion_multihybrid_t(), fusion_oracle_t::fusion_oracle_t(), fusion_priority_t::fusion_priority_t(), fusion_random_t::fusion_random_t(), fusion_singleton_t::fusion_singleton_t(), BTB_t::get_cache(), fusion_t::get_cache(), bpred_dir_t::get_cache(), core_oracle_t::get_map_node(), core_t::get_odep_link(), core_exec_STM_t::get_readyQ_node(), core_exec_DPM_t::get_readyQ_node(), core_oracle_t::get_spec_mem_node(), bpred_t::get_state_cache(), core_t::get_uop_array(), bpred_t::init_state_cache_pool(), core_fetch_STM_t::jeclear_enqueue(), main(), MC_from_string(), MC_simple_t::MC_simple_t(), memdep_blind_t::memdep_blind_t(), memdep_create(), memdep_lwt_t::memdep_lwt_t(), memdep_none_t::memdep_none_t(), memdep_oracle_t::memdep_oracle_t(), memdep_t::memdep_t(), MSHR_allocate(), prefetch_buffer_create(), prefetch_context_t::prefetch_context_t(), prefetch_create(), prefetch_filter_create(), prefetch_IP_t::prefetch_IP_t(), prefetch_nextline_t::prefetch_nextline_t(), prefetch_stream_t::prefetch_stream_t(), RAS_from_string(), RAS_perfect_t::RAS_perfect_t(), RAS_stack_t::RAS_stack_t(), core_oracle_t::recover(), bpred_t::return_state_cache(), core_commit_STM_t::ROB_fuse_insert(), core_exec_STM_t::RS_fuse_insert(), service_coherence_msg(), uncore_t::setup(), sim_main(), sim_post_init(), core_exec_DPM_t::snatch_back(), core_exec_STM_t::STQ_deallocate_senior(), core_exec_STM_t::STQ_squash_senior(), core_oracle_t::syscall_mem_access(), uncore_t::uncore_t(), core_decode_STM_t::uop_consume(), and core_decode_STM_t::uop_peek().
void fatal_hook (void(*)(FILE *stream) hook_fn)
Referenced by main().
void gzclose (FILE * fd)
FILE* gzopen (const char * fname, const char * type)
void info (const char * fmt, ...)
int log_base2 (const int n)
Referenced by bpred_2lev_t::bpred_2lev_t(), bpred_alloyedperceptron_t::bpred_alloyedperceptron_t(), bpred_bimode_t::bpred_bimode_t(), bpred_blg_t::bpred_blg_t(), bpred_pathneural_t::bpred_pathneural_t(), bpred_perceptron_t::bpred_perceptron_t(), bpred_pwl_t::bpred_pwl_t(), bpred_skewed_t::bpred_skewed_t(), bpred_tage_t::bpred_tage_t(), bpred_yags_t::bpred_yags_t(), BTB_2levbtac_t::BTB_2levbtac_t(), BTB_btac_t::BTB_btac_t(), dram_simplesdram_t::dram_simplesdram_t(), fusion_colt_t::fusion_colt_t(), and prefetch_context_t::prefetch_context_t().
void memswap (void * p1, void * p2, size_t num_bytes)
Referenced by core_exec_STM_t::ALU_heap_balance(), core_exec_STM_t::ALU_heap_remove(), cache_heap_balance(), cache_heap_remove(), fill_heap_balance(), and fill_heap_remove().
void memzero (void * base, int bytes)
Referenced by cache_reset_stats(), core_t::core_t(), core_exec_STM_t::LDQ_insert(), core_exec_DPM_t::LDQ_insert(), core_exec_STM_t::LDQ_squash(), core_exec_DPM_t::LDQ_squash(), core_fetch_DPM_t::recover(), core_decode_DPM_t::recover_uopQ(), sim_fastfwd(), sim_pre_init(), core_exec_STM_t::STQ_insert_sta(), core_exec_DPM_t::STQ_insert_sta(), core_exec_DPM_t::STQ_squash_senior(), core_exec_STM_t::STQ_squash_sta(), and core_exec_DPM_t::STQ_squash_sta().
int mod2m (int x, int m) [inline]
Definition at line 355 of file misc.h.
Referenced by zesto_component::downtick_handler(), WBB_insert(), and WBB_victim_insert().
int moddec (int x, int m) [inline]
Definition at line 346 of file misc.h.
Referenced by core_fetch_STM_t::byteQ_already_requested(), core_fetch_DPM_t::byteQ_already_requested(), core_exec_STM_t::check_load_issue_conditions(), core_exec_DPM_t::check_load_issue_conditions(), core_oracle_t::complete_flush(), core_exec_STM_t::LDQ_insert(), core_exec_DPM_t::LDQ_insert(), core_exec_STM_t::LDQ_squash(), core_exec_DPM_t::LDQ_squash(), core_exec_STM_t::LDST_exec(), core_exec_DPM_t::LDST_exec(), core_oracle_t::pipe_flush(), core_oracle_t::recover(), core_commit_STM_t::recover(), core_commit_DPM_t::recover(), core_decode_DPM_t::recover_uopQ(), core_fetch_STM_t::step(), core_fetch_DPM_t::step(), core_exec_STM_t::STQ_insert_std(), core_exec_DPM_t::STQ_insert_std(), core_exec_STM_t::STQ_squash_sta(), and core_exec_DPM_t::STQ_squash_sta().
int modinc (int x, int m) [inline]
Definition at line 337 of file misc.h.
Referenced by core_exec_STM_t::ALU_exec(), core_exec_DPM_t::ALU_exec(), core_fetch_STM_t::byteQ_request(), core_fetch_DPM_t::byteQ_request(), cache_get_evictee(), cache_get_evictee_llc(), cache_prefetch(), cache_prefetch_llc(), cache_process(), cache_process_llc(), core_exec_STM_t::check_load_issue_conditions(), core_exec_DPM_t::check_load_issue_conditions(), core_oracle_t::commit(), zesto_component::downtick_handler(), core_oracle_t::exec(), core_exec_STM_t::LDQ_deallocate(), core_exec_DPM_t::LDQ_deallocate(), core_exec_STM_t::LDQ_insert(), core_exec_DPM_t::LDQ_insert(), core_exec_STM_t::LDQ_schedule(), core_exec_DPM_t::LDQ_schedule(), core_fetch_STM_t::Mop_consume(), core_fetch_DPM_t::Mop_consume(), core_oracle_t::next_index(), core_commit_STM_t::ROB_insert(), core_commit_DPM_t::ROB_insert(), core_fetch_STM_t::step(), core_fetch_DPM_t::step(), core_decode_DPM_t::step(), core_commit_STM_t::step(), core_commit_DPM_t::step(), core_exec_DPM_t::STQ_deallocate_senior(), core_exec_STM_t::STQ_deallocate_std(), core_exec_DPM_t::STQ_deallocate_std(), core_exec_STM_t::STQ_insert_sta(), core_exec_DPM_t::STQ_insert_sta(), core_exec_DPM_t::STQ_squash_senior(), core_decode_DPM_t::uop_consume(), and WBB_insert().
void myfprintf (FILE * stream, const char * format, ...)
bool myisalpha (char c)
bool myisdigit (char c)
bool myisprint (char c)
bool myisspace (char c)
int myrand (void)
char* mysprintf (char * obuf, const char * format, ...)
void mysrand (const unsigned int seed)
Referenced by main().
char* mystrdup (const char * s)
int mystricmp (const char * s1, const char * s2)
const char* mystrrchr (const char * s, const char c)
char mytolower (char c)
Referenced by BTB_2levbtac_t::BTB_2levbtac_t(), and BTB_btac_t::BTB_btac_t().
char mytoupper (char c)
Referenced by cache_create(), cache_create_llc(), core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), and uncore_t::uncore_t().
void myvfprintf (FILE * stream, const char * format, va_list v)
char* myvsprintf (char * obuf, const char * format, va_list v)
void panic (const char * fmt, ...)
Referenced by core_oracle_t::exec().
void warn (const char * fmt, ...)
Referenced by core_oracle_t::exec(), core_exec_STM_t::LDST_exec(), core_exec_DPM_t::LDST_exec(), core_exec_STM_t::load_writeback(), core_exec_DPM_t::load_writeback(), core_commit_STM_t::step(), and core_commit_DPM_t::step().