options.h File Reference
Classes
struct opt_opt_t
union opt_opt_t::opt_opt_t::opt_variant_t
struct opt_opt_t::opt_opt_t::opt_variant_t::opt_opt_t::opt_variant_t::opt_for_int_t
struct opt_opt_t::opt_opt_t::opt_variant_t::opt_opt_t::opt_variant_t::opt_for_uint_t
struct opt_opt_t::opt_opt_t::opt_variant_t::opt_opt_t::opt_variant_t::opt_for_float_t
struct opt_opt_t::opt_opt_t::opt_variant_t::opt_opt_t::opt_variant_t::opt_for_double_t
struct opt_opt_t::opt_opt_t::opt_variant_t::opt_opt_t::opt_variant_t::opt_for_enum_t
struct opt_opt_t::opt_opt_t::opt_variant_t::opt_opt_t::opt_variant_t::opt_for_string_t
struct opt_opt_t::opt_opt_t::opt_variant_t::opt_opt_t::opt_variant_t::opt_for_long_long_t
struct opt_note_t
struct opt_odb_t
Typedefs
typedef int(* orphan_fn_t)(int i, int argc, char **argv)
Enumerations
enum opt_class_t {
oc_int = 0,
oc_uint,
oc_float,
oc_double,
oc_enum,
oc_flag,
oc_string,
oc_long_long,
oc_NUM
 }
Functions
struct opt_odb_t * opt_new (orphan_fn_t orphan_fn)
void opt_delete (struct opt_odb_t *odb)
void opt_reg_long_long (struct opt_odb_t *odb, char *name, char *desc, long long *var, long long def_val, int print, char *format)
void opt_reg_int (struct opt_odb_t *odb, char *name, char *desc, int *var, int def_val, int print, char *format)
void opt_reg_int_list (struct opt_odb_t *odb, char *name, char *desc, int *vars, int nvars, int *nelt, int *def_val, int print, char *format, int accrue)
void opt_reg_uint (struct opt_odb_t *odb, char *name, char *desc, unsigned int *var, unsigned int def_val, int print, char *format)
void opt_reg_uint_list (struct opt_odb_t *odb, char *name, char *desc, unsigned int *vars, int nvars, int *nelt, unsigned int *def_val, int print, char *format, int accrue)
void opt_reg_float (struct opt_odb_t *odb, char *name, char *desc, float *var, float def_val, int print, char *format)
void opt_reg_float_list (struct opt_odb_t *odb, char *name, char *desc, float *vars, int nvars, int *nelt, float *def_val, int print, char *format, int accrue)
void opt_reg_double (struct opt_odb_t *odb, char *name, char *desc, double *var, double def_val, int print, char *format)
void opt_reg_double_list (struct opt_odb_t *odb, char *name, char *desc, double *vars, int nvars, int *nelt, double *def_val, int print, char *format, int accrue)
void opt_reg_enum (struct opt_odb_t *odb, char *name, char *desc, int *var, char *def_val, char **emap, int *eval, int emap_sz, int print, char *format)
void opt_reg_enum_list (struct opt_odb_t *odb, char *name, char *desc, int *vars, int nvars, int *nelt, char *def_val, char **emap, int *eval, int emap_sz, int print, char *format, int accrue)
void opt_reg_flag (struct opt_odb_t *odb, char *name, char *desc, bool *var, bool def_val, int print, char *format)
void opt_reg_flag_list (struct opt_odb_t *odb, char *name, char *desc, bool *vars, int nvars, int *nelt, bool *def_val, int print, char *format, int accrue)
void opt_reg_string (struct opt_odb_t *odb, char *name, char *desc, char **var, char *def_val, int print, char *format)
void opt_reg_string_list (struct opt_odb_t *odb, char *name, char *desc, char **vars, int nvars, int *nelt, char **def_val, int print, char *format, int accrue)
void opt_process_options (struct opt_odb_t *odb, int argc, char **argv)
void opt_print_option (struct opt_opt_t *opt, FILE *fd)
void opt_print_options (struct opt_odb_t *odb, FILE *fd, int terse, int notes)
void opt_print_help (struct opt_odb_t *odb, FILE *fd)
struct opt_opt_t * opt_find_option (struct opt_odb_t *odb, char *opt_name)
void opt_reg_header (struct opt_odb_t *odb, char *header)
void opt_reg_note (struct opt_odb_t *odb, char *note)
Variables
bool opt_ignore_notes
Typedef Documentation
typedef int(* orphan_fn_t)(int i,int argc,char **argv)
Definition at line 133 of file options.h.
Enumeration Type Documentation
enum opt_class_t
Enumerator:
oc_int
oc_uint
oc_float
oc_double
oc_enum
oc_flag
oc_string
oc_long_long
oc_NUM
Definition at line 73 of file options.h.
Function Documentation
void opt_delete (struct opt_odb_t * odb)
struct opt_opt_t* opt_find_option (struct opt_odb_t * odb, char * opt_name) [read]
struct opt_odb_t* opt_new (orphan_fn_t orphan_fn) [read]
Referenced by main().
void opt_print_help (struct opt_odb_t * odb, FILE * fd)
Referenced by usage().
void opt_print_option (struct opt_opt_t * opt, FILE * fd)
void opt_print_options (struct opt_odb_t * odb, FILE * fd, int terse, int notes)
Referenced by main().
void opt_process_options (struct opt_odb_t * odb, int argc, char ** argv)
Referenced by main().
void opt_reg_double (struct opt_odb_t * odb, char * name, char * desc, double * var, double def_val, int print, char * format)
Referenced by exec_reg_options(), fetch_reg_options(), and uncore_reg_options().
void opt_reg_double_list (struct opt_odb_t * odb, char * name, char * desc, double * vars, int nvars, int * nelt, double * def_val, int print, char * format, int accrue)
void opt_reg_enum (struct opt_odb_t * odb, char * name, char * desc, int * var, char * def_val, char ** emap, int * eval, int emap_sz, int print, char * format)
void opt_reg_enum_list (struct opt_odb_t * odb, char * name, char * desc, int * vars, int nvars, int * nelt, char * def_val, char ** emap, int * eval, int emap_sz, int print, char * format, int accrue)
void opt_reg_flag (struct opt_odb_t * odb, char * name, char * desc, bool * var, bool def_val, int print, char * format)
Referenced by alloc_reg_options(), decode_reg_options(), exec_reg_options(), fetch_reg_options(), and uncore_reg_options().
void opt_reg_flag_list (struct opt_odb_t * odb, char * name, char * desc, bool * vars, int nvars, int * nelt, bool * def_val, int print, char * format, int accrue)
void opt_reg_float (struct opt_odb_t * odb, char * name, char * desc, float * var, float def_val, int print, char * format)
void opt_reg_float_list (struct opt_odb_t * odb, char * name, char * desc, float * vars, int nvars, int * nelt, float * def_val, int print, char * format, int accrue)
void opt_reg_header (struct opt_odb_t * odb, char * header)
void opt_reg_int (struct opt_odb_t * odb, char * name, char * desc, int * var, int def_val, int print, char * format)
Referenced by alloc_reg_options(), commit_reg_options(), decode_reg_options(), exec_reg_options(), fetch_reg_options(), and uncore_reg_options().
void opt_reg_int_list (struct opt_odb_t * odb, char * name, char * desc, int * vars, int nvars, int * nelt, int * def_val, int print, char * format, int accrue)
Referenced by decode_reg_options(), and exec_reg_options().
void opt_reg_long_long (struct opt_odb_t * odb, char * name, char * desc, long long * var, long long def_val, int print, char * format)
void opt_reg_note (struct opt_odb_t * odb, char * note)
void opt_reg_string (struct opt_odb_t * odb, char * name, char * desc, char ** var, char * def_val, int print, char * format)
Referenced by dram_reg_options(), exec_reg_options(), fetch_reg_options(), and uncore_reg_options().
void opt_reg_string_list (struct opt_odb_t * odb, char * name, char * desc, char ** vars, int nvars, int * nelt, char ** def_val, int print, char * format, int accrue)
Referenced by exec_reg_options(), fetch_reg_options(), and uncore_reg_options().
void opt_reg_uint (struct opt_odb_t * odb, char * name, char * desc, unsigned int * var, unsigned int def_val, int print, char * format)
void opt_reg_uint_list (struct opt_odb_t * odb, char * name, char * desc, unsigned int * vars, int nvars, int * nelt, unsigned int * def_val, int print, char * format, int accrue)
Variable Documentation
bool opt_ignore_notes