sim.h File Reference
#include <stdint.h>
#include <stdio.h>
#include <setjmp.h>
#include <time.h>
#include `options.h`
#include `stats.h`
#include `regs.h`
#include `memory.h`
#include `thread.h`
#include `../kernel/clock.h`
Classes
class zesto_component
Defines
#define NICE_DEFAULT_VALUE 0
Functions
void sim_reg_options (struct opt_odb_t *odb)
void sim_check_options (struct opt_odb_t *odb, int argc, char **argv)
void sim_reg_stats (struct thread_t **cores, struct stat_sdb_t *sdb)
void sim_pre_init (void)
void sim_post_init (void)
void sim_aux_config (FILE *stream)
void sim_main (void)
void sim_aux_stats (FILE *stream)
void sim_uninit (void)
void sim_print_stats (FILE *fd)
Variables
double cpu_speed
int sim_dump_stats
int sim_exit_now
jmp_buf sim_exit_buf
int sim_swap_bytes
int sim_swap_words
time_t sim_start_time
time_t sim_end_time
int sim_elapsed_time
struct opt_odb_t * sim_odb
struct stat_sdb_t * sim_sdb
char * sim_eio_fname [MAX_CORES]
FILE * sim_eio_fd [MAX_CORES]
FILE * sim_progfd
bool help_me
int rand_seed
bool init_quit
int nice_priority
char * sim_simout
char * sim_progout
unsigned int vcs
unsigned int ports
unsigned int buffer_size
unsigned int credits
unsigned int no_nodes
unsigned int no_mcs
unsigned long long int max_sim_time
unsigned int MC_ADDR_BITS
unsigned int BANK_BITS
unsigned int THREAD_BITS_POSITION
unsigned int do_two_stage_router
unsigned int max_phy_link_bits
unsigned int print_setup
unsigned int grid_size
unsigned int cores_per_node
Define Documentation
#define NICE_DEFAULT_VALUE 0
Definition at line 115 of file sim.h.
Function Documentation
void sim_aux_config (FILE * stream)
Definition at line 423 of file sim-zesto.cpp.
void sim_aux_stats (FILE * stream)
Definition at line 430 of file sim-zesto.cpp.
void sim_check_options (struct opt_odb_t * odb, int argc, char ** argv)
Referenced by main().
void sim_main (void)
Definition at line 1006 of file sim-zesto.cpp.
References core_t::current_thread, fastfwd, fatal(), core_t::fetch, MD_FETCH_NEXT_PC, num_threads, core_fetch_t::PC, thread_t::pin_trace, thread_t::regs, regs_t::regs_NPC, regs_t::regs_PC, sim_fastfwd(), sim_start_time, store_nextPC, and use_stored_nextPC.
Referenced by main().
void sim_post_init (void)
Definition at line 330 of file sim-zesto.cpp.
References thread_t::active, core_t::alloc, alloc_create(), BOOT_PC, core_t::commit, commit_create(), uncore_t::core, core_t::core_t(), cores_per_node, cpu_speed, thread_t::current_core, core_t::current_thread, core_t::decode, decode_create(), core_t::exec, exec_create(), fatal(), core_t::fetch, fetch_create(), thread_t::id, knobs, core_t::knobs, core_knobs_t::model, my_SIGSEGV_handler(), no_mcs, no_nodes, num_threads, core_t::oracle, thread_t::regs, regs_init(), regs_t::regs_PC, core_t::uncore, uncore_t::uncore_t(), and vcs.
Referenced by main().
void sim_pre_init (void)
Definition at line 193 of file sim-zesto.cpp.
References core_knobs_t::alloc, core_knobs_t::bpred_opt_str, core_knobs_t::branch_decode_limit, core_knobs_t::byteQ_linesize, core_knobs_t::byteQ_size, core_knobs_t::commit, core_knobs_t::decode, core_knobs_t::decoders, core_knobs_t::depth, core_knobs_t::DL1_MSHR_cmd, core_knobs_t::DL1_num_PF, core_knobs_t::DL1PF_opt_str, core_knobs_t::DL2_MSHR_cmd, core_knobs_t::DL2_num_PF, core_knobs_t::DL2PF_opt_str, core_knobs_t::exec, core_knobs_t::fetch, core_knobs_t::fp_penalty, core_knobs_t::fu_bindings, FU_FADD, FU_FCPLX, FU_FDIV, FU_FMUL, FU_IDIV, FU_IEU, FU_IMUL, FU_JEU, FU_LD, FU_SHIFT, FU_STA, FU_STD, core_knobs_t::IL1_num_PF, core_knobs_t::IL1PF_opt_str, core_knobs_t::IQ_size, core_knobs_t::issue_rate, knobs, core_knobs_t::latency, core_knobs_t::LDQ_size, MAX_DECODE_WIDTH, core_knobs_t::memory, memzero(), core_knobs_t::model, core_knobs_t::MS_latency, core_knobs_t::num_bpred_components, core_knobs_t::num_decoder_specs, core_knobs_t::num_exec_ports, core_knobs_t::payload_depth, core_knobs_t::port_binding, core_knobs_t::ROB_size, core_knobs_t::RS_size, core_knobs_t::STQ_size, core_knobs_t::target_stage, core_knobs_t::uopQ_size, and core_knobs_t::width.
Referenced by main().
void sim_print_stats (FILE * fd)
Definition at line 164 of file manifold_fullsim.cc.
References Mesh::interfaces, Mesh::link_a, Mesh::link_b, links, MAX, max_phy_link_bits, max_sim_time, no_nodes, running, sim_aux_stats(), sim_elapsed_time, sim_end_time, and sim_start_time.
Referenced by exit_now(), and main().
void sim_reg_options (struct opt_odb_t * odb)
Referenced by main().
void sim_reg_stats (struct thread_t ** cores, struct stat_sdb_t * sdb)
Referenced by main().
void sim_uninit (void)
Definition at line 437 of file sim-zesto.cpp.
Variable Documentation
unsigned int BANK_BITS
Definition at line 38 of file config_constants.h.
unsigned int buffer_size
Definition at line 48 of file config_params.h.
Referenced by dump_configuration(), iris_init(), iris_process_options(), and main().
unsigned int cores_per_node
Definition at line 48 of file manifold_fullsim.cc.
Referenced by iris_process_options(), main(), sim_post_init(), and uncore_t::uncore_t().
double cpu_speed
Definition at line 176 of file sim-zesto.cpp.
Referenced by sim_post_init(), and uncore_reg_options().
unsigned int credits
Definition at line 48 of file config_params.h.
Referenced by dump_configuration(), iris_init(), iris_process_options(), and main().
unsigned int do_two_stage_router
Definition at line 32 of file config_params.h.
unsigned int grid_size
Definition at line 44 of file config_params.h.
bool help_me
Definition at line 108 of file manifold_fullsim.cc.
Referenced by main().
bool init_quit
Definition at line 114 of file manifold_fullsim.cc.
Referenced by main().
unsigned int max_phy_link_bits
Definition at line 33 of file config_params.h.
unsigned long long int max_sim_time
Definition at line 36 of file config_params.h.
unsigned int MC_ADDR_BITS
Definition at line 37 of file config_constants.h.
int nice_priority
Definition at line 117 of file manifold_fullsim.cc.
Referenced by main().
unsigned int no_mcs
Definition at line 31 of file config_params.h.
unsigned int no_nodes
Definition at line 30 of file config_params.h.
unsigned int ports
Definition at line 48 of file config_params.h.
Referenced by dump_configuration(), iris_init(), iris_process_options(), and main().
unsigned int print_setup
Definition at line 43 of file config_params.h.
Referenced by iris_init(), iris_process_options(), and main().
int rand_seed
Definition at line 111 of file manifold_fullsim.cc.
Referenced by main().
int sim_dump_stats
Definition at line 91 of file manifold_fullsim.cc.
Referenced by signal_sim_stats().
FILE* sim_eio_fd[MAX_CORES]
char* sim_eio_fname[MAX_CORES]
int sim_elapsed_time
Definition at line 78 of file manifold_fullsim.cc.
time_t sim_end_time
Definition at line 77 of file manifold_fullsim.cc.
Referenced by sim_print_stats().
jmp_buf sim_exit_buf
Definition at line 88 of file manifold_fullsim.cc.
Referenced by main(), md_fetch_inst(), core_commit_STM_t::step(), and core_commit_DPM_t::step().
int sim_exit_now
Definition at line 85 of file manifold_fullsim.cc.
Referenced by signal_exit_now().
struct opt_odb_t* sim_odb
Definition at line 94 of file manifold_fullsim.cc.
FILE* sim_progfd
Definition at line 102 of file manifold_fullsim.cc.
Referenced by main().
char* sim_progout
Definition at line 101 of file manifold_fullsim.cc.
Referenced by main().
struct stat_sdb_t* sim_sdb
Definition at line 97 of file manifold_fullsim.cc.
char* sim_simout
Definition at line 100 of file manifold_fullsim.cc.
Referenced by main().
time_t sim_start_time
Definition at line 76 of file manifold_fullsim.cc.
Referenced by main(), sim_main(), and sim_print_stats().
int sim_swap_bytes
Definition at line 81 of file manifold_fullsim.cc.
int sim_swap_words
Definition at line 82 of file manifold_fullsim.cc.
unsigned int THREAD_BITS_POSITION
Definition at line 36 of file config_constants.h.
unsigned int vcs
Definition at line 48 of file config_params.h.
Referenced by dump_configuration(), uncore_t::enqueuable(), iris_init(), iris_process_options(), main(), and sim_post_init().