util.h File Reference
#include <iostream>
#include <sstream>
#include `../../kernel/simulator.h`
#include `../../components/interfaces/genericComponentHeader.h`
#include `../../components/interfaces/genericComponentHeader.h`
Functions
void timed_cout (string str)
Function Documentation
void timed_cout (string str)
Definition at line 23 of file util.cc.
References Simulator::Now().
Referenced by GenericRPG::handle_out_pull_event(), and GenericFlatMc::set_output_path().