zesto-exec.cpp File Reference
#include `thread.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-oracle.h`
#include `zesto-alloc.h`
#include `zesto-exec.h`
#include `zesto-memdep.h`
#include `zesto-prefetch.h`
#include `zesto-uncore.h`
#include `ZPIPE-exec.list`
Defines
#define ZESTO_PARSE_ARGS
Functions
void exec_reg_options (struct opt_odb_t *odb, struct core_knobs_t *knobs)
class core_exec_t * exec_create (const char *exec_opt_string, struct core_t *core)
Define Documentation
#define ZESTO_PARSE_ARGS
Function Documentation
class core_exec_t* exec_create (const char * exec_opt_string, struct core_t * core)
Definition at line 296 of file zesto-exec.cpp.
References fatal().
Referenced by sim_post_init().
void exec_reg_options (struct opt_odb_t * odb, struct core_knobs_t * knobs)
Definition at line 87 of file zesto-exec.cpp.
References core_knobs_t::DL1_high_watermark, core_knobs_t::DL1_low_watermark, core_knobs_t::DL1_MSHR_cmd, core_knobs_t::DL1_num_PF, core_knobs_t::DL1_opt_str, core_knobs_t::DL1_PF_buffer_size, core_knobs_t::DL1_PF_filter_reset, core_knobs_t::DL1_PF_filter_size, core_knobs_t::DL1_PF_on_miss, core_knobs_t::DL1_PFFsize, core_knobs_t::DL1_PFmax, core_knobs_t::DL1_PFthresh, core_knobs_t::DL1_WMinterval, core_knobs_t::DL1PF_opt_str, core_knobs_t::DL2_high_watermark, core_knobs_t::DL2_low_watermark, core_knobs_t::DL2_MSHR_cmd, core_knobs_t::DL2_num_PF, core_knobs_t::DL2_opt_str, core_knobs_t::DL2_PF_buffer_size, core_knobs_t::DL2_PF_filter_reset, core_knobs_t::DL2_PF_filter_size, core_knobs_t::DL2_PF_on_miss, core_knobs_t::DL2_PFFsize, core_knobs_t::DL2_PFmax, core_knobs_t::DL2_PFthresh, core_knobs_t::DL2_WMinterval, core_knobs_t::DL2PF_opt_str, core_knobs_t::DTLB2_opt_str, core_knobs_t::DTLB_opt_str, core_knobs_t::exec, core_knobs_t::fp_penalty, core_knobs_t::fu_bindings, FU_FADD, FU_FCPLX, FU_FDIV, FU_FMUL, FU_IDIV, FU_IEU, FU_IMUL, FU_JEU, FU_LD, FU_SHIFT, FU_STA, FU_STD, core_knobs_t::issue_rate, core_knobs_t::latency, core_knobs_t::LDQ_size, MAX_EXEC_WIDTH, MAX_PREFETCHERS, core_knobs_t::memdep_opt_str, core_knobs_t::memory, core_knobs_t::num_exec_ports, opt_reg_double(), opt_reg_flag(), opt_reg_int(), opt_reg_int_list(), opt_reg_string(), opt_reg_string_list(), core_knobs_t::payload_depth, core_knobs_t::port_binding, core_knobs_t::RS_size, core_knobs_t::STQ_size, core_knobs_t::throttle_partial, core_knobs_t::tornado_breaker, and core_knobs_t::warm_caches.