zesto-fetch.cpp File Reference
#include `thread.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-oracle.h`
#include `zesto-fetch.h`
#include `zesto-alloc.h`
#include `zesto-cache.h`
#include `zesto-decode.h`
#include `zesto-prefetch.h`
#include `zesto-bpred.h`
#include `zesto-exec.h`
#include `zesto-commit.h`
#include `zesto-uncore.h`
#include `zesto-MC.h`
#include `zesto-dram.h`
#include `ZPIPE-fetch.list`
Functions
void fetch_reg_options (struct opt_odb_t *odb, struct core_knobs_t *knobs)
class core_fetch_t * fetch_create (const char *fetch_opt_string, struct core_t *core)
Function Documentation
class core_fetch_t* fetch_create (const char * fetch_opt_string, struct core_t * core)
Definition at line 175 of file zesto-fetch.cpp.
References fatal().
Referenced by sim_post_init().
void fetch_reg_options (struct opt_odb_t * odb, struct core_knobs_t * knobs)
Definition at line 93 of file zesto-fetch.cpp.
References core_knobs_t::bpred_opt_str, core_knobs_t::byteQ_linesize, core_knobs_t::byteQ_size, core_knobs_t::depth, core_knobs_t::dirjmpbtb_opt_str, core_knobs_t::fetch, core_knobs_t::fusion_opt_str, core_knobs_t::IL1_high_watermark, core_knobs_t::IL1_low_watermark, core_knobs_t::IL1_num_PF, core_knobs_t::IL1_opt_str, core_knobs_t::IL1_PF_buffer_size, core_knobs_t::IL1_PF_filter_reset, core_knobs_t::IL1_PF_filter_size, core_knobs_t::IL1_PF_on_miss, core_knobs_t::IL1_PFFsize, core_knobs_t::IL1_PFmax, core_knobs_t::IL1_PFthresh, core_knobs_t::IL1_WMinterval, core_knobs_t::IL1PF_opt_str, core_knobs_t::indirjmpbtb_opt_str, core_knobs_t::IQ_size, core_knobs_t::ITLB_opt_str, core_knobs_t::jeclear_delay, MAX_HYBRID_BPRED, MAX_PREFETCHERS, core_knobs_t::memory, core_knobs_t::num_bpred_components, opt_reg_double(), opt_reg_flag(), opt_reg_int(), opt_reg_string(), opt_reg_string_list(), core_knobs_t::ras_opt_str, core_knobs_t::warm_bpred, and core_knobs_t::width.