zesto-uncore.h File Reference
#include `zesto-cache.h`
#include `../simIris/components/impl/genericInterfaceVcs.h`
#include `../simIris/components/impl/genericEvents.h`
#include `../simIris/components/interfaces/processor.h`
#include `../simIris/data_types/impl/highLevelPacket.h`
#include `../memctrl/request.h`
#include `../util/genericData.h`
#include `../util/mc_constants.h`
#include <math.h>
#include <stdint.h>
#include <fstream>
#include <deque>
Classes
class uncore_t
struct uncore_t::uncore_t::uncore_stat_t
Functions
void uncore_reg_options (struct opt_odb_t *const odb)
unsigned long long int GlobalAddrMap (unsigned long long int addr, unsigned int threadId)
unsigned long long int GlobalAddrRip (unsigned long long int addr, unsigned int threadId)
short int get_mcNo (unsigned long long int addr)
Function Documentation
short int get_mcNo (unsigned long long int addr)
unsigned long long int GlobalAddrMap (unsigned long long int addr, unsigned int threadId)
unsigned long long int GlobalAddrRip (unsigned long long int addr, unsigned int threadId)
void uncore_reg_options (struct opt_odb_t *const odb)
Definition at line 266 of file zesto-uncore.cpp.
References cpu_speed, LLC_access_rate, LLC_bus_ratio, LLC_high_watermark, LLC_low_watermark, LLC_MSHR_cmd, LLC_num_PF, LLC_opt_str, LLC_PF_buffer_size, LLC_PF_filter_reset, LLC_PF_filter_size, LLC_PF_on_miss, LLC_PF_opt_str, LLC_PFFsize, LLC_PFmax, LLC_PFthresh, LLC_WMinterval, MAX_PREFETCHERS, opt_reg_double(), opt_reg_flag(), opt_reg_int(), opt_reg_string(), and opt_reg_string_list().