zesto-decode.cpp File Reference
#include `thread.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-oracle.h`
#include `zesto-decode.h`
#include `zesto-fetch.h`
#include `zesto-bpred.h`
#include `zesto-cache.h`
#include `sim.h`
#include `zesto-uncore.h`
#include `zesto-MC.h`
#include `zesto-dram.h`
#include `ZPIPE-decode.list`
Functions
void decode_reg_options (struct opt_odb_t *odb, struct core_knobs_t *knobs)
class core_decode_t * decode_create (const char *decode_opt_string, struct core_t *core)
Function Documentation
class core_decode_t* decode_create (const char * decode_opt_string, struct core_t * core)
Definition at line 144 of file zesto-decode.cpp.
References fatal().
Referenced by sim_post_init().
void decode_reg_options (struct opt_odb_t * odb, struct core_knobs_t * knobs)
Definition at line 89 of file zesto-decode.cpp.
References core_knobs_t::branch_decode_limit, core_knobs_t::decode, core_knobs_t::decoders, core_knobs_t::depth, core_knobs_t::fusion_all, core_knobs_t::fusion_load_op, core_knobs_t::fusion_none, core_knobs_t::fusion_partial, core_knobs_t::fusion_sta_std, MAX_DECODE_WIDTH, core_knobs_t::MS_latency, core_knobs_t::num_decoder_specs, opt_reg_flag(), opt_reg_int(), opt_reg_int_list(), core_knobs_t::target_stage, core_knobs_t::uopQ_size, and core_knobs_t::width.