zesto-dram.cpp File Reference
#include <limits.h>
#include `thread.h`
#include `stats.h`
#include `options.h`
#include `zesto-opts.h`
#include `zesto-cache.h`
#include `zesto-dram.h`
#include `zesto-uncore.h`
#include `ZCOMPS-dram.list`
Defines
#define DRAM_ACCESS_HEADER unsigned int access(const enum cache_command cmd, const md_paddr_t baddr, const int bsize)
#define DRAM_REFRESH_HEADER void refresh(void)
#define DRAM_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb)
Functions
void dram_reg_options (struct opt_odb_t *const odb)
static dram_t * dram_from_string (char *const opt_string)
void dram_create (void)
Variables
class dram_t * dram = NULL
static char * dram_opt_string = NULL
Define Documentation
#define DRAM_ACCESS_HEADER unsigned int access(const enum cache_command cmd, const md_paddr_t baddr, const int bsize)
Definition at line 136 of file zesto-dram.cpp.
#define DRAM_REFRESH_HEADER void refresh(void)
Definition at line 138 of file zesto-dram.cpp.
#define DRAM_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb)
Definition at line 140 of file zesto-dram.cpp.
Function Documentation
void dram_create (void)
Definition at line 165 of file zesto-dram.cpp.
References dram_from_string(), and dram_opt_string.
static dram_t* dram_from_string (char *const opt_string) [static]
Definition at line 147 of file zesto-dram.cpp.
References fatal().
Referenced by dram_create().
void dram_reg_options (struct opt_odb_t *const odb)
Definition at line 94 of file zesto-dram.cpp.
References dram_opt_string, and opt_reg_string().
Variable Documentation
class dram_t* dram = NULL
Definition at line 89 of file zesto-dram.cpp.
char* dram_opt_string = NULL [static]
Definition at line 91 of file zesto-dram.cpp.
Referenced by dram_create(), and dram_reg_options().