stats.h File Reference
#include <stdio.h>
#include `host.h`
#include `machine.h`
#include `eval.h`
Classes
struct bucket_t
struct stat_stat_t
union stat_stat_t::stat_stat_t::stat_variant_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_int_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_uint_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_qword_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_sqword_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_float_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_double_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_dist_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_sdist_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_formula_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_string_t
struct stat_stat_t::stat_stat_t::stat_variant_t::stat_stat_t::stat_variant_t::stat_for_note_t
struct stat_sdb_t
Defines
#define HTAB_SZ 1024
#define HTAB_HASH(I) ((((I) >> 8) ^ (I)) & (HTAB_SZ - 1))
#define PF_COUNT 0x0001
#define PF_PDF 0x0002
#define PF_CDF 0x0004
#define PF_ALL (PF_COUNT|PF_PDF|PF_CDF)
Typedefs
typedef void(* print_fn_t)(struct stat_stat_t *stat, md_addr_t index, int count, double sum, double total)
Enumerations
enum stat_class_t {
sc_int = 0,
sc_uint,
sc_qword,
sc_sqword,
sc_float,
sc_double,
sc_dist,
sc_sdist,
sc_formula,
sc_string,
sc_note,
sc_NUM
 }
Functions
struct eval_value_t stat_eval_ident (struct eval_state_t *es)
struct stat_sdb_t * stat_new (void)
void stat_delete (struct stat_sdb_t *sdb)
struct stat_stat_t * stat_reg_int (struct stat_sdb_t *sdb, int print_me, const char *name, const char *desc, int *var, int init_val, const char *format)
struct stat_stat_t * stat_reg_uint (struct stat_sdb_t *sdb, int print_me, const char *name, const char *desc, unsigned int *var, unsigned int init_val, const char *format)
struct stat_stat_t * stat_reg_qword (struct stat_sdb_t *sdb, int print_me, const char *name, const char *desc, qword_t *var, qword_t init_val, const char *format)
struct stat_stat_t * stat_reg_sqword (struct stat_sdb_t *sdb, int print_me, const char *name, const char *desc, sqword_t *var, sqword_t init_val, const char *format)
struct stat_stat_t * stat_reg_float (struct stat_sdb_t *sdb, int print_me, const char *name, const char *desc, float *var, float init_val, const char *format)
struct stat_stat_t * stat_reg_double (struct stat_sdb_t *sdb, int print_me, const char *name, const char *desc, double *var, double init_val, const char *format)
struct stat_stat_t * stat_reg_dist (struct stat_sdb_t *sdb, const char *name, const char *desc, unsigned int init_val, unsigned int arr_sz, unsigned int bucket_sz, int pf, const char *format, const char **imap, print_fn_t print_fn)
struct stat_stat_t * stat_reg_sdist (struct stat_sdb_t *sdb, const char *name, const char *desc, unsigned int init_val, int pf, const char *format, print_fn_t print_fn)
void stat_add_samples (struct stat_stat_t *stat, md_addr_t index, int nsamples)
void stat_add_sample (struct stat_stat_t *stat, md_addr_t index)
struct stat_stat_t * stat_reg_formula (struct stat_sdb_t *sdb, int print_me, const char *name, const char *desc, const char *formula, const char *format)
struct stat_stat_t * stat_reg_string (struct stat_sdb_t *sdb, const char *name, const char *desc, const char *var, const char *format)
struct stat_stat_t * stat_reg_note (struct stat_sdb_t *sdb, const char *note)
void stat_print_stat (struct stat_sdb_t *sdb, struct stat_stat_t *stat, FILE *fd)
void stat_print_stats (struct stat_sdb_t *sdb, FILE *fd)
struct stat_stat_t * stat_find_stat (struct stat_sdb_t *sdb, const char *stat_name)
void print_sdist (struct stat_stat_t *stat, FILE *fd)
void print_dist (struct stat_stat_t *stat, FILE *fd)
Define Documentation
#define HTAB_HASH(I) ((((I) >> 8) ^ (I)) & (HTAB_SZ - 1))
Definition at line 93 of file zesto/stats.h.
#define HTAB_SZ 1024
Definition at line 92 of file zesto/stats.h.
#define PF_ALL (PF_COUNT|PF_PDF|PF_CDF)
Definition at line 109 of file zesto/stats.h.
#define PF_CDF 0x0004
Definition at line 108 of file zesto/stats.h.
#define PF_COUNT 0x0001
Definition at line 106 of file zesto/stats.h.
Referenced by core_fetch_STM_t::reg_stats(), core_fetch_DPM_t::reg_stats(), core_decode_STM_t::reg_stats(), core_decode_DPM_t::reg_stats(), core_commit_STM_t::reg_stats(), core_commit_DPM_t::reg_stats(), core_alloc_STM_t::reg_stats(), and core_alloc_DPM_t::reg_stats().
#define PF_PDF 0x0002
Definition at line 107 of file zesto/stats.h.
Referenced by core_fetch_STM_t::reg_stats(), core_fetch_DPM_t::reg_stats(), core_decode_STM_t::reg_stats(), core_decode_DPM_t::reg_stats(), core_commit_STM_t::reg_stats(), core_commit_DPM_t::reg_stats(), core_alloc_STM_t::reg_stats(), and core_alloc_DPM_t::reg_stats().
Typedef Documentation
typedef void(* print_fn_t)(struct stat_stat_t *stat,md_addr_t index,int count,double sum,double total)
Definition at line 115 of file zesto/stats.h.
Enumeration Type Documentation
enum stat_class_t
Enumerator:
sc_int
sc_uint
sc_qword
sc_sqword
sc_float
sc_double
sc_dist
sc_sdist
sc_formula
sc_string
sc_note
sc_NUM
Definition at line 76 of file zesto/stats.h.
Function Documentation
void print_dist (struct stat_stat_t * stat, FILE * fd)
void print_sdist (struct stat_stat_t * stat, FILE * fd)
void stat_add_sample (struct stat_stat_t * stat, md_addr_t index)
Referenced by core_decode_STM_t::check_flush(), core_decode_DPM_t::check_flush(), core_fetch_STM_t::step(), core_fetch_DPM_t::step(), core_decode_STM_t::step(), core_decode_DPM_t::step(), core_commit_STM_t::step(), core_commit_DPM_t::step(), core_alloc_STM_t::step(), and core_alloc_DPM_t::step().
void stat_add_samples (struct stat_stat_t * stat, md_addr_t index, int nsamples)
void stat_delete (struct stat_sdb_t * sdb)
struct eval_value_t stat_eval_ident (struct eval_state_t * es) [read]
struct stat_stat_t* stat_find_stat (struct stat_sdb_t * sdb, const char * stat_name) [read]
struct stat_sdb_t* stat_new (void) [read]
Referenced by main().
void stat_print_stat (struct stat_sdb_t * sdb, struct stat_stat_t * stat, FILE * fd)
void stat_print_stats (struct stat_sdb_t * sdb, FILE * fd)
struct stat_stat_t* stat_reg_dist (struct stat_sdb_t * sdb, const char * name, const char * desc, unsigned int init_val, unsigned int arr_sz, unsigned int bucket_sz, int pf, const char * format, const char ** imap, print_fn_t print_fn) [read]
Referenced by core_fetch_STM_t::reg_stats(), core_fetch_DPM_t::reg_stats(), core_decode_STM_t::reg_stats(), core_decode_DPM_t::reg_stats(), core_commit_STM_t::reg_stats(), core_commit_DPM_t::reg_stats(), core_alloc_STM_t::reg_stats(), and core_alloc_DPM_t::reg_stats().
struct stat_stat_t* stat_reg_double (struct stat_sdb_t * sdb, int print_me, const char * name, const char * desc, double * var, double init_val, const char * format) [read]
struct stat_stat_t* stat_reg_float (struct stat_sdb_t * sdb, int print_me, const char * name, const char * desc, float * var, float init_val, const char * format) [read]
struct stat_stat_t* stat_reg_formula (struct stat_sdb_t * sdb, int print_me, const char * name, const char * desc, const char * formula, const char * format) [read]
Referenced by bus_reg_stats(), cache_reg_stats(), LLC_reg_stats(), prefetch_t::reg_stats(), core_oracle_t::reg_stats(), memdep_t::reg_stats(), MC_t::reg_stats(), dram_t::reg_stats(), bpred_t::reg_stats(), RAS_t::reg_stats(), BTB_t::reg_stats(), fusion_t::reg_stats(), bpred_dir_t::reg_stats(), core_fetch_STM_t::reg_stats(), core_fetch_DPM_t::reg_stats(), core_exec_STM_t::reg_stats(), core_exec_DPM_t::reg_stats(), core_decode_STM_t::reg_stats(), core_decode_DPM_t::reg_stats(), core_commit_STM_t::reg_stats(), core_commit_DPM_t::reg_stats(), core_alloc_STM_t::reg_stats(), core_alloc_DPM_t::reg_stats(), and uncore_t::uncore_reg_stats().
struct stat_stat_t* stat_reg_int (struct stat_sdb_t * sdb, int print_me, const char * name, const char * desc, int * var, int init_val, const char * format) [read]
Referenced by prefetch_t::reg_stats(), memdep_t::reg_stats(), dram_t::reg_stats(), RAS_t::reg_stats(), BTB_t::reg_stats(), fusion_t::reg_stats(), and bpred_dir_t::reg_stats().
struct stat_stat_t* stat_reg_note (struct stat_sdb_t * sdb, const char * note) [read]
Referenced by core_oracle_t::reg_stats(), core_fetch_STM_t::reg_stats(), core_fetch_DPM_t::reg_stats(), core_exec_STM_t::reg_stats(), core_exec_DPM_t::reg_stats(), core_decode_STM_t::reg_stats(), core_decode_DPM_t::reg_stats(), core_commit_STM_t::reg_stats(), core_commit_DPM_t::reg_stats(), core_alloc_STM_t::reg_stats(), core_alloc_DPM_t::reg_stats(), and uncore_t::uncore_reg_stats().
struct stat_stat_t* stat_reg_qword (struct stat_sdb_t * sdb, int print_me, const char * name, const char * desc, qword_t * var, qword_t init_val, const char * format) [read]
Referenced by core_commit_STM_t::reg_stats(), and core_commit_DPM_t::reg_stats().
struct stat_stat_t* stat_reg_sdist (struct stat_sdb_t * sdb, const char * name, const char * desc, unsigned int init_val, int pf, const char * format, print_fn_t print_fn) [read]
struct stat_stat_t* stat_reg_sqword (struct stat_sdb_t * sdb, int print_me, const char * name, const char * desc, sqword_t * var, sqword_t init_val, const char * format) [read]
struct stat_stat_t* stat_reg_string (struct stat_sdb_t * sdb, const char * name, const char * desc, const char * var, const char * format) [read]
Referenced by memdep_t::reg_stats(), RAS_t::reg_stats(), BTB_t::reg_stats(), fusion_t::reg_stats(), and bpred_dir_t::reg_stats().
struct stat_stat_t* stat_reg_uint (struct stat_sdb_t * sdb, int print_me, const char * name, const char * desc, unsigned int * var, unsigned int init_val, const char * format) [read]