zesto-llc.cpp File Reference
#include <limits.h>
#include `thread.h`
#include `stats.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-cache.h`
#include `zesto-prefetch.h`
#include `zesto-uncore.h`
#include `zesto-exec.h`
#include `zesto-commit.h`
Functions
struct cache_t * cache_create_llc (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, const int begin_index, const int end_index, struct cache_t *const next_level_cache, struct bus_t *const next_bus)
void LLC_reg_stats (struct stat_sdb_t *const sdb, struct cache_t *const cp)
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr)
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful)
struct cache_line_t * cache_is_hit_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
static struct cache_line_t * cache_peek_llc (const struct cache_t *const cp, const md_paddr_t addr)
void cache_insert_block_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
struct cache_line_t * cache_get_evictee_llc (struct cache_t *const cp, const md_paddr_t addr, core_t *const core)
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position)
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num)
int cache_enqueuable_llc (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
void cache_enqueue_llc (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*const cb)(void *), void(*const miss_cb)(void *, int), bool(*const translated_cb)(void *, seq_t), seq_t(*const get_action_id)(void *))
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr)
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr)
static struct cache_action_t * MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd)
static void dummy_callback (void *p)
void fill_arrived_llc (struct cache_t *const cp, unsigned long long int address)
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position)
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num)
static bool cache_fillable_llc (const struct cache_t *const cp, const md_paddr_t paddr)
static void cache_fill_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t *core)
void cache_process_llc (struct cache_t *const cp)
static void cache_prefetch_llc (struct cache_t *const cp)
static void prefetch_controller_update_llc (struct cache_t *const cp)
void step_LLC_PF_controller (struct uncore_t *const uncore)
void prefetch_LLC (struct uncore_t *const uncore)
void uncore_utilize (struct cache_t *const cp)
Function Documentation
struct cache_t* cache_create_llc (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, const int begin_index, const int end_index, struct cache_t *const next_level_cache, struct bus_t *const next_bus) [read]
Definition at line 90 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_t::allocate_policy, cache_t::assoc, cache_t::bank_mask, cache_t::bank_shift, cache_t::bank_width, cache_t::banks, cache_t::blocks, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::core, cache_t::core_lookups, cache_t::core_misses, fatal(), cache_t::fill_num, cache_t::fill_pipe, cache_t::heap_size, cache_t::latency, cache_t::linesize, cache_t::log2_assoc, cache_t::MSHR, cache_t::MSHR_banks, cache_t::MSHR_mask, cache_t::MSHR_size, mytoupper(), cache_t::name, cache_line_t::next, cache_t::next_bus, cache_t::next_level, NO_WRITE_ALLOC, num_threads, cache_t::pipe, cache_t::pipe_num, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::way, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, and WRITE_THROUGH.
Referenced by uncore_t::uncore_t().
int cache_enqueuable_llc (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
Definition at line 993 of file zesto-llc.cpp.
References DO_NOT_TRANSLATE, GET_BANK, cache_t::latency, and cache_t::pipe_num.
Referenced by cache_process().
void cache_enqueue_llc (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*)(void *) cb, void(*)(void *, int) miss_cb, bool(*)(void *, seq_t) translated_cb, seq_t(*)(void *) get_action_id)
Definition at line 1012 of file zesto-llc.cpp.
References cache_action_t::action_id, cache_assert, cache_heap_balance(), cache_action_t::cb, cache_t::check_for_pipe_work, cache_t::check_for_work, cache_action_t::cmd, cache_action_t::core, DO_NOT_TRANSLATE, cache_action_t::get_action_id, GET_BANK, cache_t::latency, cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, cache_action_t::MSHR_bank, cache_action_t::MSHR_index, cache_action_t::op, cache_action_t::paddr, cache_action_t::PC, cache_t::pipe, cache_action_t::pipe_exit_time, cache_t::pipe_num, cache_action_t::prev_cp, sim_cycle, TICK_T_MAX, cache_action_t::translated_cb, cache_action_t::when_returned, and cache_action_t::when_started.
Referenced by cache_process().
static void cache_fill_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t * core) [inline, static]
Definition at line 1396 of file zesto-llc.cpp.
References cache_assert, cache_t::check_for_fill_work, cache_t::check_for_work, cache_fill_t::cmd, cache_fill_t::core, fill_heap_balance(), cache_t::fill_num, cache_t::fill_pipe, GET_BANK, cache_t::latency, cache_fill_t::paddr, cache_fill_t::pipe_exit_time, sim_cycle, and cache_fill_t::valid.
static bool cache_fillable_llc (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1384 of file zesto-llc.cpp.
References cache_t::fill_num, GET_BANK, and cache_t::latency.
struct cache_line_t* cache_get_evictee_llc (struct cache_t *const cp, const md_paddr_t addr, core_t *const core) [read]
Definition at line 755 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_t::assoc, cache_t::blocks, fatal(), cache_t::log2_assoc, cache_line_t::meta, modinc(), cache_t::name, cache_line_t::next, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::valid, and cache_line_t::way.
Referenced by cache_process_llc(), and sim_fastfwd().
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position) [static]
Definition at line 897 of file zesto-llc.cpp.
References memswap().
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num) [static]
Definition at line 923 of file zesto-llc.cpp.
References cache_action_t::cb, memswap(), cache_action_t::pipe_exit_time, and TICK_T_MAX.
void cache_insert_block_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
Definition at line 656 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_PREFETCH, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::core, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::prefetch_insertions, cache_line_t::prefetched, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::tag, cache_line_t::valid, and cache_line_t::way.
Referenced by cache_process_llc(), and sim_fastfwd().
struct cache_line_t* cache_is_hit_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 532 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_READONLY, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::tag, cache_line_t::valid, cache_line_t::way, WRITE_BACK, and cache_t::write_policy.
Referenced by cache_process_llc(), and sim_fastfwd().
static struct cache_line_t* cache_peek_llc (const struct cache_t *const cp, const md_paddr_t addr) [static, read]
Definition at line 631 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_line_t::next, cache_t::sets, cache_line_t::tag, and cache_line_t::valid.
static void cache_prefetch_llc (struct cache_t *const cp) [static]
Definition at line 2130 of file zesto-llc.cpp.
References cache_t::cache_t::PFF_t::addr, cache_assert, cache_enqueuable(), cache_enqueue(), CACHE_PREFETCH, cache_t::cache_t::PFF_t::core, DO_NOT_TRANSLATE, dummy_callback(), GET_MSHR_BANK, modinc(), NO_MSHR, cache_t::cache_t::PFF_t::PC, PF_OK, cache_t::PF_sample_interval, cache_t::PF_state, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::prefetch_max, and cache_t::prefetch_threshold.
void cache_process_llc (struct cache_t *const cp)
Definition at line 1427 of file zesto-llc.cpp.
References cache_action_t::action_id, cache_t::cache_t::PFF_t::addr, prefetch_buffer_t::addr, cache_t::addr_shift, cache_t::allocate_policy, cache_t::bank_mask, cache_t::banks, BIG_LATENCY, bus_free(), bus_use(), cache_assert, cache_fill_llc(), cache_fillable_llc(), cache_get_evictee_llc(), cache_heap_remove(), cache_insert_block_llc(), cache_invalidate(), cache_is_hit_llc(), cache_peek_llc(), CACHE_PREFETCH, CACHE_READ, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_action_t::cb, cache_t::check_for_fill_work, cache_t::check_for_MSHR_fill_work, cache_t::check_for_MSHR_work, cache_t::check_for_pipe_work, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_action_t::cmd, cache_t::cache_t::PFF_t::core, cache_line_t::core, cache_t::core, cache_action_t::core, cache_t::core_lookups, cache_t::core_misses, cache_line_t::dirty, uncore_t::enqueuable(), uncore_t::enqueue(), fatal(), fill_arrived(), fill_heap_remove(), cache_t::fill_num, cache_t::fill_pipe, cache_action_t::get_action_id, GET_MSHR_BANK, cache_t::latency, cache_t::linesize, uncore_t::LLC, cache_t::load_lookups, cache_t::load_misses, prefetch_t::lookup(), cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, modinc(), cache_t::MSHR, MSHR_allocate(), MSHR_available(), cache_action_t::MSHR_bank, cache_t::MSHR_banks, cache_t::MSHR_full_cycles, cache_action_t::MSHR_index, cache_action_t::MSHR_linked, cache_t::MSHR_mask, cache_t::MSHR_occupancy, cache_t::MSHR_size, cache_t::name, prefetch_buffer_t::next, cache_t::next_bus, cache_t::next_level, NO_MSHR, cache_t::num_prefetchers, cache_action_t::op, cache_action_t::paddr, PAGE_SIZE, cache_t::cache_t::PFF_t::PC, cache_t::PF_buffer, cache_t::PF_filter, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::PFF_tail, cache_t::pipe, cache_t::pipe_num, prefetch_filter_lookup(), prefetch_filter_update(), cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_on_miss, cache_line_t::prefetch_used, cache_t::prefetch_useful_insertions, cache_line_t::prefetched, cache_t::prefetcher, cache_action_t::prev_cp, cache_t::prev_level, sim_cycle, cache_t::start_point, cache_t::stat, cache_t::store_lookups, cache_t::store_misses, cache_line_t::tag, TICK_T_MAX, cache_action_t::translated_cb, cache_t::uncore, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, WBB_available(), cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_head, cache_t::WBB_hits, WBB_insert(), cache_t::WBB_num, cache_t::WBB_occupancy, cache_t::WBB_size, cache_t::WBB_victim_hits, cache_action_t::when_enqueued, cache_action_t::when_returned, cache_action_t::when_started, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, WRITE_THROUGH, cache_t::writeback_lookups, and cache_t::writeback_misses.
Referenced by zesto_component::downtick_handler().
static void dummy_callback (void * p) [static]
Definition at line 1243 of file zesto-llc.cpp.
void fill_arrived_llc (struct cache_t *const cp, unsigned long long int address)
Definition at line 1250 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_action_t::cb, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::MSHR, cache_t::MSHR_banks, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, cache_t::MSHR_mask, cache_t::MSHR_size, cache_action_t::paddr, sim_cycle, and cache_action_t::when_returned.
Referenced by uncore_t::handle_new_packet_event().
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position) [static]
Definition at line 1291 of file zesto-llc.cpp.
References memswap(), and cache_action_t::pipe_exit_time.
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num) [static]
Definition at line 1315 of file zesto-llc.cpp.
References memswap(), cache_fill_t::pipe_exit_time, TICK_T_MAX, and cache_fill_t::valid.
void LLC_reg_stats (struct stat_sdb_t *const sdb, struct cache_t *const cp)
Definition at line 284 of file zesto-llc.cpp.
References CACHE_READWRITE, uncore_t::core, cache_t::core_lookups, cache_t::core_misses, core_t::id, cache_t::load_lookups, cache_t::load_misses, cache_t::MSHR_combos, cache_t::MSHR_full_cycles, cache_t::MSHR_occupancy, cache_t::name, NetworkComponent::node_ip, uncore_t::num_cores, cache_t::num_prefetchers, num_threads, cache_t::prefetch_insertions, cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_useful_insertions, cache_t::prefetcher, cache_t::read_only, prefetch_t::reg_stats(), cache_t::stat, stat_reg_counter, stat_reg_formula(), cache_t::store_lookups, cache_t::store_misses, cache_t::uncore, cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_hits, cache_t::WBB_insertions, cache_t::WBB_occupancy, cache_t::WBB_victim_hits, cache_t::WBB_victim_insertions, cache_t::writeback_lookups, and cache_t::writeback_misses.
Referenced by uncore_t::uncore_reg_stats().
static struct cache_action_t* MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd) [static, read]
Definition at line 1189 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_assert, cache_action_t::cb, cache_t::check_for_MSHR_work, cache_t::check_for_work, fatal(), GET_MSHR_BANK, cache_t::MSHR, cache_t::MSHR_combos, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, cache_t::MSHR_size, cache_action_t::paddr, cache_t::stat, TICK_T_MAX, and cache_action_t::when_returned.
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1179 of file zesto-llc.cpp.
References GET_MSHR_BANK, and cache_t::MSHR_size.
static void prefetch_controller_update_llc (struct cache_t *const cp) [static]
Definition at line 2159 of file zesto-llc.cpp.
References cache_t::PF_high_watermark, cache_t::PF_last_sample, PF_OK, PF_REFRAIN, cache_t::PF_sample_interval, cache_t::PF_state, sim_cycle, cache_t::stat, and cache_t::uncore_utilization.
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr) [static]
Definition at line 486 of file zesto-llc.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful) [static]
Definition at line 503 of file zesto-llc.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
void prefetch_LLC (struct uncore_t *const uncore)
Definition at line 2180 of file zesto-llc.cpp.
References cache_prefetch_llc(), and uncore_t::LLC.
Referenced by zesto_component::downtick_handler().
void step_LLC_PF_controller (struct uncore_t *const uncore)
Definition at line 2174 of file zesto-llc.cpp.
References uncore_t::LLC, and prefetch_controller_update_llc().
Referenced by zesto_component::downtick_handler().
void uncore_utilize (struct cache_t *const cp)
Definition at line 2186 of file zesto-llc.cpp.
References cache_t::stat, and cache_t::uncore_utilization.
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1086 of file zesto-llc.cpp.
References GET_MSHR_BANK, cache_t::WBB_num, and cache_t::WBB_size.
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1096 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_line_t::c_state, cache_assert, CACHE_STAT, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), modinc(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_combines, cache_t::WBB_head, cache_t::WBB_insertions, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, and cache_t::write_combining.
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1140 of file zesto-llc.cpp.
References cache_t::addr_shift, cache_assert, CACHE_STAT, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, and cache_t::WBB_victim_insertions.