zesto-cache.cpp File Reference
#include <limits.h>
#include `thread.h`
#include `stats.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-cache.h`
#include `zesto-prefetch.h`
#include `zesto-uncore.h`
#include `zesto-exec.h`
#include `zesto-commit.h`
Functions
struct cache_t * cache_create (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, struct cache_t *const next_level_cache, struct bus_t *const next_bus)
void cache_reg_stats (struct stat_sdb_t *const sdb, const struct core_t *const core, struct cache_t *const cp)
void cache_reset_stats (struct cache_t *const cp)
void prefetch_buffer_create (struct cache_t *const cp, const int num_entries)
void prefetch_filter_create (struct cache_t *const cp, const int num_entries, const int reset_interval)
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr)
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful)
struct cache_line_t * cache_is_hit (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
static struct cache_line_t * cache_peek (const struct cache_t *const cp, const md_paddr_t addr)
void cache_insert_block (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
struct cache_line_t * cache_invalidate (struct cache_t *const cp, const md_paddr_t addr, core_t *const core)
struct cache_line_t * cache_get_evictee (struct cache_t *const cp, const md_paddr_t addr, core_t *const core)
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position)
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num)
int cache_enqueuable (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
void cache_enqueue (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*const cb)(void *), void(*const miss_cb)(void *, int), bool(*const translated_cb)(void *, seq_t), seq_t(*const get_action_id)(void *))
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr)
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block)
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr)
static struct cache_action_t * MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd)
static void dummy_callback (void *p)
void fill_arrived (struct cache_t *const cp, const int MSHR_bank, const int MSHR_index)
void print_heap (const struct cache_t *const cp)
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position)
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num)
static bool cache_fillable (const struct cache_t *const cp, const md_paddr_t paddr)
static void cache_fill (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t *core)
void cache_process (struct cache_t *const cp)
static void cache_prefetch (struct cache_t *const cp)
static void prefetch_controller_update (struct cache_t *const cp)
void step_core_PF_controllers (struct core_t *const core)
void prefetch_core_caches (struct core_t *const core)
void cache_freeze_stats (struct core_t *const core)
void cache_print (const struct cache_t *const cp)
struct bus_t * bus_create (const char *const name, const int width, const int ratio)
void bus_reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core, struct bus_t *const bus)
int bus_free (const struct bus_t *const bus)
void bus_use (struct bus_t *const bus, const int transfer_size, const int prefetch)
Function Documentation
struct bus_t* bus_create (const char *const name, const int width, const int ratio) [read]
Definition at line 2520 of file zesto-cache.cpp.
References fatal(), bus_t::name, bus_t::ratio, and bus_t::width.
int bus_free (const struct bus_t *const bus)
Definition at line 2573 of file zesto-cache.cpp.
References bus_t::ratio, sim_cycle, and bus_t::when_available.
void bus_reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core, struct bus_t *const bus)
Definition at line 2534 of file zesto-cache.cpp.
References bus_t::accesses, core_t::current_thread, thread_t::id, bus_t::name, bus_t::prefetch_utilization, bus_t::stat, stat_reg_counter, stat_reg_formula(), and bus_t::utilization.
void bus_use (struct bus_t *const bus, const int transfer_size, const int prefetch)
Definition at line 2584 of file zesto-cache.cpp.
References bus_t::accesses, bus_t::prefetch_utilization, bus_t::ratio, sim_cycle, bus_t::stat, bus_t::utilization, bus_t::when_available, and bus_t::width.
struct cache_t* cache_create (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banks, struct cache_t *const next_level_cache, struct bus_t *const next_bus) [read]
Definition at line 91 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_t::allocate_policy, cache_t::assoc, cache_t::bank_mask, cache_t::bank_shift, cache_t::bank_width, cache_t::banks, cache_t::blocks, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::core, cache_t::core_lookups, cache_t::core_misses, fatal(), cache_t::fill_num, cache_t::fill_pipe, cache_t::heap_size, cache_t::latency, cache_t::linesize, cache_t::log2_assoc, cache_t::MSHR, cache_t::MSHR_banks, cache_t::MSHR_mask, cache_t::MSHR_size, mytoupper(), cache_t::name, cache_line_t::next, cache_t::next_bus, cache_t::next_level, NO_WRITE_ALLOC, num_threads, cache_t::pipe, cache_t::pipe_num, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::way, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, and WRITE_THROUGH.
int cache_enqueuable (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
Definition at line 1110 of file zesto-cache.cpp.
References DO_NOT_TRANSLATE, GET_BANK, cache_t::latency, and cache_t::pipe_num.
void cache_enqueue (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*)(void *) cb, void(*)(void *, int) miss_cb, bool(*)(void *, seq_t) translated_cb, seq_t(*)(void *) get_action_id)
Definition at line 1129 of file zesto-cache.cpp.
References cache_action_t::action_id, cache_assert, cache_heap_balance(), cache_action_t::cb, cache_t::check_for_pipe_work, cache_t::check_for_work, cache_action_t::cmd, cache_action_t::core, DO_NOT_TRANSLATE, cache_action_t::get_action_id, GET_BANK, cache_t::latency, cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, cache_action_t::MSHR_bank, cache_action_t::MSHR_index, cache_action_t::op, cache_action_t::paddr, cache_action_t::PC, cache_t::pipe, cache_action_t::pipe_exit_time, cache_t::pipe_num, cache_action_t::prev_cp, sim_cycle, TICK_T_MAX, cache_action_t::translated_cb, cache_action_t::when_returned, and cache_action_t::when_started.
static void cache_fill (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t paddr, struct core_t * core) [inline, static]
Definition at line 1520 of file zesto-cache.cpp.
References cache_assert, cache_t::check_for_fill_work, cache_t::check_for_work, cache_fill_t::cmd, cache_fill_t::core, fill_heap_balance(), cache_t::fill_num, cache_t::fill_pipe, GET_BANK, cache_t::latency, cache_fill_t::paddr, cache_fill_t::pipe_exit_time, sim_cycle, and cache_fill_t::valid.
static bool cache_fillable (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1508 of file zesto-cache.cpp.
References cache_t::fill_num, GET_BANK, and cache_t::latency.
void cache_freeze_stats (struct core_t *const core)
Definition at line 2457 of file zesto-cache.cpp.
References core_t::core_t::core_memory_t::DL1, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::DTLB, core_t::core_t::core_memory_t::DTLB2, cache_t::frozen, core_t::core_t::core_memory_t::IL1, core_t::core_t::core_memory_t::ITLB, and core_t::memory.
struct cache_line_t* cache_get_evictee (struct cache_t *const cp, const md_paddr_t addr, core_t *const core) [read]
Definition at line 874 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_t::assoc, cache_t::blocks, fatal(), cache_t::log2_assoc, cache_line_t::meta, modinc(), cache_t::name, cache_line_t::next, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::valid, and cache_line_t::way.
static void cache_heap_balance (struct cache_action_t *const pipe, const int insert_position) [static]
Definition at line 1015 of file zesto-cache.cpp.
References memswap().
static void cache_heap_remove (struct cache_action_t *const pipe, const int pipe_num) [static]
Definition at line 1041 of file zesto-cache.cpp.
References cache_action_t::cb, memswap(), cache_action_t::pipe_exit_time, and TICK_T_MAX.
void cache_insert_block (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, core_t *const core)
Definition at line 745 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_PREFETCH, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::core, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::prefetch_insertions, cache_line_t::prefetched, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::tag, cache_line_t::valid, and cache_line_t::way.
struct cache_line_t* cache_invalidate (struct cache_t *const cp, const md_paddr_t addr, core_t *const core) [read]
Definition at line 841 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_invalidate(), cache_peek(), cache_line_t::dirty, fatal(), cache_line_t::next, cache_t::prev_level, cache_t::sets, cache_line_t::tag, and cache_line_t::valid.
Referenced by cache_invalidate(), cache_process(), and cache_process_llc().
struct cache_line_t* cache_is_hit (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 621 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_READONLY, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::tag, cache_line_t::valid, cache_line_t::way, WRITE_BACK, and cache_t::write_policy.
static struct cache_line_t* cache_peek (const struct cache_t *const cp, const md_paddr_t addr) [static, read]
Definition at line 720 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_line_t::next, cache_t::sets, cache_line_t::tag, and cache_line_t::valid.
static void cache_prefetch (struct cache_t *const cp) [static]
Definition at line 2398 of file zesto-cache.cpp.
References cache_t::cache_t::PFF_t::addr, cache_assert, cache_enqueuable(), cache_enqueue(), CACHE_PREFETCH, cache_t::cache_t::PFF_t::core, DO_NOT_TRANSLATE, dummy_callback(), GET_MSHR_BANK, modinc(), NO_MSHR, cache_t::cache_t::PFF_t::PC, PF_OK, cache_t::PF_sample_interval, cache_t::PF_state, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::prefetch_max, and cache_t::prefetch_threshold.
void cache_print (const struct cache_t *const cp)
Definition at line 2467 of file zesto-cache.cpp.
References cache_t::banks, CACHE_READ, CACHE_WRITE, CACHE_WRITEBACK, cache_action_t::cb, cache_action_t::cmd, cache_t::fill_pipe, cache_t::latency, cache_t::MSHR, cache_t::MSHR_size, cache_t::name, cache_action_t::op, cache_fill_t::paddr, cache_t::pipe, and cache_fill_t::valid.
void cache_process (struct cache_t *const cp)
Definition at line 1557 of file zesto-cache.cpp.
References cache_action_t::action_id, cache_t::cache_t::PFF_t::addr, prefetch_buffer_t::addr, cache_t::addr_shift, cache_t::allocate_policy, cache_t::bank_mask, cache_t::banks, BIG_LATENCY, bus_free(), bus_use(), cache_assert, cache_enqueuable(), cache_enqueuable_llc(), cache_enqueue(), cache_enqueue_llc(), cache_fill(), cache_fillable(), cache_get_evictee(), cache_heap_remove(), cache_insert_block(), cache_invalidate(), cache_is_hit(), cache_peek(), CACHE_PREFETCH, CACHE_READ, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_action_t::cb, cache_t::check_for_fill_work, cache_t::check_for_MSHR_fill_work, cache_t::check_for_MSHR_work, cache_t::check_for_pipe_work, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_action_t::cmd, cache_t::cache_t::PFF_t::core, cache_action_t::core, cache_line_t::core, cache_t::core, cache_t::core_lookups, cache_t::core_misses, cache_line_t::dirty, core_t::core_t::core_memory_t::DL2, DO_NOT_TRANSLATE, dummy_callback(), fatal(), fill_arrived(), fill_heap_remove(), cache_t::fill_num, cache_t::fill_pipe, cache_action_t::get_action_id, GET_MSHR_BANK, cache_t::latency, cache_t::linesize, cache_t::load_lookups, cache_t::load_misses, prefetch_t::lookup(), core_t::memory, cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, modinc(), cache_t::MSHR, MSHR_allocate(), MSHR_available(), cache_action_t::MSHR_bank, cache_t::MSHR_banks, cache_t::MSHR_full_cycles, cache_action_t::MSHR_index, cache_action_t::MSHR_linked, cache_t::MSHR_mask, cache_t::MSHR_occupancy, cache_t::MSHR_size, cache_t::name, prefetch_buffer_t::next, cache_t::next_bus, cache_t::next_level, NO_MSHR, cache_t::num_prefetchers, cache_action_t::op, cache_action_t::paddr, PAGE_SIZE, cache_action_t::PC, cache_t::cache_t::PFF_t::PC, cache_t::PF_buffer, cache_t::PF_filter, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::PFF_tail, cache_t::pipe, cache_t::pipe_num, prefetch_filter_lookup(), prefetch_filter_update(), cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_on_miss, cache_line_t::prefetch_used, cache_t::prefetch_useful_insertions, cache_line_t::prefetched, cache_t::prefetcher, cache_action_t::prev_cp, cache_t::prev_level, sim_cycle, cache_t::start_point, cache_t::stat, cache_t::store_lookups, cache_t::store_misses, cache_line_t::tag, TICK_T_MAX, cache_action_t::translated_cb, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, WBB_available(), cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_head, cache_t::WBB_hits, WBB_insert(), cache_t::WBB_num, cache_t::WBB_occupancy, cache_t::WBB_size, cache_t::WBB_victim_hits, WBB_victim_insert(), cache_action_t::when_enqueued, cache_action_t::when_returned, cache_action_t::when_started, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, WRITE_THROUGH, cache_t::writeback_lookups, and cache_t::writeback_misses.
void cache_reg_stats (struct stat_sdb_t *const sdb, const struct core_t *const core, struct cache_t *const cp)
Definition at line 283 of file zesto-cache.cpp.
References CACHE_READWRITE, core_t::current_thread, fatal(), thread_t::id, cache_t::load_lookups, cache_t::load_misses, cache_t::MSHR_combos, cache_t::MSHR_full_cycles, cache_t::MSHR_occupancy, cache_t::name, cache_t::num_prefetchers, cache_t::prefetch_insertions, cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_useful_insertions, cache_t::prefetcher, cache_t::read_only, prefetch_t::reg_stats(), cache_t::stat, stat_reg_counter, stat_reg_formula(), cache_t::store_lookups, cache_t::store_misses, cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_hits, cache_t::WBB_insertions, cache_t::WBB_occupancy, cache_t::WBB_victim_hits, cache_t::WBB_victim_insertions, cache_t::writeback_lookups, and cache_t::writeback_misses.
void cache_reset_stats (struct cache_t *const cp)
Definition at line 518 of file zesto-cache.cpp.
References cache_t::core_lookups, cache_t::core_misses, memzero(), num_threads, and cache_t::stat.
static void dummy_callback (void * p) [static]
Definition at line 1359 of file zesto-cache.cpp.
void fill_arrived (struct cache_t *const cp, const int MSHR_bank, const int MSHR_index)
Definition at line 1367 of file zesto-cache.cpp.
References cache_assert, cache_action_t::cb, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::MSHR, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, sim_cycle, TICK_T_MAX, and cache_action_t::when_returned.
static void fill_heap_balance (struct cache_fill_t *const pipe, const int insert_position) [static]
Definition at line 1417 of file zesto-cache.cpp.
References memswap(), and cache_action_t::pipe_exit_time.
static void fill_heap_remove (struct cache_fill_t *const pipe, const int pipe_num) [static]
Definition at line 1441 of file zesto-cache.cpp.
References memswap(), cache_fill_t::pipe_exit_time, TICK_T_MAX, and cache_fill_t::valid.
static struct cache_action_t* MSHR_allocate (struct cache_t *const cp, const md_paddr_t paddr, const enum cache_command cmd) [static, read]
Definition at line 1305 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_assert, cache_action_t::cb, cache_t::check_for_MSHR_work, cache_t::check_for_work, fatal(), GET_MSHR_BANK, cache_t::MSHR, cache_t::MSHR_combos, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, cache_t::MSHR_size, cache_action_t::paddr, cache_t::stat, TICK_T_MAX, and cache_action_t::when_returned.
static int MSHR_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1295 of file zesto-cache.cpp.
References GET_MSHR_BANK, and cache_t::MSHR_size.
void prefetch_buffer_create (struct cache_t *const cp, const int num_entries)
Definition at line 534 of file zesto-cache.cpp.
References prefetch_buffer_t::addr, fatal(), prefetch_buffer_t::next, cache_t::PF_buffer, and cache_t::PF_buffer_size.
static void prefetch_controller_update (struct cache_t *const cp) [static]
Definition at line 2427 of file zesto-cache.cpp.
References cache_t::next_bus, cache_t::PF_high_watermark, cache_t::PF_last_sample, PF_OK, PF_REFRAIN, cache_t::PF_sample_interval, cache_t::PF_state, sim_cycle, bus_t::stat, and bus_t::utilization.
void prefetch_core_caches (struct core_t *const core)
Definition at line 2450 of file zesto-cache.cpp.
References cache_prefetch(), core_t::core_t::core_memory_t::DL1, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::IL1, and core_t::memory.
void prefetch_filter_create (struct cache_t *const cp, const int num_entries, const int reset_interval)
Definition at line 555 of file zesto-cache.cpp.
References fatal(), prefetch_filter_t::mask, prefetch_filter_t::num_entries, cache_t::PF_filter, prefetch_filter_t::reset_interval, and prefetch_filter_t::table.
static int prefetch_filter_lookup (struct prefetch_filter_t *const p, const md_paddr_t addr) [static]
Definition at line 577 of file zesto-cache.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
static void prefetch_filter_update (struct prefetch_filter_t *const p, const md_paddr_t addr, const int useful) [static]
Definition at line 594 of file zesto-cache.cpp.
References prefetch_filter_t::last_reset, prefetch_filter_t::mask, prefetch_filter_t::num_entries, prefetch_filter_t::reset_interval, sim_cycle, and prefetch_filter_t::table.
void print_heap (const struct cache_t *const cp)
Definition at line 1401 of file zesto-cache.cpp.
References cache_t::banks, cache_t::name, cache_t::pipe, cache_action_t::pipe_exit_time, and cache_t::pipe_num.
void step_core_PF_controllers (struct core_t *const core)
Definition at line 2442 of file zesto-cache.cpp.
References core_t::core_t::core_memory_t::DL1, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::IL1, core_t::memory, and prefetch_controller_update().
static int WBB_available (const struct cache_t *const cp, const md_paddr_t paddr) [inline, static]
Definition at line 1203 of file zesto-cache.cpp.
References GET_MSHR_BANK, cache_t::WBB_num, and cache_t::WBB_size.
static void WBB_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1213 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_assert, CACHE_STAT, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), modinc(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_combines, cache_t::WBB_head, cache_t::WBB_insertions, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, and cache_t::write_combining.
static void WBB_victim_insert (struct cache_t *const cp, struct cache_line_t *const cache_block) [static]
Definition at line 1256 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_assert, CACHE_STAT, cache_line_t::core, cache_line_t::dirty, GET_MSHR_BANK, mod2m(), cache_t::stat, cache_line_t::tag, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, and cache_t::WBB_victim_insertions.