zesto-prefetch.cpp File Reference
#include `sim.h`
#include `stats.h`
#include `valcheck.h`
#include `zesto-opts.h`
#include `zesto-core.h`
#include `zesto-bpred.h`
#include `zesto-cache.h`
#include `zesto-prefetch.h`
#include `zesto-uncore.h`
#include `ZCOMPS-prefetch.list`
Defines
#define PREFETCH_LOOKUP_HEADER md_paddr_t lookup(const md_addr_t PC, const md_paddr_t paddr)
#define PREFETCH_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, const struct core_t * const core)
Functions
struct prefetch_t * prefetch_create (const char *const opt_string, struct cache_t *const cp)
Define Documentation
#define PREFETCH_LOOKUP_HEADER md_paddr_t lookup(const md_addr_t PC, const md_paddr_t paddr)
Definition at line 142 of file zesto-prefetch.cpp.
#define PREFETCH_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, const struct core_t * const core)
Definition at line 144 of file zesto-prefetch.cpp.
Function Documentation
struct prefetch_t* prefetch_create (const char *const opt_string, struct cache_t *const cp) [read]
Definition at line 157 of file zesto-prefetch.cpp.
References fatal(), and prefetch_t::type.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), core_fetch_STM_t::core_fetch_STM_t(), and uncore_t::uncore_t().