zesto-alloc.cpp File Reference
#include <limits.h>
#include `thread.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-oracle.h`
#include `zesto-decode.h`
#include `zesto-alloc.h`
#include `zesto-exec.h`
#include `zesto-commit.h`
#include `ZPIPE-alloc.list`
Functions
void alloc_reg_options (struct opt_odb_t *odb, struct core_knobs_t *knobs)
class core_alloc_t * alloc_create (const char *alloc_opt_string, struct core_t *core)
Function Documentation
class core_alloc_t* alloc_create (const char * alloc_opt_string, struct core_t * core)
Definition at line 116 of file zesto-alloc.cpp.
References fatal().
Referenced by sim_post_init().
void alloc_reg_options (struct opt_odb_t * odb, struct core_knobs_t * knobs)
Definition at line 87 of file zesto-alloc.cpp.
References core_knobs_t::alloc, core_knobs_t::depth, core_knobs_t::drain_flush, opt_reg_flag(), opt_reg_int(), and core_knobs_t::width.