zesto-prefetch.h File Reference
#include `machine.h`
#include `zesto-structs.h`
#include `zesto-cache.h`
Classes
class prefetch_t
Functions
class prefetch_t * prefetch_create (const char *const, struct cache_t *const)
Function Documentation
class prefetch_t* prefetch_create (const char * const, struct cache_t * const) [read]
Definition at line 157 of file zesto-prefetch.cpp.
References fatal(), and prefetch_t::type.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), core_fetch_STM_t::core_fetch_STM_t(), and uncore_t::uncore_t().