zesto-commit.cpp File Reference
#include `sim.h`
#include `thread.h`
#include `zesto-core.h`
#include `zesto-opts.h`
#include `zesto-oracle.h`
#include `zesto-fetch.h`
#include `zesto-decode.h`
#include `zesto-alloc.h`
#include `zesto-exec.h`
#include `zesto-cache.h`
#include `zesto-commit.h`
#include `zesto-bpred.h`
#include `ZPIPE-commit.list`
Defines
#define ZESTO_PARSE_ARGS
Functions
void commit_reg_options (struct opt_odb_t *odb, struct core_knobs_t *knobs)
class core_commit_t * commit_create (const char *commit_opt_string, struct core_t *core)
Define Documentation
#define ZESTO_PARSE_ARGS
Function Documentation
class core_commit_t* commit_create (const char * commit_opt_string, struct core_t * core)
Definition at line 116 of file zesto-commit.cpp.
References fatal().
Referenced by sim_post_init().
void commit_reg_options (struct opt_odb_t * odb, struct core_knobs_t * knobs)
Definition at line 90 of file zesto-commit.cpp.
References core_knobs_t::branch_limit, core_knobs_t::commit, opt_reg_int(), core_knobs_t::ROB_size, and core_knobs_t::width.