zesto-cache.h File Reference
Classes
struct cache_line_t
struct cache_action_t
struct cache_fill_t
struct prefetch_buffer_t
struct prefetch_filter_t
struct bus_t
struct cache_t
struct cache_t::cache_t::PFF_t
Defines
#define NO_MSHR (-1)
#define BIG_LATENCY 99999
#define CACHE_STAT(x) {if(!cp $\rightarrow$ frozen) {x}}
#define GET_BANK(x) (((x)>>cp $\rightarrow$ bank_shift) & cp $\rightarrow$ bank_mask)
#define GET_MSHR_BANK(x) (((x)>>cp $\rightarrow$ bank_shift) & cp $\rightarrow$ MSHR_mask)
#define cache_fatal(msg, retval)
#define cache_assert(cond, retval)
Enumerations
enum cache_command {
CACHE_NOP,
CACHE_READ,
CACHE_WRITE,
CACHE_WRITEBACK,
CACHE_PREFETCH,
REFRESH,
CACHE_NOP,
CACHE_READ,
CACHE_WRITE,
CACHE_WRITEBACK,
CACHE_PREFETCH,
REFRESH,
INVALIDATE,
FWD_DIRTY,
READ_RESPONSE,
WRITE_RESPONSE,
ACK
 }
enum repl_policy_t {
REPLACE_LRU,
REPLACE_MRU,
REPLACE_RANDOM,
REPLACE_NMRU,
REPLACE_PLRU,
REPLACE_CLOCK,
REPLACE_LRU,
REPLACE_MRU,
REPLACE_RANDOM,
REPLACE_NMRU,
REPLACE_PLRU,
REPLACE_CLOCK
 }
enum alloc_policy_t { WRITE_ALLOC,
NO_WRITE_ALLOC,
WRITE_ALLOC,
NO_WRITE_ALLOC
 }
enum write_policy_t { WRITE_THROUGH,
WRITE_BACK,
WRITE_THROUGH,
WRITE_BACK
 }
enum read_only_t { CACHE_READWRITE,
CACHE_READONLY,
CACHE_READWRITE,
CACHE_READONLY
 }
enum coherence_state { MOD,
EXC,
SHR,
INV
 }
enum PF_state_t { PF_REFRAIN,
PF_OK
 }
Functions
struct cache_t * cache_create (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banked, struct cache_t *const next_level_cache, struct bus_t *const bus_next)
struct cache_t * cache_create_llc (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banked, const int begin_index, const int end_index, struct cache_t *const next_level_cache, struct bus_t *const bus_next)
void cache_reg_stats (struct stat_sdb_t *const sdb, const struct core_t *const core, struct cache_t *const cp)
void LLC_reg_stats (struct stat_sdb_t *const sdb, struct cache_t *const cp)
void cache_reset_stats (struct cache_t *const cp)
void prefetch_buffer_create (struct cache_t *const cp, const int num_entries)
void prefetch_filter_create (struct cache_t *const cp, const int num_entries, const int reset_interval)
void cache_process (struct cache_t *const cp)
void cache_process_llc (struct cache_t *const cp)
struct cache_line_t * cache_is_hit (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
struct cache_line_t * cache_is_hit_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
void cache_insert_block (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
struct cache_line_t * cache_invalidate (struct cache_t *const cp, const md_paddr_t addr, core_t *const core)
void cache_insert_block_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
struct cache_line_t * cache_get_evictee (struct cache_t *const cp, const md_paddr_t addr, struct core_t *const core)
struct cache_line_t * cache_get_evictee_llc (struct cache_t *const cp, const md_paddr_t addr, struct core_t *const core)
int cache_enqueuable (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
int cache_enqueuable_llc (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
void cache_enqueue (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*const cb)(void *), void(*const miss_cb)(void *, int), bool(*const translated_cb)(void *, seq_t), seq_t(*const get_action_id)(void *))
void cache_enqueue_llc (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*const cb)(void *), void(*const miss_cb)(void *, int), bool(*const translated_cb)(void *, seq_t), seq_t(*const get_action_id)(void *))
void fill_arrived (struct cache_t *const cp, const int MSHR_bank, const int MSHR_index)
void fill_arrived_llc (struct cache_t *const cp, unsigned long long int address)
void step_core_PF_controllers (struct core_t *const core)
void prefetch_core_caches (struct core_t *const core)
void step_LLC_PF_controller (struct uncore_t *const uncore)
void prefetch_LLC (struct uncore_t *const uncore)
void cache_freeze_stats (struct core_t *const core)
struct bus_t * bus_create (const char *const name, const int width, const int ratio)
void bus_reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core, struct bus_t *const bus)
int bus_free (const struct bus_t *const bus)
void bus_use (struct bus_t *const bus, const int transfer_size, const int prefetch)
Define Documentation
#define BIG_LATENCY 99999
Definition at line 87 of file zesto-cache.h.
#define cache_assert(cond, retval)
Value:
{ \
  if(!(cond)) { \
    fprintf(stderr,"assertion failed (%s,%d:%s): ",__FILE__,__LINE__,cp->name); \
    fprintf(stderr,"%s\n",#cond); \
    return (retval); \
  } \
}
Definition at line 515 of file zesto-cache.h.
#define cache_fatal(msg, retval)
Value:
{ \
  fprintf(stderr,"fatal (%s,%d:%s): ",__FILE__,__LINE__,cp->name); \
  fprintf(stderr,"%s\n",msg); \
  return (retval); \
}
Definition at line 503 of file zesto-cache.h.
#define CACHE_STAT(x) {if(!cp $\rightarrow$ frozen) {x}}
Definition at line 89 of file zesto-cache.h.
#define GET_BANK(x) (((x)>>cp $\rightarrow$ bank_shift) & cp $\rightarrow$ bank_mask)
Definition at line 91 of file zesto-cache.h.
#define GET_MSHR_BANK(x) (((x)>>cp $\rightarrow$ bank_shift) & cp $\rightarrow$ MSHR_mask)
Definition at line 92 of file zesto-cache.h.
#define NO_MSHR (-1)
Definition at line 83 of file zesto-cache.h.
Enumeration Type Documentation
enum alloc_policy_t
Enumerator:
WRITE_ALLOC
NO_WRITE_ALLOC
WRITE_ALLOC
NO_WRITE_ALLOC
Definition at line 103 of file zesto-cache.h.
enum cache_command
Enumerator:
CACHE_NOP
CACHE_READ
CACHE_WRITE
CACHE_WRITEBACK
CACHE_PREFETCH
REFRESH
CACHE_NOP
CACHE_READ
CACHE_WRITE
CACHE_WRITEBACK
CACHE_PREFETCH
REFRESH
INVALIDATE
FWD_DIRTY
READ_RESPONSE
WRITE_RESPONSE
ACK
Definition at line 96 of file zesto-cache.h.
enum coherence_state
Enumerator:
MOD
EXC
SHR
INV
Definition at line 106 of file zesto-cache.h.
enum PF_state_t
Enumerator:
PF_REFRAIN
PF_OK
Definition at line 108 of file zesto-cache.h.
enum read_only_t
Enumerator:
CACHE_READWRITE
CACHE_READONLY
CACHE_READWRITE
CACHE_READONLY
Definition at line 105 of file zesto-cache.h.
enum repl_policy_t
Enumerator:
REPLACE_LRU
REPLACE_MRU
REPLACE_RANDOM
REPLACE_NMRU
REPLACE_PLRU
REPLACE_CLOCK
REPLACE_LRU
REPLACE_MRU
REPLACE_RANDOM
REPLACE_NMRU
REPLACE_PLRU
REPLACE_CLOCK
Definition at line 102 of file zesto-cache.h.
enum write_policy_t
Enumerator:
WRITE_THROUGH
WRITE_BACK
WRITE_THROUGH
WRITE_BACK
Definition at line 104 of file zesto-cache.h.
Function Documentation
struct bus_t* bus_create (const char *const name, const int width, const int ratio) [read]
Definition at line 2465 of file config/zesto-cache.cpp.
References fatal(), bus_t::name, bus_t::ratio, and bus_t::width.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), and uncore_t::uncore_t().
int bus_free (const struct bus_t *const bus)
Definition at line 2518 of file config/zesto-cache.cpp.
References bus_t::ratio, sim_cycle, and bus_t::when_available.
Referenced by cache_process(), and cache_process_llc().
void bus_reg_stats (struct stat_sdb_t *const sdb, struct core_t *const core, struct bus_t *const bus)
Definition at line 2479 of file config/zesto-cache.cpp.
References bus_t::accesses, core_t::current_thread, thread_t::id, bus_t::name, bus_t::prefetch_utilization, bus_t::stat, stat_reg_counter, stat_reg_formula(), and bus_t::utilization.
Referenced by core_exec_STM_t::reg_stats(), and uncore_t::uncore_reg_stats().
void bus_use (struct bus_t *const bus, const int transfer_size, const int prefetch)
Definition at line 2529 of file config/zesto-cache.cpp.
References bus_t::accesses, bus_t::prefetch_utilization, bus_t::ratio, sim_cycle, bus_t::stat, bus_t::utilization, bus_t::when_available, and bus_t::width.
Referenced by cache_process(), and cache_process_llc().
struct cache_t* cache_create (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banked, struct cache_t *const next_level_cache, struct bus_t *const bus_next) [read]
Definition at line 88 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_t::allocate_policy, cache_t::assoc, cache_t::bank_mask, cache_t::bank_shift, cache_t::bank_width, cache_t::banks, cache_t::blocks, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::core, cache_t::core_lookups, cache_t::core_misses, fatal(), cache_t::fill_num, cache_t::fill_pipe, cache_t::heap_size, cache_t::latency, cache_t::linesize, cache_t::log2_assoc, cache_t::MSHR, cache_t::MSHR_banks, cache_t::MSHR_mask, cache_t::MSHR_size, mytoupper(), cache_t::name, cache_line_t::next, cache_t::next_bus, cache_t::next_level, NO_WRITE_ALLOC, num_threads, cache_t::pipe, cache_t::pipe_num, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::way, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, and WRITE_THROUGH.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_exec_STM_t::core_exec_STM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), and core_fetch_STM_t::core_fetch_STM_t().
struct cache_t* cache_create_llc (struct core_t *const core, const char *const name, const bool read_only, const int sets, const int assoc, const int linesize, const char rp, const char ap, const char wp, const char wc, const int banks, const int bank_width, const int latency, const int WBB_size, const int MSHR_size, const int MSHR_banked, const int begin_index, const int end_index, struct cache_t *const next_level_cache, struct bus_t *const bus_next) [read]
Definition at line 87 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_t::allocate_policy, cache_t::assoc, cache_t::bank_mask, cache_t::bank_shift, cache_t::bank_width, cache_t::banks, cache_t::blocks, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::core, cache_t::core_lookups, cache_t::core_misses, fatal(), cache_t::fill_num, cache_t::fill_pipe, cache_t::heap_size, cache_t::latency, cache_t::linesize, cache_t::log2_assoc, cache_t::MSHR, cache_t::MSHR_banks, cache_t::MSHR_mask, cache_t::MSHR_size, mytoupper(), cache_t::name, cache_line_t::next, cache_t::next_bus, cache_t::next_level, NO_WRITE_ALLOC, num_threads, cache_t::pipe, cache_t::pipe_num, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::way, cache_t::WBB, cache_t::WBB_head, cache_t::WBB_num, cache_t::WBB_size, cache_t::WBB_tail, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, and WRITE_THROUGH.
int cache_enqueuable (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
Definition at line 1076 of file config/zesto-cache.cpp.
References DO_NOT_TRANSLATE, GET_BANK, cache_t::latency, and cache_t::pipe_num.
Referenced by cache_prefetch(), cache_prefetch_llc(), cache_process(), core_exec_STM_t::LDQ_schedule(), core_exec_DPM_t::LDQ_schedule(), core_fetch_STM_t::step(), core_fetch_DPM_t::step(), core_exec_STM_t::STQ_deallocate_std(), and core_exec_DPM_t::STQ_deallocate_std().
int cache_enqueuable_llc (const struct cache_t *const cp, const int thread_id, const md_paddr_t addr)
Definition at line 989 of file config/zesto-llc.cpp.
References DO_NOT_TRANSLATE, GET_BANK, cache_t::latency, and cache_t::pipe_num.
void cache_enqueue (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*)(void *) cb, void(*)(void *, int) miss_cb, bool(*)(void *, seq_t) translated_cb, seq_t(*)(void *) get_action_id)
Definition at line 1095 of file config/zesto-cache.cpp.
References cache_action_t::action_id, cache_assert, cache_heap_balance(), cache_action_t::cb, cache_t::check_for_pipe_work, cache_t::check_for_work, cache_action_t::cmd, cache_action_t::core, DO_NOT_TRANSLATE, cache_action_t::get_action_id, GET_BANK, cache_t::latency, cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, cache_action_t::MSHR_bank, cache_action_t::MSHR_index, cache_action_t::op, cache_action_t::paddr, cache_action_t::PC, cache_t::pipe, cache_action_t::pipe_exit_time, cache_t::pipe_num, cache_action_t::prev_cp, sim_cycle, TICK_T_MAX, cache_action_t::translated_cb, cache_action_t::when_returned, and cache_action_t::when_started.
Referenced by cache_prefetch(), cache_prefetch_llc(), cache_process(), core_exec_STM_t::LDQ_schedule(), core_exec_DPM_t::LDQ_schedule(), core_fetch_STM_t::step(), core_fetch_DPM_t::step(), core_exec_STM_t::STQ_deallocate_std(), and core_exec_DPM_t::STQ_deallocate_std().
void cache_enqueue_llc (struct core_t *const core, struct cache_t *const cp, struct cache_t *const prev_cp, const enum cache_command cmd, const int thread_id, const md_addr_t PC, const md_paddr_t addr, const seq_t action_id, const int MSHR_bank, const int MSHR_index, void *const op, void(*)(void *) cb, void(*)(void *, int) miss_cb, bool(*)(void *, seq_t) translated_cb, seq_t(*)(void *) get_action_id)
Definition at line 1008 of file config/zesto-llc.cpp.
References cache_action_t::action_id, cache_assert, cache_heap_balance(), cache_action_t::cb, cache_t::check_for_pipe_work, cache_t::check_for_work, cache_action_t::cmd, cache_action_t::core, DO_NOT_TRANSLATE, cache_action_t::get_action_id, GET_BANK, cache_t::latency, cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, cache_action_t::MSHR_bank, cache_action_t::MSHR_index, cache_action_t::op, cache_action_t::paddr, cache_action_t::PC, cache_t::pipe, cache_action_t::pipe_exit_time, cache_t::pipe_num, cache_action_t::prev_cp, sim_cycle, TICK_T_MAX, cache_action_t::translated_cb, cache_action_t::when_returned, and cache_action_t::when_started.
void cache_freeze_stats (struct core_t *const core)
Definition at line 2402 of file config/zesto-cache.cpp.
References core_t::core_t::core_memory_t::DL1, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::DTLB, core_t::core_t::core_memory_t::DTLB2, cache_t::frozen, core_t::core_t::core_memory_t::IL1, core_t::core_t::core_memory_t::ITLB, and core_t::memory.
Referenced by core_commit_STM_t::step(), and core_commit_DPM_t::step().
struct cache_line_t* cache_get_evictee (struct cache_t *const cp, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 840 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_t::assoc, cache_t::blocks, fatal(), cache_t::log2_assoc, cache_line_t::meta, modinc(), cache_t::name, cache_line_t::next, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::valid, and cache_line_t::way.
Referenced by cache_process(), and sim_fastfwd().
struct cache_line_t* cache_get_evictee_llc (struct cache_t *const cp, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 751 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_t::assoc, cache_t::blocks, fatal(), cache_t::log2_assoc, cache_line_t::meta, modinc(), cache_t::name, cache_line_t::next, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::valid, and cache_line_t::way.
void cache_insert_block (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
Definition at line 742 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_PREFETCH, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::core, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::prefetch_insertions, cache_line_t::prefetched, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::tag, cache_line_t::valid, and cache_line_t::way.
Referenced by cache_process(), and sim_fastfwd().
void cache_insert_block_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core)
Definition at line 653 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_PREFETCH, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::core, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::prefetch_insertions, cache_line_t::prefetched, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_t::stat, cache_line_t::tag, cache_line_t::valid, and cache_line_t::way.
struct cache_line_t* cache_invalidate (struct cache_t *const cp, const md_paddr_t addr, core_t *const core) [read]
Definition at line 841 of file zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_invalidate(), cache_peek(), cache_line_t::dirty, fatal(), cache_line_t::next, cache_t::prev_level, cache_t::sets, cache_line_t::tag, and cache_line_t::valid.
Referenced by cache_invalidate(), cache_process(), and cache_process_llc().
struct cache_line_t* cache_is_hit (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 618 of file config/zesto-cache.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_READONLY, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::tag, cache_line_t::valid, cache_line_t::way, WRITE_BACK, and cache_t::write_policy.
Referenced by cache_process(), and sim_fastfwd().
struct cache_line_t* cache_is_hit_llc (struct cache_t *const cp, const enum cache_command cmd, const md_paddr_t addr, struct core_t *const core) [read]
Definition at line 529 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_t::blocks, cache_assert, CACHE_READONLY, CACHE_WRITE, CACHE_WRITEBACK, cache_line_t::dirty, fatal(), cache_t::log2_assoc, cache_line_t::meta, cache_line_t::next, cache_t::read_only, REPLACE_CLOCK, REPLACE_LRU, REPLACE_MRU, REPLACE_NMRU, REPLACE_PLRU, REPLACE_RANDOM, cache_t::replacement_policy, cache_t::sets, cache_line_t::tag, cache_line_t::valid, cache_line_t::way, WRITE_BACK, and cache_t::write_policy.
void cache_process (struct cache_t *const cp)
Definition at line 1523 of file config/zesto-cache.cpp.
References cache_action_t::action_id, cache_t::cache_t::PFF_t::addr, prefetch_buffer_t::addr, cache_t::addr_shift, cache_t::allocate_policy, cache_t::bank_mask, cache_t::banks, BIG_LATENCY, bus_free(), bus_use(), cache_assert, cache_enqueuable(), cache_enqueuable_llc(), cache_enqueue(), cache_enqueue_llc(), cache_fill(), cache_fillable(), cache_get_evictee(), cache_heap_remove(), cache_insert_block(), cache_invalidate(), cache_is_hit(), cache_peek(), CACHE_PREFETCH, CACHE_READ, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_action_t::cb, cache_t::check_for_fill_work, cache_t::check_for_MSHR_fill_work, cache_t::check_for_MSHR_work, cache_t::check_for_pipe_work, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_action_t::cmd, cache_t::cache_t::PFF_t::core, cache_action_t::core, cache_line_t::core, cache_t::core, cache_t::core_lookups, cache_t::core_misses, cache_line_t::dirty, core_t::core_t::core_memory_t::DL2, DO_NOT_TRANSLATE, dummy_callback(), fatal(), fill_arrived(), fill_heap_remove(), cache_t::fill_num, cache_t::fill_pipe, cache_action_t::get_action_id, GET_MSHR_BANK, cache_t::latency, cache_t::linesize, cache_t::load_lookups, cache_t::load_misses, prefetch_t::lookup(), core_t::memory, cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, modinc(), cache_t::MSHR, MSHR_allocate(), MSHR_available(), cache_action_t::MSHR_bank, cache_t::MSHR_banks, cache_t::MSHR_full_cycles, cache_action_t::MSHR_index, cache_action_t::MSHR_linked, cache_t::MSHR_mask, cache_t::MSHR_occupancy, cache_t::MSHR_size, cache_t::name, prefetch_buffer_t::next, cache_t::next_bus, cache_t::next_level, NO_MSHR, cache_t::num_prefetchers, cache_action_t::op, cache_action_t::paddr, PAGE_SIZE, cache_action_t::PC, cache_t::cache_t::PFF_t::PC, cache_t::PF_buffer, cache_t::PF_filter, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::PFF_tail, cache_t::pipe, cache_t::pipe_num, prefetch_filter_lookup(), prefetch_filter_update(), cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_on_miss, cache_line_t::prefetch_used, cache_t::prefetch_useful_insertions, cache_line_t::prefetched, cache_t::prefetcher, cache_action_t::prev_cp, cache_t::prev_level, sim_cycle, cache_t::start_point, cache_t::stat, cache_t::store_lookups, cache_t::store_misses, cache_line_t::tag, TICK_T_MAX, cache_action_t::translated_cb, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, WBB_available(), cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_head, cache_t::WBB_hits, WBB_insert(), cache_t::WBB_num, cache_t::WBB_occupancy, cache_t::WBB_size, cache_t::WBB_victim_hits, WBB_victim_insert(), cache_action_t::when_enqueued, cache_action_t::when_returned, cache_action_t::when_started, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, WRITE_THROUGH, cache_t::writeback_lookups, and cache_t::writeback_misses.
Referenced by core_exec_STM_t::LDST_exec(), core_exec_DPM_t::LDST_exec(), core_fetch_STM_t::step(), and core_fetch_DPM_t::step().
void cache_process_llc (struct cache_t *const cp)
Definition at line 1422 of file config/zesto-llc.cpp.
References cache_action_t::action_id, cache_t::cache_t::PFF_t::addr, prefetch_buffer_t::addr, cache_t::addr_shift, cache_t::allocate_policy, cache_t::bank_mask, cache_t::banks, BIG_LATENCY, bus_free(), bus_use(), cache_assert, cache_fill_llc(), cache_fillable_llc(), cache_get_evictee_llc(), cache_heap_remove(), cache_insert_block_llc(), cache_invalidate(), cache_is_hit_llc(), cache_peek_llc(), CACHE_PREFETCH, CACHE_READ, CACHE_STAT, CACHE_WRITE, CACHE_WRITEBACK, cache_action_t::cb, cache_t::check_for_fill_work, cache_t::check_for_MSHR_fill_work, cache_t::check_for_MSHR_work, cache_t::check_for_pipe_work, cache_t::check_for_WBB_work, cache_t::check_for_work, cache_action_t::cmd, cache_t::cache_t::PFF_t::core, cache_line_t::core, cache_t::core, cache_action_t::core, cache_t::core_lookups, cache_t::core_misses, cache_line_t::dirty, uncore_t::enqueuable(), uncore_t::enqueue(), fatal(), fill_arrived(), fill_heap_remove(), cache_t::fill_num, cache_t::fill_pipe, cache_action_t::get_action_id, GET_MSHR_BANK, cache_t::latency, cache_t::linesize, uncore_t::LLC, cache_t::load_lookups, cache_t::load_misses, prefetch_t::lookup(), cache_action_t::miss_cb, cache_action_t::miss_cb_invoked, modinc(), cache_t::MSHR, MSHR_allocate(), MSHR_available(), cache_action_t::MSHR_bank, cache_t::MSHR_banks, cache_t::MSHR_full_cycles, cache_action_t::MSHR_index, cache_action_t::MSHR_linked, cache_t::MSHR_mask, cache_t::MSHR_occupancy, cache_t::MSHR_size, cache_t::name, prefetch_buffer_t::next, cache_t::next_bus, cache_t::next_level, NO_MSHR, cache_t::num_prefetchers, cache_action_t::op, cache_action_t::paddr, PAGE_SIZE, cache_t::cache_t::PFF_t::PC, cache_t::PF_buffer, cache_t::PF_filter, cache_t::PFF, cache_t::PFF_head, cache_t::PFF_num, cache_t::PFF_size, cache_t::PFF_tail, cache_t::pipe, cache_t::pipe_num, prefetch_filter_lookup(), prefetch_filter_update(), cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_on_miss, cache_line_t::prefetch_used, cache_t::prefetch_useful_insertions, cache_line_t::prefetched, cache_t::prefetcher, cache_action_t::prev_cp, cache_t::prev_level, sim_cycle, cache_t::start_point, cache_t::stat, cache_t::store_lookups, cache_t::store_misses, cache_line_t::tag, TICK_T_MAX, cache_action_t::translated_cb, cache_t::uncore, cache_line_t::valid, cache_line_t::victim, cache_t::WBB, WBB_available(), cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_head, cache_t::WBB_hits, WBB_insert(), cache_t::WBB_num, cache_t::WBB_occupancy, cache_t::WBB_size, cache_t::WBB_victim_hits, cache_action_t::when_enqueued, cache_action_t::when_returned, cache_action_t::when_started, WRITE_ALLOC, WRITE_BACK, cache_t::write_combining, cache_t::write_policy, WRITE_THROUGH, cache_t::writeback_lookups, and cache_t::writeback_misses.
void cache_reg_stats (struct stat_sdb_t *const sdb, const struct core_t *const core, struct cache_t *const cp)
Definition at line 280 of file config/zesto-cache.cpp.
References CACHE_READWRITE, core_t::current_thread, fatal(), thread_t::id, cache_t::load_lookups, cache_t::load_misses, cache_t::MSHR_combos, cache_t::MSHR_full_cycles, cache_t::MSHR_occupancy, cache_t::name, cache_t::num_prefetchers, cache_t::prefetch_insertions, cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_useful_insertions, cache_t::prefetcher, cache_t::read_only, prefetch_t::reg_stats(), cache_t::stat, stat_reg_counter, stat_reg_formula(), cache_t::store_lookups, cache_t::store_misses, cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_hits, cache_t::WBB_insertions, cache_t::WBB_occupancy, cache_t::WBB_victim_hits, cache_t::WBB_victim_insertions, cache_t::writeback_lookups, and cache_t::writeback_misses.
Referenced by core_fetch_STM_t::reg_stats(), core_fetch_DPM_t::reg_stats(), core_exec_STM_t::reg_stats(), and core_exec_DPM_t::reg_stats().
void cache_reset_stats (struct cache_t *const cp)
Definition at line 515 of file config/zesto-cache.cpp.
References cache_t::core_lookups, cache_t::core_misses, memzero(), num_threads, and cache_t::stat.
Referenced by emergency_recovery(), and sim_fastfwd().
void fill_arrived (struct cache_t *const cp, const int MSHR_bank, const int MSHR_index)
Definition at line 1333 of file config/zesto-cache.cpp.
References cache_assert, cache_action_t::cb, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::MSHR, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, sim_cycle, TICK_T_MAX, and cache_action_t::when_returned.
Referenced by cache_process(), and cache_process_llc().
void fill_arrived_llc (struct cache_t *const cp, unsigned long long int address)
Definition at line 1245 of file config/zesto-llc.cpp.
References cache_t::addr_shift, cache_action_t::cb, cache_t::check_for_MSHR_fill_work, cache_t::check_for_work, cache_t::MSHR, cache_t::MSHR_banks, cache_action_t::MSHR_link, cache_action_t::MSHR_linked, cache_t::MSHR_mask, cache_t::MSHR_size, cache_action_t::paddr, sim_cycle, and cache_action_t::when_returned.
void LLC_reg_stats (struct stat_sdb_t *const sdb, struct cache_t *const cp)
Definition at line 281 of file config/zesto-llc.cpp.
References CACHE_READWRITE, uncore_t::core, cache_t::core_lookups, cache_t::core_misses, core_t::id, cache_t::load_lookups, cache_t::load_misses, cache_t::MSHR_combos, cache_t::MSHR_full_cycles, cache_t::MSHR_occupancy, cache_t::name, NetworkComponent::node_ip, uncore_t::num_cores, cache_t::num_prefetchers, num_threads, cache_t::prefetch_insertions, cache_t::prefetch_lookups, cache_t::prefetch_misses, cache_t::prefetch_useful_insertions, cache_t::prefetcher, cache_t::read_only, prefetch_t::reg_stats(), cache_t::stat, stat_reg_counter, stat_reg_formula(), cache_t::store_lookups, cache_t::store_misses, cache_t::uncore, cache_t::WBB_combines, cache_t::WBB_full_cycles, cache_t::WBB_hits, cache_t::WBB_insertions, cache_t::WBB_occupancy, cache_t::WBB_victim_hits, cache_t::WBB_victim_insertions, cache_t::writeback_lookups, and cache_t::writeback_misses.
void prefetch_buffer_create (struct cache_t *const cp, const int num_entries)
Definition at line 531 of file config/zesto-cache.cpp.
References prefetch_buffer_t::addr, fatal(), prefetch_buffer_t::next, cache_t::PF_buffer, and cache_t::PF_buffer_size.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), and uncore_t::uncore_t().
void prefetch_core_caches (struct core_t *const core)
Definition at line 2395 of file config/zesto-cache.cpp.
References cache_prefetch(), core_t::core_t::core_memory_t::DL1, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::IL1, and core_t::memory.
Referenced by zesto_component::downtick_handler().
void prefetch_filter_create (struct cache_t *const cp, const int num_entries, const int reset_interval)
Definition at line 552 of file config/zesto-cache.cpp.
References fatal(), prefetch_filter_t::mask, prefetch_filter_t::num_entries, cache_t::PF_filter, prefetch_filter_t::reset_interval, and prefetch_filter_t::table.
Referenced by core_exec_DPM_t::core_exec_DPM_t(), core_fetch_DPM_t::core_fetch_DPM_t(), and uncore_t::uncore_t().
void prefetch_LLC (struct uncore_t *const uncore)
Definition at line 2229 of file config/zesto-llc.cpp.
References cache_prefetch_llc(), and uncore_t::LLC.
void step_core_PF_controllers (struct core_t *const core)
Definition at line 2387 of file config/zesto-cache.cpp.
References core_t::core_t::core_memory_t::DL1, core_t::core_t::core_memory_t::DL2, core_t::core_t::core_memory_t::IL1, core_t::memory, and prefetch_controller_update().
Referenced by zesto_component::downtick_handler().
void step_LLC_PF_controller (struct uncore_t *const uncore)
Definition at line 2223 of file config/zesto-llc.cpp.
References uncore_t::LLC, and prefetch_controller_update_llc().