zesto-bpred.cpp File Reference
#include <math.h>
#include `sim.h`
#include `stats.h`
#include `valcheck.h`
#include `zesto-core.h`
#include `zesto-bpred.h`
#include `ZCOMPS-bpred.list`
#include `ZCOMPS-fusion.list`
#include `ZCOMPS-btb.list`
#include `ZCOMPS-ras.list`
Defines
#define BPRED_STAT(x) if(!frozen) {x}
#define BPRED_LOOKUP_HEADER bool lookup(class bpred_sc_t * const scvp, const md_addr_t PC, const md_addr_t tPC, const md_addr_t oPC, const bool outcome)
#define BPRED_UPDATE_HEADER void update(class bpred_sc_t * const scvp, const md_addr_t PC, const md_addr_t tPC, const md_addr_t oPC, const bool outcome, const bool our_pred)
#define BPRED_SPEC_UPDATE_HEADER void spec_update(class bpred_sc_t * const scvp, const md_addr_t PC, const md_addr_t tPC, const md_addr_t oPC, const bool outcome, const bool our_pred)
#define BPRED_RECOVER_HEADER void recover(class bpred_sc_t * const scvp, const bool outcome)
#define BPRED_FLUSH_HEADER void flush(class bpred_sc_t * const scvp)
#define BPRED_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
#define BPRED_RESET_STATS_HEADER void reset_stats(void)
#define BPRED_GET_CACHE_HEADER class bpred_sc_t * get_cache(void)
#define BPRED_RET_CACHE_HEADER void ret_cache(class bpred_sc_t * const scvp)
#define FUSION_LOOKUP_HEADER bool lookup(class fusion_sc_t * const scvp,const bool * const preds,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome)
#define FUSION_UPDATE_HEADER void update(class fusion_sc_t * const scvp,const bool * const preds,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome,const bool our_pred)
#define FUSION_SPEC_UPDATE_HEADER void spec_update(class fusion_sc_t * const scvp,const bool * const preds,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome,const bool our_pred)
#define FUSION_RECOVER_HEADER void recover(class fusion_sc_t * const scvp,bool const outcome)
#define FUSION_FLUSH_HEADER void flush(class fusion_sc_t * const scvp)
#define FUSION_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
#define FUSION_RESET_STATS_HEADER void reset_stats(void)
#define FUSION_GET_CACHE_HEADER class fusion_sc_t * get_cache(void)
#define FUSION_RET_CACHE_HEADER void ret_cache(class fusion_sc_t * const scvp)
#define BTB_LOOKUP_HEADER md_addr_t lookup(class BTB_sc_t * const scvp,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome,const bool our_pred)
#define BTB_UPDATE_HEADER void update(class BTB_sc_t * const scvp,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const md_addr_t our_target,const bool outcome,const bool our_pred)
#define BTB_SPEC_UPDATE_HEADER void spec_update(class BTB_sc_t * const scvp,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const md_addr_t our_target,const bool outcome,const bool our_pred)
#define BTB_RECOVER_HEADER void recover(class BTB_sc_t * const scvp,const bool outcome)
#define BTB_FLUSH_HEADER void flush(class BTB_sc_t * const scvp)
#define BTB_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
#define BTB_RESET_STATS_HEADER void reset_stats(void)
#define BTB_GET_CACHE_HEADER class BTB_sc_t * get_cache(void)
#define BTB_RET_CACHE_HEADER void ret_cache(class BTB_sc_t * const scvp)
#define RAS_PUSH_HEADER void push(const md_addr_t PC,const md_addr_t ftPC,const md_addr_t tPC,const md_addr_t oPC)
#define RAS_POP_HEADER md_addr_t pop(const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC)
#define RAS_RECOVER_HEADER void recover(class RAS_chkpt_t * const cpvp)
#define RAS_RECOVER_STATE_HEADER void recover_state(class RAS_chkpt_t * const cpvp)
#define RAS_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
#define RAS_RESET_STATS_HEADER void reset_stats(void)
#define RAS_GET_STATE_HEADER class RAS_chkpt_t * get_state(void)
#define RAS_RET_STATE_HEADER void ret_state(class RAS_chkpt_t * const cpvp)
Functions
static class bpred_dir_t * bpred_from_string (char *const opt_string)
static class fusion_t * fusion_from_string (const int num_pred, struct bpred_dir_t **bpreds, char *const opt_string)
static class BTB_t * BTB_from_string (char *const opt_string)
static class RAS_t * RAS_from_string (char *const opt_string)
Define Documentation
#define BPRED_FLUSH_HEADER void flush(class bpred_sc_t * const scvp)
Definition at line 125 of file zesto-bpred.cpp.
#define BPRED_GET_CACHE_HEADER class bpred_sc_t * get_cache(void)
Definition at line 131 of file zesto-bpred.cpp.
#define BPRED_LOOKUP_HEADER bool lookup(class bpred_sc_t * const scvp, const md_addr_t PC, const md_addr_t tPC, const md_addr_t oPC, const bool outcome)
Definition at line 117 of file zesto-bpred.cpp.
#define BPRED_RECOVER_HEADER void recover(class bpred_sc_t * const scvp, const bool outcome)
Definition at line 123 of file zesto-bpred.cpp.
#define BPRED_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
Definition at line 127 of file zesto-bpred.cpp.
#define BPRED_RESET_STATS_HEADER void reset_stats(void)
Definition at line 129 of file zesto-bpred.cpp.
#define BPRED_RET_CACHE_HEADER void ret_cache(class bpred_sc_t * const scvp)
Definition at line 133 of file zesto-bpred.cpp.
#define BPRED_SPEC_UPDATE_HEADER void spec_update(class bpred_sc_t * const scvp, const md_addr_t PC, const md_addr_t tPC, const md_addr_t oPC, const bool outcome, const bool our_pred)
Definition at line 121 of file zesto-bpred.cpp.
#define BPRED_STAT(x) if(!frozen) {x}
Definition at line 98 of file zesto-bpred.cpp.
Referenced by bpred_t::lookup(), bpred_t::spec_update(), BTB_t::spec_update(), fusion_t::spec_update(), bpred_dir_t::spec_update(), bpred_t::update(), fusion_t::update(), and bpred_dir_t::update().
#define BPRED_UPDATE_HEADER void update(class bpred_sc_t * const scvp, const md_addr_t PC, const md_addr_t tPC, const md_addr_t oPC, const bool outcome, const bool our_pred)
Definition at line 119 of file zesto-bpred.cpp.
#define BTB_FLUSH_HEADER void flush(class BTB_sc_t * const scvp)
Definition at line 490 of file zesto-bpred.cpp.
#define BTB_GET_CACHE_HEADER class BTB_sc_t * get_cache(void)
Definition at line 496 of file zesto-bpred.cpp.
#define BTB_LOOKUP_HEADER md_addr_t lookup(class BTB_sc_t * const scvp,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome,const bool our_pred)
Definition at line 482 of file zesto-bpred.cpp.
#define BTB_RECOVER_HEADER void recover(class BTB_sc_t * const scvp,const bool outcome)
Definition at line 488 of file zesto-bpred.cpp.
#define BTB_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
Definition at line 492 of file zesto-bpred.cpp.
#define BTB_RESET_STATS_HEADER void reset_stats(void)
Definition at line 494 of file zesto-bpred.cpp.
#define BTB_RET_CACHE_HEADER void ret_cache(class BTB_sc_t * const scvp)
Definition at line 498 of file zesto-bpred.cpp.
#define BTB_SPEC_UPDATE_HEADER void spec_update(class BTB_sc_t * const scvp,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const md_addr_t our_target,const bool outcome,const bool our_pred)
Definition at line 486 of file zesto-bpred.cpp.
#define BTB_UPDATE_HEADER void update(class BTB_sc_t * const scvp,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const md_addr_t our_target,const bool outcome,const bool our_pred)
Definition at line 484 of file zesto-bpred.cpp.
#define FUSION_FLUSH_HEADER void flush(class fusion_sc_t * const scvp)
Definition at line 304 of file zesto-bpred.cpp.
#define FUSION_GET_CACHE_HEADER class fusion_sc_t * get_cache(void)
Definition at line 310 of file zesto-bpred.cpp.
#define FUSION_LOOKUP_HEADER bool lookup(class fusion_sc_t * const scvp,const bool * const preds,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome)
Definition at line 296 of file zesto-bpred.cpp.
#define FUSION_RECOVER_HEADER void recover(class fusion_sc_t * const scvp,bool const outcome)
Definition at line 302 of file zesto-bpred.cpp.
#define FUSION_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
Definition at line 306 of file zesto-bpred.cpp.
#define FUSION_RESET_STATS_HEADER void reset_stats(void)
Definition at line 308 of file zesto-bpred.cpp.
#define FUSION_RET_CACHE_HEADER void ret_cache(class fusion_sc_t * const scvp)
Definition at line 312 of file zesto-bpred.cpp.
#define FUSION_SPEC_UPDATE_HEADER void spec_update(class fusion_sc_t * const scvp,const bool * const preds,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome,const bool our_pred)
Definition at line 300 of file zesto-bpred.cpp.
#define FUSION_UPDATE_HEADER void update(class fusion_sc_t * const scvp,const bool * const preds,const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC,const bool outcome,const bool our_pred)
Definition at line 298 of file zesto-bpred.cpp.
#define RAS_GET_STATE_HEADER class RAS_chkpt_t * get_state(void)
Definition at line 680 of file zesto-bpred.cpp.
#define RAS_POP_HEADER md_addr_t pop(const md_addr_t PC,const md_addr_t tPC,const md_addr_t oPC)
Definition at line 670 of file zesto-bpred.cpp.
#define RAS_PUSH_HEADER void push(const md_addr_t PC,const md_addr_t ftPC,const md_addr_t tPC,const md_addr_t oPC)
Definition at line 668 of file zesto-bpred.cpp.
#define RAS_RECOVER_HEADER void recover(class RAS_chkpt_t * const cpvp)
Definition at line 672 of file zesto-bpred.cpp.
#define RAS_RECOVER_STATE_HEADER void recover_state(class RAS_chkpt_t * const cpvp)
Definition at line 674 of file zesto-bpred.cpp.
#define RAS_REG_STATS_HEADER void reg_stats(struct stat_sdb_t * const sdb, struct core_t * const core)
Definition at line 676 of file zesto-bpred.cpp.
#define RAS_RESET_STATS_HEADER void reset_stats(void)
Definition at line 678 of file zesto-bpred.cpp.
#define RAS_RET_STATE_HEADER void ret_state(class RAS_chkpt_t * const cpvp)
Definition at line 682 of file zesto-bpred.cpp.
Function Documentation
static class bpred_dir_t* bpred_from_string (char *const opt_string) [static]
Definition at line 143 of file zesto-bpred.cpp.
References fatal(), bpred_dir_t::name, and bpred_dir_t::type.
Referenced by bpred_t::bpred_t().
static class BTB_t* BTB_from_string (char *const opt_string) [static]
Definition at line 509 of file zesto-bpred.cpp.
References fatal(), BTB_t::name, and BTB_t::type.
Referenced by bpred_t::bpred_t().
static class fusion_t* fusion_from_string (const int num_pred, struct bpred_dir_t ** bpreds, char *const opt_string) [static]
Definition at line 322 of file zesto-bpred.cpp.
References fatal(), fusion_t::name, and fusion_t::type.
Referenced by bpred_t::bpred_t().
static class RAS_t* RAS_from_string (char *const opt_string) [static]
Definition at line 691 of file zesto-bpred.cpp.
References fatal(), RAS_t::name, and RAS_t::type.
Referenced by bpred_t::bpred_t().